### ISSUE TITLE
build against a Dæmon directory that is outside of source tree

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1000]
Having to deal with Dæmon as a submodule is annoying, what could be far more convenient would be to just clone Unvanquished and Daemon this way:

```sh
cd ~/src
git clone https://github.com/Unvanquished/Unvanquished.git
git clone https://github.com/DaemonEngine/Daemon.git
```

then build Dæmon and Unvanquished this way:

```sh
cd Daemon
mkdir build; cd build
cmake ..
make
```

```sh
cd Unvanquished
mkdir build; cd build
cmake -DDAEMON_PATH=~/src/Daemon ..
make
```

We are already able to run the game that way:

```sh
~/src/Daemon/build/daemon -libpath ~/src/Unvanquished/build
```

So it would make sense to have the convenience to build them that way, and nobody would have to complain about that annoying submodule thing. By the way the `daemon` submodule can be kept for people who just want to build the game without having to hack the code, fetching the submodule if `DAEMON_PATH` cmake option is not set.

Feel free to suggest a better cmake option name if you think having a better idea for it of if there is some best practice to follow. :wink:

**Comment by Viech** [comment]
Congratulations on opening the 1000th issue. :neutral_face:

**Comment by illwieckz** [comment]
only dead projects have small issue numbers :wink:
