### ISSUE TITLE
Rendering problem on certain map

### ISSUE THREAD

**Issue by FreeSlave** [Unvanquished/Unvanquished#1010]
Screenshots:

![unvanquished_2017-06-01_193056_000](https://cloud.githubusercontent.com/assets/5596503/26700583/8ea07d3e-4726-11e7-9c2b-62887840de73.jpg)
![unvanquished_2017-06-01_193102_000](https://cloud.githubusercontent.com/assets/5596503/26700584/8ec0de80-4726-11e7-8c19-e4c4b937d9f6.jpg)

Here's map where it happens (I needed to put pk3 in another zip to stop github from complaining):

[map-tremtest_1.0.pk3.zip](https://github.com/Unvanquished/Unvanquished/files/1046026/map-tremtest_1.0.pk3.zip)

For me this bug happens on 0.50. @illwieckz says that he has this bug on master.

**Comment by Viech** [comment]
Does the map include a dynamic light entity?

**Comment by FreeSlave** [comment]
Just regular light entities with no flags nor q3map2 properties.

**Comment by illwieckz** [comment]
is there some kind of fog? I noticed similar behavior with dynamic light and fog in siege map.

**Comment by bmorel** [comment]
How to load a pk3 in unvanquished, to see if that's still true (very likely, but hey, giving the recipe will help people check from time to time, and maybe motivate a fix)?

**Comment by slipher** [comment]
> How to load a pk3 in unvanquished, to see if that's still true (very likely, but hey, giving the recipe will help people check from time to time, and maybe motivate a fix)?

`fs_legacypaks` might help

**Comment by illwieckz** [comment]
This map is recent enough, you just have to rename `map-tremtest_1.0.pk3` to `map-tremtest_1.0.dpk`.

**Comment by bmorel** [comment]
To me, it looks like fixed: ![2021-12-21-114451_1366x758_scrot](https://user-images.githubusercontent.com/1316300/146917427-e1ca77fa-c64e-47ba-a100-c1bfc3e60d01.png)

**Comment by illwieckz** [comment]
Sorry @freem, but I still reproduce it on my end (Mesa radeon driver). I'll keep this one closed (to avoid a duplicate) but keep this one open:

https://github.com/DaemonEngine/Daemon/issues/61

**Comment by bmorel** [comment]
No worries. If I'm wrong, I'm wrong, you did added some useful info: it's a Radeon problem, so, people will know more how to reproduce it.
