### ISSUE TITLE
Please implement tokens in chat binds to print player variables (e.g. current health)

### ISSUE THREAD

**Issue by lavacano201014** [Unvanquished/Unvanquished#1011]
I swear this used to be a thing in Tremulous, though it's possible that it was an exclusive feature to some third-party client at the time (or I may even be thinking of a different Q3A descendant entirely). I'd been Googling for an old Tremulous reference but haven't found one.

Basically, the way it would work is, the user would bind a key to run some say_team command like:
`/say_team I have ^2$health HP ^5 and am carrying ^3$weapon`

And it would appear in team chat like this:
![screenshot_20170606_121801](https://user-images.githubusercontent.com/4407155/26847555-5686394a-4ab2-11e7-8450-66b91f54011c.png)

Other tokens might include `$location`, `$credits` (which would print morph points on the alien team), `$buildpoints`, things of that nature.

(I asked a dev in game if this was already here and he said "possibly", but nothing I could think of as a token worked, so I'm making the issue just in case - worst case scenario is it gets closed)

**Comment by DolceTriade** [comment]
It's there. The token is a little unusual. You can substitute any cvar into the string. So you should try:

/bind key say_team I have ^2$p_health$ ^7and am carrying an ^2$p_weapon$

Check the p_* cvars to see what else you can substitute.
