### ISSUE TITLE
predator cloak bug

### ISSUE THREAD

**Issue by tvezet** [Unvanquished/Unvanquished#1024]
So here is the problem i described in the forum: https://forums.unvanquished.net/viewtopic.php?p=17919#p17919

As requested:
```
$ lspci -nn | grep VGA
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Redwood XT [Radeon HD 5670/5690/5730] [1002:68d8]
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD REDWOOD (DRM 2.46.0 / 4.8.0-36-generic, LLVM 3.8.0)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 12.0.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 12.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 12.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

**Comment by tvezet** [comment]
```
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD REDWOOD (DRM 2.46.0 / 4.8.0-36-generic, LLVM 5.0.0)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.2.1 - padoka PPA
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.1 - padoka PPA
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.2.1 - padoka PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```
This seemed to work out since i cannot see any buildings disappear as they used to, no matter how many i put in a base. Additionally i had to cheat some bp to impress the frame rate in a significant way.
However the problem might still occur when there is a pulse rifle or flame thrower around, because whenever there is a flashing from a weapon now, the view freezes and shutters while the visible lights fill up the whole screen with white:
<a href="https://www.pic-upload.de" target="_blank"><img src="https://www2.pic-upload.de/img/33995707/unvanquished_2017-09-28_123818_000.jpg" title="Bilder oder Fotos hochladen"></a>
<a href="https://www.pic-upload.de" target="_blank"><img src="https://www2.pic-upload.de/img/33995706/unvanquished_2017-09-28_123827_000.jpg" title="Bilder oder Fotos hochladen"></a>
I don't know if the problem is solved by this and i am now facing a different bug.
Thanks for support so far!

**Comment by illwieckz** [comment]
Oh, I wonder if this it related to [this one](https://github.com/DaemonEngine/Daemon/issues/34) which happens on speed but also starts from bright dots and fill the screen.

How your new bug looks when you disable blooming? (`r_bloom 0`)

**Comment by tvezet** [comment]
Bright dots don't fill the screen anymore but it still shutters and i can paint with some lights and slow projectiles: 
<a href="https://www.pic-upload.de" target="_blank"><img src="https://www2.pic-upload.de/img/33996012/unvanquished_2017-09-28_151000_000.jpg" title="Bilder oder Fotos hochladen"></a><a href="https://www.pic-upload.de" target="_blank"><img src="https://www2.pic-upload.de/img/33996014/unvanquished_2017-09-28_151004_000.jpg" title="Bilder oder Fotos hochladen"></a>

**Comment by bmorel** [comment]
Anyone seen such thing recently? Screenshots are gone, but I'm pretty sure I never noticed such big disappearances in game.

**Comment by bmorel** [comment]
Re-asking, will close it next time I see it if still no answer (too much issues is too much noise, makes it harder to find real issues)

**Comment by necessarily-equal** [comment]
Hopefully this is fixed. If it isn't, please reopen
