### ISSUE TITLE
The game does not start if there is no sound card at all

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1031]
From faldor20 on discord:

> i found a kind of unique bug this morning the game does not start if you dont have any audio devices. my laptop has a broken soundcard and it throws an error unless i plug in an external one

He is running Windows 10.

**Comment by faldor20** [comment]
"couldn't initialize audio subsystem" is the exact error

**Comment by slipher** [comment]
Yes, it's true that you can't start the game if the audio initialization is unsuccessful. I have run into this a number of times, because there is this one program I use that frequently crashes the audio driver. Would be nice if the audio is not required.

**Comment by DolceTriade** [comment]
I wonder if here is such a thing as a null output/input that we can use instead of a real thing?

**Comment by lavacano201014** [comment]
> I wonder if here is such a thing as a null output/input that we can use instead of a real thing?

In Linux there is, in the form of a "dummy" sound device. I don't think it's loaded by default, because iirc it's mainly used for kernel dev.

Virtual Audio Cable (a program designed to be more of a finely-controlled "stereo mix") could be used in Windows as a bandaid - install it, make sure there's at least one "virtual cable" set up, et voila - just make sure nothing is using that device as default microphone unless you want to play your game sounds over Skype or Discord :V

**Comment by t4im** [comment]
Isn't that what https://github.com/DaemonEngine/Daemon/blob/master/src/engine/null/NullAudio.cpp is for?

**Comment by slipher** [comment]
NullAudio.cpp is for the TTY client.

**Comment by illwieckz** [comment]
I configured a special schroot environment to build Unvanquished. I usually build it on Ubuntu 20.04 LTS as my testing environment is 20.04 based (I simply rsync the build to other systems) but I wanted to update my daily workstation on something more recent than that, hence the schroot solution.

In the process, I forgot I would face some race conditions in accessing audio device from main system and the schroot, and well, I got this:

```
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Device or resource busy
Warn: Could not open an OpenAL device. 
Warn: Couldn't initialize the audio subsystem. 
Debug: ----- CL_Shutdown ----- 
```

For now I configured the schroot environement to use another soundcard to let the engine run, but this is the kind of situation where letting the engine run with a dummy sound rendering would be good.

**Comment by illwieckz** [comment]
I discovered that a possible cross-platform workaround is to set `ALSOFT_DRIVERS='null'` environment variable to tell OpenAL to use a dummy sound device.

Anyway, a fix in the engine is in the pipe, see https://github.com/DaemonEngine/Daemon/pull/524
