### ISSUE TITLE
how is that possible the engine looks for “level3.iqm:pain2” file name?

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1044]
I don't know if it's an engine, gamecode or asset issue, but:

```
Debug: Failed to open 'models/players/level3/level3.iqm:die2' for reading: Filename contains invalid characters 
Debug: Failed to open 'models/players/level3/level3.iqm:die3' for reading: Filename contains invalid characters 
Debug: Failed to open 'models/players/level3/level3.iqm:gesture' for reading: Filename contains invalid characters 
Debug: Failed to open 'models/players/level3/level3.iqm:attack3' for reading: Filename contains invalid characters 
Debug: Failed to open 'models/players/level3/level3.iqm:swim' for reading: Filename contains invalid characters 
Debug: Failed to open 'models/players/level3/level3.iqm:turn' for reading: Filename contains invalid characters 
Debug: Failed to open 'models/players/level3/level3.iqm:pain1' for reading: Filename contains invalid characters 
Debug: Failed to open 'models/players/level3/level3.iqm:pain2' for reading: Filename contains invalid characters 
```

But `models/players/level3/level3.iqm:pain2` is definitely not a file name.

**Comment by slipher** [comment]
I looked into this, and the query for file names with a colon (while ugly) is working as intended. IQM animations are bundled into the model file, and are registered with these fictitious file names when the model is loaded.

From the asset standpoint, I'm not sure. Some of the animations could be optional, while the lack of others is a bug.

**Comment by Viech** [comment]
Having "magic" animation names like these is not that useful. In cgame, there is a big table that maps standard buildable animations (those that are triggered by sgame via an enum value) to their actual, potentially arbitrary animation name – this is the most flexible approach (in terms of not explaining string standards to animators and in terms of potentially having buildable-specific enums), and it makes these magic names superfluous.

**Comment by illwieckz** [comment]
Fixed in https://github.com/DaemonEngine/Daemon/pull/72, especially in https://github.com/DaemonEngine/Daemon/pull/72/commits/46e903fe3f00fa1aab7adc3d2a9e50264f2189d0.
