### ISSUE TITLE
Alpha 51: jetpack smoke is broken

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1046]
Jetpack smoke is broken in alpha 51 packages, but I don't get any warning/debug message about it. I don't know where to look for.

**Comment by illwieckz** [comment]
ok it's related to #1042 I don't know why, but one useless model needs to be there to get smoke. Closing because it works. let's do another issue for the depreaction itself.

**Comment by Viech** [comment]
@illwieckz does the smoke not use a tag on the jetpack model for placement? Because it should be.

**Comment by DolceTriade** [comment]
@Viech It was due to bad code (ie, we return early if that unused model is missing, thus never actually adding smoke to the scene).
