### ISSUE TITLE
jetpack smoke needs obsolete jetpack flash model

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1047]
I don't know why, but jetpack smoke does not work if useless jetpack_flash model is not registered, but this model is an old model from trem and unused today (and not visible in game). I guess the problem is in the game code, for some reason the smoke depends on the registration of the jetpack_flash model.

Once the code for the jetpack_flash is removed from the gamecode and jetpack smoke made available without the flash, we would be able to revert UnvanquishedAssets/res-players_src.dpkdir@4a4ef62 to remove those useless files.

Related code:

```
src/cgame/cg_local.h:	qhandle_t   jetpackFlashModel;
src/cgame/cg_main.cpp:	cgs.media.jetpackFlashModel = trap_R_RegisterModel( "models/players/human_base/jetpack_flash.md3" );
src/cgame/cg_players.cpp:				flash.hModel = cgs.media.jetpackFlashModel;
```

This can be postponed after alpha 0.51 but as a cleaning task and since 0.51 was a strong effort to not ship unneeded stuff, if it's ready for 0.51 it's cool.

**Comment by DolceTriade** [comment]
Is the model empty or blank? If so, then yes, we should absolutely remove it.

**Comment by DolceTriade** [comment]
I did some research. It should be removed.
!(https://i.imgur.com/mfirMRh.png)[jetpack flash]

**Comment by illwieckz** [comment]
Yes it was just the blue flame from propeller on trem jetpack, we have to nuke it.

**Comment by illwieckz** [comment]
fixed.

**Comment by Viech** [comment]
@illwieckz when a commit references an issue via "fixes" or "closes", you don't need to close the issue as it will be auto-closed when the commit enters master. 😉
