### ISSUE TITLE
main

### ISSUE THREAD

**Issue by Filipeh** [Unvanquished/Unvanquished#1055]
Where is the main function on this repo?

**Comment by DolceTriade** [comment]
The engine has main() function here: https://github.com/DaemonEngine/Daemon/blob/84c07a6fe2b3e6ade77ee471d5eb444b3d0a4d0a/src/engine/framework/System.cpp#L671

Each of the VMs have their main functions defined as vmMain() inside their respective [cg|sg]_main.cpp files.
