### ISSUE TITLE
Buildable models are scaled two times

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1063]
I discovered that the game code scales buildables two times, for example if there is `5` in some `.model.cfg` file, the model is scaled  `5²` hence `25` time.

To say it the another way, to scale `25` time a model we have to write the wrong `5` factor in model configuration file.

I verified that player models are scaled correctly. I have not looked to weapon models yet, but currently it looks like the bug only affects buildables.

It's not a blocking issue for 0.51.0 because I plan to scale buildable models at package build time so they can be displayed correctly within NetRadiant too (see [NetRadiant!84](https://gitlab.com/xonotic/netradiant/merge_requests/84)), hence the `modelScale` will be `1` in buildable `.model.cfg` files in 0.51.0 release.

And unlike player models, there is not “advanced buildable” which is just another model scaled up, so there will no _visible_ bug, but the bug is there!

Currently if someone wants to scale a buildable models `N` time he must set `modelScale √N` in `<name>.model.cfg`, experimenting with new models (for Unvanquished main game or a mod) requires to use wrong values.

**Comment by Viech** [comment]
> I plan to scale buildable models at package build time so they can be displayed correctly within NetRadiant too (see NetRadiant!84), hence the modelScale will be 1 in buildable .model.cfg files in 0.51.0 release.

Wouldn't it be better to also scale them in NetRadiant? Scaling and rotating via config files is a very handy feature when you add a new model, and not everyone has the tools and know-how to change the model itself. I'm also thinking about third-party (map) models here.

**Comment by illwieckz** [comment]
It would have been cool if IQE format had a metadata part to tell the standard iqm compiler to rotate/scale/offset the model, or is IQM format also had a metadata like this to tell the rotate/scale/offset information to the software that renders it.

To scale the models in NetRadiant we need NetRadiant reading the same metadata file and format than the Dæmon engine, and that is an issue. I'm not sure it's a good strategy to patch all the editing tools involved supports both model rotation/scale/offset and dæmon's model.cfg format.

By applying rotate/scale/offset transformation at build time we ensure every tool rendering iqm files can render them as expected _without checking that particular tool or patching it_.

The [iqm tool extended by the FTE QW](https://sourceforge.net/p/fteqw/code/HEAD/tree/trunk/iqm/) project added proper scale/rotate/offset abilities (applied to animations too) plus the ability to read a command file, so these command files can be stored as sidecar alongside the iqe file in repository. At build time the `iqm` binary just read those command files.

People not mapping from source will just use shipped dpk so they will have already scaled/rotated models so they don't care.

For people mapping from source we have to ship an SDK including urcheon, q3map2, daemonmap, cwebp, our crunch, that iqm tool etc. Our toolchain already requires a lot of weird stuff like our own daemonmap fork and our own crunch fork so we already have to ship an SDK if we don't want people being lost, and adding this improved iqm tool to that SDK would be easy to do.

**Comment by necessarily-equal** [comment]
I believe the fix has been merged and that this can be closed.

**Comment by illwieckz** [comment]
Right, fixed by #1264.
