### ISSUE TITLE
Gameplay

### ISSUE THREAD

**Issue by Xallax** [Unvanquished/Unvanquished#1066]
Hey, im a brand new player and I REALLY love tremulous. I downloaded the game today and started playing, but I realized there was nobody on. Is this source of gaming have nobody playing it anymore? I was online at 5 EST, so im not sure where the servers are exactly located.

**Comment by illwieckz** [comment]
Hi @Xallax! We don't advertise the game a lot, so there is not so much people yet. Most servers are european. Is Sunday 19:00 UTC a good day and time for you? I'll be there. :wink: 

Note that we have a forum: https://forums.unvanquished.net, and there is a poll about scheduled games there: https://forums.unvanquished.net/viewtopic.php?f=35&t=2137 :wink: 
Github is a better place for bug reports and threads there are meant to be closed, on the other hand forum threads are usually never closed. :smiley:

**Comment by Xallax** [comment]
Unfortunately I will not be able to make it at 19:00 UTC time, I will be working sadly... I will check out the forums, thank you for replying to me!

**Comment by illwieckz** [comment]
That's unfortunate! See you soon on the forum or in game at some other hours :smiley: 

I'm closing this thread to not let it count as an not-closed issue. Feel free to start a new thread on forums if you have some other questions. :relaxed:
