### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Buom01** [Unvanquished/Unvanquished#1079]
Hi, sorry to open issue here
I just report than for more than a week the official website did'nt work, so I can't install the game
Additionnaly there aren't any tweets concerning this
Is it a known problem ?

**Comment by mbasaglia** [comment]
Yes, it is a known problem. The server owner has raised a ticket to the hosting company

**Comment by illwieckz** [comment]
You can download the game there: https://github.com/Unvanquished/Unvanquished/releases
The _Download_ link on Unvanquished website just pointed to this page.

**Comment by illwieckz** [comment]
Note that the master server is also down. You can join my server there by the way : gg.illwieckz.net:27960

**Comment by illwieckz** [comment]
We've just set up a landing page on a temporary place to welcome people while waiting for the server to come back: https://unvanquished.net/

The master server is up again but since it's hosted on that temporary place the server owners have to restart their instances to resolve the master server ip again and get listed.

**Comment by DolceTriade** [comment]
The hosters bricked our server. We're waiting a replacement server to be shipped.

**Comment by Buom01** [comment]
Who was your website hoster ?

**Comment by DolceTriade** [comment]
delimiterVPS

**Comment by illwieckz** [comment]
The https://unvanquished.net/activity/ page is up again. Still waiting for news from hoster…

**Comment by illwieckz** [comment]
Website is up again :wink: 

→ https://www.unvanquished.net/

**Comment by illwieckz** [comment]
a blog post was published to explain that recent server down time: https://www.unvanquished.net/?p=1145
