### ISSUE TITLE
resolve master server at map load, not at engine start

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1082]
It looks like once the engine starts it resolves the master server address forever and you have to quit the engine entirely and restart it to resolve the master server address again if it changed. It would be more useful if the game resolves the master server address on map load.

I don't know if it's a game issue or an engine issue.

**Comment by slipher** [comment]
The benefit of this seems rather limited (especially if we proceed with the plan to always query all master servers).

**Comment by illwieckz** [comment]
The benefit is to not have to ask all server owners to manually restart their server the day a master server is moved to another hosting or provider with another ip. 10 days after I moved the master server on a new host (with a new IP) there is still 1 server on 3 that have not yet resolved the master server.

Having multiple master servers will just hide the problem until all master server will be moved.

**Comment by slipher** [comment]
Fair enough. Is there any reason to prefer on map load, to some arbitrary refresh interval?

**Comment by illwieckz** [comment]
Good question! I have no reason to prefer on map load, that's just the first thing that crossed my mind, resolving at map load is just a known way to make it happens sooner than it happens now. I agree I just proposed a solution instead of properly stating the issue. :stuck_out_tongue: 

I don't mind the way, what the game need is a way to resolve the master server address from time to time. :grin:
