### ISSUE TITLE
[RFE] Provide Flatpak for Unvanquished

### ISSUE THREAD

**Issue by AsciiWolf** [Unvanquished/Unvanquished#1099]
[Flatpak](https://flatpak.org) is becoming a standard for cross-distro Linux application distribution. Please, consider providing a Flatpak for Unvanquished and hosting it on [Flathub](https://flathub.org) to help Linux users easily install and update Unvanquished.

**Comment by illwieckz** [comment]
We may just repackage our universal build as a Flatpak, but that would not make Flatpak an alternative if our universal build doesn't work for any reason.

**Comment by illwieckz** [comment]
Related issues:

- https://github.com/flathub/flathub/pull/2369 _Unvanquished: new flatpak_
- https://github.com/Unvanquished/Unvanquished/pull/1422 _Add appstream data_
- https://github.com/Unvanquished/Unvanquished/issues/1423 _Deal with the "infrastructure files" in a nicer way_
- https://github.com/Unvanquished/updater/issues/95 _Fuse the two desktop files_

**Comment by slipher** [comment]
This is done I guess?

 https://github.com/flathub/net.unvanquished.Unvanquished/
https://flathub.org/apps/details/net.unvanquished.Unvanquished
