### ISSUE TITLE
0.51.1 dpk md5sums file is empty

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1100]
This file is empty:
http://cdn.unvanquished.net/unvanquished_0.51.1/pkg/md5sums

it makes `download-dpk.sh` unusable.

**Comment by illwieckz** [comment]
this was due to the switch from pk3 to dpk, scripts were fixed long time ago, this issue will remain open until release to be sure we double-check it before release.

**Comment by illwieckz** [comment]
As said there: https://github.com/Unvanquished/Unvanquished/issues/1168#issuecomment-609504748

> If you use `download-paks` from latest master ([there](https://raw.githubusercontent.com/Unvanquished/Unvanquished/master/download-paks)), and install `aria2c`, it will download paks using bittorrent so you wouldn't have to mind the empty `md5sums` file.

**Comment by slipher** [comment]
It is checked in https://github.com/Unvanquished/validate-release so we cannot forget it in the future!
