### ISSUE TITLE
Flamer poor performance (ground fires)

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#1109]
The presence of a flamer (or especially 2 flamers) causes excessively large FPS drops with latest engine master. Need to check if it was already like that for a long time, or if recent gfx changes have contributed.

**Comment by DolceTriade** [comment]
Would be interesting to note if it is related to heat haze.

**Comment by illwieckz** [comment]
latest master allow to enable parallax while disabling normal mapping, makes us able to test a stressy lighting (parallaxed flamer realtime lighting) with or without heathaze (heathaze being a normal map), solarium xonotic map is a good test bed for this.

**Comment by Viech** [comment]
This could also easily be related to the dynamic light that the flamer spawns.

**Comment by slipher** [comment]
The problem occurs on my Windows 7 machine with a Radeon R7 250 card. All Driver version is Radeon Software 20.4.2 (5/15/2020). All Unvanquished gfx settings at default values. I did not see the problem when testing with Nvidia or Intel integrated GPUs. At least one other person has agreed during dev games that the flamer causes a severe FPS drop. illwieckz reports no performance hit due to ground flames on an R9 390x.

The problem is caused by the flame sprites which are created when the ground is lit on fire and the particle system `scripts/fire.particle` is spawned. A minimal difference to produce the problem or not is whether the fire shader has more than 1 stage. If I delete https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/blob/f0409b2dc2b0db3a5a90fabeba9692ba0138bb47/scripts/fire.shader#L20-L29, then the FPS issues go away. If I delete only https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/blob/f0409b2dc2b0db3a5a90fabeba9692ba0138bb47/scripts/fire.shader#L25-L29, then I still experience low FPS. 

I found some people saying that frequently switching textures can cause poor performance. I found that if I change the `animMap` lines in the shader to be identical to each other, there is no performance issue. This seems to confirm that if there is no texture switching, the performance is OK.

In the slow case (2 stages in the shader), over 50% of wall time ends up being spent in [this glDrawRangeElements call](https://github.com/DaemonEngine/Daemon/blob/d07f61c37ff5735e8fbda52253c2b62f3990fcbd/src/engine/renderer/tr_shade.cpp#L296) in the cases where it is applied to the fire shader - 1.1 s in a ~2s period. The maximum individual instance usually takes 4-10 ms (!), while the average is 25 us.

In the fast case of leaving only 1 stage in the fire shader, the glDrawRangeElements calls for the fire shader consumed only 51 ms during the 2s period.

The problem occurs both on version 0.51 and the latest master.

I used a 2-second demo for testing the problem with ground flames.

With the 2nd and 3rd stages of fire.shader removed:
![unvanquished_2020-08-28_211702_000](https://user-images.githubusercontent.com/7809431/91631486-9a34c980-e98e-11ea-8880-69b022fb357a.png)

With only the 3rd stage of fire.shader removed:
![unvanquished_2020-08-28_211417_000](https://user-images.githubusercontent.com/7809431/91631491-a1f46e00-e98e-11ea-90ff-5a009a56ac99.png)

**Comment by DolceTriade** [comment]
Wow, very nice find! Should we fix this in the shader?

**Comment by slipher** [comment]
> Should we fix this in the shader?

Well, yes... if someone knows how!

**Comment by illwieckz** [comment]
In fact I also reproduce the issue with my AMD R9 390X card if I put many flames.

> This could also easily be related to the dynamic light that the flamer spawns.

@Viech, there is two issues, the issue related to the flamer flame (likely realtime light stuff since tiled renderer is known to be way faster than old forward one on that task), the issue related to the flames on the ground, slipher is currently talking about the one about flames on the ground.

**Comment by illwieckz** [comment]
On a side note, this fire shader was never meant to be spammed everywhere on screen, at first it was designed for torches on corridors (like in hamunaptra map).

**Comment by Viech** [comment]
I think the flamer attack fire with the heat flimmering effect was made by /dev/humancontroller. The floor fire was added by me but as you can see it has placeholder quality. Just remove any stage that's problematic, though some sort of smoke effect should stay for it to not become even more hideous.

**Comment by illwieckz** [comment]
I agree with Viech, this is a placeholder and an ugly placeholder, if we can make it faster while somewhat not making obviously worst we must do it.

**Comment by slipher** [comment]
https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/pull/4

**Comment by slipher** [comment]
It was merged.
