### ISSUE TITLE
unv-nacl-sdk

### ISSUE THREAD

**Issue by stevennt** [Unvanquished/Unvanquished#1119]
dpkg-checkbuilddeps: error: Unmet build dependencies: unv-nacl-sdk

The build failed with above missing package. I can't seem to find that unv-nacl-sdk package anywhere on the web. Any suggestion team? Thanks.

**Comment by slipher** [comment]
Don't try to use the Debian packages. They are not maintained

**Comment by illwieckz** [comment]
Hi, as said by slipher the debian packages are not maintained but the debian scripts (in `debian/` subdirectory) are not maintained too. So don't use them.

At this point the only supported way to build Unvanquished is the one described in [README](https://github.com/Unvanquished/Unvanquished/blob/master/README.md#download-instructions) file:

```
git clone --recurse-submodules https://github.com/Unvanquished/Unvanquished.git
cd Unvanquished/
cmake -H. -Bbuild
cmake --build build -- -j4
```

You'll still need to download dpk files you can obtain in [universal zip](https://unvanquished.net/download/zip).

I close this issue. If you face problems with the supported build instructions feel free to open a new issue.
