### ISSUE TITLE
Available buildpoints do not change with cvar change

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1124]
Changing g_BPBudgetPerMiner or g_BPInitialBudget only take effect after a leech/drill is build.

**Comment by slipher** [comment]
I wouldn't really expect it to work to change these in the middle of a game.

**Comment by Viech** [comment]
That's semi-intentional, some of the mining related calculations are expensive, so for simplicity all of them are only performed when the miner landscape changes.

It could be that `give bp` still works, at least until you build a miner. :wink:

**Comment by Gireen** [comment]
Is it ok to add a command to trigger the calculation manually?

**Comment by Viech** [comment]
@Gireen sure! Though maybe it's better to hook the relevant commands and make them perform the update?
