### ISSUE TITLE
Default key binds missing/not working

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1155]
Evolve, deconstruct and beacon menu are shown unbound ingame and don't work.
Pressing Q returns `Unknown command "+active"`
Setting key binds via menu works except for humans deconstruct.
Alt+E as human returns `usage: vstr <variablename> — executes a variable command `

**Comment by illwieckz** [comment]
Hmm, that's bad! See also: #544 _Create new default key bindings_ we may fix that while fixing others.

**Comment by slipher** [comment]
I think it's supposed to be `+activate`.

**Comment by Gireen** [comment]
New keybindings would be good but depending on when a new version is scheduled a bugfix release could be needed.
Everyone new player has to change his binds in the options to evolve or deconstruct buildings. 
Since humans are the most popular team only deconstructing is affected, which can either be only set to any key except E or E must be set first to another command.

**Comment by illwieckz** [comment]
A bugfix release would be good to have.
