### ISSUE TITLE
Evolve menu class descriptions out of order

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1165]
The class name and description in the evolve menu are out of order
For the Dretch are AdvGranger informations displayed and from there always from the class before.
This is since #1138 
The change should work but it seems that `setDS alienEvolveList` has no effect at all
https://github.com/Unvanquished/Unvanquished/blob/adc6e154435a71828bb26362de6f647d17990c6a/src/cgame/cg_rocket_dataformatter.cpp#L425

**Comment by illwieckz** [comment]
I experienced it, this is a release blocking bug. We have to fix it or revert the change.
