### ISSUE TITLE
The game only draws to the bottom left of the window on macOS Catalina, 10.15.3

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#1166]
I've just managed to build the game on macOS Catalina, and have noticed similar problems to other quake-based games, including Tremulous. When launching the game, it will launch only drawing in the bottom left hand corner of the window with the rest of the window flickering red/black. I believe this is something to do with High DPI mode. I also did a bit of research and found these posts;

https://github.com/redeclipse/base/issues/920
https://github.com/ioquake/ioq3/issues/422
https://github.com/godotengine/godot/issues/32805

Related:
https://hg.libsdl.org/SDL/rev/46b094f7d20e

Screenshot below;
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/13281185/76964562-d6152e80-691a-11ea-8fb4-1036c2b44ebf.png">

**Comment by illwieckz** [comment]
This looks interesting:
https://github.com/MaddTheSane/Quake2/pull/2/files

**Comment by cu-kai** [comment]
It does and whilst it's a valid point, it doesn't actually solve the problem, nor does it allow me to launch the game from my terminal (which I almost always do).

That solution is more like brushing the problem under the carpet as opposed to fixing it.

**Comment by illwieckz** [comment]
Ah, you mean the plist file is only used when clicking icons?

**Comment by cu-kai** [comment]
Yes, and I don't use the `Unvanquished.app`, I always launch with `./daemon`, hence why it would be good for it to be fixed in the code rather than the `.app`'s `info.plist` file

**Comment by illwieckz** [comment]
That's bad, it would mean launching the game from updater would end with this bug too. And the plan is to use the updater as the launcher.

**Comment by cu-kai** [comment]
Indeed, I haven't tested your fix as I know it'll work when launching with the `.app`. Doom 3 suffers from it here but they appear to have another workaround for launching the game in standard DPI...

https://github.com/dhewm/dhewm3/issues/276

The solutions in [this post](https://github.com/dhewm/dhewm3/issues/276#issuecomment-587168821) did not work for me when trying it with Unvanquished.

**Comment by illwieckz** [comment]
Just for testing purpose, what if you modify this line:

https://github.com/DaemonEngine/Daemon/blob/42e408a4f45f6e78b59fe9b7022f57456a7677d6/src/engine/renderer/gl_shader.cpp#L727

This way:

```cpp
	AddDefine( env, "r_FBufSize", 2 * glConfig.vidWidth, 2 * glConfig.vidHeight );
```

**Comment by illwieckz** [comment]
> For what it's worth, if you compile the game on any macOS older than Catalina, it'll scale fine.
> 
> I believe the real fix is here: https://hg.libsdl.org/SDL/rev/46b094f7d20e

Do you mean a proper fix is to use a newer SDL?

**Comment by cu-kai** [comment]
> @cu-kai commented:
> 
> > For what it's worth, if you compile the game on any macOS older than Catalina, it'll scale fine.
> > I believe the real fix is here: https://hg.libsdl.org/SDL/rev/46b094f7d20e
> 
> Do you mean a proper fix is to use a newer SDL?

Most likely, yeah, or incorporate this fix somehow into the current setup.

**Comment by cu-kai** [comment]
> Just for testing purpose, what if you modify this line:
> 
> https://github.com/DaemonEngine/Daemon/blob/42e408a4f45f6e78b59fe9b7022f57456a7677d6/src/engine/renderer/gl_shader.cpp#L727
> 
> This way:
> 
> ```c++
> 	AddDefine( env, "r_FBufSize", 2 * glConfig.vidWidth, 2 * glConfig.vidHeight );
> ```

I don't have this line, I probably should have said I'm using the master branch.

**Comment by illwieckz** [comment]
This is engine master branch, you may enter the dæmon submodule and pull it.

**Comment by cu-kai** [comment]
I've compiled this recently on macOS and I don't think it's an issue any more, the game renders correctly. I don't recall seeing this in a long time.
