### ISSUE TITLE
Tutorial is printed behind the inventory

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1184]
Tutorial is printed behind the inventory:

[![tutorial above inventory](https://dl.illwieckz.net/b/unvanquished/bugs/tutorial-behind-inventory/unvanquished_2020-04-26_050626_001.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/tutorial-behind-inventory/unvanquished_2020-04-26_050626_001.jpg)

**Comment by slipher** [comment]
The positioning of these was adjusted in 0.52.
