### ISSUE TITLE
Bizarre code calling for trouble in CG_Rocket_GetBuildTimerProgress

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1189]
1. What happens if this test fails and `max` is undefined?
2. Does `max` can be `0` (then divide by `0`)?

https://github.com/Unvanquished/Unvanquished/blob/f79ea6e9b10f6d0d0c32b59f9ed371e099c52b9a/src/cgame/cg_rocket_progressbar.cpp#L59-L60

https://github.com/Unvanquished/Unvanquished/blob/f79ea6e9b10f6d0d0c32b59f9ed371e099c52b9a/src/cgame/cg_rocket_progressbar.cpp#L70-L78

**Comment by DolceTriade** [comment]
It would crash I suppose. Hasnt't happend yet, but, maybe log loudly if it does to document that assertion?

**Comment by illwieckz** [comment]
This is the [complete code](https://github.com/Unvanquished/Unvanquished/blob/f79ea6e9b10f6d0d0c32b59f9ed371e099c52b9a/src/cgame/cg_rocket_progressbar.cpp#L57-L79):

**Comment by martin-t** [comment]
I know nothing about the surrounding code but

1. In C++ static variables are automatically initialized to their default values (here 0) so it should be well defined.
2. With ints, div by 0 would be undefined but the values are first casted to float which should be well defined and produce NaN (in case of 0.0/0.0) or +-inf (in other cases). These values might cause trouble in code which uses the return value.

**Comment by illwieckz** [comment]
This is the [complete code](https://github.com/Unvanquished/Unvanquished/blob/f79ea6e9b10f6d0d0c32b59f9ed371e099c52b9a/src/cgame/cg_rocket_progressbar.cpp#L57-L79):

```c++
static float CG_Rocket_GetBuildTimerProgress()
{
	static int misc = 0;
	static int max;
	playerState_t *ps = &cg.snap->ps;
	weapon_t weapon = BG_GetPlayerWeapon( ps );

	// Not building anything
	if ( weapon != WP_HBUILD && weapon != WP_ABUILD && weapon != WP_ABUILD2 )
	{
		return 0;
	}

	// Building something new. Note max value.
	if ( ps->stats[ STAT_MISC ] > 0 && misc <= 0 )
	{
		max = ps->stats[ STAT_MISC ];
	}

	misc = ps->stats[ STAT_MISC ];

	return ( float ) misc / ( float ) max;
}
```

We see that `misc` is always equal to `0` at the time the `misc <= 0` test is done, so we can rewrite it this way:


```c++
static float CG_Rocket_GetBuildTimerProgress()
{
	static int misc = 0;
	static int max;
	playerState_t *ps = &cg.snap->ps;
	weapon_t weapon = BG_GetPlayerWeapon( ps );

	// Not building anything
	if ( weapon != WP_HBUILD && weapon != WP_ABUILD && weapon != WP_ABUILD2 )
	{
		return 0;
	}

	// Building something new. Note max value.
	if ( ps->stats[ STAT_MISC ] > 0 )
	{
		max = ps->stats[ STAT_MISC ];
	}

	misc = ps->stats[ STAT_MISC ];

	return ( float ) misc / ( float ) max;
}
```

And since `misc` is then set to `ps->stats[ STAT_MISC ]` unconditionally, we can rewrite the code this way:

```c++
static float CG_Rocket_GetBuildTimerProgress()
{
	static int max; is not expected to be used 
	playerState_t *ps = &cg.snap->ps;
	weapon_t weapon = BG_GetPlayerWeapon( ps );

	// Not building anything
	if ( weapon != WP_HBUILD && weapon != WP_ABUILD && weapon != WP_ABUILD2 )
	{
		return 0;
	}

	// Building something new. Note max value.
	if ( ps->stats[ STAT_MISC ] > 0 )
	{
		max = ps->stats[ STAT_MISC ];
	}

	return ( float ) ps->stats[ STAT_MISC ] / ( float ) max;
}
```

Then since `max` is set to `ps->stats[ STAT_MISC ]` when `ps->stats[ STAT_MISC ]` is greater than `0` we can rewrite this way:

```c++
static float CG_Rocket_GetBuildTimerProgress()
{
	static int max;
	playerState_t *ps = &cg.snap->ps;
	weapon_t weapon = BG_GetPlayerWeapon( ps );

	// Not building anything
	if ( weapon != WP_HBUILD && weapon != WP_ABUILD && weapon != WP_ABUILD2 )
	{
		return 0;
	}

	// Building something new. Note max value.
	if ( ps->stats[ STAT_MISC ] > 0 )
	{
		return ( float ) ps->stats[ STAT_MISC ] / ( float ) ps->stats[ STAT_MISC ];
	}

	return ( float ) ps->stats[ STAT_MISC ] / ( float ) max;
}
```

And since `N/N` is equal to `1` when `N` is different to `0`, we can rewrite this way:

```c++
static float CG_Rocket_GetBuildTimerProgress()
{
	static int max;
	playerState_t *ps = &cg.snap->ps;
	weapon_t weapon = BG_GetPlayerWeapon( ps );

	// Not building anything
	if ( weapon != WP_HBUILD && weapon != WP_ABUILD && weapon != WP_ABUILD2 )
	{
		return 0;
	}

	// Building something new. Note max value.
	if ( ps->stats[ STAT_MISC ] > 0 )
	{
		return 1;
	}

	return ( float ) ps->stats[ STAT_MISC ] / ( float ) max;
}
```
Also, when `ps->stats[ STAT_MISC ]` is equal to `0`, the result for `ps->stats[ STAT_MISC ] / max` is always equal to `0` if `max` is not equal to `0`.

Currently the code is expected to return `0` if `ps->stats[ STAT_MISC ]` is equal to `0` and the allocation does not initialize `max` to `0`. If  `ps->stats[ STAT_MISC ]` is equal to `0` and `max` is initialized to `0`, a division by zero occurs.

The code is expected to return an unpredictable value when `ps->stats[ STAT_MISC ]` is negative if `max` is not initialized to `0`, or make a division by `0` if `max` is initialized to `0`.

As far as I know, `ps->stats[ STAT_MISC ]` is never expected to be negative, other parts of the code has explicit tests to set it to zero when a substraction produces a negative number:

https://github.com/Unvanquished/Unvanquished/blob/f79ea6e9b10f6d0d0c32b59f9ed371e099c52b9a/src/sgame/sg_active.cpp#L906-L909

Note: we also see that but the `CG_Rocket_GetBuildTimerProgress` function is expected to return `0` in those case (those usages are not build timer but weapon charge).

https://github.com/Unvanquished/Unvanquished/blob/f79ea6e9b10f6d0d0c32b59f9ed371e099c52b9a/src/shared/bg_pmove.cpp#L3824-L3827

https://github.com/Unvanquished/Unvanquished/blob/f79ea6e9b10f6d0d0c32b59f9ed371e099c52b9a/src/shared/bg_pmove.cpp#L3850-L3853

So the code can be rewritten this way:

```c++
static float CG_Rocket_GetBuildTimerProgress()
{
	static int max;
	playerState_t *ps = &cg.snap->ps;
	weapon_t weapon = BG_GetPlayerWeapon( ps );

	// Not building anything
	if ( weapon != WP_HBUILD && weapon != WP_ABUILD && weapon != WP_ABUILD2 )
	{
		return 0;
	}

	// Building something new. Note max value.
	if ( ps->stats[ STAT_MISC ] != 0 )
	{
		return 1;
	}
	else if ( max != 0 )
	{
		return 0;
	}
	else
	{
		return 0 / ( float ) max;
	}
}
```

So I guess the code is just returning `1` or `0`. I don't know how the code is supposed to have worked until now.

**Comment by martin-t** [comment]
I don't think your first assumption is correct, it's a static variable so it keeps its value from the previous call (the `= 0` is run only once to initialize it) so `misc = ps->stats[ STAT_MISC ];` can influence the next run of the function.

**Comment by illwieckz** [comment]
The thing is that function is obviously not returning either `1` or `0`, because the buildtimer is displayed correctly (I mean… variable).

**Comment by illwieckz** [comment]
> I don't think your first assumption is correct, it's a static variable so it keeps its value from the previous call (the `= 0` is run only once to initialize it) so `misc = ps->stats[ STAT_MISC ];` can influence the next run of the function.

So you mean it acts like a global variable, but with the namespace being bound to the block?

**Comment by martin-t** [comment]
Yes, to my knowledge, it's effectively a global but visible only inside the function in which it's declared.

**Comment by illwieckz** [comment]
So, you mean that code:

```c
int method( int n )
{
	static int i = 0;
	
	if ( n == 42 )
	{
		i = 3;
	}
	
	return 4 + i;
}
```

is not similar to:

```c
int method( int n )
{
	static int i;
	int = 0;
	
	if ( n == 42 )
	{
		i = 3;
	}
	
	return 4 + i;
}
```

and not to:

```c
int method( int n )
{
	if ( n == 42 )
	{
		return 7; // 4 + 3
	}
	
	return 4;
}
```

but somewhat behaves like this:

```c

static int i_with_unique_name;

int method( int n )
{
	if ( n == 42 )
	{
		i_with_unique_name = 3;
	}
	
	return 4 + i_with_unique_name;
}
```

or this:

```c

static int i_with_unique_name;

int method( int n )
{
	if ( n == 42 )
	{
		i_with_unique_name = 3;
		return 4 + i_with_unique_name;
	}
	
	return 4 + i_with_unique_name;
}
```

That looks crazy!

**Comment by illwieckz** [comment]
I did that:

```c++
	Log::Warn("misc before: %d", misc);

	// Building something new. Note max value.
	if ( ps->stats[ STAT_MISC ] > 0 && misc <= 0 )
	{
		max = ps->stats[ STAT_MISC ];
	}

	misc = ps->stats[ STAT_MISC ];

	Log::Warn("misc after: %d", misc);
```

And I got that:

```
Warn: misc before: 0
Warn: misc after: 0
Machinegun Turret built by illwieckz
Warn: misc before: 0
Warn: misc after: 6000
Warn: misc before: 6000
Warn: misc after: 5900
Warn: misc before: 5900
Warn: misc after: 5800
Warn: misc before: 5800
Warn: misc after: 5800
Warn: misc before: 5800
[…]
```

So, I learnt something today… :astonished:

**Comment by martin-t** [comment]
Yeah, it pretty much a global static variable with more limited scope: https://godbolt.org/z/4h9Vqe - it even looks the same a as normal global in asm - initialized once statically - i think the values end up in some special section of the executable file. Note whether you set it to 0 or leave the initializer out completely is the same - afaik 0 doesn't get saved to the executable to save space because 0 is so common.

**Comment by martin-t** [comment]
Actually i meant to say just global variable, static means something else in C(++) for globals https://stackoverflow.com/questions/7837190/c-c-global-vs-static-global - it's kinda like private but lame because C was "designed" by amateurs who didn't bother with too complicated things like a proper module and visibility system.
