### ISSUE TITLE
Already pressed key is not read after closing build menu

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1196]
I'm implementing a hack to force the advanced granger to wallwalk when the buildmenu is open (see #1195). That works. Unfortunately, when I build the selected buildable and release the forced wallwalk, the key I press to wallwalk (Ctrl, the default one) is not read until I release it and press it again. Because of this I instantly fall after having selected the buildable to build.

**Comment by illwieckz** [comment]
Note: any other regular key seems to be affected. If I press continuously T while I select the buildable, the chat form does not pop-up.

**Comment by illwieckz** [comment]
@DolceTriade, do you have an idea about that issue?

Also, is there a way for the client to know there is a menu open (i.e. some librocket thing is reading input instead of the game)?

**Comment by slipher** [comment]
`KEYCATCHER_`something flags determine whether binds are interpreted by the engine or not.

**Comment by illwieckz** [comment]
Oh that's nice!

At first I implemented a hack that uses a command force wallwalk on build menu opening and a command to stop to force wallwalk on build menu closing, but I'm now thinking about testing for a menu being opened…

Anyway, I don't know how to tell the server the keycatcher changed unless I call `trap_Key_GetCatcher` on the client every frame which is probably a bad idea…  What do you people think about it?

**Comment by slipher** [comment]
I think this should wait until after the release. This issue only applies to a non-default wallwalk mode, so it can't be that important. We need to avoid doing an excessive number of enhancements at the last minute, or we may get burned out and not release anything. And we don't want to introduce bugs by adding sketchy hacks at the last minute.

**Comment by illwieckz** [comment]
yep, I was hoping this was easy, I'm just uncovering more bugs…

**Comment by illwieckz** [comment]
Anyway the FocusManager was what I was looking for.

**Comment by slipher** [comment]
I suppose this was fixed by #2900.
