### ISSUE TITLE
Move `BUTTON_` definitions into gamelogic

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#1202]
The constants like `BUTTON_ATTACK`, `BUTTON_ACTIVATE` etc. should be moved from the engine into the gamelogic.
A few of them are referenced in the engine for some reason but we can at least move all the other ones.

**Comment by DolceTriade** [comment]
Yeah, it seems probably that a lot of the engine logic that requires these buttons could be moved to the gamelogic as well. The main thing that seems concerning is something like VoIP...

**Comment by bmorel** [comment]
The only ones engine actually use are TALK/ANY/WALKING. It could very likely be fixed, I'm not sure.
Functions which uses those symbols only writes the values into `cmd->buttons`. They are:

* void CL_KeyMove( usercmd_t *cmd )
* void CL_JoystickMove( usercmd_t *cmd )
* void CL_GameControllerMove( usercmd_t *cmd )
* void CL_CmdButtons( usercmd_t *cmd )

One can see comments such as:

```
  // adjust for speed key / running
  // the walking flag is to keep animations consistent
  // even during acceleration and deceleration
```

Code in CL_JoystickMove() and CL_GameControllerMove() seems mostly duplicated, and likely could be factored to be put in a common block with CL_KeyMove(), and I still doubt setting the flag is really required to be done in engine.

BUTTON_ANY is *never* read, and BUTTON_TALK is only checked in PmoveSingle( pmove_t *pmove ), but seems actually useful.

**Comment by bmorel** [comment]
Considering the fact that:

> A few of them are referenced in the engine for some reason but we can at least move all the other ones.

has been done, I'm closing this, despite being likely that things could be definitely moved out of engine.
