### ISSUE TITLE
Bots don't defend themselve and don't defend the base when healing from overmind while an human is attacking

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1211]
Recently alien bots behaviour was greatly improved as the now retreat to overmind when low on health, making them less suicidal. This also induces some surprisingly good behaviour like an alien bot passing by an human player without attacking it because “he has better to do”.

There is one big downside to this. If an human player has direct sight to the overmind, shooting on alien near the overmind make sure they keep themselves near the overmind and never attack the human, making them absolutely useless, giving no challenge to the human at all:

[![shy bots](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_184649_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_184649_000.jpg)

[![shy bots](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_185012_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_185012_000.jpg)

[![shy bots](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_185102_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_185102_000.jpg)

[![shy bots](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_185637_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_185637_000.jpg)

[![shy bots](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_185839_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/shy-bots/unvanquished_2020-09-05_185839_000.jpg)

I guess a solution would be to tell the bot to retreat when low on health unless it has the overmind in sight and an human in sight.

Would be cool to continue to retreat if the human in sight is not seen by the overmind but I don't know if it's doable because it requires a bot (an entity) to know what the overmind (another entity) see.

@Gireen, can you look at this?

**Comment by Gireen** [comment]
yeah, i have no good idea for that yet. when bots execute a specific behavior they ignore everything else including the behavior tree.
