### ISSUE TITLE
Compile error, "error: ‘LUA_QL’ was not declared in this scope"

### ISSUE THREAD

**Issue by oyvindsaether** [Unvanquished/Unvanquished#1218]
<pre>
[  0%] Building CXX object CMakeFiles/ROCKET_LIB.dir/libs/libRocket/Source/Core/Lua/GlobalLuaFunctions.cpp.o
/home/oyvinds/src/Unvanquished/libs/libRocket/Source/Core/Lua/GlobalLuaFunctions.cpp: In function ‘int Rocket::Core::Lua::LuaPrint(lua_State*)’:
/home/oyvinds/src/Unvanquished/libs/libRocket/Source/Core/Lua/GlobalLuaFunctions.cpp:133:34: error: ‘LUA_QL’ was not declared in this scope; did you mean ‘LUA_OK’?
  133 |             return luaL_error(L, LUA_QL("tostring") " must return a string to "
      |                                  ^~~~~~
      |                                  LUA_OK
gmake[2]: *** [CMakeFiles/ROCKET_LIB.dir/build.make:2513: CMakeFiles/ROCKET_LIB.dir/libs/libRocket/Source/Core/Lua/GlobalLuaFunctions.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:430: CMakeFiles/ROCKET_LIB.dir/all] Error 2
gmake: *** [Makefile:103: all] Error
</pre>

This is with lua-5.4.0.

**Comment by slipher** [comment]
Maybe it has to be 5.3 to work.

**Comment by oyvindsaether** [comment]
found a solution in https://savannah.nongnu.org/bugs/index.php?58681

[0001-Fix-compile-error.patch.txt](https://github.com/Unvanquished/Unvanquished/files/5271261/0001-Fix-compile-error.patch.txt)
<pre>
diff --git a/Source/Core/Lua/GlobalLuaFunctions.cpp b/Source/Core/Lua/GlobalLuaFunctions.cpp
index 9c5f46f..c44af30 100644
--- a/Source/Core/Lua/GlobalLuaFunctions.cpp
+++ b/Source/Core/Lua/GlobalLuaFunctions.cpp
@@ -130,8 +130,7 @@ int LuaPrint(lua_State* L)
         lua_call(L, 1, 1);
         s = lua_tostring(L, -1);  /* get result */
         if (s == NULL)
-            return luaL_error(L, LUA_QL("tostring") " must return a string to "
-                                 LUA_QL("print"));
+	    return luaL_error(L, "'tostring' must return a string to 'print'");
         if (i>1) 
             output += "\t";
         output += String(s);
-- 
2.28.0
</pre>

Not that it helps much, there's other different Lua 5.4-related errors in RocketContextsProxy.cpp and Rocket.cpp
