### ISSUE TITLE
Bots ignore dynamic map elements

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1220]
it seens that entities func_spawn and func_destructable are ignored by bots.

**Comment by illwieckz** [comment]
Bots have been reported to miss `func_sarah_connor` repeatedly! :robot:

**Comment by bmorel** [comment]
If this is fixed, maybe it can be closed?

**Comment by Gireen** [comment]
nope. The merged pr only fixed part of the problem. Witch is enough for me but to solve this completely more investigation and changes would be needed.
 
> doesn't work on walls that are spawned on map start

and func_destructable would require the same changes

**Comment by bmorel** [comment]
Yes, it's clearly not fixed.

> But unlike doors bots currently ignore this objects and just try to run trough them

This is even wrong: bots also ignore doors and try to run through them. They do *not* pause but run until the door opens and let them pass, basically. This can be seen notably in usstremor.

**Comment by slipher** [comment]
> bots also ignore doors and try to run through them

That's basically what I do too. Especially with high ping 😛

**Comment by bmorel** [comment]
Won't be easy to fix, especially with recast. Moving to Q3's original AAS might help a lot though.

**Comment by bmorel** [comment]
Is there is a map with those entities? I'd be curious to know what they are meant to do, and see if I can fix that, one way or another.
For now, I'd likely just make them consider those as obstacles, even if that's not a proper implementation.

**Comment by bmorel** [comment]
I'm tempted to close this issue for 3 reasons:

1. it's vague. Yes, bots ignore some stuff, in many cases, and those are all different feature requests (waiting for an event, have subgoals to activate a door before going through it, etc)
2. all of the bot-specific problems I could find in actual maps (more than 50!) were fixed
3. no map was named, so there is no way to easily reproduce the issue

**Comment by Gireen** [comment]
func_destructable can be any brush. it has health and disappears when it received enough damage
but can also be reset by the map

func_spawn can be any brush and be toggled by the map

1. its precise. bots ignore this elements cause they don't update the navmesh
and the related PR shows parts of a solution for this
2. I don't its a good reason to close a issue without fixing, just to close as many as possible. The bug wont go away and when it is found again it requires unnecessary time to investigate its source again. 
3. There are probably plenty of old tremulous maps that use this. Any map where destructible elements are or objects like walls instantly appear or disappear should be affected.

**Comment by bmorel** [comment]
> its precise. bots ignore this elements cause they don't update the navmesh
and the related PR shows parts of a solution for this

Well, then I could say that bots should be able to use them, too, otherwise even if navmesh is updated they'll ignore it, right?

> There are probably plenty of old tremulous maps that use this

I would really like to have a name, so that I could work to make it fixed, once and (hopefully) for all.

**Comment by bmorel** [comment]
func_destructable is fixed in a branch. See https://github.com/Unvanquished/Unvanquished/issues/2054#issuecomment-1427514487

**Comment by bmorel** [comment]
I'm pretty sure this is now fixed. Feel free to reopen with a way to reproduce the problem if you still find one.
