### ISSUE TITLE
Medistation can still heal between death and explosion?

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1226]
While playing chasm, at some point an mantis killed the medistation, I came with a construction kit to deconstruct it before it explodes. While I was close enough to be a bit above the medistation, the medistation animation was played, even if the buildable was already dead. Because I was too much slow to operate, the medistation exploded.

I don't know if I got healed between medistation death and explosion, but for sure, the animation played and it's unexpected.

**Comment by bmorel** [comment]
I believe this is fixed in 0.52.0/sync?
