### ISSUE TITLE
Pause the game at startup until a real player joins

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1227]
It would be cool if on a server the game is paused at startup until a real player joins. This will save a lot of energy on idling servers.

**Comment by Gireen** [comment]
I think that is something that would require to be done on the engine side.

**Comment by slipher** [comment]
I think doing it in the gamelogic would work well. `pause` is implemented as an sgame command.

**Comment by Gireen** [comment]
That's also true. 
`pause` reduces the needed cpu load but has no effect on memory usage.

It depends on how much energy or resources should be saved or how you define this.
For maximum effect the server could cache the status informations and shut down to only responding to status queries.
If then a player connects the server could start again with the announced map.

**Comment by illwieckz** [comment]
At least a simple pause saving CPU cycles would be a lot!

**Comment by necessarily-equal** [comment]
I believe this should be close as https://github.com/Unvanquished/Unvanquished/pull/1234 got merged. (It contains "fix #1234" and not "fixes #1234")
