### ISSUE TITLE
missing cursesw

### ISSUE THREAD

**Issue by ishlun** [Unvanquished/Unvanquished#1240]
Hi! I can't compile Unvanqushed on fedora 33.` cmake -H. -Bbuild` returns 
`Could NOT find CursesW (missing: CURSESW_LIBRARY)`

**Comment by slipher** [comment]
Install the needed library using your package manager. Or alternatively, add `-DUSE_CURSES=0` if you don't want this feature.

**Comment by ishlun** [comment]
Thank you!!!!
