### ISSUE TITLE
Glitch when jumping upward as a dragoon on plat23

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1253]
![Screenshot from 2020-12-30 23-45-48](https://user-images.githubusercontent.com/59283660/103426255-637af400-4bb8-11eb-995f-1dd604165452.png)

![Screenshot from 2020-12-31 22-40-18](https://user-images.githubusercontent.com/59283660/103426367-35e27a80-4bb9-11eb-930f-a6f3169fe23e.png)

As per the screenshot above, the blue "force shield" gets very bright. I guess that's because a lot of copies are over one another. Since it's very short, it almost blinks. It actually happens for all the top parts of the map, except the stellar background

This seems to be related to motion blur, as disabling it makes the effect disappear. I can trigger this with 0.52.0/sync and the released binary (v0.51.1).

**Comment by necessarily-equal** [comment]
hmm, actually maybe this should be moved to daemon's issue tracker.

**Comment by illwieckz** [comment]
Yes, it's already reported here: https://github.com/DaemonEngine/Daemon/issues/34

Disabling bloom looks to prevent it, that's all we know for the moment.
