### ISSUE TITLE
Battlesuit player bounding box is too tall

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1257]
![Screenshot from 2021-01-01 21-41-41](https://user-images.githubusercontent.com/59283660/103445950-5292b700-4c7a-11eb-8cc1-9088a874984e.png)

Example here: I'm firing above the head, and it hits.

This is actually quite a big problem, I thought there was no headshot possible on a battlesuit for quite some time :O

**Comment by illwieckz** [comment]
You can display bboxes with `cg_drawBBOX 1` (if maps was loaded with `devmap`). And you're right, the bsuit bbox seems to be oversized…

**Comment by illwieckz** [comment]
Meh

[![bsuit oversized bbox](https://dl.illwieckz.net/b/unvanquished/bugs/bsuit-oversized-bbox/unvanquished_2021-01-01_215741_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/bsuit-oversized-bbox/unvanquished_2021-01-01_215741_000.jpg)
