### ISSUE TITLE
Outdated comment on default config

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1258]
Comment on https://github.com/Unvanquished/Unvanquished/blob/32bfe2c0a04028706631a2b6f751592598104342/dist/configs/config/server.cfg#L3-L7 is wrong.

Could someone update it?

**Comment by DolceTriade** [comment]
Is this broken?

**Comment by necessarily-equal** [comment]
Seems like it already *was* updated https://github.com/Unvanquished/Unvanquished/pull/1221/files.
