### ISSUE TITLE
improve devteam: get a correct view direction

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1269]
The feature (see #1091) works but can be improved, @Gireen said in #1235:

> I have here a problem with the view direction, it changes when spawning and makes player turn 180°.

**Comment by necessarily-equal** [comment]
I've investigated it a bit. It looks like a lot like the angles view vector isn't copied over to the new entity as the view will point north anyhow. On the other hand, [`src/sgame/sg_cmds.cpp` / `Cmd_Devteam_f`](https://github.com/Unvanquished/Unvanquished/blob/8c6250aa7b0eaf95cdfcc4fadb4c8a87fec3f4cb/src/sgame/sg_cmds.cpp#L543) tries to copy the angles2 vector. (And copying both angles vector or only the other one doesn't fix it either.)
