### ISSUE TITLE
[0.52] Humans don't bleed, they have tiny explosions

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1271]
![Screenshot from 2021-01-06 04-48-48](https://user-images.githubusercontent.com/59283660/103727129-cf0afa00-4fda-11eb-9d4a-18a0d2aada90.png)

See that little explosion on the leg? New regression spotted.

![Screenshot from 2021-01-06 11-49-16](https://user-images.githubusercontent.com/59283660/103761613-3cd51700-5017-11eb-9898-13e24e736c42.png)

![Screenshot from 2021-01-06 11-49-21](https://user-images.githubusercontent.com/59283660/103761643-478fac00-5017-11eb-9032-66fa643aa623.png)

**Comment by illwieckz** [comment]
Is this goon spitting fire for real?

![Human fire blood](https://dl.illwieckz.net/b/unvanquished/bugs/human-fire-blood/unvanquished_2021-02-06_080348_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/human-fire-blood/unvanquished_2021-02-06_080348_000.jpg)

I believe #1272 fixed that, closing this.
