### ISSUE TITLE
bot dretch will never attack turrets

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1304]
But they can theoretically damage them.

https://github.com/Unvanquished/Unvanquished/blob/0.52.0/sync/src/sgame/sg_bot_util.cpp#L668
https://github.com/Unvanquished/Unvanquished/blob/0.52.0/sync/src/sgame/sg_bot_util.cpp#L2093

should probably check if the amount of damages dealt is non-zero and if building is from enemy team instead of checking for class == dretch.

**Comment by illwieckz** [comment]
Hmm, that's probably a relic from the time dretch could not attack anything.

**Comment by necessarily-equal** [comment]
I've got something in the works
