### ISSUE TITLE
[0.52] “growing alien buildable” animation when a buildable is built is not displayed

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1314]
I wonder what introduced this regression.

**Comment by illwieckz** [comment]
[![broken growing alien buildable animation](https://dl.illwieckz.net/b/unvanquished/bugs/broken-growing-alien-buildable-animation/unvanquished_2021-02-09_083344_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/broken-growing-alien-buildable-animation/unvanquished_2021-02-09_083344_000.jpg)

[![broken growing alien buildable animation](https://dl.illwieckz.net/b/unvanquished/bugs/broken-growing-alien-buildable-animation/unvanquished_2021-02-09_083347_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/broken-growing-alien-buildable-animation/unvanquished_2021-02-09_083347_000.jpg)

[![broken growing alien buildable animation](https://dl.illwieckz.net/b/unvanquished/bugs/broken-growing-alien-buildable-animation/unvanquished_2021-02-09_083355_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/broken-growing-alien-buildable-animation/unvanquished_2021-02-09_083355_000.jpg)

**Comment by necessarily-equal** [comment]
Having a look

**Comment by necessarily-equal** [comment]
it was fairly subtle, https://github.com/Unvanquished/Unvanquished/pull/1317

**Comment by illwieckz** [comment]
Fixed by #1317.
