### ISSUE TITLE
Lucifer cannon knockback consumes jetpack fuel

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1323]
The lucifer cannon knockback consumes jetpack fuel. Take a luci, a medium armour and a jetpack, go outside in plat23, aim the floor, charge the luci until it explodes of overcharging, be knocked in air, look at the jetpack fuel bar.

**Comment by Pretuer** [comment]
> look at the jetpack fuel bar.

Maybe The unvanquished army uses auto-stabilsers when you have jp fuel, so it triggers it.

**Comment by necessarily-equal** [comment]
I'm not sure if it's a bug or a feature. When you take damage, your jetpack fuel gets lower, so that's to be expected. Would we want self-damage to be excluded instead?

**Comment by illwieckz** [comment]
Oh, that could be a damage, makes sense then, after #1322 being also related to jetpack I assumed a bug. 😅

Can we figure out that's damage and that's expected? That's probably like when you barb a jetpacker…

**Comment by bmorel** [comment]
I'm pretty certain this is because health damages reduce jetpack's fuel, so I think this issue can be closed.
