### ISSUE TITLE
It's possible to get more than 2K points for humans

### ISSUE THREAD

**Issue by Pretuer** [Unvanquished/Unvanquished#1324]
I got the Battle suit while having a jetpack and I got 20 points more of 2K.

![image](https://user-images.githubusercontent.com/39959123/108088036-103a0380-7089-11eb-9870-7e9f545a464b.png)

**Comment by slipher** [comment]
You can go over 2000 by selling equipment. It's intended behavior that you never lose your credits by selling an item.

**Comment by Pretuer** [comment]
> You can go over 2000 by selling equipment. It's intended behavior that you never lose your credits by selling an item.

okay, I thought that creds were to be maxxed out at 2K
