### ISSUE TITLE
Eye level is too high for the battlesuit

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1327]
I'll need to check, but I suspect that just as the bounding box was too high after changing the battlesuit model, the eye level is too high too.

**Comment by Pretuer** [comment]
agreed, all other players with the B.S. on look shorter

**Comment by necessarily-equal** [comment]
https://github.com/UnvanquishedAssets/res-players_src.dpkdir, `configs/classes/human_bsuit.model.cfg`, change the `eyelevel` value.

To check the eye level, look at a bot in battlesuit. `/give momentum 300; give funds 2000`. In the bot menu, check "unlimited funds" and buy a battlesuit. Compare who has the higher eyes.
