### ISSUE TITLE
Switching to and from a weapon need the weapon to be ready to fire, or reloading

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1338]
For example, firing the blaster makes it hard to switch back to your main weapon, for example. Maybe we can remove the delay, as the delay to switch from a weapon to another is already long enough, IMO. Or maybe we can have the switch automatic once the delay is elapsed?

Instances where I found it frustrating: I'm net to the alien base, for some reason I end up switching from pulse blast to blaster. I shot anyway, because every small bit helps, press the switching key, it doesn't work, I continue firing, I look for the other key that's supposed to switch because obviously that one isn't working and I get killed by the dretch. You would think medium+pulse would handle itself better against a dretch.

Another instance: I'm in base and after a battle where I used the blaster, I switch back to CK with the intent to repair a building. The key press did nothing, so surely it must be the other key, right? Well, that's how you throw a grenade in your base :P

**Comment by slipher** [comment]
The weapon cooldown is needed to prevent various cheats such as switching to blaster and back to fire faster, or firing faster by repeatedly selling the weapan at the armory.
