### ISSUE TITLE
move files from res-* repos to a better suited one

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1352]
In #1336 (make dretch able to attack turrets) there is a discussion that we had on IRC, too, about moving some files from the assets repositories to the unvanquished mod repository.

In a nutshell, current file partitioning makes it difficult to submit changes.
For example, creating an alien form with special ability would require 4 PRs: one for res-players, one for res-weapons, one for unvanquished_src, and finally one last in Unvanquished. This is a lot.
Of course, other examples (and more realistic ones) are less extremes: #1336 (dretch) for example only touches 2 repositories (Unvanquished and res-buildables), #1345 (improvements to bots) should touch 2 repositories too (Unvanquished and unvanquished_src, for adding UI to configure bots).

The reason repositories were split is mostly about performance problems: bandwidth when cloning and disk storage. There may be other reasons, too.

I believe that moving some files from the asset repositories to this repo would make things easier with the PRs, while keeping the performance problem worked around. Namely, those files:

* `*.attr.cfg`: only contains gameplay related informations.
* `*.locdamage.cfg`: only contains gameplay related informations.
* `beacon.cfg`: beacons are only player utilities to communicate.
* `missile.cfg`: those might be split before. Most of their informations are about physics, but some informations refers to graphics and sounds, such as: sprite, spriteSize, trailSystem, impactMark, impactMarkSize, impactParticleSystem, impactSound

I think a 1st step would be to move whole missile.cfg files, since I don't think it makes much sense to have it stored without their affiliated weapon's properties. This would already make life easier, especially considering the fact they are parsed by code which lies in Unvanquished itself.
I suppose splitting missile.cfg files as a 2nd step would make sense, in this regard.

Until now, this ticket only talks about suggestions that would only make things easier to developers. It would not solve the issue of contributing, e.g. a new alien form or defensive building: a contributor would still need to touch multiple repositories.
I suppose a solution for that would be to regroup graphical and sound resources in per-species repository, so that it would also be easier to get the whole "species's theme" and/or tend to more unified species.

I open this issue so that some solutions could be agreed upon, at least for the part I feel the most concerned about: improving code quality, UI and gameplay.

[edit]
There is a problem with that moving files, though: PRs touching them will be invalidated. As of today, the only PR I could see that would be affected is related to #1336.

**Comment by illwieckz** [comment]
It is probably better to do the split/merge jon once 0.52 is released, because even without PR, because some repostories may have `0.52.0/sync` branches and those are implicit PR.

On the topic of “what would be a better layout?” I would like to see the weight of possible `res-aliens` and `res-humans` evaluated (to replace `res-weapons`, `res-buildables`, `res-players`). That may not be a bad idea, but that would be a huge split/merge operation (my [unvanquished_split](https://github.com/illwieckz/unvanquished_split) scripts may be extended in purpose).

**Comment by illwieckz** [comment]
I had a look at `acid_tube.attr.cfg`:

```c
// Generic
humanName         "Acid Tube"
description       "Alien base defense.
Sprays corrosive gas on approaching humans.
Most effective in groups or in conjunction with a trapper."
team              aliens
icon              "icons/iconb_acid_tube"

// Generic limits
unlockThreshold   0
buildPoints       8
buildTime         15000
buildWeapon       alien

// Placement limits
minNormal         0.0
allowInvertNormal

// Vitality
health            125
regen             10

// Explosion
splashDamage      50
splashRadius      100
meansOfDeath      alienBuildable

// Misc
creepSize         64
```

Maybe this can be a config file (or two, see below):

```c
// Generic
humanName         "Acid Tube"
description       "Alien base defense.
Sprays corrosive gas on approaching humans.
Most effective in groups or in conjunction with a trapper."
icon              "icons/iconb_acid_tube"

// Misc
creepSize         64
```

And this can be hardcoded:

```
// Generic
team              aliens

// Generic limits
unlockThreshold   0
buildPoints       8
buildTime         15000
buildWeapon       alien

// Placement limits
minNormal         0.0
allowInvertNormal

// Vitality
health            125
regen             10

// Explosion
splashDamage      50
splashRadius      100
meansOfDeath      alienBuildable
```

In fact the `creepSize` is a “how looks the model” option, it may be part of the model configuration instead, in the repository storing the model.

For `humanName`, `description` and `icon`, living in `unvanquished_src.dpkdir`, especially since the icon lives there. Those fields may also be hardcoded in `Unvanquished`, especially `humanName` and `description`. For `icon`, it's good someone can both rename a file and edit the icon path in the config file in the same repository.

**Comment by bmorel** [comment]
> In fact the `creepSize` is a “how looks the model” option, it may be part of the model configuration instead, in the repository storing the model.

Creep have 2 gameplay effects I think: aliens on it heal faster, and humans walking on it are slown. Increasing creep's size of some buildings is actually something I plan to play with, notably barricades, so that they would make the "open door, retreat from barricade enough so that acid tubes becomes useless and fire" pattern harder, increasing alien defenses' potential (because of the speed nerf, which is also affected by armors, IIRC).

> For `humanName`, `description` and `icon`, living in `unvanquished_src.dpkdir`,

And this reminds me I forgot to mention some file types:

* `*.bt`: bot behavior trees, have a strong dependency with their C++ counterpart (behavior trees can't do maths, for example)
* `*.rml`: those are the UI description. Adding a cVar shuold ideally be reflected in the GUI, so that it would be easier to discover it's existence for players and admins. A simple example on this one is: adding cVar to allow bots to equip armors or radar (related to my #1332 PR).

There may be more files I forgot to mention.

**Comment by slipher** [comment]
For defining attributes in code, we could use a builder pattern, like
```
auto acidTube = AlienBuildingConfig()
    .unlockThreshold(0)
    .buildPoints(8)
    .buildTime(15000);
```

To define fields of a config type we would use a macro e.g. `DEFINE_CONFIG_FIELD(int, unlockThreshold)`. The macro would have two purposes: first, to define the setter method (as shown above) and second, to register the name of the field so that it could be overridden from a `gameplay.cfg` file, which might have lines like `buildables.acidTube.buildPoints 6`.

**Comment by slipher** [comment]
`*.rml` files are very strongly coupled with cgame, with many dependencies in both directions; it is indeed unfortunate that they are in separate repositories. You can hardly change one without the other.

With `*.bt` files the situation is not as bad. It is at least easy to makes some changes to the gamelogic side without breaking backwards compatibility with existing behavior trees.

Most cvars will never be part of the GUI.

**Comment by Gireen** [comment]
Overlapping with #1247
Moving all config files to the Unvanquished repository would already be a huge benefit.
maybe renaming `unvanquished_src.dpkdir` to `res-basics_src.dpkdir` containing ui image assets and the like 
and create a new unvanquished_src.dpkdir in Unvanquished/Unvanquished containing all config, rml and bt files

**Comment by slipher** [comment]
UI images are closely coupled to RML, so I don't think it makes sense to separate those.

**Comment by bmorel** [comment]
True, UI graphics should probably go with code, I don't think they are heavy enough to justify being outside of repository.
And yes, it seems #1247 is about the same problem, thanks gireen.

**Comment by illwieckz** [comment]
@Gireen, see https://github.com/Unvanquished/Unvanquished/issues/1371

**Comment by bmorel** [comment]
I believe this issue could be closed, now, considering it was (mostly?) fixed.

**Comment by illwieckz** [comment]
Yep, the files listed as to-be-moved were moved. We may discuss other files in other threads.
