### ISSUE TITLE
Duplicate GUID

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1357]
If a client crashes or has connection issues resulting in reconnecting to the server, it happens that connecting is denied with the message.
`Duplicate GUID`

Witch indicates that the server thinks the unresponsive but still connected client is not lagging. 

https://github.com/Unvanquished/Unvanquished/blob/2783e77acc2e41fc1f717124394ed851f1b612e6/src/sgame/sg_client.cpp#L1218-L1222

**Comment by Gireen** [comment]
To reproduce this bug kill Unvanquished while connecting to a server. 
If one then reconnects its not possible with the warning `Duplicate GUID`

**Comment by slipher** [comment]
I think we should keep this open to remember to investigate why lagging players can have 0 ping. It is possible to legitimately have 0 ms ping so the heuristic of 0 means lagging is not perfect.
