### ISSUE TITLE
Connecting problems are only printed to the console

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1365]
If there is problem while connecting there is only a warning printed in the console.
This might happen when:
-connecting to a password protected server
-servers with mod and no downloads enabled
-if a player is kicked
 
It would be nice if we could again a window show up containing the message.

**Comment by necessarily-equal** [comment]
This probably would be best implemented by a Sys::Drop after https://github.com/Unvanquished/Unvanquished/issues/1501 gets fixed.

**Comment by cu-kai** [comment]
I think this can be considered as closed by https://github.com/DaemonEngine/Daemon/pull/937
