### ISSUE TITLE
Dretch bots become slow as soon as I join as human player

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1374]
That's weird because I don't reproducing it on RC server, but I reproduce it locally and it looks like I use the same commit references… 🤔

When I add alien bots, dretches walk at their usual fast speed, but as soon as I join as human, they are ridiculously slow.

**Comment by illwieckz** [comment]
I do like:

```
/bot fill 10 aliens
```

Aliens are fast!

Then I join as human, aliens are slow!

I then do:

```
/bot fill 10 humans
```

Aliens are fast again!

**Comment by illwieckz** [comment]
When running the 0.52 RC2 build and do the same, the aliens are not slow, but I see many dretches coming back and forth…

**Comment by illwieckz** [comment]
I reproduce the issue with own dæmon build from `0.52.0/sync`, with cgame and sgame buillt own build (as shared libraries) from `0.52.0/sync`, and the dpk files from 0.52 RC.

**Comment by illwieckz** [comment]
@bmorel Can you try to reproduce it? There may be a regression in bot code.

**Comment by slipher** [comment]
Fixed by https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/48.
