### ISSUE TITLE
Give "sprint" a visual clue

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1390]
The only way to know you are sprinting is that your stamina reduces when you move. I think this could be improved, maybe by changing bar's colour, the same way as wall-walking have visual clue.

**Comment by Gireen** [comment]
Its strange i thought there was already an indicator for this, that the logo would light up or so.

**Comment by necessarily-equal** [comment]
I wanted to make the stamina bar to close this, but it turns out to be more complicated than I thought, and I am thus waiting on the RML-UI port before doing the low-level reworks that would require.
