### ISSUE TITLE
The long time issue about the pulse rifle disappearing

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1393]
It is known the pulse rifle is disappearing when is pointed toward X, Y or Z axis.

It was noticed that If the player reloads the weapon magazine while the pulse rifle is not rendered, the pulse rifle briefly reappears then disappear, while the gesture make it not pointing the axis.

This bug was talked about back in 2014 in https://github.com/Unvanquished/Unvanquished/issues/409

But that issue also tracked another bug that is fixed, so let's use that thread for the specificity of pulse rifle.

**Comment by illwieckz** [comment]
At the time, @Viech said:

> It doesn't happen for me, except with the weapons that have a bogus rendering bounding box (e.g. the pulse rifle) which makes them disappear depending on the animation and probably the field of view. Never continuously though.

And @DolceTriade said:

> when it disappears, see if r_nocull 1 makes it reappear.

For the bug tracked in #409, it changed nothing. But I noticed `r_nocull 1` fixes the pulse rifle issue on my end.

**Comment by illwieckz** [comment]
Adding `cull disable` keywords in pulse rifle materials does not workaround the issue.

**Comment by illwieckz** [comment]
Here: https://github.com/DaemonEngine/Daemon/blob/478350a73aceb8e90729c1167a70885a75174bb7/src/engine/renderer/tr_main.cpp#L344-L347

Changing this test by true:

```
cullResult_t R_CullBox( vec3_t worldBounds[ 2 ] )
{
	bool anyClip;
	cplane_t *frust;
	int i, r;

	if ( r_nocull->integer ) // ←
	{
		return cullResult_t::CULL_CLIP;
	}
```

workarounds the bug, without obvious performance hit, at first glance (culling is done everywhere else).

**Comment by illwieckz** [comment]
Here: https://github.com/DaemonEngine/Daemon/blob/478350a73aceb8e90729c1167a70885a75174bb7/src/engine/renderer/tr_model_iqm.cpp#L925-L941

Replacing the `R_CullBox()` call by `cullResult_t::CULL_CLIP ` in switch test:

```c++
static void R_CullIQM( trRefEntity_t *ent ) {
	// …

	switch ( R_CullBox( ent->worldBounds ) ) // ← here
	{
	case cullResult_t::CULL_IN:
		tr.pc.c_box_cull_md5_in++;
		ent->cull = cullResult_t::CULL_IN;
		return;
	case cullResult_t::CULL_CLIP:
		tr.pc.c_box_cull_md5_clip++;
		ent->cull = cullResult_t::CULL_CLIP;
		return;
	case cullResult_t::CULL_OUT:
	default:
		tr.pc.c_box_cull_md5_out++;
		ent->cull = cullResult_t::CULL_OUT;
		return;
	}
}
```

workarounds the bug, without obvious performance hit, at first glance: culling is done everywhere else, including other parts of the code that also call `R_CullBox()`.

Note: It looks like other model code (md5, md3) does not have similar culling code.

**Comment by illwieckz** [comment]
@DolceTriade, given you were already suspecting culling at the time, what is your opinion on this? Does it ring another bell?

**Comment by slipher** [comment]
Viech's comment about the bogus bounding box seems to be accurate. I found that the pulse rifle disappears only when I am facing in certain directions. This makes sense because the cull calculations use axis-aligned boxes to bound the extent of the model, meaning the calculation is affected by rotation of the viewpoint.

The bounding box is apparently not part of the IQE, but [generated by the converter](https://github.com/lsalzman/iqm/blob/0ae27ac0843cc31740d12de72533d08ae3a81458/blender-2.80/iqm_export.py#L363) (is that the script?). So I don't know if the problem is in the IQE, the converter, the gamelogic or the engine.

I opened https://github.com/DaemonEngine/Daemon/pull/459 which is similar to illwieckz's suggestion above, but more selective by applying to 1st-person models only.

**Comment by illwieckz** [comment]
Prior to 0.51, we were using `.iqm` files that were either produced by the [Blender python exporter](https://github.com/lsalzman/iqm/blob/0ae27ac0843cc31740d12de72533d08ae3a81458/blender-2.80/iqm_export.py#L363) you linked, either converted from `.md5mesh` format using the [`iqm` c++ tool](https://github.com/lsalzman/iqm/blob/0ae27ac0843cc31740d12de72533d08ae3a81458/iqm.cpp).

For the 0.51 release, those iqm models were converted back to `.iqe` text format for inclusion in repositories, using [`iqm_to_iqe.py`](https://github.com/ccxvii/asstools/blob/0c52fe1abfa13988d05238d4f45c7376576d6cc3/iqm_to_iqe.py), `.iqe` files we convert to `.iqm` again at asset build time using [FTE's `iqm` fork, revision `5570`](https://sourceforge.net/p/fteqw/code/5570/tree/trunk/iqm/) (that supports complete translation/rotation/scaling at build time while still being easy to build without FTE QW).

So, the issue was reproduced before we convert buggy iqm back to iqe, and reproduced after we recompiled that iqe to iqm again. So the various steps of conversion seems to not affect the bug, or to reproduce the bug constantly.

**Comment by illwieckz** [comment]
That six years old issue is now fixed (worked around).

Celebrate, dance, sing songs of joy! 🕺💃
