### ISSUE TITLE
Apple Silicon support?

### ISSUE THREAD

**Issue by rafi16jan** [Unvanquished/Unvanquished#1396]
When first I saw build-macosx-app-universal.sh file I thought it was the new universal build (x86-64 + arm64) but after I read the source it was actually the old 32 + 64 x86 universal build. Is the new Apple Silicon supported?

**Comment by slipher** [comment]
> Is the new Apple Silicon supported?

Not directly. You can use the compatibility mode.

**Comment by rafi16jan** [comment]
I'm trying to build Unvanquished without NaCl as I came across this https://github.com/Unvanquished/Unvanquished/issues/1015#issuecomment-320276902. Looks like compiling using `-DBUILD_GAME_NACL=0 -DBUILD_GAME_NACL_NEXE=0` is not supported anymore? Because I got "Unrecognized host architecture" error from daemon/libs/nacl/native_client/src/include/portability.h (NaCl still compiles)

**Comment by slipher** [comment]
`-DBUILD_GAME_NACL=0` disables building of the gamelogic binaries which run inside the NaCl virtual machine.

This error comes from the infrastructure for hosting the virtual machine, which is required to play the game, and does not support your architecture. So I guess you should try `-DCMAKE_OSX_ARCHITECTURES=x86_64`.

**Comment by rafi16jan** [comment]
> `-DBUILD_GAME_NACL=0` disables building of the gamelogic binaries which run inside the NaCl virtual machine.
> 
> This error comes from the infrastructure for hosting the virtual machine, which is required to play the game, and does not support your architecture. So I guess you should try `-DCMAKE_OSX_ARCHITECTURES=x86_64`.

Ohh. So even though I pass `-DBUILD_GAME_NACL=0 -DBUILD_GAME_NACL_NEXE=0` the NaCl is still needed? My understanding of @illwieckz's comment:
> it's probably not a problem to run the game code/server code as shared libs.

is that NaCl can be bypassed?

**Comment by slipher** [comment]
You can't disable building of the code used to host NaCl virtual machines. This code is needed if you want to play on online servers.

**Comment by rafi16jan** [comment]
I don't want to actually, I just want to play local games

**Comment by slipher** [comment]
> You can't disable building of the code used to host NaCl virtual machines.

Still stands.

**Comment by illwieckz** [comment]
Hi @rafi16jan, would you be able to test the our latest release candidate of next version of Unvanquished and confirm it works correctly with the compatibility mode? https://forums.unvanquished.net/viewtopic.php?f=4&t=2221 =)

**Comment by rafi16jan** [comment]
> Hi @rafi16jan, would you be able to test our latest release candidate of next version of Unvanquished and confirm it works correctly with the compatibility mode? https://forums.unvanquished.net/viewtopic.php?f=4&t=2221 =)

You mean install it via Rosetta directly right? (Without building or anything)

**Comment by illwieckz** [comment]
Yes, using the amd64 binaries in the zip, relying on Rosetta2 compatibility layer. Once extracted, make sure the `Unvanquished.app` (in `macos-amd64.zip`) is next to `pkg/` directory, as explained in the `README` file. If I'm right someone told me the 0.51.2 was working, I want to make sure our next release, the 0.52 one, runs as expected.

**Comment by rafi16jan** [comment]
Okay, will do

**Comment by illwieckz** [comment]
Hi @rafi16jan, do you have any news about that test? 🙂

**Comment by rafi16jan** [comment]
> Hi @rafi16jan, do you have any news about that test? 🙂

Sorryy, I am indeed very keen to test it but Apple as usual really likes surprise and decided to disable some of my apps on the latest big sur update and I'm currently downloading the downgrade image. I live in a pretty much rural area so the internet is bad here, will soon download Unvanquished after that though 🙏

**Comment by illwieckz** [comment]
@rafi16jan For your information the current master branch of the engine can now be built for `arm64` on Linux (not on mac). The problem we face with macOS is that the NaCl virtual machine we use to run the sandboxed game code doesn't support arm on macOS.

Right now on macOS we run both the engine and the virtual machine with Rosetta 2.

What may be theoretically possible would be to have a native arm64 engine on macOS running the game virtual machine on Rosetta 2. So half of the game would be native, and the native half would be the one requiring the most performances.
