### ISSUE TITLE
using right click when observing a sniper user triggers the zooming shader

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1399]
To reproduce, with RC6's default bindings: run with ` /devmap plat23; bot fill 4`, forbids human bots to wear any weapon which is not sniper, give them infinite funds. Spec a human bot, and try to "unspec".

**Comment by necessarily-equal** [comment]
To me, without looking much into the issue, it sounds like the problem is that cgame is using the keybinds of the team you have joined instead of the .

looks like src/cgame/cg_main.cpp:548

**Comment by slipher** [comment]
Binds are not the cause of the issue. It is normal to have a non-team-specific secondary fire bind. And regardless of binds, you can still execute the secondary fire command, and it should not do a zoom for spectators.

**Comment by bmorel** [comment]
Can I put the confirmed tag, here? I'm still the only one reporting it.
