### ISSUE TITLE
medistation effect blinds the user

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#1409]
It was suggested to me by a player, than the medistation animation blinds the user too much.

**Comment by slipher** [comment]
It's an anti-camping feature :smirk:

**Comment by illwieckz** [comment]
I'm annoyed by that. I had the idea to blend the effect as much as you're close to it.

Basically it would be very translucent when being on the medistation, and like it is now when looking someone else on the medistation.
