### ISSUE TITLE
let players give instructions to bots

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1418]
This is feature request, which would allow implementing a way to give basic instructions to bots or ask them what they're gonna do. If bots could read instructions which are destined to all bots, close bots (use SAY_TEAM_AREA) or specific a bot (private message or start the request with $BOT_NAME).

**Comment by slipher** [comment]
Probably should use beacons for the instructing of bots.

**Comment by Gireen** [comment]
>Probably should use beacons for the instructing of bots.

That was also my first thought. But it might actually provide usable. 
If the chat commands are given with a circlemenu they are easy to use and readable for the whole team.
They could be used not only for bots but all players. 
Some examples:
```
- Defend Base
- *botname* attack from *roomname*
- Someone follow me
- Help
- Defend *roomname*
- *botname* fallback 
- OM/RC down
```

Bots and players could also announce what they are doing.
PMs to bots are not so good they could be easy abused.
I think beacons are still needed but this could be a good addition to it.

**Comment by bmorel** [comment]
On another FPS I play, this is how it works: teamchat menu sends to team chat, providing "instruction presets" which can be read by both bots and humans (all of team, basically).
There's no beacon by themselves, but the game would not really use them, it's not strategical enough.

Beacons can be used to point at/give objectives, but as Gireen said, they can't be used to say things like "follow me", "retreat", and the like: they really says "defend this", "attack this in 30s", etc. This is in my opinion a different kind of instructions, and I think both can be useful.
Also, beacons are given to whole team, which might end up in a mess. Unvanquished provides area chats, which might be more suited to quickly give instructions (or feedback on what one's doing) without flooding the whole teamchat (chat is hard enough to follow as it is, let's not add too much burden on it, even if someone improves it at some point, it's always better to have things giving a higher signal/noise ratio).

**Comment by slipher** [comment]
There's also `vsay` / `vsay_local` / 'vsay_team` ... you can see the available sounds [here](https://github.com/UnvanquishedAssets/res-voices_src.dpkdir/tree/master/voice). They are rarely heard since there is no UI to issue them. Except the grenade one which is automatically sent when you throw a grenade.

**Comment by Gireen** [comment]
We can skip the whole chat part and give bots direct instructions by adding a console command like botcmd or so.
There could still be an additional chat text but bots would only have to react on the command.
For example `botcmd Bot#1 rush` could change just the rushscore for the bot.
Or `botcmd Bot#1 follow` could change the behavior to escort and set the player as goal. 
There is no escort Behavior or different goal prioritys but it could be used like that.

**Comment by bmorel** [comment]
I think sending bots orders (or instructions or informations) through chat is interesting in that it may allows bots to react to informations given by their mates (such as, cover someone which is reloading or retreating).
of course, orders will be easier to implement than situational behaviors, but I think if orders are done through team chat, that'll help implementing further squad play.

**Comment by Gireen** [comment]
But that doesn't require bots to read the chat. Except if you want to create something where players have to write a message and text recognition would then interpret this. That would be interesting for complex conversations or voice recognition but not simple commands. 

To make a better example: Grenades.
At the moment if a grenade is thrown there is a textmessage send. Instead of having bots read this and interpret it we would instead additional to the text also send a command like `botcmd watchout grenade`

**Comment by Viech** [comment]
I think the existing beacons are nice for this as they are already meant for communicating with other players quickly. Adding another command just overloads the UX. For instance, the _grenade_ beacon could make bots avoid grenades placed in a sphere around it. That alone would be super useful. This can encourage players to use the existing beacons as well.

**Comment by Gireen** [comment]
😐  yes that's right, the example works only in comparison to text parsing.
Human Bods should just avoid grenade enitys all the time. 😄

I think there are overlapping elements with bot commands and beacons with general orders. But there is nothing to give a specific bot a command. Beacons don't offer that functionality. Sure we could just let the closest bot react on a beacon, that's better than nothing but if you want to give a command to a bot that is not around its not possible.

**Comment by Viech** [comment]
I think Unvanquished is too fast paced for you to ever want to give a command to a particular bot in a live match. Personally I would want them to rush with me, defend with me, dodge grenades, maybe follow me around. Apart from that I wouldn't want to micro-manage them.

**Comment by bmorel** [comment]
It's not about micro managing them, but about giving hints of what you'll do.
I'm suggesting using a command-menu which would emit chat for that very reason: communication between players is _also_ hard and slow, and such a command-menu could even help with that. Of course, for that, we need menus which do not freeze players, but that's a different issue.

Using normal chat instead of another dedicated mechanism also allows one to bind keys for that, and considering the fact daemon have "say" facilities for area, it allows you to not need to confuse people on the whole team nor to somehow point at them, which would be, indeed, slow.

**Comment by slipher** [comment]
Vsays also have area- and team-limited broadcast.

**Comment by Gireen** [comment]
> Using normal chat instead of another dedicated mechanism also allows one to bind keys for that

thats wrong. for one you can bind anything to keys, then you also can bind multiple actions to a key.

We are here not restricted to chose only one way over another. 
In the extreme case one could make 

```
bind 5 "say Bot#2 attack; botcmd Bot#2 attack; beacon attack"
```

In every case we would need a way for bots to have more goals, weighted in different priority depending on its current state.
For example  Attackcommand/beacon, closer enemys and the need to heal.

**Comment by bmorel** [comment]
> In every case we would need a way for bots to have more goals, weighted in different priority depending on its current state.

Working on it, at least the weighting. As for "more goals" I think it would be easier to make this change their root behavior, instead of adding more goals. Easier to maintain.
Still need a way to have 2 different "targets" at a time, one short-time (the enemy attacking you) and a long-time one (the medistat you want to reach) but that's probably not that hard to build, when bots are able to read-access instructions (needs time, but I don't think it's hard, per-se).

**Comment by bmorel** [comment]
> but stuck-detection isn't: If there has not been an enemy entity on your navmesh for x time, you are stuck.

Would be a lot more reliable than current method (which is to check for traveled distance in the last few time, which makes bots bug quite a lot: when repairing (this one is "fixed" with a workaround but still), when healing, when attacking...) for sure.

**Comment by Viech** [comment]
Yeah that is not very sensible. Not being stuck is easily defined by being on a navmesh that allows you to interact with the game. If there's only friends on that mesh including a significant number of buildables then you are stuck in base, which is a common problem that leaves only defense as an option. If there is nothing you'd want to either defend or attack on your mesh (or when you are not even on a mesh), then you are clearly not getting anything done in the near future.

**Comment by bmorel** [comment]
Now, that would make bots chain suicide in some maps, still, like hangar28 or rsmse (which currently can not be played by bots, I still hope to fix that soon though) but I'm not sure it's that much of a problem

**Comment by bmorel** [comment]
Limited instructions can be handled cleanly with some changes I have in mod, but requires more work. I believe it can be done for 0.54.

**Comment by bmorel** [comment]
Has to be noted that @sweet235 had some changes merged for this. I do not know if this enough to close the issue though?

**Comment by DolceTriade** [comment]
I would think so. Any improvements should have issues of their own.

For reference, this was implemented in https://github.com/Unvanquished/Unvanquished/commit/756925e9ec1a4d31e680511423f2ba3609057ba0
