### ISSUE TITLE
Make Arch Linux use the distro-independant running scripts.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#1428]
The Debian package scripts are expected to be up to date and working (see https://github.com/Unvanquished/Unvanquished/pull/1135 ). I fixed them. I not only fixed Debian stuff, I improved some of those files to be reusable by other distros.

For example, Arch package has yet to be updated to the new distro-independant running scripts, which are meant to ensure to reduce duplication of efforts and feature fragmentation.

_Originally posted by @illwieckz in https://github.com/Unvanquished/Unvanquished/issues/1422#issuecomment-857235917_

**Comment by illwieckz** [comment]
One side topic being redoing the .desktop file (also a side topic for Flatpak).

Currently we have in repo:

- [`archlinux/unvanquished.desktop`](https://github.com/Unvanquished/Unvanquished/blob/6ac003a0ceee239fa56a97b0b2de782b6f91be53/archlinux/unvanquished.desktop) (2014)
- [`debian/unvanquished.desktop`](https://github.com/Unvanquished/Unvanquished/blob/6ac003a0ceee239fa56a97b0b2de782b6f91be53/debian/unvanquished.desktop) (2012)

They are both outdated, for example they both path URL without `-connect` prefix that became mandatory inhttps://github.com/DaemonEngine/Daemon/commit/64fb03c06afebcf8eddd9dbdf545a5d3a9773999

One thing, though, they are currently hardcoding the engine path in `Exec=` line, so it's distro-dependant. On my Ubuntu system, system wide `.desktop` files just use non-absolute paths given `/usr/games` is in `${PATH}`, so maybe that can be a solution to avoid duplication.

**Comment by Viech** [comment]
I would be fine patching the `.desktop` file in my `PKGBUILD`.

(Although I honestly think `/usr/games` is weird and should not exist; `/usr/lib/PACKAGE` is clearly the place for `PACKAGE`-specific binaries that you don't want in your `PATH`, no matter what kind of application `PACKAGE` is.)

Sorry for the duplicate, the "make an issue from this comment" function was just too snappy. (Should've pinged me in #1425 though.)

**Comment by illwieckz** [comment]
No worry about the duplicate, I got a big smile by discovering your title was almost the same as mine. 😃

About paths, I even don't know if the Debian package follows Debian guidelines…

**Comment by Viech** [comment]
Both `unvanquished` and `unvanquished-git` use the distro-independant scripts (and additional attached files) now.
