### ISSUE TITLE
Some particle rendering regression since 0.52

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1431]
0.52:

[![particle regression](https://dl.illwieckz.net/b/unvanquished/bugs/particle-regression/unvanquished_2021-06-12_051148_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/particle-regression/unvanquished_2021-06-12_051148_000.jpg)

master:

[![particle regression](https://dl.illwieckz.net/b/unvanquished/bugs/particle-regression/unvanquished_2021-06-12_051239_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/particle-regression/unvanquished_2021-06-12_051239_000.jpg)

**Comment by illwieckz** [comment]
@slipher it looks to have been introduced in d5906850945dc0b0610380b49d3d965fb7a645c6

**Comment by slipher** [comment]
Hmm, there probably shouldn't be an `else` on line 1599.

**Comment by illwieckz** [comment]
That's not that.
