### ISSUE TITLE
add an encyclopedia

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1436]
The game lack a built-in encyclopedia, which would document the rules. Such encyclopedia might contain tips (as reported in #1435) but I think most if not all it's content should be generated from the actual rules of the game.

What it would contain would be, for example:

* description, damages, rate of fire and cost of weapons
* description, health, movement speed, regen rate, cost of classes
* description, cost of upgrades
* same for buildables

Ideally, with icons (from buy/construction menu), images and screenshots, but I think those (especially screenshots) are subject to deprecation so may not be that useful.
Intent would be to demystify the game's inner working, despite the lack of tutorial

**Comment by Gireen** [comment]
That's more or less what the human buy menu already displays.
This could be just extended for aliens and buildings.

The source of this informations is tricky. One could extract all gameplay settings from unv and create a list that is usable by lua in the ui.
Or if #1247 was implemented those settings could be accessed directly as cvars.

**Comment by bmorel** [comment]
I think discussions led to: won't implement (on irc).
