### ISSUE TITLE
destroyed buildings can be deconstructed, preventing them from exploding

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1437]
All is in title. I'm pretty sure it's not what is wanted.

Thx Super Dupont for talking about it

**Comment by slipher** [comment]
This has been known for a long time, and considered a "responsibility" of builders to prevent further base damage. I haven't seen anyone viewing it as a bug before.

**Comment by illwieckz** [comment]
This is intentional indeed, you have to deconstruct the dead buildable to prevent the explosion to cause further damage on close buildables. You can add a tip for that, it's not a bug, you're even expected to do this.

**Comment by illwieckz** [comment]
Note: in the past we had repeater that could were designed to cause large damage when exploding, even being able to cause chain reaction… So the deconstruction of dead buildables was even _taught_ to new players. Now it's less critical, bu still, this is part of gamplay.

**Comment by bmorel** [comment]
Then this is a documentation bug :)
