### ISSUE TITLE
Setting resolution + graphical settings via CLI

### ISSUE THREAD

**Issue by michaellarabel** [Unvanquished/Unvanquished#1440]
Hi, many releases ago with Unvanquished for benchmarking I was able to pass +set r_customwidth and +set r_customheight to ./daemon when launching followed by +vid_restart and it worked out fine for testing different resolutions. Similarly, using +presets with the preset cfg file desired for high/medium/ultra configurations worked as well for automating the demo testing with Unvanquished.

With Unvanquished 0.52.1 this no longer seems to be the case. Is there new CLI options recommended for setting the resolution/graphics or perhaps just some option that needs to be set that I am missing?

Thanks for any guidance.

**Comment by illwieckz** [comment]
Hi @michaellarabel that would be awesome to get unvanquished benchmarks. =)

If I'm right, the command to set a borderless window with a custom resolution is:

```sh
./daemon -set r_fullscreen 0 -set r_noBorder 1 -set r_mode -1 -set r_customWidth 1920 -set r_customHeight 1080
```

Note: When doing [those tests](https://wiki.unvanquished.net/wiki/GPU_compatibility_matrix) I never seen (I mean seen, not measured with tools) any performance difference when using windowed mode instead of fullscreen (even on 15 years old computers), so I would recommend doing benchmarks in windowed mode as it makes easier to use arbitrary custom resolutions even if the screen may not support it in fullscreen mode.

**Comment by illwieckz** [comment]
About syntax, we now like, `-syntax` for engine stuff and `+syntax` for game commands

For example:

```sh
temp_unv_home="$(mktemp -d)"
./daemon -homepath "${temp_unv_home}" +devmap plat23
rm -r "${temp_unv_home}"
```

**Comment by michaellarabel** [comment]
Hmm okay, trying again looks like it might be working now with some tweaks. In which case will have up some GPU benchmarks soon. Thanks.

The only other difference compared to years ago is that now the ability to easily quit Unvanquished on demo completion doesn't seem to work any longer. Previously was doing along the lines of +timedemo 1 +set demodone "quit" +set demoloop1 "demo pts26" +set nextdemo "vstr demodone" +vstr demoloop1

Now that nextdemo handling doesn't seem to work, after adjusting for demo_play and other demo/timedemo string related differences with the latest Unvanquished versions. In which case I am now just monitoring the log file for "Demo completed" and killing the process, but if there is some other way to achieve the above / "time demo quit" that would be useful.

**Comment by illwieckz** [comment]
If you want to make a significant demo, you can load the plat23 map, have some look at the default outside scene (easy scene), then have a look on the alien base scene (heavy models scene), then buy a flamer and fire it for 5 sec somewhere in the human base (heavy gfx with real time lights on reliefmapped textures).

You can type that in game console to unlock everything to buy or build what you want, given you loaded the map with `devmap` (cheats enabled):

```
/give momentum 9999 ; give funds 9999 ; give bp 9999`
```

**Comment by illwieckz** [comment]
This command will put the camera on the heavy plat23 alien base scene, for example I myself don't mark as `passed` in our compatibility matrix a GPU that can't render this scene as 60 fps:

```
/setviewpos 2062 1891 12 0 0
```

Even if some are hidden by the edges, there is 11 models on this scene, among the most complex ones.

You can also set this other similar scene with a bsuit and a flamer:

```
/setviewpos 2332 1841 46 67 
```

Firing the flamer there as human will produce a very heavy scene, it will add soft particles from alien acid tubes, plus flames and heat haze. Use `/god` to not die at all.

From anywhere you can type `/viewpos` in game console to get viewpos values you may want to set by command line.

**Comment by illwieckz** [comment]
> Now that nextdemo handling doesn't seem to work, after adjusting for demo_play and other demo/timedemo string related differences with the latest Unvanquished versions. In which case I am now just monitoring the log file for "Demo completed" and killing the process, but if there is some other way to achieve the above / "time demo quit" that would be useful.

@slipher, do you know if we have something handy for that use case? I know some parts of the demo code was deeply rewritten but don't know that part that much.

**Comment by slipher** [comment]
I probably deleted that stuff. I don't see anything better than scanning for "Demo completed."

**Comment by illwieckz** [comment]
@michaellarabel I tried to run the Unbanquished benchmark using PTS but for some reason the actual script never finished on my computer (the `tail` never ended).

So I modified the script like this on my end and it worked:

```sh
#!/bin/sh

cd unvanquished_0.52.1

./daemon $@ > $LOG_FILE 2>&1 &

# Daemon seems to have dropped timedemoquit-like functionality as used in unvanquished-1.5.1 test profile and prior
sleep 1
while ! grep -q '^Demo completed$' $LOG_FILE
do
	sleep 1
done

killall -9 daemon
```

I opened an isssue on our end so we can take care of providing a convenient option to quit the game after a demo has played in the future: https://github.com/DaemonEngine/Daemon/issues/487

Anyway, all my benchmarks, whatever screen resolution and preset had a result of an average 150fps, which makes no sense.

I then remembered we have to set `common.framerate.max 0` to unlock framerate, but then after having set it to zero, the benchmark was still caped at 150fps. What's weird is that anyway our default limit is `125` not `150`… so I don't know what is capping the framerate when running Unvanquished through PTS.

**Comment by illwieckz** [comment]
> so I don't know what is capping the framerate when running Unvanquished through PTS.

That may just be my CPU 😅

**Comment by illwieckz** [comment]
@michaellarabel with Unvanquished 0.53.0 there will be a generic `common.shutdownOnDrop` option to quit the engine on game end (called `drop` in engine terminology), which means it will also quit the engine on demo end if the option is enabled.

The option will be usable this way:

```
./daemon -set common.shutdownOnDrop on -set demo.timedemo on +demo_play […]
```

Also for your information I'm working on a script to generate at release time an up-to-date demo tailored for benchmarking purpose because demo may be tied to release.

I'll remind you those things the day we publish the release so you can update the PTS benchmark properly. 👍️

I assume all the questions or needs got an answer, let's close this ticket. 🙂️
