### ISSUE TITLE
0.52.1 randomly sent back to main menu with mouse stuck in top left corner

### ISSUE THREAD

**Issue by ZikZakFR** [Unvanquished/Unvanquished#1444]
I installed 0.52.1 as I could not join a server with 0.52.0, trying to do so will only result in a zero bps download forever.
0.52.1 randomly (quite often and usually within 5 minutes) kick me out of the game, I'm back on the main screen with a mous pointer stuck in the top left corner.
I have to switch back to my window manager to get back control and rejoin or close the game.

uname:
5.12.12-arch1-1 #1 SMP PREEMPT Fri, 18 Jun 2021 21:59:22 +0000 x86_64 GNU/Linux

There is this message in the console when it happens:
Warn: IPC: Socket closed by remote end 
...
Error during cgame shutdown: IPC: Failed to send message: Broken pipe 
Warn: VM exited with non-zero exit code 245

**Comment by slipher** [comment]
Probably this same crash reported [on the forum](https://forums.unvanquished.net/viewtopic.php?f=6&t=2232). #1441 should fix it.

**Comment by slipher** [comment]
lautre on IRC discovered that the crash occurs when selecting the "Lowest" graphics preset. It can be prevented by selecting "Low" or higher.

**Comment by ZikZakFR** [comment]
> lautre on IRC discovered that the crash occurs when selecting the "Lowest" graphics preset. It can be prevented by selecting "Low" or higher.

I'll check that.
My graphic settings are set manually and quite high actually, almost all switch-on and 4K resolution.
Previously I tried by switching off the 'exprimental' ones, to no success.

**Comment by slipher** [comment]
Supposedly the actual setting that makes the difference is `/cg_bounceParticles 1` (OK) vs. `/cg_bounceParticles 0` (crash).

**Comment by ZikZakFR** [comment]
Default setup at max is ok, medium too. 3 games in a row without a single crash.

**Comment by necessarily-equal** [comment]
So I think this is fixed now?

**Comment by ZikZakFR** [comment]
The workaround worked, I haven't checked yet if by reactivating the visual enhancement on particles I get a crash again.

**Comment by slipher** [comment]
There hasn't been a new release since the bug. Some servers have rebuilt their game modules since the release and thus have the fix, but if you then go on others it will crash again.

**Comment by bmorel** [comment]
still around?
