### ISSUE TITLE
Failed to initialize download

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1445]
On some servers (all except unvanquished.net) its not possible to download 0.51.1 files.

For example remove res-weapons_0.52.1.dpk

Connecting to a server is stuck on the download window and in the console repeats

```
Bad download base path specification 
Failed to initialize download for 'dl.unvanquished.net/pkg/res-weapons_0.52.1.dpk
```

**Comment by illwieckz** [comment]
The I've set my own server (gg.illwieckz.net) as fallback url of unvanquished.net, and I was surprised that when I uploaded the bugfix and joined unvanquished.net, the bugfix was downloaded from my server (so the fallback), if the primary download on dl.unvanquished.net failed that may explain why…
