### ISSUE TITLE
Proof that navmesh can go through walls

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1448]
This looks OK right?

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_230758_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_230758_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231237_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231237_000.jpg)

No!

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_230817_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_230817_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231044_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231044_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231104_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231104_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231119_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231119_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231124_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231124_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231145_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231145_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231148_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231148_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231200_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231200_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231251_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231251_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231253_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231253_000.jpg)

[![bots and fake door](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231256_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/bots-and-fake-door/unvanquished_2021-07-05_231256_000.jpg)

**Comment by bmorel** [comment]
some more:

![2021-09-11-131421_1366x758_scrot](https://user-images.githubusercontent.com/1316300/132946090-4330133e-6cb6-4b5d-b77a-ca9ace027b61.png)
![2021-09-11-131602_1366x758_scrot](https://user-images.githubusercontent.com/1316300/132946096-51b89e5c-f81d-440a-be89-5fe0874358ad.png)

**Comment by bmorel** [comment]
Note that this problem is still true with updated recast, even if it improved the situation a bit.

**Comment by bmorel** [comment]
This is also a daemonmap bug, and/or might be caused by maps directly. It is not directly linked to unvanquished.

**Comment by bmorel** [comment]
Note that the screens here are on station15

**Comment by bmorel** [comment]
According to some of my recent experiments, it seems this is caused by lack of precision in the navmesh generator, but I don't know enough yet to be certain about that.
Those experiments also shown that navmeshes can go under stairs in some conditions, and this particular issue may be related to that.

**Comment by necessarily-equal** [comment]
There is currently no such navmesh that goes through wall at this place on this map. Either this problem was due to an older version of recast, or, more likely, it is due to bugs in the debug draw.

This problem should be tracked in https://github.com/Unvanquished/Unvanquished/issues/2337.
