### ISSUE TITLE
OpenGL 2.1 support and user base

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1457]
This is the parent issue for OpenGL 2.1 support.

There may be issues, pull requets, etc. in both:

- the engine,
- the game,
- the assets.

The idea is to paste there links to “Unvanquished on OpenGL 2.1” related threads (issues, pull-requests, comments…) to easily track them, and also report various usages we may met.

Today we've got a new OpenGL 2.1 user on Linux so I thought it would be good to help gathering what we know, what we do, what we want, etc.

Context
-------

Intel [was still launching GPUs with OpenGL 2.1 in 2010](https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Gen5), it means some workstations and laptops may have still been sold brand new in 2011 or 2012 with those GL 2.1 graphic solutions. Those cards may perform like Radeon cards from 2001, that's super annoying. Outside of our very specific problem with models, and given low preset and resolution are used, performances are usually acceptable though.

Unfortunately we may still find many users of such hardware among Linux users, because Linux is known to work well on such hardware so people don't have to throw them to the bin. Also, Intel had the best out-of-the box open source graphics support at the time so it's likely to be over-represented on Linux users' hands.

I got a report for an Intel Gen 3 this month and someone with a Gen 4 today. We know Gen 5 is also a GL 2.1 generation.

They were featured in a lot of high-quality professional workstations and laptops. For example the Thinkpad T410 was a very good product that was still flowing the second hand market one or two years ago. Companies may have bought them new around 2012, then when renewing them refurbishing companies acquired them in 2015 or 2017 given the original owner renew in 3 or 5 years, those refurbishing companies sold them again for years, usually with new SSD etc. in a way they can start a new life without worrying at all. This was stil pretty common to buy a second-hand refurbished Thinkpad T410 two years ago. Such products were recommended a lot and are very good values, also they are very reliable and age very well. We can expect many Linux users to still have such kind of hardware.

The Dæmon engine supports cards with OpenGL 2.1 and `ARB_half_float_vertex` and `ARB_framebuffer_object` (`EXT_framebuffer_object` is not enough).

Our problem is that Unvanquished models have too much bones, and GL 2.1 hardware can only accelerate models with less bones than what our models have. Then the engine falls back on a CPU implementation we have but that's not performant enough for our models. Some optimizations have been merged but that's still not enough.

There are two solutions we can explore (not exclusive):

- import more optimizations by ZTM, see this comment,
- add alternate models with less bones.

For alternate models with less bones, the simplest is to distribute alternate models without animation at all when possible (acid tubes, overmind, eggs, leech, booster, hive). This would not be very hard to do because we would just drop animation with the bones. What sounds very hard to do is to reduce the number of bones while keeping animations, like making humans finger not animated or alien eyes not animated.

One second problem is that some Intel drivers may emulate the feature to accelerate on GPU the model animation and lie to the game, because of that, the game would not select our own CPU implementation and the emulation by the driver may be even slower than our own CPU emulation. We then need an option in GUI to enable the CPU fallback by hand (`set r_vboVertexSkinning 0`). Also we may do some driver detection to do it automatically on know hardware requiring it.

One note: the Intel Gen 3 supports GL 2.1, also the GL 2.1 is disabled by default to prevent some application to do OpenGL when their software implementation is faster. I submitted a patch to enable GL 2.1 on hardware supporting it.

Also, Gen 3 does not support `ARB_half_float_vertex`, it's technically possible to make the game work with non-half float, but there is no point implementing if the game is unplayable because of models having too much bones.

As said, the problematic hardware are the Intel ones. OpenGL 2.1 GPUs from other brands are much older.

It's possible that some less old hardware are only supported with OpenGL 2.1 on macOS (for reference, macOS software fallback is still OpenGL 2.1).

There was also S3 GPUs with OpenGL 2.1, I got a report for one this month but they have no hardware acceleration on Linux at all anyway. We have a similar problem with their OpenGL 3+ cards, we never put our hands on them, whatever the operating system.

There is no strong need to focus that much on GPUs older than Intel Gen 5, though the report from today was about a Gen 4 and I got a report for an Intel Gen 3 this month (from a French non-profit dedicated to set-up lan parties and bring open source games to people) but improving GL 2.1 support on Unvanquished would benefit for any older GPU.

Here is a summary about **_Linux support_**:

Brand   |Last known launch date¹      |Generation       |Driver |Annoyances    |Performance problems                |Does it run?
--------|-----------------------------|-----------------|-------|--------------|------------------------------------|------------
Broadcom|2019-06-24 (Raspberry Pi 4B) |4.2              |v3d    |              |                                    |maybe (if we can build/emulate)
Broadcom|2018-03-14 (Raspberry Pi 3B+)|2.1              |vc4    |              |SIGSEGV                             |no
Intel   |2010-01-07 (Arrandale)       |Gen 5            |i915   |              |(assumed) slow and emulated models³ |(assumed) yes
Intel   |                             |Gen 4            |i915   |              |slow and emulated models³           |yes
Intel   |                             |Gen 3            |i915   |small shaders¹|slow and emulated models³           |no, missing `ARB_half_float_vertex`⁴
ATI     |2007-11-30 (Radeon X1700 SE) |R500             |r300   |              |slow models                         |yes
ATI     |                             |R400             |r300   |              |slow models                         |yes
ATI     |                             |R400             |r300   |small ALU¹    |slow models                         |yes
Nvidia  |2007-07 (Geforce 7150)       |Curie (Geforce 7)|nouveau|              |slow models                         |no, missing `ARB_framebuffer_object`⁵
Nvidia  |                             |Curie (Geforce 6)|nouveau|              |slow models                         |no, missing `ARB_framebuffer_object`⁵
S3      |2005-03-11 (Chrome 20)       |Chrome S20       |viafb  |unknown       |unknown                             |no, no hardware acceleration implementation

¹ some hardware may have been launched more recently but have not found solid documentation. Especially the S3 date is the first launch of the first product so not the more recent one.
² some hardware may not support large shader or large operations but work with lowest preset.
³ our own software fallback may be faster than driver software fallback.
⁴ when `ARB_half_float_vertex` is not supported, non-half floats are.
⁵ when `ARB_framebuffer_object` is not supported, `EXT_framebuffer_object` is. Nvidia proprietary driver worked but is not supported on current kernels.

Ability to test
---------------

We never tested Intel Gen 5.

I personally own a Gen 4 on a Thinkpad laptop, that's by testing the game on my Gen 4 laptop I noticed we broke GL 2.1 support with the Nvidia fix, we fixed GL 2.1 again, that laptop makes testing GL 2.1 very convenient for me.

I also have access to a Gen 3 workstation. Intel did super shady things, there are workstations with Pentium E5200 with Gen 4 and others with Pentium E5200 with Gen 3. I have access to both but not on a daily basis (one is in production, other one is in a distant place).

I also own a bunch of old ATI Radeon cards with GL 2.1 (much older than Intel), both R300, R400, R500. They are less of a concern but I can very easily test them, I have ready to use testing rig to host them so they make testing GL 2.1 very convenient.

I also own some old Nvidia with GL 2.1 (Curie / Geforce 6000) but those are riddled with bugs and those are much older than Intel GPUs, so they are far less of a concern.

I don't have access to Via hardware with OpenGL 2.1 support and the one having sent me a report does not run Windows.

Then, we can simulate some GL configurations with Mesa, but that's basically disabling features and not emulate the various hardware limits or driver pitfalls. That allows us to do some tests within our CI tools.

**Comment by necessarily-equal** [comment]
I'm really unsure of the usefulness of this, as even with [my old computer](https://www.thinkwiki.org/wiki/Category:X230), mesa provides OpenGL 4.2 according to Daemon.

**Comment by illwieckz** [comment]
I've just looked at the Raspberry Pi 3B+ (2018) and Raspberry Pi 4B (2019) and they both provide OpenGL 2.1, no more:

Raspberry Pi 3B+

```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Broadcom (0x14e4)
    Device: VC4 V3D 2.1 (0xffffffff)
    Version: 20.3.5
    Accelerated: yes
    Video memory: 909MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Broadcom
OpenGL renderer string: VC4 V3D 2.1
OpenGL version string: 2.1 Mesa 20.3.5
OpenGL shading language version string: 1.20
```

Raspberry Pi 4B:

```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Broadcom (0x14e4)
    Device: V3D 4.2 (0xffffffff)
    Version: 20.3.5
    Accelerated: yes
    Video memory: 7812MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Broadcom
OpenGL renderer string: V3D 4.2
OpenGL version string: 2.1 Mesa 20.3.5
OpenGL shading language version string: 1.20
```

For now we cannot build the game on arm64 but this is not something we want to close the door to.

I tried running the game using [Box64](https://github.com/ptitSeb/box64), the updater installed it but then at startup I got a crash when generating the pubkey (Box64 may not emulate some intrinsics?). By copying an existing pubkey the engine continued. On the PI3 I got a SIGSEGV when discovering the OpenGL Configuration but on the PI4 everything when fine, configured the OpenGL, drawn the window (gray screen), and continued up to the moment it tired to load the VM. It went stuck with CPU being 100% so the game is unusable but the renderer works on the PI4.

This is the log on PI3:

```
SDL using driver "x11" 
Initializing OpenGL display 
Using GLEW version 2.2.0 
Display aspect: 1.778 
Display resolution: 1920x1080 
...setting mode -2: 1920×1080 
Using preferred context - 24-bit OpenGL 2.1 compatibility 
OpenGL Renderer: VC4 V3D 2.1 
Using GL3 Renderer in OpenGL 2.x mode... 
]Warning, no wrapper for glXGetCurrentDisplayEXT
Available modes: '1280x720 1600x900 1920x1080 1280x800 1680x1050 720x480 640x480 800x600 1024x768 1280x1024 ' 
Detected graphics driver class 'integrated' 
Detected graphics hardware class 'generic' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...found shading language version 120 
...using GL_ARB_half_float_pixel 
...GL_ARB_texture_float not found. 
...GL_EXT_gpu_shader4 not found. 
...GL_EXT_texture_integer not found. 
...GL_ARB_texture_rg not found. 
...GL_ARB_texture_gather not found. 
...GL_EXT_texture_compression_s3tc not found. 
...GL_ARB_texture_compression_rgtc not found. 
...GL_EXT_texture_filter_anisotropic not found. 
...using GL_ARB_half_float_vertex 
...using GL_ARB_framebuffer_object 
...no program binary formats 
...ignoring GL_ARB_get_program_binary 
...using GL_ARB_buffer_storage 
...GL_ARB_uniform_buffer_object not found. 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
Warn: SSAO not used because GL_ARB_texture_gather is not available. 
Warn: floating point image '_depthtile1Render' cannot be loaded 
Warn: floating point image '_depthtile2Render' cannot be loaded 
Warn: floating point image '_dlightImage' cannot be loaded 
Warn: R_CheckFBO: (_lighttile) Framebuffer incomplete attachment 
Warn: compressed image 'lights/mkintsquarelight1a' cannot be loaded 
Warn: compressed image 'lights/squarelight1' cannot be loaded 
1704|Double SIGSEGV (code=1, pc=0x7fa793763c, addr=0x6a496000)!
```

And here the log on the PI4:

```
SDL using driver "x11" 
Initializing OpenGL display 
Using GLEW version 2.2.0 
Display aspect: 1.778 
Display resolution: 1920x1080 
...setting mode -2: 1920×1080 
Using preferred context - 24-bit OpenGL 2.1 compatibility 
OpenGL Renderer: V3D 4.2 
Using GL3 Renderer in OpenGL 2.x mode... 
]Warning, no wrapper for glXGetCurrentDisplayEXT
Available modes: '1280x720 1600x900 1920x1080 1280x800 1680x1050 720x480 640x480 800x600 1024x768 1280x1024 ' 
Detected graphics driver class 'integrated' 
Detected graphics hardware class 'generic' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...found shading language version 120 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_EXT_gpu_shader4 
...using GL_EXT_texture_integer 
...using GL_ARB_texture_rg 
...using GL_ARB_texture_gather 
...using GL_EXT_texture_compression_s3tc 
...GL_ARB_texture_compression_rgtc not found. 
...using GL_EXT_texture_filter_anisotropic 
...using GL_ARB_half_float_vertex 
...using GL_ARB_framebuffer_object 
...no program binary formats 
...ignoring GL_ARB_get_program_binary 
...using GL_ARB_buffer_storage 
...using GL_ARB_uniform_buffer_object 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
GL_VENDOR: Broadcom 
GL_RENDERER: V3D 4.2 
GL_VERSION: 2.1 Mesa 20.3.5 
GL_MAX_TEXTURE_SIZE: 4096 
GL_SHADING_LANGUAGE_VERSION: 1.20 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16384 
GL_MAX_VERTEX_ATTRIBS 16 
Occlusion query bits: 64 
GL_MAX_DRAW_BUFFERS: 4 
GL_TEXTURE_MAX_ANISOTROPY_EXT: 16.000000 
GL_MAX_RENDERBUFFER_SIZE: 4096 
GL_MAX_COLOR_ATTACHMENTS: 4 
PIXELFORMAT: color(24-bits) 
MODE: -2, 1920 x 1080 fullscreen hz: N/A 
Using OpenGL version 2.1, requested: 2.1 
Using OpenGL 2.x context. 
Using OpenGL extensions: GL_ARB_half_float_pixel GL_ARB_texture_float GL_EXT_gpu_shader4 GL_EXT_texture_integer GL_ARB_texture_rg GL_ARB_texture_gather GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_ARB_half_float_vertex GL_ARB_framebuffer_object GL_ARB_buffer_storage GL_ARB_uniform_buffer_object GL_ARB_map_buffer_range GL_ARB_sync 
Missing OpenGL extensions: GL_ARB_texture_compression_rgtc 
Using S3TC (DXTC) texture compression. 
Using GPU vertex skinning with max 256 bones in a single pass, models are hardware accelerated. 
```

**Comment by DolceTriade** [comment]
I agree. I think when we dropped support for the legacy renderer, we wanted to only support older versions of OpenGL when it was feasible to do so without a huge maintenance burden.

**Comment by VReaperV** [comment]
Note that low-quality models (with less bones) have been added, and `ARB_half_float_vertex` is no longer required.

**Comment by illwieckz** [comment]
Yeah, this thread was meant to be a “parent issue for OpenGL 2.1 support”, but it simply works, so let's consider this closed.
