### ISSUE TITLE
Armory problems

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1467]
Currently, the armory have several issues:

1. the UI is way too slow (which is currently being worked on by gireen I believe)
2. bindings allow to instantly change a full equipment set, which puts a big hole between normal players and very advanced players (and *in my opinion* this is a problem)
3. armory is usable at some distance. Menu will only pop at a *lesser* distance. This favors bind users, again.
4. bots always act as people which have everything bound (they instantly-change their whole equipment)

**Comment by bmorel** [comment]
Only point 1 remains.
Also, sometimes the events seems lost, or happen so late that if the player switched tab in the meantime, a weapon will be bought instead of armor, and vice versa.
Hopefully RMLui will have this fixed or at least drastically improved.

**Comment by bmorel** [comment]
This will need more verifications after 0.53 since lib handling the HUD/GUI will have been replaced.

**Comment by necessarily-equal** [comment]
Closing in favor of https://github.com/Unvanquished/Unvanquished/issues/2287 and https://github.com/Unvanquished/Unvanquished/issues/2288.
