### ISSUE TITLE
map loading screen: give user feedback of engine being compiling GLSL shaders at map load when using `r_lazyShaders 1`

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1469]
map loading screen: give user feedback of engine being compiling GLSL shaders at map load when using `r_lazyShaders 1`

**Comment by illwieckz** [comment]
One thing that can confuse users is that the GLSL compilation happens after 100% is reached, so the game is stuck at 100% without any other feedback.

**Comment by slipher** [comment]
I've been thinking we need this anyway (for shader compilation on engine startup). It takes ~60 seconds on my machine if using Intel drivers. Doing it on game load would be nice since it is easier to draw some text using the cgame.

**Comment by necessarily-equal** [comment]
I think this has been fixed?
