### ISSUE TITLE
idea: implement a way to disable navmesh connections for a specific time

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1478]
It is currently possible to add connections between navmeshes from inside unvanquished (using the `navedit` and `addcon` commands).
Those connections can (I verified it) be used to teach bots the use of some elevators: maps on which this is the most obvious: vega, most recent parpax, yocto.
The conditions for that to work is that the elevator's trigger is _on_ the elevator itself. But, there is a problem: when those elevators are in their _up_ position, bots try to reach upper navmesh by moving under the elevator, which can have 2 effects: either the elevator's normal position if the down one, and it comes back to crush them, or it is the upper one, and they are stuck, crushed when someone takes the elevator.

What I suggest would fix the simpler problem: going under an elevator and being crushed when it goes back to it's normal, "sleeping" position: if when triggered, the elevator was able to disable a connected navmesh link for a specific amount of time, bots would be able to use some elevators, drastically increasing their usefulness on maps having those.

Unfortunately, I have no idea how this could be done. Maybe the real solution would be to have movable navmeshes, maybe it would be to effectively do what I said (seems a lot more hackish, but is more likely technically possible "right now").

**Comment by Gireen** [comment]
https://github.com/Unvanquished/Unvanquished/pull/1229
That's how the navmesh can be changed dynamically.

A possible solution might be for example with parpax, to have a toggleable wall at the bottom of the lift that creates a bot obstacle when the lift is up. How good this works depends on if the blocking wall needs to be solid to count for bots as obstacle.

**Comment by superdupont-fr** [comment]
> #1229 That's how the navmesh can be changed dynamically.
> 
> A possible solution might be for example with parpax, to have a toggleable wall at the bottom of the lift that creates a bot obstacle when the lift is up. How good this works depends on if the blocking wall needs to be solid to count for bots as obstacle.

So, some players can hide under the elevator and won't be reached by bot?

**Comment by bmorel** [comment]
> So, some players can hide under the elevator and won't be reached by bot?

this is how things currently work actually: navmesh is not generated around movable entities. What would be required is (probably) to generate navmesh on all fixed positions, add a navmesh connection and disable navmesh of where the movable is.

**Comment by bmorel** [comment]
Fun fact, I investigated a bit on that few days ago, and it turns out it's mostly already implemented, but buggy. See `SetMoverState( gentity_t *ent, moverState_t moverState, int time )` in [src/sgame/sg_spawn_mover.cpp](https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_spawn_mover.cpp#L533)

**Comment by bmorel** [comment]
Considering the fact it works, even if it seems buggy, this can be closed. I need further investigations to definitely be certain this is buggy or if the feature is just misused.
