### ISSUE TITLE
prepare for cylinder like bounding boxes

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1500]
Currently, all models have squared bounding boxes. Squares have same X and Y sizes, and thus one of those dimensions are useless. The "^mins" and "^maxs" lines still have 3 coordinates.
Removing the Y axis would allow to prepare for cylinders bounding bounding boxes and even for current situation would reduce complexity.

This would change nothing as long as the cylinder is not implemented since, currently, X and Y are always the same the same value in practice.

**Comment by Gireen** [comment]
Why? I see no benefit benefit in it, only reduced flexibility.
The way it is now we could for example add rectangular bounding boxes.

**Comment by bmorel** [comment]
Well, the benefits I was seeing were few (not big, though, I'd understand that this idea would be rejected):

* the navigation system we use for bots rely on cylinders :) (to adapt methods to a tool is a bad idea though, but i'll admit that's the original, bad, reason for this)
* it would naturally provide, in the end, smoother movements when a player's BBox have a veeeeery tiny collision on a wall. This currently block whole movement, but with cylinders, it would simply be possible to slightly deflect the player away from the wall

But you are right that this will force rather boring shapes (X==Y, always) in characters. Maybe there's some way to get at least part of those benefits without the limitations the cylinder would bring.

**Comment by bmorel** [comment]
won't fix
