### ISSUE TITLE
UI for significant errors

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1501]
As written in https://github.com/DaemonEngine/Daemon/pull/524 we need some UI to tell the user when some significant error happens.

For example, when failing to load a map, the game returns to main menu, bot no explanation is given to the user, despite the engine may have known what has happened and have printed an appropriate error message in logs.

As seen in https://github.com/DaemonEngine/Daemon/pull/524 we may want to tell the user he has no working sound card available, so if he does not get in-game sound, he knows it's not the volume.

One idea would be to fill a text buffer with some significant error messages, and if this buffer exists, displays it on both main-menu and ingame main-menu with an appropriate appearance (like a big red in-game window).

To prevent errors to pile up and become irrelevant, we may reset the buffer on every map load, not on engine restart, so if we load a map and the map load fails, the buffer is kept when returning to main menu,  but one error faced when loading one map will not be kept when loading the next map (it will only reappear if the next map also face this issue).

**Comment by illwieckz** [comment]
In the past we had an error window like that (screenshots from Unvanquished 0.35 and Unvanquished 0.17):

[![max points on winding](https://dl.illwieckz.net/b/unvanquished/bugs/max-points-on-winding/unvanquished_2019-12-02_033147_000.png)](https://dl.illwieckz.net/b/unvanquished/bugs/max-points-on-winding/unvanquished_2019-12-02_033147_000.png)

[![max points on winding](https://dl.illwieckz.net/b/unvanquished/bugs/max-points-on-winding/unvanquished_2019-12-02_040707_000.png)](https://dl.illwieckz.net/b/unvanquished/bugs/max-points-on-winding/unvanquished_2019-12-02_040707_000.png)

The error depicted in those screenshot was worked around in https://github.com/DaemonEngine/Daemon/pull/312 but at the time the game was just returning to main menu without telling the user what has happened.

So in fact the lack of such UI is a regression.

**Comment by illwieckz** [comment]
Here is the error window: https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/blob/master/ui/error.rml

If I'm right the feature disappeared with some code rewrite related to `Sys:Error` and `com_errorMessage`.

**Comment by bmorel** [comment]
NOt sure if should be considered bug, or feature request. Regression, for sure, and it certainly needs to be fixed, too.

**Comment by cu-kai** [comment]
I think this can be considered as closed by https://github.com/DaemonEngine/Daemon/pull/937
