### ISSUE TITLE
spectators "detach" is considered by game as using secondary fire

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1505]
Steps to reproduce:

* spectate an mass driver user
* use right click to stop observing them
* you will have the scoped view

The problem here is that the scoped view should never appear for spectators.

**Comment by necessarily-equal** [comment]
Something to check to identify the issue: check whatever shows the scope effet shader in cgame, and ensure it uses `cgs.clientinfo[ cg.clientNum ].team` (the team you belong to) instead of `cg.predictedPlayerState.persistant[PERS_TEAM]` (the team you are following)
