### ISSUE TITLE
Flickering claw on spectator view when following someone who isn't spawned

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1537]
Steps to reproduce (example):
* start a game and add many bots at the same time: `/bot fill 10`
* follow someone who hasn't spawned yet

Here is an example capture, but it doesn't show the flickering. (One can notice the health cross isn't here, but that's minor enough.)
![Screenshot from 2021-10-19 02-22-10](https://user-images.githubusercontent.com/59283660/137823867-6601b595-bbb0-4ead-8fcf-a554b8f537f2.png)

The issue is also present on 0.52.1. It also happens when following a non-spawned yet human, or someone who is waiting to respawn after dying.

**Comment by Gireen** [comment]
This happens only when spectating bots.
For me it doesn't flicker.

**Comment by necessarily-equal** [comment]
Current lead `Rocket_ShowHud(weapon_t)` is alternatively called with 0 (WP_NONE) and 1 (WP_LEVEL0). It is called by `CG_TransitionSnapshot` that update the cgame state from the new `cg.snap`, and specifically, set the HUD to the one of the current weapon.

So why is the HUD flickering? I first though « that's because `CG_ReadNextSnapshot` that swaps between two `cg.activeSnapshots` and does it so incorrectly », but it seems that it's actually what trap_GetSnapshot gives. I'll stop searching for now.

**Comment by necessarily-equal** [comment]
So, I've confirmed that the playerState is correct in sgame, and coherent with what the server sends in cgame. The netcode seems unaffected too, as it's sending and receiving the content of the player state according to what the server asks.

The problem seems to be in dæmon, around `SV_BuildClientSnapshot`. I don't know why as of now.

You can find the `spectator-claws-investigation` branch on my fork that adds some (pretty ugly, messy and fuzzy) debugging code.

**Comment by necessarily-equal** [comment]
If I remember correctly, my conclusion of last time I investigated that, was that bots actually switch twice their `snapshot_t->playerState_t->weapon` each frame, and that daemon seems to copy that to send it without checking if it the game is calculating a frame or not. This means that the state is sometimes sent mid-frame, and flickers.

I don't intend on working on this at the moment.

**Comment by bmorel** [comment]
For some unknown reason, it seems the flickering disappear on both the betterai and the nightly server. I'd like someone else's confirmation before closing this though.

**Comment by necessarily-equal** [comment]
I think you said you managed to still reproduce it, or at least 
something similar. Care to explain this here maybe?

**Comment by bmorel** [comment]
I'm closing this particular issue. I think it's fixed in master. 
There is still a bug about HUD being shown with wrong informations inside, but it's different thing which should receive a different ticket.

**Comment by necessarily-equal** [comment]
Just saw it on 0.53.0/sync

**Comment by slipher** [comment]
I assume this is fixed by c4d3db81b4e86a108621615e311229cfc74125cd + 83f68511db0c7e81794020109257f98011b9265e. Although it remains a mystery why it only happened for bots.
