### ISSUE TITLE
Show in build menu buildables which can't be done for any pre-requisites

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1568]
Currently, in build menus, the game only shows "locked" buildables for a momentum reason. This is only *one* of the four possibilities to allow/disallow building something. Others are:

* do the buildable have the `unique` property? (RC/OM)
* are the buildables prerequisites met? That is, is there is a functional RC/OM around?
* is there is enough BPs?

**Comment by slipher** [comment]
BPs are already checked. There's a dollar bill icon when there is not enough. Search `BuildableAvailability` for source code

**Comment by bmorel** [comment]
Indeed. Closed.
