### ISSUE TITLE
AI try to heal with buildables on ceilings

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1588]
since #1532, alien AI try to heal 1st with ceiling leeches.
While the idea seems good at first, considering the fact AI don't know the heights, it makes aliens run toward walls endlessly, which is a considerable regression.

**Comment by necessarily-equal** [comment]
Good catch. This is one of those case where an improvement will reveal a past buggy behavior because we are pushing the boundary forward. I'll propose a fix when I'll find some time.

**Comment by bmorel** [comment]
To be honest, have aliens heal at barricades or other defensive buildings is not that great neither, especially for barricades since they are usually placed behind doors, to prevent them to be destroyed from afar. Having a bot sitting here will considerably help enemies, since it will keep the door open, allowing humans to fire at barricade without being affected by the defenses which are usually behind barricade, and thus way too far.

Other "not so great" buildings are spikers and trappers.
For spikers, because this will prevent spikes to be thrown, for trappers because it will 1) reveal the trapper and 2) block the blob's path.

Overall, I think only support buildings should be considered as decent healing points:

* booster (favored against most other alternatives, possibly depending on distance)
* leeches (when on ground)
* eggs (when on ground)
* overmind

To know when a building is on ground, the only thing needed is to check it's normal, such a snippet can be found [here](https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_bot_util.cpp#L1034).
