### ISSUE TITLE
miners auto-repair even without unique building

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1591]
There may be other buildings affected. I only tried those things:

leeches auto-repair without overmind.
drills auto-repair without reactor.

At my knowledge, they are the only buildings which can do that, and there is no indication about this in game or in wiki.

**Comment by necessarily-equal** [comment]
I think this is because those buildables are considered to be always powered on.

Question is:
1. Do we want that?
2. If we don't want that, should we set the entity to be powered off anyway, and add an exception in the MiningComponent instead of everywhere else where we eventually notice a bug?
