### ISSUE TITLE
possible crash when a building is "destroyed by <world>"

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1592]
I analysed my server logs. Turns out that that each time I have a message saying `^3Warn: IPC: Socket closed by remote end` (that is: a crash, this should not be marked as an inoffensive warning, to me, but that's another topic) it is immediately preceded by something like `^3Deconstruct: 169 66 telenode MOD_ROCKETPOD: Telenode destroyed by <world>`.

Logs shows various kinds of buildings, of course, all are humans, but I don't think this is related to only human buildings.
I also could reproduce it by emptying a server from bots and building a situation in which I could check it in peace.

**Comment by bmorel** [comment]
Actually, it's when a building is destroyed by the explosion of a nearby building.

**Comment by Sswweet** [comment]
This seems to happen in master (dd5062f1b 2021-10-31) with a local server. I built 6 turrets in 2 rows and removed the reactor. Then I made one explode, such that 2 or 3 other turrets get destroyed by this explosion. Server crashed.

When this was tried on illwieckz's server, nothing bad happened.
