### ISSUE TITLE
Destroying a buildable doesn't give any sound feedback

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1610]
Gunning down an enemy gives a "ting" sound, we could have the same for buildables.

One could imagine a sound of torn metal when destroying an human buildable and a some dying sound for the alien buildables (I'm not fond of a screeching or an "erk" sound because of the negative connotation, but well)

**Comment by cu-kai** [comment]
On Bunker, we added a buildable death sound: https://github.com/enneract/AA-QVM/commit/2a062e07ade9a2f76e90b3f2794b08189db75e89

The asset for this was included in the original Tremulous data-1.1.0 pk3 though I am not sure of its' license and we don't include it in our assets.

**Comment by cu-kai** [comment]
This was closed by #2854 / commit cb971edfbf378624ea3e61ce8223dc12b3e278c2
