### ISSUE TITLE
bot action moveTo doesnt work correct

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1620]
moveTo has a second argument which is supposed to be the radius around the goal to reach.
This has no effect at all. 
```
selector
{
        action moveTo( E_A_OVERMIND, 300 )
}
```
Bots will walk constantly against the goal and ignore the radius.
That should also not happen if no radius is given.

**Comment by bmorel** [comment]
MoveTo and other Move-like actions should be allowed to fail, imo this would be the fix of many problems.

**Comment by bmorel** [comment]
I believe this is fixed. @Gireen could you verify this?

**Comment by bmorel** [comment]
moved to 0.54 anew because it shuold not block 0.53 release, as I'm pretty sure it's now fixed.

**Comment by necessarily-equal** [comment]
It looks fixed in my tests.
