### ISSUE TITLE
add a per-game reputation system to ease troll fighting

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1627]
Currently, the only way to fight trolls is to do a `/callvote kick` command, followed by the name of the person to kick, which may be quite complex, with codes to insert colours or icons.

What I propose is to implement a non-persistent reputation system, with several thresholds: a certain number of warnings to the offender, and then a kick.
It would work as following:

* someone kills a friendly entity (bot, building or player)
* if the victim is a player, they receive a vote to punish of forbid the offender. Increment the corresponding count.
* if the victim is not a player, send the vote to whole team except offender. The offender's counts are increased by each ratio
* if a victim or team member does not vote after a time (server config), consider it a null vote: nothing is added to any counters
* when the punish + forgive count is above a threshold, check the ratio. Take a configurable action depending on the ratio.

This way, not only there would be less need for a GUI to start a `/callvote kick $NAME`, but also it would not require one to pause for several seconds to launch such a vote.
The reputation score could also be shown publicly, and maybe it could be used in other ways.

**Comment by slipher** [comment]
> the only way to fight trolls

The standard way is to appoint admins

**Comment by bmorel** [comment]
The standard way is not the realistic one in this case. Also, even with appointed admins, kicking a troll with current (lack of) interface is a pain.

**Comment by necessarily-equal** [comment]
(Note there are no per-player votes as of now, but this is a minor point here)

**Comment by bmorel** [comment]
Not needed, can mitigated by having active admins, and impossible to do without requiring account creation anyway.
