### ISSUE TITLE
armory menu can be triggered when buildable has been destroyed

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1632]
To reproduce: start a map with not bot, spawn as human, move near armory, shoot at it until destruction, try to use it: menu will spawn.

What would be expected: menu should not appear, but a text saying one can't use a powered down or destroyed building should appear.

**Comment by necessarily-equal** [comment]
I could fix it, but I'll wait a bit so I can avoid a conflict. Maybe if someone reviews https://github.com/Unvanquished/Unvanquished/pull/1546 :eyes:

**Comment by bmorel** [comment]
ping

**Comment by bmorel** [comment]
Finally I simply fixed it myself.
