### ISSUE TITLE
ground fire can be seen from the other side of thin "bridges"

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1634]
Noticed when checking #1609. To reproduce, either throw firebombs of use flamer on a thin surface, and go check the other side. One should likely see nothing, but will see parts of the fire particles, as shown here: 
![2021-12-17-130122_1366x758_scrot](https://user-images.githubusercontent.com/1316300/146542621-ae3706cf-ab9d-4bef-8923-00292315c29f.png)

When looking at grid-like ground, like here: ![2021-12-17-131054_1366x758_scrot](https://user-images.githubusercontent.com/1316300/146543155-d63c84ee-6833-49aa-94a0-bff389ea5563.png) it looks like the fire is "sinking" into the ground (better seen in-game, with noclip and godmod to move around without problems).

**Comment by slipher** [comment]
It's not a model, but rather a two-dimensional sprite.

**Comment by bmorel** [comment]
Not only fire can be seen through those, but also it can give the "burning" attribute to buildings.

**Comment by bmorel** [comment]
see #1609

**Comment by illwieckz** [comment]
This will be fixed by:

- https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/pull/15
