### ISSUE TITLE
crash with "Warn: MSG_WriteDeltaEntity: Bad entity number: 31523067" message

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1638]
To reproduce, you need a mod. I'll use my mod-betterai as an example. Steps:

1. `/set fs_extrapaks; devmap niveus; bot fill 6 a 9; bot fill 6 h 9`
2. `/set fs_extrapaks mod-betterai; devmap niveus; bot fill 6 a 9; bot fill 6 h 9`

Step 1 works, step 2 will crash. Repeating step 1 won't make game crash. If one starts with step 2, repeating it won't make game crash, but will crash step 1 is done.

**Comment by slipher** [comment]
I could not reproduce a bug using these steps except with `chasm` instead of `niveus`. I took care to set `vm.cgame.type` and `vm.sgame.type` to 0, so that the mod is loaded and not some DLL.

**Comment by bmorel** [comment]
I had the problem with the current official build on debian 11 (should have specified that, even if OS is likely unrelated) . I'll give it a try with a master build and/or with `chasm`.

**Comment by bmorel** [comment]
It looks that this problem happens only with my mod, not with exgp for example, so the problem is likely in my code. I'll investigate this, thanks for feedback.
