### ISSUE TITLE
swimming position is not used when walking underwater

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1641]
It seems it is possible to "walk" underwater. I'm not sure if that's to be considered a bug or an enhancement request or just a wontclose: this screenshot is on mission-one, with exgp mod (otherwise map will just go to next on rotation after ~5s)
![2021-12-20-225356_1366x758_scrot](https://user-images.githubusercontent.com/1316300/146837881-75797c87-13b5-4bbe-8a8e-3c492bb60733.png)

**Comment by Gireen** [comment]
I would say its fine as it is.
Divers don't crawl over the Oceanfloor.

**Comment by necessarily-equal** [comment]
Looks fine as is. Though apparently the walking speed isn't quite right according to @illwieckz. Maybe the anim should be made slower. If you confirm this is an issue, I would rather close this one and open a new one.
