### ISSUE TITLE
Humans can walljump while using jetpack

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#1648]
If you activate the jetpack and then keep holding jump after running out of fuel, then you can walljump without using any stamina.

**Comment by bmorel** [comment]
I can't reproduce with 0.52.1.

**Comment by bmorel** [comment]
Pretty sure it has been fixed by #1289 , like #1288 that this issue duplicates.
Can you confirm?

**Comment by slipher** [comment]
Yes it is fixed. I use the pushcannon_b3a vent for testing.
