### ISSUE TITLE
macOS: Symbol not found: _aligned_alloc

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1650]
I got this on a macOS Mojave recently (I installed using updater, 0.52.1), someone on IRC just reproduced it:

```
$ ./daemon
dyld: lazy symbol binding failed: Symbol not found: _aligned_alloc
  Referenced from: /Users/illwieckz/Games/Unvanquished/Unvanquished.app/Contents/MacOS/libopenal.1.18.2.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _aligned_alloc
  Referenced from: /Users/illwieckz/Games/Unvanquished/Unvanquished.app/Contents/MacOS/libopenal.1.18.2.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

**Comment by illwieckz** [comment]
The Mojave install that does not run it today is the exact same system that builds it before, except it received macOS updates since.

**Comment by illwieckz** [comment]
It runs properly on a macOS Catalina install that is disconnected from network since months (and then haven't received any macOS update since ages).

**Comment by illwieckz** [comment]
I just rebuild the engine and get the same issue.

**Comment by slipher** [comment]
You'd need to rebuild OpenAL to hope for any difference. `cd daemon/external_deps && ./build.sh macosx64 openal && ./build.sh macosx64 install` before rebuilding the engine

**Comment by illwieckz** [comment]
Thanks, it works! I just have to replace the existing libopenal dylib with the produced libopenal using the same file name and it works on both up-to-date Mojave and out-of-date Catalina (there is no mistake in that sentence).

So basically, one may replace `Unvanquished.app/Contents/MacOS/libopenal.1.18.2.dylib` with this file and may get Unvanquished working again:

- https://dl.illwieckz.net/b/unvanquished/build/patches/libopenal-for-unvanquished-0.52.1-20211229/libopenal.1.18.2.dylib

**Comment by slipher** [comment]
> user should not run the updater after replacing the library file to not overwrite it

The updater shouldn't overwrite the files until a new version is released. And the bug ought to be fixed in a new version.

**Comment by illwieckz** [comment]
Ah, right. I was probably confused by the fact that if I'm right if one clicks on the button on the splash screen to open the download & configuration window, a check is performed again before launching the game.
