### ISSUE TITLE
HUD disappear when switching graphics

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1657]
To reproduce, join a game, spawn, and select a different preset. The HUD will not show after the game reloaded, but will go back at 1st death

**Comment by bmorel** [comment]
Need check after 0.53 is out

**Comment by slipher** [comment]
I had this problem with the RmlUi branch at some point, but then I fixed it. Never had it with libRocket.

**Comment by DolceTriade** [comment]
I can't repro this. If someone else can give a different repro method, then we can re-open.
