### ISSUE TITLE
Warnings that shader recompilation is necessary appear unnecessarily

### ISSUE THREAD

**Issue by velociostrich** [Unvanquished/Unvanquished#166]
When changing these cvars
* r_hdrRendering
* r_bloom

the console warns, "____ will be changed upon recompiling shaders."

However, the effect of changing these cvars is immediate and seemingly no additional change is brought about by recompiling. 

There may be other cvars, I don't know. If my memory serves me right, recompilation is needed to ensure that the new combination of enabled cvars work together correctly.

**Comment by Viech** [comment]
Closing as old and potentially invalid.
