### ISSUE TITLE
bots should charge lucifer cannon at appropriate value depending on their target and the immediate danger

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1663]
The negative effects of this is that they are slow to kill dretches, and use more time to adv dragoons (that can normally be killed in a single shot).

I think they should charge the weapon depending on enemy's class, but I'm unsure how to calculate this (that is, what should I aim for).
There is also a problem in that, this should likely depend on their skill, but that feels like unnecessary complexity to me (for a start).

**Comment by illwieckz** [comment]
I guess they don't use lucifer cannon secondary fire as well?

**Comment by bmorel** [comment]
Indeed they don't.

**Comment by bmorel** [comment]
"The negative effects of this is that they are slow to kill dretches" for example :)

**Comment by bmorel** [comment]
Also technically they' don't only do 50%, they are really random, *but* mostly ends up at 50%.

**Comment by bmorel** [comment]
Renamed title, because the feature request here is to make bots to either use alt-fire of luci if target is a dretch, or do charging. And when doing charging, to try to charge for a value optimized depending on the enemy they fight, and maybe release when they feel in danger of dying (so that at least they damage their opponent)

**Comment by bmorel** [comment]
Done, except that the estimation of nearby danger is very rough (it's really just checking if health too  low...)

**Comment by bmorel** [comment]
closed by #2570
