### ISSUE TITLE
aliensense or human radars sometimes stop working

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1682]
I was pretty sure this was already reported, but can't find it.

No idea how exactly to reproduce, the symptoms are that beacons on enemies are no longer shown. I think they still appear on friends, though, but I'll need to record such event to be certain.
I never seen it appear in single player games, but it might be because games are too short.
We were 5 on the game it happened to me today: 2 aliens, 3 humans, forlorn.

I'm opening this ticket so that it would be possible to grab as much info as possible on the bug.

**Comment by Gireen** [comment]
yes. #1169
