### ISSUE TITLE
0.53 cleanup

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1706]
There will be stuff kept for compatibility that are no longer needed, to remove in 0.53.

Myself I mark them: `TODO: remove in 0.53`

**Comment by slipher** [comment]
I've been using `TODO(0.53)`

**Comment by necessarily-equal** [comment]
looks like the only instance of this is in bg_misc's `BG_PlayerStateToEntityStateExtraPolate`.

**Comment by slipher** [comment]
I already took care of most of them
