### ISSUE TITLE
improve what traces can detect

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#1707]
There is a problem I've had when trying to improve bots: they can not detect fire on ground (on buildings, that can probably be done) and hence are not able to dodge it.
Obstacle avoidance is done by recognizing what is forward, which can detect most entities and geometry, but for some reason fire can not be detected (I think it's because it's considered a missile).
If possible, it would be nice to also be able to trace actual missiles, to give bots a chance to dodge them, but that seems quite hard to do for me for now

**Comment by slipher** [comment]
Fire has its own entity type ET_FIRE. The reason it cannot be detected with traces is that the content flags (`ent->r.contents`) is 0. We just need to define a content flag for fires and then we could trace against them.

**Comment by slipher** [comment]
The steps for making an entity traceable are
1.  Set content flags as mentioned above
2. trap_LinkEntity
