### ISSUE TITLE
switch to a more widely use vector lib than vec3_t

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1709]
The situation: both daemon and unvanquished rely on the vec3_t API, which is partially reimplemented as a Vec3 API, which is also very partially used.

The problems:
1. Both vec3_t and Vec3 APIs lack any documentation.
2. vec3_t, the most used API, can only be passed around by-value
3. vec3_t is painful to debug, being a mere pointer to a bunch of floats, it requires the dev to manually dereference the pointer 3 times

The solution:
migrate to a lib which already exists and is maintained by other people, with proper documentation.

The suggestion:
Move to glm. Why glm? Mostly because I already worked with it. Also, it's a C++ library, which provides nice API, and it have a quality documentation.
It also tries to mimic shader API, which might be useful for engine development.
It is possible to "convert" glm to a vec3_t by doing `glm::vec3 bla; someVec3tFunction( &bla[0] );` which is pretty trivial.
Last but not least, I have work migrating several parts of the code (sgame/sg_bot* to be exact) to glm.

Of course, I'm open to other suggestions, but I really think we should get rid of the NiH stuff. From my experience, vec3_t will have to be kept around since sadly, it is used by the API between daemon and unvanquished.

**Comment by necessarily-equal** [comment]
Fun fact: there is vec3_t in q3map too

**Comment by bmorel** [comment]
I think this task could be done in several "small" steps:

0. prepare the build system (and probably CI, not sure how to do that)
1. replace `vec3_t` occurrences by `glm::vec3` inside the implementation of functions and when easy stop using q_math.h to interact with 3D vectors
2. update "internal" prototypes (the static functions) to use `glm::vec3` in their signature
3. implement proxy functions for daemon's API
4. update "module" API to use `glm::vec3` in their signature, that is, cgame, sgame, bots
5. update shared API to use `glm::vec3`
6. update daemon's API to use `glm::vec3` 
7. slowly (or not?) stop using q_math.h

The work I did was _more or less_ done that way, and I think this protocol could lead to rather easy to review migration. I really think the end result will be worth it, possibly for performances, but most certainly for maintainance.

**Comment by cu-kai** [comment]
Has the GLM move been completed? Can we close this now?

**Comment by slipher** [comment]
There's always more stuff to convert to GLM, but at least GLM is now well-established and we got rid of `Vec3` (in gamelogic).

**Comment by bmorel** [comment]
hm... I'm not sure if this task should be closed, yet. I see several things that it could be useful for.
For gamelogic, there are still important areas where I think it has not been done, notably the headers. In some cases it's simply not possible, in the other cases it would be nice to just have a tool to do semantic replacement such as coccinelle, because it's very mechanic stuff.
Maybe a decent middle ground could be found if all the public API was moved to glm, instead of the current mix?
