### ISSUE TITLE
3rd person animation for weapon reloading not played

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1728]
Reload "animations" (which are mostly lower the weapon for some time) are not shown for other players.

To reproduce:

* /devmap spacetracks
* take human, go near a mirror
* fire and reload: 1st person animation plays, in the mirror the "animation" lowers the weapon
* join aliens and make yourself a /god for more comfort
* add a human bot, only allow it to use multi-clip weapons and allow him to cheat
* meet the bot and observe the pauses: weapon is never lowered (if you try several weapon, you might also notice that the mass driver seems to aim far above where the bot shoot at, but that's another problem)

**Comment by slipher** [comment]
I believe this is because modelers only drew such animations for first person.

Are you saying that you've discovered we have 3rd-person animations for these, but they aren't played?

**Comment by bmorel** [comment]
> Are you saying that you've discovered we have 3rd-person animations for these, but they aren't played?

Yes. Except that the "animation" is a placeholders (lowering the weapon to mark the reload certainly looks like a placeholder to me), but still, the behavior when you look into a mirror (or in cg_thirdPerson) seems to not be the same as the behavior of other human players, which is quite weird.

**Comment by illwieckz** [comment]
For each character we have a first person model and a third person model, it's possible animations have been implemented in first person model but not in third person model, but even if some may have been implemented in third person model (I'm not sure), I doubt there is code to handle them in third person view.

Some random facts about first/third person distinction :

- In contrary to the third person model, the first person model is not drawn in the same plane the world is so if a model can be clipped by the world in third person view, it isn't clipped in first person view;
- First person model can be more detailed (for what is visible) and stripped down (from what is not visible), sometime even the right part of the weapon you carry on with your right hand (so you only see the left part of it) is not there at all, while the third person model is usually low poly (and can also have less bones and less animations), to combine details in first person and performance in third person.

So animating the two models is twice the work. On the other hand, out third person models, while less detailed on the geometry part, are very detailed regarding to amount of bones: our third person player models allow us to implement full animations in third person view. I wonder if it's possible to apply hand animations from first person model to third person model if the skeleton of that part is exactly the same and is named the same way.

**Comment by slipher** [comment]
>> Are you saying that you've discovered we have 3rd-person animations for these, but they aren't played?

> Yes.

How can you tell?

**Comment by bmorel** [comment]
> How can you tell?

I describe the procedure which makes me think that. Obviously, it's not easy to be 100% certain since I'm doing it with default bots, and bots won't just idle, but there is still an absence of height for the weapon when looking at other's 3rd person model, which differs from what is seen in a mirror or with cg_thirdPerson enabled.

**Comment by illwieckz** [comment]
One can open a player's third person .iqm or .md5anim file with IqeBrowser to see if there are reload animations there.

**Comment by bmorel** [comment]
Reloading:

![2022-01-31-211941_1366x768_scrot](https://user-images.githubusercontent.com/1316300/151866679-6a1ac851-c923-44b1-b821-700ba4ebb7f8.png)

Not reloading:
![2022-01-31-211958_1366x768_scrot](https://user-images.githubusercontent.com/1316300/151866689-b4b3e5cf-0116-45bf-9d66-6fd87206cac8.png)

Now, observe a bot firing at you (enable the /god, will be easier): you will never see the weapon in the "reload" position AFAIK.

**Comment by illwieckz** [comment]
Ah, that animation, I would not be surprised if that's the only animation implemented in third person view. So the issue would be that sometime, this simple third person animation is not played? I'm accustomed to see this animation on other players, maybe that's a bot issue ?

**Comment by bmorel** [comment]
Dunno, maybe I'm wrong and don't see it, it's hard to catch, but I did tried for more than 5 minutes today. It might be about bots, but that'd surprise me.

**Comment by bmorel** [comment]
Looking at it anew, with `/timescale 0.5`, it seems the animation "flickers", that is, the weapon does not stays "low" for the whole time. It's also easier to see a tyrant, see the following screenshot as a dretch (the MD is pointing way too high, but I guess it can't be helped):

![2022-01-31-213556_1366x768_scrot](https://user-images.githubusercontent.com/1316300/151869193-f628e409-ebed-466e-a967-7bdc48c03767.png)
