### ISSUE TITLE
First person weapons disappear with FPS >= 334

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#1734]
If I set `common.framerate.max 334`, and get a high enough frame rate, then the first-person gun models temporarily disappear a lot. It's a sharp discontinuity from 333, so presumably it has something to do with 1000/333 = 3 and 1000/334 = 2 in integer division.

**Comment by Calinou** [comment]
I've seen this issue too. It's not specially new, I remember being able to reproduce this back in 2016.

**Comment by illwieckz** [comment]
If I'm right a similar issue can happen (disappearing first person weapons) with low fps if for some reason your computer is heavily computing other tasks, like if there was enough resources to do everything but first person weapons.

**Comment by illwieckz** [comment]
I also get flashing screen (black frame) when firing weapon (reproduced with rifle) when FPS > 333.
