### ISSUE TITLE
Built-in shaders failed: shaders failed to link!

### ISSUE THREAD

**Issue by JeanPaulLucien** [Unvanquished/Unvanquished#1736]
https://github.com/Unvanquished/Unvanquished/issues/1689

Steps to reproduce: 
1. Install Windows XP 32-bit SP3
2. Install the game
3. Run daemon.exe

Result:   the game returns your to  to desktop and report message from thi topic title, you can ress "OK" oly.

Expected: something other.

**Comment by illwieckz** [comment]
Can you send the daemon.log file?

You're very likely having a too old OpenGL version or driver.

When do this happen, do you reach the main menu, if yes, is the issue happening at map load?

**Comment by JeanPaulLucien** [comment]
Search reports that 250 support sOpenGL 3.3, but some developer says about 4.3 on GT 9600. Unishaders is 4.
I did not reacho something, this just shows black screen and then dropped to deskto.

**Comment by illwieckz** [comment]
OK, can you attach or link to the `daemon.log` file?

**Comment by illwieckz** [comment]
It is not stored where the engine is stored, but in the user directory:

` %USERPROFILE%\Documents\My Games\Unvanquished `

**Comment by illwieckz** [comment]
If you get at least a black screen, I would be surprised you don't have a `daemon.log` file in `Documents\My Games\Unvanquished` (or `My Documents\My Games\Unvanquished` on WinXP), because creation of the window happens after the start of the writing of the log file.

**Comment by JeanPaulLucien** [comment]
```
Starting crash logging server

[FS] Loading pak 'unvanquished_0.52.1.dpk'...

[FS] Loading pak 'unvanquished_0.52.0.dpk'...

[FS] Loading pak 'tex-common_2.2.dpk'...

[FS] Loading pak 'res-players_0.52.dpk'...

[FS] Loading pak 'res-legacy_0.52.dpk'...

[FS] Loading pak 'res-weapons_0.52.1.dpk'...

[FS] Loading pak 'res-weapons_0.52.dpk'...

[FS] Loading pak 'res-buildables_0.52.dpk'...

[FS] Loading pak 'res-voices_0.52.dpk'...

[FS] Loading pak 'res-soundtrack_0.52.dpk'...


execing 'default.cfg'
execing 'presets/input/wasd.cfg'


^3Warn: Couldn't read conhistory: No such file or directory
----- 
Client Initialization -----

Loading RSA keys from pubkey
Daemon RSA public-key found.
----- 
Client Initialization Complete -----

Winsock Initialized



Loaded GeoIP data: 
^1IPv4 
^1IPv6
Hostname: 


IP: 
IP: 
Opening IP6 socket: [::]:*

^3Warn: NET_IP6Socket: socket: WSAEAFNOSUPPORT

^3Warn: Couldn't bind to an IPv6 address.

Opening IP socket: 0.0.0.0:*
--- 
Common Initialization Complete ---


Calling GetRefAPI…
SDL_Init( SDL_INIT_VIDEO )... 
Using SDL Version 2.0.12

SDL using driver "windows"

Initializing OpenGL display

Display aspect: 1.333
...
setting mode -2:
 1024 768

Using 24 Color bits, 24 depth, 8 stencil display.

Using GLEW 2.2.0

Using enhanced (GL3) 
Renderer in GL 3.x mode...

Available modes: '640x480 800x600 1024x768 '

GL_RENDERER: GeForce GTS 250/PCIe/SSE2
Detected graphics driver class 'OpenGL 3+'

Detected graphics hardware class 'generic'

Initializing OpenGL extensions
...
ignoring GL_ARB_debug_output
...
found shading language version 150
...

using GL_ARB_half_float_pixel
...
using GL_ARB_texture_float
...
using GL_EXT_gpu_shader4
...
using GL_EXT_texture_integer
...
using GL_ARB_texture_rg
...
GL_ARB_texture_gather not found
...
using GL_EXT_texture_compression_s3tc
...
using GL_ARB_texture_compression_rgtc
...
using GL_EXT_texture_filter_anisotropic
...
using GL_ARB_half_float_vertex
...
using GL_ARB_framebuffer_object
...
using GL_ARB_get_program_binary
...
GL_ARB_buffer_storage not found
...
using GL_ARB_uniform_buffer_object
...
using GL_ARB_map_buffer_range
...
using GL_ARB_sync


^3Warn: OpenGL error GL_INVALID_OPERATION detected at /Unvanquished/daemon/src/engine/sys/sdl_glimp.cpp:1175

^3Warn: SSAO not used because GL_ARB_texture_gather is not available.

^3Warn: Link log:
Fragment info
-------------
0(145) : error C7011: implicit cast from "int" to "uint"

^3Warn: Built-in shaders failed: Shaders failed to link!

[FS] Loading pak 'unvanquished_0.52.1.dpk'...

[FS] Loading pak 'unvanquished_0.52.0.dpk'...

[FS] Loading pak 'tex-common_2.2.dpk'...

[FS] Loading pak 'res-players_0.52.dpk'...

[FS] Loading pak 'res-legacy_0.52.dpk'...

[FS] Loading pak 'res-weapons_0.52.1.dpk'...

[FS] Loading pak 'res-weapons_0.52.dpk'...

[FS] Loading pak 'res-buildables_0.52.dpk'...

[FS] Loading pak 'res-voices_0.52.dpk'...

[FS] Loading pak 'res-soundtrack_0.52.dpk'...
```

**Comment by illwieckz** [comment]
Ah! the return of the Nvidia Tesla driver bug (#368) (and indeed the GeForce GTS 250 is an Nvidia Tesla GPU). This is a driver bug, we have implemented a workaround but for the workaround to work we do some guessing to try to detect the buggy driver (#370). It looks like it failed at detecting yours.

Can you create next to `daemon.exe` a file named `daemon.cmd` that contains this:

```cmd
@daemon.exe -set r_arb_texture_gather 0
```

And run `daemon.cmd` instead of `daemon.exe`?

Then if the game runs properly, quit and send me again the `daemon.log` file so we can see if it's possible to implement a workaround for such driver or not.

**Comment by JeanPaulLucien** [comment]
`r_arb_texture_gather` is OpenGL 2.0. I played more than 50 games and tid not receive issues before.

```
using GL_ARB_sync

^3Warn: OpenGL error GL_INVALID_OPERATION detected at /Unvanquished/daemon/src/engine/sys/sdl_glimp.cpp:1175
^3Warn: SSAO not used because GL_ARB_texture_gather is not available.
^3Warn: Link log:
Fragment info
-------------
0(145) : error C7011: implicit cast from "int" to "uint"


^3Warn: Built-in shaders failed: Shaders failed to link!
```

**Comment by JeanPaulLucien** [comment]
`Copyright (C) 1999-2005 Id Software, Inc.`
I you changed nothing, the reason in other place.

**Comment by illwieckz** [comment]
Can you edit the `daemon.cfg` file this way and run it?

```
@daemon.exe +preset presets/graphics/low.cfg
```

That copyright string has no incidence on the current problem. 2005 is the year id Software stopped contributing to this file before releasing it, but we maintain it indeed, the OpenGL 2/OpenGL 3 code is even entirely new if I'm right.

**Comment by illwieckz** [comment]
I just notice that in your log:

```
found shading language version 150
```

Even if the OpenGL version detected is OpenGL 3, this looks to be a pre-OpenGL 3 GLSL version. This is probably not a Core OpenGL version.

**Comment by illwieckz** [comment]
Can you replace the `daemon.exe` file with the one from this zip (backup the existing one somewhere):

https://cdn.unvanquished.net/unvanquished_0.52.0/windows-i686.zip

This one is a bit older but that's because the 0.52.1 build has a bug with OpenGL 2.1 (and we haven't published fixed builds yet even if we already fixed it).

Then you edit the `daemon.cmd` file this way, and run it:

```cmd
@daemon.exe -set r_glMinorVersion 2 -set r_glMajorVersion 1
```

This is to force the engine to run in OpenGL 2.1 mode even if higher is available.

**Comment by illwieckz** [comment]
I made a mistake in the code to paste in the `daemon.cmd` file, I just edited my previous comment with proper code.

**Comment by JeanPaulLucien** [comment]
```
static void reportHardwareType(bool force)
{
  static const char *const hardware[] = {"generic", "ATI R300"};
  if (glConfig.hardwareType > glHardwareType_t::GLHW_UNKNOWN && (unsigned) glConfig.hardwareType < ARRAY_LEN(hardware) )
	{
		logger.Notice("%s graphics hardware class '%s'",
		           force ? "User has forced" : "Detected",
		           hardware[Util::ordinal(glConfig.hardwareType)] );
	}
}
```
I suppose my case don't start code inside IF.

^3Warn: Link log:
Fragment info
-------------

0(145) : error C7011: implicit cast from "int" to "uint"

3Warn: Built-in shaders failed: Shaders failed to link!

**Comment by illwieckz** [comment]
We don't have enough information yet to even know where the bug is happening in the code (even the given line is just about where one error is caught by the engine, not where it is happening, neither how many errors they are), it's too early to read at code.

Did you tried to set the `low` preset?

```cmd
@daemon.exe +preset presets/graphics/low.cfg
```

Did you tried to force GL 2.1 with the [older engine build](https://cdn.unvanquished.net/unvanquished_0.52.0/windows-i686.zip)?

```cmd
@daemon.exe -set r_glMajorVersion 2 -set r_glMinorVersion 1
```

What would be interesting would be to know which shader is failing.

Can you edit and run the `daemon.cmd` file this way?

```cmd
@daemon.exe -set logs.logLevel.default debug -set logs.logLevel.glconfig debug
```

I need answers to those three questions.

Note: I'll be busy for the rest of the day, but I'll read you tomorrow.

Note: don't forget to mark your log as code with surrounding \`\`\` (I edited your previous comment)

**Comment by JeanPaulLucien** [comment]
`found shading language version 150`
> Even if the OpenGL version detected is OpenGL 3, this looks to be a pre-OpenGL 3 GLSL version

150 is OpenGL 3.2. But GTS 250 suportOpenGL 3.3 version. Quake 3 shows OpenGL 3.3, so should be version 330.  I don't see in logs infor what version is extacly. So, maaby code tect rong OpenGL version.

**Comment by necessarily-equal** [comment]
I'm not sure this issue should stay open, if it's when running on a old (unsupported) version of windows.

**Comment by illwieckz** [comment]
The discussion can continue even if the ticket is closed and the original poster has additional information.

Keeping this ticjet open would mean that's an actual problem for Unvanquished. While it would be interesting to know if the game can run on an operating system as old as Vista, this is not a requirement to consider our expectations for Unvanquished are met.
