### ISSUE TITLE
Build a firejail profile.

### ISSUE THREAD

**Issue by Soldy** [Unvanquished/Unvanquished#1737]
Hi all,
I working on a fire jail profile for unvanquished. 
Any one tried this before me ? 
I missed some thing. I stack with this:

```
firejail --private=~/.firejail/unvanquished/  --ipc-namespace=unvanquished  /opt/unvanquished/daemon
Reading profile /etc/firejail/gameOpengl.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 21774, child pid 21775
5 programs installed in 9.15 ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Blacklist violations are logged to syslog
Child process initialized in 41.14 ms
Unvanquished 0.52.1 Linux x86_64 Feb  9 2022
cmdline:
[FS] Lib path: /opt/unvanquished 
[FS] Home path: /home/xxx/.local/share/unvanquished 
[FS] Pak search path: /opt/unvanquished/pkg 
[FS] Pak search path: /home/xxx/.local/share/unvanquished/pkg 
[FS] Loading pak '/opt/unvanquished/pkg/unvanquished_0.52.1.dpk'... 
[FS] Loading pak '/opt/unvanquished/pkg/unvanquished_0.52.0.dpk'... 
[FS] Loading pak '/opt/unvanquished/pkg/tex-common_2.2.dpk'... 
[FS] Loading pak '/opt/unvanquished/pkg/res-players_0.52.dpk'... 
[FS] Loading pak '/opt/unvanquished/pkg/res-legacy_0.52.dpk'... 
[FS] Loading pak '/opt/unvanquished/pkg/res-weapons_0.52.1.dpk'... 
[FS] Loading pak '/opt/unvanquished/pkg/res-weapons_0.52.dpk'... 
[FS] Loading pak '/opt/unvanquished/pkg/res-buildables_0.52.dpk'... 
[FS] Loading pak '/opt/unvanquished/pkg/res-voices_0.52.dpk'... 
[FS] Loading pak '/opt/unvanquished/pkg/res-soundtrack_0.52.dpk'... 
execing 'default.cfg' 
execing 'presets/input/wasd.cfg' 
Warn: Couldn't read conhistory: No such file or directory 
----- Client Initialization ----- 
Loading RSA keys from pubkey 
Daemon RSA public-key found. 
----- Client Initialization Complete ----- 
]Error Opening file /usr/share/GeoIP/GeoIP.dat
Error Opening file /opt/unvanquished/GeoIP.dat
Error Opening file /usr/share/GeoIP/GeoIPv6.dat
Error Opening file /opt/unvanquished/GeoIPv6.dat
Loaded GeoIP data: IPv4 IPv6 
NET_GetLocalAddress: Unable to get list of network interfaces: Operation not supported
 
Opening IP6 socket: [::]:* 
Opening IP socket: 0.0.0.0:* 
--- Common Initialization Complete --- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL Version 2.0.14 
SDL using driver "x11" 
Initializing OpenGL display 
Display aspect: 2.370 
...setting mode -2: 
 2560 1080 
Using 24 Color bits, 24 depth, 8 stencil display. 
Using GLEW 2.1.0 
Using enhanced (GL3) Renderer in GL 3.x mode... 
Available modes: '2560x1080 1280x720 1600x900 1920x1080 1680x1050 720x480 640x480 800x600 1024x768 1280x1024 ' 
GL_RENDERER: GeForce GT 1030/PCIe/SSE2 
Detected graphics driver class 'OpenGL 3+' 
Detected graphics hardware class 'generic' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...found shading language version 150 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_EXT_gpu_shader4 
...using GL_EXT_texture_integer 
...using GL_ARB_texture_rg 
...using GL_ARB_texture_gather 
...using GL_EXT_texture_compression_s3tc 
...using GL_ARB_texture_compression_rgtc 
...using GL_EXT_texture_filter_anisotropic 
...using GL_ARB_half_float_vertex 
...using GL_ARB_framebuffer_object 
...using GL_ARB_get_program_binary 
...using GL_ARB_buffer_storage 
...using GL_ARB_uniform_buffer_object 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
glsl shaders took 103 msec to build 
Warn: Couldn't find image file 'flareShader' 
Warn: Couldn't find image file 'sun' 
GL_VENDOR: NVIDIA Corporation 
GL_RENDERER: GeForce GT 1030/PCIe/SSE2 
GL_VERSION: 3.2.0 NVIDIA 460.91.03 
GL_SHADING_LANGUAGE_VERSION: 1.50 NVIDIA via Cg compiler 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 4096 
Using OpenGL 3.x context 
Using GPU vertex skinning with max 233 bones in a single pass 
]AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Warn: Could not open an OpenAL device. 
Warn: Couldn't initialize the audio subsystem. 
Extracting VM module cgame-x86_64.nexe from /opt/unvanquished/pkg/unvanquished_0.52.1.dpk...
 
Loading VM module cgame-x86_64.nexe... 
Using loader args:  /opt/unvanquished/nacl_helper_bootstrap /opt/unvanquished/nacl_loader --r_debug=0xXXXXXXXXXXXXXXXX --reserved_at_zero=0xXXXXXXXXXXXXXXXX -v -B /opt/unvanquished/irt_core-x86_64.nexe -e -i 100:37 -- /home/xxx/.local/share/unvanquished/cgame-x86_64.nexe 100 
Warn: Error during initialization: IPC: Socket closed by remote end 
]
```

**Comment by illwieckz** [comment]
Hmm, our game code and downloaded mods already runs in a sandbox (but you have to trust our engine), maybe issue arise when trying to sandbox the sandbox? For example I know some Steam games doesn't work in chroot because the Steam sandbox doesn't work when sandboxed itself, same for Steam in flatpak. On the other hand our game works properly in flatpak so there is already one use case where sandboxing the sandbox works…

**Comment by illwieckz** [comment]
Do firejail allows access to `/home/laszlo/.local/share/unvanquished/cgame-x86_64.nexe`?

**Comment by Soldy** [comment]
``` /home/xxx/.local/share/unvanquished/ ``` that's an empty directory

**Comment by illwieckz** [comment]
Also note that this error message:

> Warn: Error during initialization: IPC: Socket closed by remote end

Is not from firejail, but from Dæmon engine, it's the IPC of our own sandbox (Native Client).

This message may have multiple cause, but usually it means the engine failed to load the game code executable (.nexe file).

**Comment by illwieckz** [comment]
Also note that the `cgame-x86_64.nexe` file is expected to be extracted from `unvanquished_0.52.1.dpk`, then the engine executes it (the extracted one), so when running in firejail, the engine must be able to write this file where our sandbox expects it to be.

**Comment by Soldy** [comment]
got it. Now i have this :
```
$ ls /home/xxx/.firejail/unvanquished/.local/share/unvanquished/
cgame.nacl_loader.log  cgame-x86_64.nexe  crashdump  daemon.log  glsl  pkg  pubkey
```

But I stack with the same message. Have any IPC namespace what I can use ?

**Comment by illwieckz** [comment]
According to `firejail --help`:

```
       --private
              Mount new /root and /home/user directories in temporary filesystems. All modifica‐
              tions are discarded when the sandbox is closed.
[…]
       --private=directory
              Use  directory as user home.  --private and --private=directory cannot be used to‐
              gether.

              Example:
              $ firejail --private=/home/netblue/firefox-home firefox
```

So if I understand it properly, it is expected the Dæmon engine cannot access `/home/xxx/.local/share/unvanquished/cgame-x86_64.nexe` and then fail to load the game.

What I don't understand is why you get `/home/xxx/.local/share/unvanquished/cgame-x86_64.nexe` in `nacl_helper_bootstrap` command line instead of `/home/xxx/.firejail/unvanquished/.local/share/unvanquished/cgame-x86_64.nexe`.

What if you do:

```sh
( export HOME="${HOME}/.firejail/unvanquished" ; firejail --private="${HOME}" --ipc-namespace=unvanquished  /opt/unvanquished/daemon )
```

_Note:_ make sure to **not** forget the parentheses to not modify your current shell environment.

**Comment by Soldy** [comment]
So this is an ELF 
``` 
head -c 16  cgame-x86_64.nexe 
ELF
```
I see.

**Comment by illwieckz** [comment]
Yes, a `.nexe` file is an operating-system independent binary, the virtual machine we currently use is [NativeClient](https://developer.chrome.com/docs/native-client/).

By doing that we are not limited to the old C of LCC (Q3VM) or the old C-ish QuakeC, our game code is in C++ and relies on third-party C++ libraries (something Q3VM and QuakeC can't do).

Note: we are replacing NativeClient with [WebAssembly](https://webassembly.org/), but that's not done yet, so we still build and ship NativeClient nexe files.

**Comment by Soldy** [comment]
>What if you do:
```bash 
( export HOME="${HOME}/.firejail/unvanquished" ; firejail --private="${HOME}" --ipc-namespace=unvanquished /opt/unvanquished/daemon )
```

Well I guess I can show why this isn't work.

```
$ firejail --private=~/.firejail/unvanquished/ --profile=firefox --ipc-namespace=unvanquished  pwd
/home/xxx
```

**Comment by illwieckz** [comment]
Yeah I guessed that…

Wait, there is another thing you can do instead of modifying `${HOME}` environment variable:

```
firejail --private=~/.firejail/unvanquished/ --ipc-namespace=unvanquished /opt/unvanquished/daemon -homepath ~/.firejail/unvanquished
```

I recommend you to purge `~/.firejail/unvanquished` before since you already filled with things while using a different configuration.

The `cgame-x86_64.nexe` file and other files (like user configuration) will be stored in `~/.firejail/unvanquished` directly (without `.local/share/unvanquished` subdirectory).

**Comment by Soldy** [comment]
I have no DBUS in my system ? This can be the problem ?

**Comment by illwieckz** [comment]
We don't make use of D-Bus ourselves, I can't speak for firejail though.

**Comment by Soldy** [comment]
>FWIW I play to unvanquished without any issue on a debian stripped from dbus, and all systemd-* components (including systemd's PID1 obviously) (except for udev which was swallowed by systemd, because I'm too lazy to move on) and this works perfectly.
The only thing is, I regularly need to allow overcommit when playing, especially if I have one or more web browsers opened.


I hate systemd too. So I use openBSD or gentoo :) eudev can help you. Be lazy and try [ DEVUAN https://www.devuan.org/ ](https://www.devuan.org/)


I find the issues i have this in my config  

```
noexec /tmp   
```

I can be replaced with a ``` private-tmp ``` so not a big deal. Thank you for the help. I should commit the firejail profile.

**Comment by illwieckz** [comment]
Ah nice!

For that temporary directory thing, maybe you can try to use a `${TMPDIR}`? (not sure if everything is compatible with that environment variable though).

See you in game maybe. :smiley:

**Comment by bmorel** [comment]
I don't actually *hate* systemd, and I've used devuan for a while. Not the right place to talk about it, better for you to come on IRC for that, but, quickly:  basically, debian always had other inits supported. Eudev would not add me anything, since it's the same ugly architecture as udev anyway. End of out-topic for me :)

**Comment by Soldy** [comment]
> For that temporary directory thing, maybe you can try to use a `${TMPDIR}`? (not sure if everything is compatible with that environment variable though).

As you expected. TMPDIR didn't work. 

But for me is the ``` private-tmp ``` are perfect.

```
       --private-tmp
              Mount an empty temporary filesystem on top of /tmp directory whitelisting X11 and PulseAudio sockets.

              Example:
              $ firejail --private-tmp
              $ ls -al /tmp
              drwxrwxrwt  4 nobody nogroup   80 Apr 30 11:46 .
              drwxr-xr-x 30 nobody nogroup 4096 Apr 26 22:18 ..
              drwx------  2 nobody nogroup 4096 Apr 30 10:52 pulse-PKdhtXMmr18n
              drwxrwxrwt  2 nobody nogroup 4096 Apr 30 10:52 .X11-unix
```

One more thing about this:
```
firejail --private=~/.firejail/unvanquished --ipc-namespace=unvanquished /opt/unvanquished/daemon -homepath ~/.firejail/unvanquished
```
The target directory in this case will be  ``` /home/xxx/.firejail/unvanquished/.firejail/unvanquished ```. So I use this:
```
firejail --private=~/.firejail/unvanquished --ipc-namespace=unvanquished /opt/unvanquished/daemon -homepath ~/
```

**Comment by rusty-snake** [comment]
> --ipc-namespace=unvanquished 

`ipc-namespace` does not take an argument.

**Comment by Soldy** [comment]
> > --ipc-namespace=unvanquished
> 
> `ipc-namespace` does not take an argument.

That right. This is was my unpublished fork... Sorry
