### ISSUE TITLE
vote delays are hard-coded

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1740]
If I am not wrong, the time in which a specific vote can be done is hard-coded when they are limited in time, for example, for how long it is possible to vote for a map change.
Moving the hard-coded value in a CVar would be a useful addition for admins (I'm echoing something I've seen asked for by someone hosting a server, I may not be exactly accurate in the description)

**Comment by slipher** [comment]
You're talking about the cvar `g_mapVotesBefore` ?

**Comment by bmorel** [comment]
`sgame/sg_main.cpp:Cvar::Cvar<int> g_mapVotesBefore("g_mapVotesBefore", "map change votes not allowed after this many minutes", Cvar::NONE, 5);`

I guess I was, yes. Sorry for the noise!

**Comment by necessarily-equal** [comment]
I think that restriction is a bit stupid by the way, because someone could do `/callvote nextmap x` then `/callvote draw`
