### ISSUE TITLE
migrate navcon files from binary to text format

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1772]
Currently, files used to store off-mess connections (that is, connections between 2 navmeshes or shorcuts within a navmesh), commonly referred to as `navcon`, use a binary format which does works well with versioning, script edition or even manual edition.

Navcons are linked directly to navmeshes, and some might be possible to generate automatically, for example those of movers (hopefully, if not, please complete) exhaustive list:

* doors;
* elevators;
* teleporters;
* pushers;
* pendulums;
* ladders;
 
But some are very unlikely to be generated automatically one day, namely, the ones which interacts with normal geometry. From this PoV, ladders navcons will also be harder ones to generate, since they just that: geometry, with a special texture applied on it (which explains many of the problems of ladders, even for players):

* jumping over chasms
* jumping upward
* jumping downard

Note that with some tricks, it is possible to get some limited jumping up/down-ward done automatically, but it will be limited in height at agent's height minus one unit (`crouchMaxs[2] - mins[2] - 1` in code), and might lead to new problems itself, like revealing new bugs in generator.

Each "agent" have it own navmesh, and agents are currently defined with those values:

* radius;
* height (crouched height should be used, combined with obstacle detection changes, but currently only max height is);

The current list is hard-coded (list of `class_t`), mostly considering the values above, and without considering their abilities (as an `upgrade_t` can alter the abilities of a `class_t`), which is an error as it effectively prevents to distinguish agents of same size but different abilities, for example: a naked human with a jetpack, a dretch can not pounce but mantises, which are of same size, can.
There are also other different damages modifiers which can be taken depending on the length of the fall, or even only the height magnitude.

Off-mesh connections can at least the following properties set from the editor:

* 3D start coordinates
* 3D end coordinates
* one-way or two-way
* "tunnel" radius
* `class_t` which is able to use it

What is needed to do here is to find a way to describe them so that enough information can be bound to them so that a bot can be able to know if that navcon concerns it or not, which may even depend on their health status (let's dream, but honestly that's one of the things I could not care too much for a 1st implementation).

**Comment by bmorel** [comment]
Note that it could also be possible to use navigation connections to help players triggering complex actions, like "enabling" a ladder (and play a specific animation while on the ladder), a cinematic mode or other effects that I can not imagine right now. Those notes are just a point of detail though.

**Comment by slipher** [comment]
Not exactly related, but could we conceivably ever use automatically generated navcons? Or should anything done by the generator always be part of the navmesh? I guess I'm just asking what the difference between navcon and navmesh is, other than being user-edited.

**Comment by bmorel** [comment]
> I guess I'm just asking what the difference between navcon and navmesh is, other than being user-edited.

That's actually sums it all. Algos may be very powerful, when there are enough strong enough brains behind them, but they still need human tinkering.

In our case, I think we need to find the middleground between what is reasonable to ask to mappers to do (fun maps for real players, with maybe hints for AIs) and with what players will expect (maps that are fun even if there are no players around).
For that, I think a combination of mapper work (giving hints), tools (generating navmeshes with some easy links) and map debuggers (who'd give feedbacks and patches, including for AI, and maybe improving player interaction with maps) is required. The same way we collaborate between engine devs, tools (CI) and gamelogic devs.

But  I think I'm missing your point here...

**Comment by illwieckz** [comment]
> I guess I'm just asking what the difference between navcon and navmesh is

@slipher Well, I guess you know a bit what a navmesh is (you'll seen them with navedit and you ported the generation code from daemonmap).
 
A navcon is very simple in comparison, it's just a pair of two point, A and B : coordinates of them, is the link bidirectional or not…

Here is a proposal of textual navcon format (converted from our actual binary-format of navcon) of some real navcons I created in Unvanquished:

```
# format: x1 z1 y1 x2 z2 y2 rad flags areas dirs userids
```
```
-1623.585205078125 226.0 1772.6363525390625 -1665.3758544921875 76.25360107421875 1898.5557861328125 50.0 1 63 0 0
-1219.1612548828125 250.0 2232.142578125 -1232.4483642578125 142.98577880859375 2318.962646484375 50.0 1 63 1 0
```

Here is a quick & dirty binary-to-text convertor: https://pastebin.com/vcwMFVec

It would be good to have a special header with a version though (like `#navcon 2\n`) to be future proof.

It would be interesting to know if we can avoid floats or not…

**Comment by bmorel** [comment]
> Here is a proposal of textual navcon format (converted from our actual binary-format of navcon)

That's the problem I have actually. This is not future-proof and none of us understand what the fieds are (well, I understand it a bit, but not much). Feel free to prove me wrong: I'd love to see doc, in any forms.

Let me give a shot at it:

> # format: x1 z1 y1 x2 z2 y2 rad flags areas dirs userids

XZY? Why not. That's because of quake, though.

* Rad: radius. We describe a cylinder here, as I said.
* Flags, areas: no idea what they are
* dirs: one or two way
* userids: that the thing I want to know how to work with. Abilities, notably.

**Comment by illwieckz** [comment]
> This is not future-proof and none of us understand what the fieds are (well, I understand it a bit, but not much).

When I say it is a proposal, it's because we have to start discussing something, it does not mean it's ready.

- One important thing in that proposition is that it's a space-separated format with every con on its own line, like the already existing layout files.  
- I suggest adding a header, so we can change or extend the format in the future and detect it.

Do we agree on those two points?

The x/z/y part comes from the fact it's stored this way in current binary navcon file and this proposal is a direct textual transcription of the current binary file, but I would be OK with another format. One important remark is that even if xzy is weird, I assume it's consistent with other things in engine (layouts? viewpos?).

**Comment by bmorel** [comment]
> Do we agree on those two points?

Yes.

> One important remark is that even if xzy is weird, I assume it's consistent with other things in engine (layouts? viewpos?).

This is linked to the fact recast navigation use Z as depth and Y as height, while the game uses Y as depth and Z as height. Is that consistent, now, I would not be able to say (navigation code needs to swap the vars each time).

**Comment by bmorel** [comment]
Also note I think using floats here make no sense, we do not need that level of precision. Like, at all. Coding with integers is easier (esp for text representation!), triggers less bugs, more compact... there's no real reason to use floats, considering granularity of the game: keep in mind that even *pulse blast* have BBox of 5x5x5.

**Comment by illwieckz** [comment]
I want this as a prerequisite to commit navcons in official Unvanquished repositories.

Because this is about making navcons git friendly, diff friendly, etc.

**Comment by illwieckz** [comment]
Inspiration can be taken from layout parser, it's just the fields are for another data or not have the same order.

**Comment by DolceTriade** [comment]
fwiw, I don't think the layout parser is a good example for this. The layout parser has a single buildable per line and each buildable has only a few parameters: origin, angles (both vec[3]).

navcons are stored differently:
```
	int conCount = nav->process.con.offMeshConCount;
	OffMeshConnectionHeader header;
	header.version = LittleLong( NAVMESHCON_VERSION );
	header.numConnections = LittleLong( conCount );
	trap_FS_Write( &header, sizeof( header ), f );

	size_t size = sizeof( float ) * 6 * conCount;
	float *verts = ( float * ) dtAlloc( size, DT_ALLOC_TEMP );
	memcpy( verts, nav->process.con.verts, size );
	SwapArray( verts, conCount * 6 );
	trap_FS_Write( verts, size, f );
	dtFree( verts );

	size = sizeof( float ) * conCount;
	float *rad = ( float * ) dtAlloc( size, DT_ALLOC_TEMP );
	memcpy( rad, nav->process.con.rad, size );
	SwapArray( rad, conCount );
	trap_FS_Write( rad, size, f );
	dtFree( rad );

	size = sizeof( unsigned short ) * conCount;
	unsigned short *flags = ( unsigned short * ) dtAlloc( size, DT_ALLOC_TEMP );
	memcpy( flags, nav->process.con.flags, size );
	SwapArray( flags, conCount );
	trap_FS_Write( flags, size, f );
	dtFree( flags );

	trap_FS_Write( nav->process.con.areas, sizeof( unsigned char ) * conCount, f );
	trap_FS_Write( nav->process.con.dirs, sizeof( unsigned char ) * conCount, f );

	size = sizeof( unsigned int ) * conCount;
	unsigned int *userids = ( unsigned int * ) dtAlloc( size, DT_ALLOC_TEMP );
	memcpy( userids, nav->process.con.userids, size );
	SwapArray( userids, conCount );
	trap_FS_Write( userids, size, f );
	dtFree( userids );
```

In other words, it's just a shitload of vertices that are going to be annoying to parse. The only diffable thing we can get out of them will be the fact that something changed.

I think a reasonable format for text navcons would be the following:

```
version 1
numConnections 100

// verts
1 2 3 4 5 6
7 8 9 10 11

// radius
1
2
3

// flags
1
2
3

// areas
text

// dirs
text

// userids
1
2
3
```

WYDT?

**Comment by illwieckz** [comment]
Aren't `1 2 3 4 5 6` coordinates for point A and point B (because it's a connection between point A and B)? If I'm wrong, then another format is a better idea. But if I'm right I had compared the values with `viewpos`.

**Comment by DolceTriade** [comment]
Ah you're right...

```
struct dtOffMeshConnection
{
	/// The endpoints of the connection. [(ax, ay, az, bx, by, bz)]
	float pos[6];

	/// The radius of the endpoints. [Limit: >= 0]
	float rad;		

	/// The polygon reference of the connection within the tile.
	unsigned short poly;

	/// Link flags. 
	/// @note These are not the connection's user defined flags. Those are assigned via the 
	/// connection's dtPoly definition. These are link flags used for internal purposes.
	unsigned char flags;

	/// End point side.
	unsigned char side;

	/// The id of the offmesh connection. (User assigned when the navigation mesh is built.)
	unsigned int userId;
};
```

I guess we can do one connection per line? Seems pretty trivial to write a python script to hack this up...

**Comment by bmorel** [comment]
> WYDT?

Please no.
Proposed format would require writing one more parser by hand, and those are a current major pain source in unv's codebase.
Also, you guys are talking about implementing a format for a feature, but have you actually tried to use the navcon edition unvanquished provides?

Before describing a format, it would be better to define it's role. As for git, formating stuff in one-liner would be better, yes, as long as lines can be easily read in the forge: long lines are a pain in github, the forge we currently use.
Again, I'm against the use floats for this, it makes no sense. So:

```
-1623.585205078125 226.0 1772.6363525390625 -1665.3758544921875 76.25360107421875 1898.5557861328125 50.0 1 63 0 0
-1219.1612548828125 250.0 2232.142578125 -1232.4483642578125 142.98577880859375 2318.962646484375 50.0 1 63 1 0
```

Should be:

```
-1623 226 1772 -1665 76 1898 50.0 1 63 0 0
-1219 250 2232 -1232 142 2318 50.0 1 63 1 0
```

Which is actually pretty easy to diff.
I think coordinates should be grouped together, too, like this:


```
{ -1623 226 1772 } { -1665 76 1898 } 50.0 1 63 0 0
{ -1219 250 2232 } { -1232 142 2318 } 50.0 1 63 1 0
```

And I also think whitespaces should not be a syntax element. I'll never understand why python did that choice, it's a really stupid one imo. So:

```
{ { -1623 226 1772 } { -1665 76 1898 } 50.0 1 63 0 0 }
{ { -1219 250 2232 } { -1232 142 2318 } 50.0 1 63 1 0 }
```
At this point, we could just add some commas as field ends, for readability's sake.

```
{ { -1623 226 1772 }, { -1665 76 1898 }, 50, 1, 63, 0, 0, }
{ { -1219 250 2232 }, { -1232 142 2318 }, 50, 1, 63, 1, 0, }
```

Note that, I had to add the commas to notice that there was still some `.0` around. I'll let them here for the demonstration that floats in diffable format *just sucks*. They're enough of a pain in codebases, let's not have them in text formats without good reason, please.

Since this all text, it compresses pretty well, but that last snippet is still unreadable to me, so I'd suggest to print the fields names:

> # format: x1 z1 y1 x2 z2 y2 rad flags areas dirs userids

```
{ start = { -1623 226 1772 }, end = { -1665 76 1898 }, radius = 50, flags = 1, areas = 63, dirs = 0, userids = 0, }
{ start = { -1219 250 2232 }, end = { -1232 142 2318 }, radius = 50, flags = 1, areas = 63, dirs = 1, userids = 0, }
```

There. It's better, but still a pain, some stuff make no sense at all. Let's fix all remaining issues in one shot:

```
{ start = { -1623 226 1772 }, end = { -1665 76 1898 }, radius = 50, flags = {1,}, areas = { 63, }, dir = oneway, UID = { 0, }, }
{ start = { -1219 250 2232 }, end = { -1232 142 2318 }, radius = 50, flags = {1,}, areas = { 63, }, dir = twoway, UID = { 0, }, }
```

It's pretty close to json, by now, but json have a pretty poor specs which makes it a pain to be really compliant, so I'm not sure I want it.
Also, I want comments, in there:

```
# thunder human base
{ start = { -1623 226 1772 }, end = { -1665 76 1898 }, radius = 50, flags = {1,}, areas = { 63, }, dir = oneway, UID = { 0, }, }
# thunder alien base
{ start = { -1219 250 2232 }, end = { -1232 142 2318 }, radius = 50, flags = {1,}, areas = { 63, }, dir = twoway, UID = { 0, }, }
```

And, yes, it's possible to get those comments automatically generated, because quake3 maps have those entities which serve exactly that kind of purpose.
One line per navcon, extensible format, diffable, readable. I think the last of those meet all requirements.
You might notice the fact I have commas to mark the *end* of a field. It's a bit weird for a non-coder, but this makes it actually nice to parse, including for a trained human eye.
I think I can implement a parser generator in coco/R for that in less than a day.

**Comment by DolceTriade** [comment]
If it's close to json, should we just use json? or maybe jsonl?

**Comment by bmorel** [comment]
> If it's close to json, should we just use json? or maybe jsonl?

Why not. But json is just a "meta format", it's still important to define what we really want, the "tags" we want, and the features we need.
For example, the "areas" thing, in the above posts, I have no idea what it is for.

**Comment by bmorel** [comment]
One thing that might be very precious is to have *one* navcon file for multiple classes.
Ideally, we shuold probably migrate toward the same regarding the navMesh files, because the current situation really does not scales well.

If we keep the 2 files per class paradigm, it means that we'll end with 22 files in  the `maps/` folder per map. My server currently hosts 114 maps, so it means it could top at 2508 files.

**Comment by illwieckz** [comment]
> One thing that might be very precious is to have one navcon file for multiple classes.

Maybe.

In all cases one of the advantage of text navcons is that you can easily copy paste some of them for other classes.

For example while working a bit on the RSMSE map these days, I experimented about adding some navcons and see how bots behave. It looked like The navcons I did for one classes were 100% reusable with other classes, though I may want to add only one navcon for a specific class while sharing all the others. With a text navcon I would just do all the generic navcons first then the specific one last and copy paste all-but-last entries for every classes.

**Comment by illwieckz** [comment]
Such format like those look good to me:

```
# thunder human base
{ start = { -1623 226 1772 }, end = { -1665 76 1898 }, radius = 50, flags = {1,}, areas = { 63, }, dir = oneway, UID = { 0, }, }
# thunder alien base
{ start = { -1219 250 2232 }, end = { -1232 142 2318 }, radius = 50, flags = {1,}, areas = { 63, }, dir = twoway, UID = { 0, }, }
```

Why not jsonl.

I don't mind that much the format but I would really appreciate if a single connection fits in one line, it would make very easy to copy/paste or even move connections around files.

About the coordinates and the ordering of X, Y, Z, etc.), I would recommend to use the same ordering the data are stored in .map files, which is the same ordering which is used in layout files (which is already appreciated as one can already copy paste coordinates from layouts to map entities..

**Comment by bmorel** [comment]
>  It looked like the navcons I did for one classes were 100% reusable with other classes,

Exact, it's even how I work most of the time: do navcons for a class, shrug and duplicate it for all classes. Thinking about it, a single file for all classes would just make the thing easier to maintain, as it would have less duplication.

I'm even thinking that, instead of classes, it would be possible to specify requirements, as in, "agent radius between X and Y, agent height between W and Z, jump magnitude > A, requires abilities D, E, F, G".
Ofc, currently we only have the in-game editor, and it would not be able to easily support that, but since anyway we use in-game editor and then refine it manually (or rather, copy/paste the file) I don't think this would be a problem.
About abilities, it's things like: have a jectpack, can wallwalk, can pounce, can walljump, can wallrun, takes fall damages, etc.


> I don't mind that much the format but I would really appreciate if a single connection fits in one line, it would make very easy to copy/paste or even move connections around files.

I consider this a requirement. Otherwise things won't be easy to diff.

**Comment by sweet235** [comment]
I spent some time making navcon files for quite a few maps (https://github.com/sweet235/navcon). Maintaining these files is cumbersome in the long run, I agree on that we need a text file format. There is a PR with a binary to text converter (https://github.com/Unvanquished/Unvanquished/pull/2329). I would suggest to use this format and add a header to indicate the file format version. What do you think about that?
