### ISSUE TITLE
The need of simple `bot fill` as a cvar aka `minplayers`

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1786]
Configuring the amount of bots of a server as a cvar has many advantage:

- no need for specific `map/default.cfg` config for simple-enough good-enough configuration (while complex things can still be done);
- makes easy to set-up a configuration entry in UI;
- it's usually the way it is done in other games so people may be familiar.

For example in Smokin' Guns this is configured with `bot_minplayers` cvar, the number is the amount of minimal players a server always have on a map, being bots or real players (so the server fills with bots if needed). Another cvar named `bot_enable` can enable or disable bot filling without setting `bot_minplayers` to `0`.

In ET:Legacy (Wolfenstein: Enemy Territory) the cvar is also named `bot_minplayers` and there is also `bot_enable`.

In Xonotic, this is configured with `minplayers` and `minplayers_per_team` cvars, the first one being the amount of filling bots on non-team games and the second one the amount of filling bots per team on team-based games.

This can be implemented by calling `bot fill` with a cvar value at the start of the game. We may want to do that before actually reading map config files so config files can override this with direct `bot fill` calls.

Additionally Xonotic implements `bot_number` for a minimal amount of bots. I assume it's the equivalent of calling a bunch of `bot add` at every map start.

**Comment by illwieckz** [comment]
In fact, `bot_minplayers` and `bot_enable` are found in Quake 3 as well (as ancestor of both Smokin'Guns and Wolfenstein: Enemy Territory).

**Comment by illwieckz** [comment]
Regarding solo game problem (#1758) I would simply set `bot_minplayers` to `6` (in a way there are 6 bots on the empty servers) and enable `bot_enable` by default, so players can start a local game in two clicks (open server creation window, start).

**Comment by slipher** [comment]
So get rid of `bot fill` and have 4 cvars `g_bot_fillHumans` `g_bot_fillAliens` `g_bot_skillHumans` and `g_bot_skillAliens`?

**Comment by bmorel** [comment]
Currently, bots have:

* g_bot_default_skill
* g_bot_attackStruct
* g_bot_fov
* g_bot_chasetime
* g_bot_reactiontime
* g_bot_infinite_funds

Adding a 7th one for minimum number of players would be nice indeed.

As for the per-team idea, I do not dislike it, BUT it would be inconsistent. I think we either need a way to get arrays, which would apply for all those cvars, or to have actual objects, so that we would have one cvar per team.

I am going to implement the single cvar version, because I think this is really needed.
