### ISSUE TITLE
Map configs can't set layouts

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#1796]
Setting `g_layouts` in a map config does not work as intended, because map configs are not executed until after the first sgame frame. This is a consequence of command buffering - when trap_SendConsoleCommand is called, it does not immediately execute the command but rather inserts it into a buffer to be executed later.

Earlier we discussed the annoying consequences of configs being executed after the new map starts - you can't use the map config to set cvars that require a restart like `fs_extrapaks`. The current issue happens because the configs are executed after the *first frame* of the new map.

**Comment by Gireen** [comment]
is this the maprotation or default map configuration?
in the rotation its `layouts` https://wiki.unvanquished.net/wiki/Server/Map_rotation

**Comment by slipher** [comment]
Map rotations hopefully work. This is about the config files in a directory specified by `g_mapConfig` (`$g_mapConfig$/default.cfg` and `$g_mapConfig$/$mapname$.cfg`)

**Comment by bmorel** [comment]
map rotation random layout selection works, yes. The only issue i had there was that I had to export the default layout, to put in the list, as in `layouts "default" "alt1"` while I would have preferred a way to list the builtin instead of default.
I do not think it's a good idea for config files to be able to change the layout, though. I don't even see what it could be used for?

**Comment by slipher** [comment]
> I do not think it's a good idea for config files to be able to change the layout, though. I don't even see what it could be used for?

Maybe on some map you want a certain layout to always be used.

**Comment by Gireen** [comment]
could we move the relevant parts to a separate file?
like `$g_mapConfig$/$mapname$.before.cfg` with anything that requires a mapchange
Where the file would be executed at the end of the previous map.

**Comment by slipher** [comment]
> could we move the relevant parts to a separate file? like `$g_mapConfig$/$mapname$.before.cfg` with anything that requires a mapchange Where the file would be executed at the end of the previous map.

 The problem is that all config files are requested to be executed from inside the VM. But the map/devmap commands immediately kill the sgame VM and move to the next map, so there's no way for the sgame to consistently ensure something is executed before it starts.

But maybe it would be reasonable to implement this in the engine. Perhaps we could try to execute the "before" config between ClearPaks and FS_LoadBasePak in SV_SpawnServer.

**Comment by DolceTriade** [comment]
If you want to use mapConfigs to set layouts you should run `/restart <layoutname>` and not set any cvars.

**Comment by slipher** [comment]
I don't remember why I thought this ought to work anyway.
