### ISSUE TITLE
Games with players not listed by Unvanquished bot

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1797]
I've noticed since several months that my instances are never listed by the `Unvanquished` bot, and decided to try to find out why today.
Note that the information is *correctly* reported by game client.

After a bisect, the bug appears with commit 6185aa8c5
I tried to enable g_autoPause (and g_autopause) in my configuration files, with the last version of my mod, and it did not fixed the problem, so maybe in my mod something else triggers the bug, but the bug still seems to appear at this commit, which is right after v0.52.1 tag.
I think, but I'm not sure about it, that the nightly server is not affected.
I also think it may be unrelated to that cvar, since it really makes no sense to me.

I've opened this issue to keep track of hints about this problem.

**Comment by bmorel** [comment]
This bug is actually present in unvanquished's official server, located in USAs (my server is located in france) and running v0.52.1.

**Comment by necessarily-equal** [comment]
Not freem said on IRC the bisect was actually not successful and that it doesn't prove any commit changed this. So this suggests that this has not changed since 0.52.1 and would be caused by something else

**Comment by illwieckz** [comment]
There are multiple things that may prevent a server to be listed, some are fixed in master:

- #1748  
to fix https://github.com/Unvanquished/Unvanquished/issues/1747#issuecomment-1038325925
- https://github.com/DaemonEngine/Daemon/pull/579
to fix https://github.com/DaemonEngine/Daemon/issues/534  
- #1749

Are you sure the disappearing server doesn't fall into one of the two first issue?

**Comment by bmorel** [comment]
Well, my server does appear in-game and on https://unvanquished.net/servers/, that's all I can say.
I tried hacking server.cfg config file, could not get any obvious clue, investigations continue.

**Comment by bmorel** [comment]
So far, it seems that only the SKx and the "stable official" instances are affected, but the SKx instances are  listed on https://unvanquished.net/servers/.
I've tried ITA, illwieckz, new-edge... none is affected.

I've tried disabling only the loading of my mod, and it fixes the problem, yet the previous bisect work showed nothing obvious. I'll dig more in the history of my mod, just in case there's something I've missed...

**Comment by bmorel** [comment]
I did a recent update, which was resynced on master, and the bug seems solved.
