### ISSUE TITLE
cg_disabled* cvars dont work as implied

### ISSUE THREAD

**Issue by t4im** [Unvanquished/Unvanquished#180]
e.g.: cg_disabledBuildDialog or cg_disabledUpgradeDialog will only disable build/upgrade related warnings, while the build, evolve and buy dialogs/menus will still pop up.

this should be fixed independed wheter they disable the wrong things or are just badly named cvars (dialogs imply a two directional communication, needing a feedback/selection more than just 'close'/ok)

**Comment by DolceTriade** [comment]
Obsolete.
