### ISSUE TITLE
Allow bots to ignore momentum when g_bot_infinite_funds is on

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1801]
Currently, making bots cheat only give them infinite credits. They still can't buy stuff which is still locked.
Doing so would make it possible to let them buy stuff even if locked after some time, in dedicated BTs, which I'm planning to use to create "mob BT" for PvE layouts.

One question is, should it be possible to enable only one kind of cheat mode? That is, either the infinite funds, or the infinite momentum, or both?

Also, it might be interesting to only allow some bots to cheat, for example by making it a BT action.

See #1802.

**Comment by necessarily-equal** [comment]
For the record, I do have a `g_disableMomentum` (still fairly hacky) cvar that I use for my prototype tutorial mod. Would this work for you or do you think it would be important to keep the momentum system for the other team?

**Comment by bmorel** [comment]
For a start, I think it should not apply to players.

Then, yes, a global cvar could work, but sometimes I think I'd like to have specific settings on a per-bot fashion (without having to write a specific BT each time). This is likely a bigger change to do though, and out of scope of this feature request.

**Comment by necessarily-equal** [comment]
Yeah so you are looking for a different thingy

**Comment by bmorel** [comment]
I guess it should be a separate CVar.
