### ISSUE TITLE
Implement levelTime condition for BTs

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1802]
This would allow bots to change behavior based on how old the game is, to become more aggressive, for example.
See #1801

**Comment by necessarily-equal** [comment]
"LGTM" by @bmorel on IRC

**Comment by bmorel** [comment]
This actually already exists:

* https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_bot_parse.cpp#L351
* https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_bot_parse.cpp#L223-L226
