### ISSUE TITLE
"Warn: no more slots for bot" is spammed all the time

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1812]
Instead, this should be only printed *once* when the command is run.
And the warning should be more visible, like what happens when one does a `/warn` in console, since the actual chat might be flooded already, and this means that teams will be imbalanced, so it's important to not miss it. And one can't scroll the scoreboard AFAIK so only the log can be used to notice that fact.
I also suspect this can have a huge performance cost.

**Comment by necessarily-equal** [comment]
This doesn't seem to be run every frame, so I'd say this is fine performance-wise. Does this happen only with `bot fill 32`? I could reproduce with `bot fill 32` but not `30`.

**Comment by bmorel** [comment]
Just do `/bot fill 127`, observe the output of `top`, and then do `bot fill FOO` replacing FOO with half the maximum number of clients on your server.
On my cheap VPS, there is a real performance impact, maybe because I log unvanquished's stdout and stderr by piping them to another process (which only adds a timestamp, saves them and does rotation).

**Comment by slipher** [comment]
Bot fill quotas are checked every 2 seconds IIRC.

**Comment by necessarily-equal** [comment]
Workaround: don't try to add more bots than the maximum number of allowed client minus one.

**Comment by bmorel** [comment]
> Bot fill quotas are checked every 2 seconds IIRC.

Exact. One warning per full team, every 2 seconds. The problem is less important than I thought then, but I think a correct behavior would be to warn only when the command is ran, with number of effectively filled bots set to maximum value.

**Comment by bmorel** [comment]
I no longer think this can be fixed, as there is no way to know what will happen in the future, that is, players or spectators arriving or leaving the game. This would change the number of clients, and hence affect the number of slots.

**Comment by xXRaptorSc0pezXx** [comment]
The “Warn: no more slots for bot” message really needs to get fixed before the next release it is driving me crazy having it flash up in the corner constantly. Like I'll just start a local game and spawn in and it automatically fills the teams up and then that message just keeps flashing over and over and over and over it's incredibly annoying. It literally makes the game unplayable with how distracting it is for me.

**Comment by slipher** [comment]
@xXRaptorSc0pezXx This is likely a result of using the `Server setup > Bots: General > Minimum bots per team` option. You can fix your personal issue by sliding it to 0 (or any number less than 10).

**Comment by xXRaptorSc0pezXx** [comment]
Yes that fixes it, but my point is that the message needs to get fixed because I shouldn't have to micro-manage the game for itself. I should be able to start up a local/LAN game and it should spawn the correct number of bots without displaying warning messages that distract the player.

**Comment by bmorel** [comment]
I agree this is a problem.
So far, both a user and a developer reported it, so just saying people to RTFM and do the job the game should do is not the correct answer.

**Comment by bmorel** [comment]
This also prooves the importance of better GUI, as it prooves the fact people want to run the game in LAN or solo. We need to put more efforts in that area, now that bots are almost decent.

**Comment by xXRaptorSc0pezXx** [comment]
Agreed @bmorel "proves the fact people want to run the game in LAN or solo" I pretty much play exclusively in solo to be honest so I am excited about the bot improvements and more future improvements to the singleplayer experience in Unvanquished.

**Comment by bmorel** [comment]
> and more future improvements to the singleplayer experience in Unvanquished.

It's good to know, as I'm planning to have the mechanism to have campaigns. But don't hold your breath, especially since I'll likely mostly use "contrib" maps. Mostly for online gaming, but there's no reason to make this unusable in solo, far from it.
To be honest, I'd like unvanquished to be more playable solo, sometimes I enjoy solo-ing too, and currently unvanquishsed is not very good at that.
And I started AI improvements because I was actually playing a lot... solo :)

**Comment by xXRaptorSc0pezXx** [comment]
Yea solo is great I've been playing since...2016? if I remember correctly. When I was younger I used to have this crappy little laptop and no money for Steam games so Unvanquished was one of the only games I could play. It was fun to bring my laptop on trips and be able to play some singleplayer matches while just sitting around in the hotel room. Glad to hear more singleplayer focused updates are coming! :D

**Comment by bmorel** [comment]
It's not technically focused on SP, but it does not means SP won't benefit from it.
