### ISSUE TITLE
Implement a way to make bots verbose without changing BT

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1828]
The way it should work is, by switching a CVar, bots should say which action they're taking and it's result. Possibly also condition evaluations. Ideally with the line number.

**Comment by slipher** [comment]
I implemented something similar a while back. If you `g_bot_traceClient` to a client number, the currently running action and its line number are printed each frame for the respective bot. (Only one bot at a time since printing all of them would seem unbearably spammy.)
