### ISSUE TITLE
have per-faction BT folder

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1829]
Currently, each behavior can be used by any faction.
The problem is that alien and human factions are very different, and their BTs really are not similar at all, and as the bots are improved, this difference will increase.

I think it would make much more sense to have a directory layout like this:

* bot/ => contains the shared code snippets (mostly unstick, maybe more someday)
* bot/alien => contains files specific to aliens
* bot/human => contains files specific to humans
* bot/neutral => ok, no real need for now :) (or, one could make bots  move to spectator instead of being kicked, this would allow them to keep their money when players log in/off...)

This would allow to have one "default.bt" per species, without the need for explicit splitting as done currently.

To be honest, I'm not sure this would bring many (if any) benefits.

**Comment by necessarily-equal** [comment]
I'm not sure one can have a `/` inside the behavior name.

**Comment by bmorel** [comment]
> Why not "spectator" instead of "neutral"?

Because I prefer generic things.

> I think, this BT system must be replaced, 

All it needs is people with time, skill and will to do it. And the problem to have many files in a same place, or just a bunch of few unreadable files would still be true with a different mechanism.

**Comment by bmorel** [comment]
I don't think this is going to happen, and it's not really important anyway.
