### ISSUE TITLE
Hardly visible "cancel" button in circle menus

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1836]
In the screenshots I did for #1835, I noticed one thing: the "cancel" button is hardly visible, in both 0.52 and 0.53.
Since it's not a regression, I'll call than an enhancement request.

**Comment by necessarily-equal** [comment]
Fixed by https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/commit/28b772899a97b932adbe0b349d842134f929caf3, I believe
