### ISSUE TITLE
bots should rebuild critical buildings when destroyed

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1868]
I think bots should be able to (re)build critical buildings when they never existed or lasts ones (plural for spawns) were destroyed (not moved).
Those are:

* spawns (egg/telenode)
* uniques (RC/OM)
* armoury
* healers( medistat/booster)

They shall build those either near (as in navmesh near) the unique (RC/OM), or , for when the Unique (RC/OM) was destroyed:

* neither old place is considered safe, then rebuild it
* old place is unsafe... wander around to find a new, reasonably safe place, and build

The intent would be to multiple, but includes making players do less camping as bots would do some of the basic rebuild tasks.

I believe this is technically doable in current status of 0.52 unvanquished, and will be much easier in 0.53 considering the objectives I put there myself (that I all have a rough idea how to do).

**Comment by bmorel** [comment]
just so that the idea I got recently is not lost, I know a possible way to implement it:

* expose BT API to check for number of buildings of a specific type;
* expose BT API to place building's blueprints;
* expose BT API to choose the spawn class. This means that BT should be ran even when the bot is dead;
* generate navmeshes for buildings. This will allow bots to know where they can build, at the cost of generating *a lot* more navmeshes when a map is 1st loaded;

The main difficulty in the rebuilding idea is basically to query where things can be built, and that's exactly what navmeshes provide in the end: a surface where a specific entity can be.
Of course this won't easily allow alien bots to build on walls and ceilings, but that's still would be an interesting start.

**Comment by slipher** [comment]
This has been done. There is now `spawnAs` to spawn as builder and an action that rebuilds critical buildables which is used in the default BT as well as `build.bt`.
