### ISSUE TITLE
It's impossible to switch back to native screen resolution once you tested another screen size

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1892]
If your screen has a resolution that isn't in the list, you can't select it, and you thus can't have the correct resolution for your screen.

Example test procedure:
* have a 1366×768 screen or anything else not in the resolution list
* launch a new profile
* see your resolution marked as "custom"
* switch to another resolution
* restart the game (maybe?)
* try to switch back to your normal screen resolution.

**Comment by bmorel** [comment]
Editing the autogenerated config file to modify width, I could switch back to normal resolutions without any problem

**Comment by necessarily-equal** [comment]
Oh yes that's what I did too (editing the cvar manually). The only reason I don't have https://github.com/Unvanquished/Unvanquished/issues/1891 as a problem every day.
