### ISSUE TITLE
Implement RmlUI font fallback

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1893]
We have more than one font family in the dpk, notable we have the GNU Unifont that's here as a fallback, beside being used by the console. Problem is that it isn't actually marked as a fallback, so it won't be used in the UI.

This can allow some font rendering for (e.g.) Cyrillic or CJK languages. Not sure if that'd be enough for e.g. arabic.

**Comment by DolceTriade** [comment]
it would allow rendering of those fonts, but it wouldn't correctly render them RTL unless we include libharfbuzz

**Comment by slipher** [comment]
I tried to do that in fb43dd4c860817abfa31557c4e536086f1b4df30. Is it not working?

**Comment by necessarily-equal** [comment]
My bad then. Here are some text samples:

![image](https://user-images.githubusercontent.com/59283660/179327626-a56f09bb-3d3a-4bdd-bd88-6a3eb4428bb5.png) ![Screenshot from 2022-07-16 02-44-57](https://user-images.githubusercontent.com/59283660/179327637-9d89a5ed-0e18-4c50-a65d-144793f3aa7a.png) ![image](https://user-images.githubusercontent.com/59283660/179327662-9a2fb538-4e4f-4fa7-bcad-c71222ddb547.png)

It looks like unicode text is working well enough even if arabic is probably forced left-to-right.

I'll close this.

**Comment by necessarily-equal** [comment]
(btw this is current 0.53.0, you can note that the text is unreadably tiny — something I try to improve in https://github.com/Unvanquished/Unvanquished/pull/1840 and in its companion PR)
