### ISSUE TITLE
improve beacon system

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1896]
Currently, there are 5 beacons which do not last long at all:

* attack: 10s
* defend: 10s
* pointer: 2s
* repair: 6.5s
* timer: 3s

This is way too short to be of any use. Can probably be multiplied by 3 without much problem.

Also, I think becons should be accompanied with team-chat, and possibly some could be modified. I mean, "pointer", for example, what can it be used for? Especially if this lasts 2s only, it's roughly the time you need to select it with the circle menu.

**Comment by DolceTriade** [comment]
+1. Beacons are super powerful and very cool. We need to find better and utilize them to aid teamwork

**Comment by bmorel** [comment]
well, one way to enforce their use would be to make bots understand them, but this requires preliminary work. I have stuff to go in that direction, but don't expect a real multi-goal to be ready soon.
Maybe the gameplay itself could reward team play, though? Like, a kill would earn extra money and/or momentum if helped considerably by a friend, and extra reward for a "revenge"? Those are just random ideas.
