### ISSUE TITLE
0.53 bright circle menu icons

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1918]
Icons in circle menu that can be bought (unlocked) are very bright. @necessarily-equal: This might be for the same reason as for #1834 

This is not blocking, though, but imo (taste thing) it looks ugly.

**Comment by slipher** [comment]
The 0.52 circle menu images were terrible. I could hardly tell which building was which on the building menus. It looks way better in 0.53. Stop trying to say that bug fixes are regressions :laughing:

**Comment by necessarily-equal** [comment]
That would be me https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/113/commits/8ce05ba3d4fd1104e63ded137f33082ee4ea612a#diff-480b0eca4816a92d641848b6be3c9337d2ef02bf82b0f6a5e962ac7a1a30b81d

**Comment by bmorel** [comment]
> The 0.52 circle menu images were terrible.

They still are, because the icons are over-detailed, but this is a different problem. Actually, the over-bright icons makes the small black lines even harder to see than before.

Here are the 2 screenshots btw:

0.53:

![2022-07-18-224147_1362x748_scrot](https://user-images.githubusercontent.com/1316300/179614004-14f6d245-0950-4630-b0a3-17bea07a883e.png)


0.52:

![2022-07-18-224055_1362x748_scrot](https://user-images.githubusercontent.com/1316300/179614021-7ac6e82f-886b-4500-8a69-c9e21149ec79.png)


So that we have the same reference.

Now that I take those, I see 2 unrelated things (with this issue): the tick's position has changed, probably not on purpose (not a problem) and it's hardly visible at all.
The brightness change, which is probably due to the same bug which was there in 0.52 for the levelshot, is obvious here. If it's not considered a bug, fine. Call that a feature request if you prefer.

**Comment by slipher** [comment]
The 0.52 evolve menu looks OK. The human building one is one that was bad.

**Comment by bmorel** [comment]
The alien building also looks bad. The icons are over-detailed, which is the root of that particular problem imo. Unrelated to brightness change though.

**Comment by bmorel** [comment]
I think this can be closed now.
