### ISSUE TITLE
allow BT to select the birth class in BT

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#1932]
Currently, bots *always* spawn as naked+smg or as dretch. This decision should belong to the behavior tree, as it would allow bots to spawn with a ckit when repairs are needed, or when base in on fire.

In future, it would also allow them to build missing armory.

Note that, for granger spawn, navmeshes for grangers have to be generated, and IIRC this is explicitly prevented in the 0.53 navmesh generation merge (because currently bots are unable to either spawn as, or devolte to, granger, so this makes sense).

**Comment by necessarily-equal** [comment]
This isn't simple because the BT isn't even called if the bot is dead.

I'd say the first step would be to change that, and check something like `condition isDead(E_SELF) { behavior selectClass }` at the beginning of every BT.

**Comment by bmorel** [comment]
Yep. There are 2 BotThink() functions, and that's the root of the problem.

**Comment by slipher** [comment]
We did that. The `selectClass` tree
