### ISSUE TITLE
implement some UI to select the default bot skill

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1936]
Bot skill can range from 1 to 9, included.
The bot setup dialog box should allow to configure that.

**Comment by necessarily-equal** [comment]
Like this? https://github.com/Unvanquished/Unvanquished/pull/1626

**Comment by bmorel** [comment]
This introduces a Cvar, but there's no UI AFAIK

**Comment by bmorel** [comment]
see https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/147

**Comment by bmorel** [comment]
fixed by https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/147
