### ISSUE TITLE
allow to distinguished between connected and actually here players

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1942]
Currently, it is logged when players are connecting and when they are joining. It is not really obvious they are ready to see what happens. I think this should be fixed.

**Comment by slipher** [comment]
The "entered the game" message isn't what you want? If not I don't understand what you're looking for.

**Comment by necessarily-equal** [comment]
Agreed, I've had this one on my todo list for long.

**Comment by necessarily-equal** [comment]
The problem is that you often say "hi" when you see "X connected", except they are actually on the loading screen.

**Comment by bmorel** [comment]
I wonder if the message "foo connected" is actually of any use. People *do* see it, and misinterpret it for "foo is here" but foo won't be able to see messages nor interact in any way.
Maybe we should simply remove that 1st useless message.

**Comment by Gireen** [comment]
the message is there to know that a player is still there when they are for example downloading a map.
it could be renamed to `Playername is connecting...` to prevent misunderstandings

**Comment by slipher** [comment]
> The problem is that you often say "hi" when you see "X connected", except they are actually on the loading screen.

Well, if you know what's up, then you can say "hi" when you see "X entered the game".

**Comment by necessarily-equal** [comment]
> Well, if you know what's up, then you can say "hi" when you see "X entered the game".

Well, we can also have non-confusing UI.

I'm making a PR to change the message, but maybe we could remove it entirely, not sure.
