### ISSUE TITLE
Contrast is bad on server list

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1943]
![image](https://user-images.githubusercontent.com/59283660/180102492-64810c97-c34f-4466-90ea-e98ddffcaaf1.png)

The dark blue/turquoise links are not very visible. The color should be changed for something more contrasted.

I can guide someone on how to do that.

**Comment by cu-kai** [comment]
I think we can consider this closed by https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/commit/a06f6009f00d892990e868b205a61fb7f751a460?
