### ISSUE TITLE
Build/Test 0.53 Linux client

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#1962]

**Comment by necessarily-equal** [comment]
Well I think I kinda did that already locally, because I'm doing more than half my tests on the 0.53.0/sync branch. This doesn't test the release binary though.

**Comment by DolceTriade** [comment]
Specifically,  this is testing the binary we plan to release. More than bugs, we have to ensure it runs on various distros, libc, gcc issues, etc.

**Comment by DolceTriade** [comment]
Done. Only a small not-reproducible issue found.
