### ISSUE TITLE
Server list shows only one server

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1965]
with 0.52.1 as packaged in NixOS:

![image](https://user-images.githubusercontent.com/59283660/180644598-9f5883d7-9fec-46ee-9b66-a14b5c6c0833.png)

with daemon a5c48479de66913b0766d2a12cae92786b41fbf8 and unv.dpkdir from around 30 jun 0.53.0/sync in a flatpak:

![image](https://user-images.githubusercontent.com/59283660/180644583-57ff7ae6-8fea-4e4f-8530-b79ed34a0e94.png)

those day I have a 100% reproducibility rate, and pressing the "refresh" button make the list empty. So this is pretty annoying.

**Comment by Gireen** [comment]
It really odd that there is only one server and not a random number of them.

Can it be a network problem?
In a network traffic log you should see a query to the two masterservers and the responses.
Unlikely but if they are really short like 5 chars then that could be the source. 

Then there are getstatus requests send to all servers and there should also be responses.
If there is only one then that might be the reason.

**Comment by necessarily-equal** [comment]
This is an instance of https://github.com/DaemonEngine/Daemon/issues/654
