### ISSUE TITLE
momentum can be negative

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1966]
Currently, momentum can be negative. The faster way to check is: `devmap plat23`, then `/team h; give momentum -50; give momentum 100`. This will only unlock stage 1, and not stage 2.

This is either a bug in gameplay, if negative momentum should not exist, or a bug in UI, as the momentum bar can't show negative momentum.

**Comment by bmorel** [comment]
FWIW I hacked a command to just print momentum of both teams, and deconstruction clearly allows to have neg momentum, unlike loosing a building.

**Comment by DolceTriade** [comment]
Can you actually get negative momentum without using cheat commands? If not, then I don't consider this a bug. Cheat commands are cheat commands because they can do things that break the game.

**Comment by bmorel** [comment]
Otherwise I would not have reported this.

**Comment by DolceTriade** [comment]
I see. I only ask because your repro instructions involve using a cheat command. Is there a way to repro without using a cheat command? Never the less, I'll audit the code.

**Comment by bmorel** [comment]
just deconstruct anything at start of a botless game and use /print_momentum

**Comment by Viech** [comment]
It's a little bit late but I like to clarify that negative momentum was intended to prevent a net momentum gain from start-of-game deconstruction followed by reconstruction.

I don't mind the clamp at zero much but it does open up some cheeky strategies where you get an advantage for first deconstrucing unwanted buildables and *then* construcing those you do want.

**Comment by bmorel** [comment]
I would argue that default layouts always suck, to the point of actively feeding enemy. To the point that people don't even have time to connect to protect, i.e. the 1st turret in chasm.
So deconstructing the starting base is a necessity in many situations, and until we get this fixed in official maps & layouts, then moving should not be punished.
