### ISSUE TITLE
momentum is not affected by timescale

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1970]
To reproduce: `/timescale 5; give momentum 50`, wait a bit, momentum decreases as slowly as with timescale of 1.
This makes debugging harder.

**Comment by necessarily-equal** [comment]
Remilestoning for 0.55 as this is a debug tooling issue and not one that show up in-game.

**Comment by bmorel** [comment]
It's not just a debug tooling issue, nothing would prevent people from hosting accelerated or slowed down servers.
But the problem is:

* non trivial;
* a low priority;
* timescale affects many other things in such buggy way;

So I think this should be milestoned for post-beta, considering the low emergency, wide impact and big complexity of the problem.

**Comment by slipher** [comment]
I just tested this with `give momentum` and `print_momentum` and it works as expected. The momentum decreases faster with a high timescale. Anyone who can reproduce this may reopen.

**Comment by bmorel** [comment]
`give_momentum` always gives a fixed amount so yes, it's not affected by timescale ofc. IIRC what did not scaled was the momentum you gain by killing a building or an enemy.

**Comment by necessarily-equal** [comment]
What may happen is that it could be displayed wrong on the client. 
After all the client has a different "/set timescale" settings because 
its cvar is different. And setting the cvar on the client gives… 
interesting results. Maybe that would be the real issue here. (Not sure 
if worth fixing or not. Maybe not.)

**Comment by necessarily-equal** [comment]
@bmorel I think you could reopen the issue after updating the description to describe the slightly different problem that you said is the real one.

**Comment by bmorel** [comment]
need to verify before.
