### ISSUE TITLE
Game crashes on certain maps, likely graphics-related

### ISSUE THREAD

**Issue by VReaperV** [Unvanquished/Unvanquished#1971]
Certain maps crash (game immediately closes) when loading, sirius crashes when looking at certain spots. That most likely means that the crash is graphics-related.
An example of such spot on sirius is looking up from the default spectator spawn: 0 -580 128, towards positive Z.
Maps that crash immediately after loading: orion, procyon, terminus. Maybe on some other maps too. Crash dump is included (for sirius), console log does not seem to have anything of note.
[064b2261-4c47-4c1e-b3f4-10fc723e9ed3.zip](https://github.com/Unvanquished/Unvanquished/files/9176051/064b2261-4c47-4c1e-b3f4-10fc723e9ed3.zip)

**Comment by slipher** [comment]
I haven't checked the crash dump but it's probably #1444, which occurs if you selected the "lowest" graphics preset.

It can be avoided by selecting the "Low" preset. (Or alternatively, type `/cg_bounceParticles 1` in the console.)

**Comment by bmorel** [comment]
Just to be sure, do you have the crash when starting the game locally? AFAIK only betterai servers have sirius map, and they do have various experimental changes. I don't think it could make client crash, but it might be safe to double check that.

**Comment by VReaperV** [comment]
> I haven't checked the crash dump but it's probably #1444, which occurs if you selected the "lowest" graphics preset.
> 
> It can be avoided by selecting the "Low" preset. (Or alternatively, type `/cg_bounceParticles 1` in the console.)

It was already set to 1.

**Comment by VReaperV** [comment]
> Just to be sure, do you have the crash when starting the game locally? AFAIK only betterai servers have sirius map, and they do have various experimental changes. I don't think it could make client crash, but it might be safe to double check that.

Crashes on local too.

**Comment by VReaperV** [comment]
Apparently this has to do with the lighting system. Grid light crashes (r_vertexLighting == 1), light map doesn't.

**Comment by slipher** [comment]
Oh, must be this one: https://github.com/DaemonEngine/Daemon/issues/500

**Comment by slipher** [comment]
Checked the crash dump and confirmed that it is the same as https://github.com/DaemonEngine/Daemon/issues/500. Fix underway.
