### ISSUE TITLE
Granger UI BP text size is too small

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#1972]
This is a regression.

## Alpha 53
![](https://i.imgur.com/1b85Ok9.jpg)

## Master
![](https://i.imgur.com/9hU60uo.jpg)

**Comment by bmorel** [comment]
Weird, it was fixed few days ago, see #1833 
@necessarily-equal any idea what happened?

**Comment by necessarily-equal** [comment]
I didn't touch this line. Fixed it on human side though. Btw the one on the left is also wrongly sized

**Comment by necessarily-equal** [comment]
Not sure why it's not linked on this issue automatically, but fixed by https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/137

**Comment by bmorel** [comment]
Weird, I'm pretty sure I checked this one was fixed in the recent past... Guess I'm wrong on that.

**Comment by DolceTriade** [comment]
Fixed by https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/137
