### ISSUE TITLE
translation infrastructure

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1986]
There are not that many strings in unvanquished, so I'd like to play with translating it to french, but I have various infrastructure and methodology questions that I think should be solved before. Maybe some were answered in past PRs or issues. To prevent this to be hard to find, I'm introducing the A-Translation label.

Code should now support translations anew, but I have several questions regarding this process.

Translations are usually done by scanning source files for a token, to generate a `.pot` file, which is then used to generate one `.po` file per language. Those files originally only contains "C" versions of strings with the location where they were found.
Currently, I see 3 repositories in which we can find strings to translate:

* daemon-engine, C++ files. Not sure if there's things to translate here, possibly error messages, but *only* if the "C translation" is also shown, as otherwise support will prove extremely hard to do. CVar's descriptions *might* be candidates, though.
* unvanquished, C++ files. Same remarks as for daemon-engine, except that this repo also contains things like `The Overmind is dying!` which are obviously to translate.
* unvanquished_src.dpk, rml and config files. Most of the user-facing strings here are probably to translate, this includes configuration files which contains the descriptions of equipments and classes.

Am I missing something?

Other questions are:

* are we going to use `gettext` for all the stuff, or only for the C++ sides?
* should the translations of unvanquished and unvanquished_src.dpkdir be split, at the cost of making things much more painful, or should the translations go in their respective repo, increasing the problem of style mismatch?

If there are other points or questions I've missed, please say so. This issue is also far from being urgent, since the current priority is 0.53, but I think it would be nice to be able to draft some translation infrastructure for 0.54. I'm still milestonning this to post-beta because there's probably much to talk about, and it might require work not directly related to this to be done (I'm thinking about the problem of the unvanquished_src.dpkdir submodule, here).

**Comment by DolceTriade** [comment]
Ultimately, gettext (or tinygettext in our case) will be used for all the strings. Ie, we should store all the strings in a .po file, and we should setup web based infrastructure to do this translation.

**Comment by slipher** [comment]
We decided not to support translation in the engine for now. All translation strings come from the single repository which now contains Unvanquished C++ and RML sources.

Translation strings are scraped with gettext plus custom scripts, stored in the path `tools/translation/`.

The README contains instructions for accessing the translation web interface.
