### ISSUE TITLE
Server list doesn't refresh after checking local servers

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#1988]
On the in-game server browser, once you have opened the local server list, the internet server list can no longer be refreshed. This happens on both libRocket and RmlUi. Steps to reproduce:

1. Open server list
2. Click "Local" tab
3. Click "Internet" tab
4. Click "Refresh"

**Comment by DolceTriade** [comment]
Cannot reproduce on Linux. Are you clicking on the "Local" tab before the servers load in the Internet tab?

**Comment by slipher** [comment]
I don't think we need to fix it for 0.53 as it was already there in 0.52 and no one reported it before.

**Comment by necessarily-equal** [comment]
I don't think this issue is being worked on at the moment. If somebody or wants to fix it before 0.54, this could still be possible, but I'm removing it from the todo list for 0.54.
