### ISSUE TITLE
server list background uses #333333 which is used by unv's color codes

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1989]
#333333 is the color code "Dark Grey", `^0`. I think it should be replaced with something not in [this](https://wiki.unvanquished.net/wiki/Colours) list (except for the free-style colors, obviously).

**Comment by Gireen** [comment]
why?

**Comment by illwieckz** [comment]
Because that means the server will have his name hidden (and you know well about this 🤭️)

**Comment by bmorel** [comment]
To reduce the chances of invisible characters because of same character color than background?

**Comment by Gireen** [comment]
oh ok. #333333 is the background color and not font color. then it makes sense 😄

**Comment by bmorel** [comment]
sorry for lack of precision... you know how it is, you see a thing, report it before forgetting about it, but still miss all important details :/
