### ISSUE TITLE
game menu no longer allow to change "first-person weapons" setting

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1990]
In 0.52 it is possible to use the menu and config popups to draw alien's 1st person animations.
In 0.53 this no longer works.

**Comment by bmorel** [comment]
regression or ability to test to it started at e7f250b07009ad642dd05f43fad7f2f51ad49bef according to a git bisect.
Abitlity to test for it, because for several commits, it's impossible to do anything with the UI. We shuold have squashed those together, as they currently break bisecting.

**Comment by bmorel** [comment]
bisecting anew, considering the untestable commits as "good": 6627fb75bdeb5dfa172ded658acadcb40156427b is the  1st  bad commit.

This means that the regression comes from the broken commits of rmlui integration.
Can I suggest those to be squashed for the future master branch? This will make bisects easier in the future.

**Comment by slipher** [comment]
Fixed by #1996.
