### ISSUE TITLE
make OM/RC move mark a team vote

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1993]
When someone marks OM/RC for move, automatically trigger a team vote. If after few seconds, people didn't voted "no", it should then be considered a "yes", since they don't care.
This would give a way to people to refuse a move, or at least to be prepared for it.

**Comment by DolceTriade** [comment]
Building is already a chore...

**Comment by bmorel** [comment]
it is, but moving main at wrong time can kill a team

**Comment by DolceTriade** [comment]
Sure, but then you can have admins come in and revert if it was a throw.

**Comment by bmorel** [comment]
Gameplay should not rely on rely on admins to be around. Admins should, ideally, be useless, imo.

**Comment by necessarily-equal** [comment]
The other problem with a vote, is that it will be really hard to explain where it will be built in the near future. We would need high quality minimaps for this kind of things.

**Comment by bmorel** [comment]
> We would need high quality minimaps for this kind of things.

It is technically possible to have higher resolution minimaps, I did that yesterday to check if a bug was shared between minimaps and navmeshes. But this would probably not help to visualize where the Main would go anyway, minimaps being a problem of their own (they're flat, while the game is really in 3D).
