### ISSUE TITLE
Human player model: `Warn: Couldn't find image file 'default'`

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1998]
This warning can be seen since years when loading an Unvanquished game:

> Warn: Couldn't find image file 'default' 

It comes from the human md5 model, the md5 model isn't textured properly but the model is always skinned by the game whatever the texture being wrong or not so this is very low priority

This issue reminds other issues to fix like:

- the human model is copy-pasted three times for any naked/medium/heavy armour variant without any reason, the copies are 100% the same files,
- we may want to port the model to iqm once deduplicated, I first thought the md5mesh models were duplicated because of different models sharing the same md5anim file, in fact all three models are 100% the same file, the differences are just done with skinning: a translucent texture is applied by game code to hide helmet on naked variant, and another armour color texture is applied by game code for heavy armour.

I consider we better want to postpone that for after 0.53.0 as there is no bug in gameplay at all.

**Comment by DolceTriade** [comment]
Fixed by https://github.com/UnvanquishedAssets/res-players_src.dpkdir/pull/13

**Comment by illwieckz** [comment]
I opened https://github.com/Unvanquished/Unvanquished/issues/2000 so we can close this issue once https://github.com/UnvanquishedAssets/res-players_src.dpkdir/pull/13 is merged.

**Comment by bmorel** [comment]
Dropping a comment here to remind people of some facts:

* there's a female human model which needs work (lowering number of tris, notably)
* game have support for skins, but this is currently not used, it would be nice to have feature used to allow distinguishing players... and even ideally bots. This is important if we want to give bots actual differences in behavior, and I already have some code to go toward this direction

**Comment by bmorel** [comment]
> Fixed by UnvanquishedAssets/res-players_src.dpkdir#13

Let's wait a bit (one week or two) or until one of the others close this, before I do it myself.

**Comment by DolceTriade** [comment]
> there's a female human model which needs work (lowering number of tris, notably)

I thought the issue was animations?

> game have support for skins, but this is currently not used

It is used, but not in the traditional sense of skins. Skins are used to distinguish between different armor types. I'm worried about the gameplay implications of skins. For example, knowing by looking what type of armor a human is wearing.

**Comment by bmorel** [comment]
>I'm worried about the gameplay implications of skins. For example, knowing by looking what type of armor a human is wearing.

What is usually done, I think, is to allow players to only modify some parts of the skin, not the whole skin. I think this would be very desirable to have some ability to identify a player *or a bot* visually. Other elements could be used, too, see #1671 for a feature request, which seems pretty complicated to implement.
I take most of my inspiration from 2 other FPSes, really: red-eclipse 1.x and battlefield. To give unv some of their features would clearly make unv way better :)

But I think I'm deriving out of topic now

**Comment by DolceTriade** [comment]
Agree it would be good to have different skins for different armor types. We would need a way to be able to merge skins.

**Comment by DolceTriade** [comment]
This is fixed. If you want a separate issue for skins, then let's make another issue for that.
