### ISSUE TITLE
Admin commands sometimes do not produce an output on the server

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2009]
Admin commands tend to not produce any response or output. This is very difficult to reproduce, but bunker server has been running for a few days now and trying to enter any command produces no feedback. The command does run however (kick, ban, for example).

It's difficult to reproduce because when first running the server it seems fine.

![image](https://user-images.githubusercontent.com/13281185/181997098-0011a4a7-9424-4046-9996-c88d0796c0ac.png)

**Comment by Gireen** [comment]
probably logs.suppression

`logs.suppression.enabled 0`
should fix this

maybe it should be disabled by default for servers or generally set higher

**Comment by cu-kai** [comment]
Yes, this fixes it for me. Perhaps this issue should be renamed to reflect that request, or should a new one be opened?

**Comment by slipher** [comment]
Fixed by https://github.com/DaemonEngine/Daemon/pull/667.
