### ISSUE TITLE
Messages about things unlocked by momentum are not scaled on screen.

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2013]
It's too late for 0.53.0, this will be for the next release.

**Comment by slipher** [comment]
There are a few things in `px` units in our RML. They seem to be mostly about radio buttons and checkboxes though.

**Comment by necessarily-equal** [comment]
Does it affects momentum only or every "center print" message?

**Comment by necessarily-equal** [comment]
This would be for every message: https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/blob/adb0b4eb66e409331f0b3aea4288bf8582a3b248/ui/hud_overlay.rml#L9

**Comment by necessarily-equal** [comment]
Fixed by https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/145

**Comment by illwieckz** [comment]
Yes it affects every messages:

[![unscaled message](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-07-31_231359_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-07-31_231359_000.jpg)

[![unscaled message](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-01_034721_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-01_034721_000.jpg)

[![unscaled message](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-01_192101_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-01_192101_000.jpg)

[![unscaled message](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-02_023910_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-02_023910_000.jpg)

[![unscaled message](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-02_054325_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-02_054325_000.jpg)

[![unscaled message](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-02_054953_001.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-02_054953_001.jpg)

Including map messages:

[![unscaled message](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-07-31_224724_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-07-31_224724_000.jpg)

[![unscaled message](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-07-31_232314_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-07-31_232314_000.jpg)

[![unscaled message](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-03_185008_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unscaled-message/unvanquished_2022-08-03_185008_000.jpg)

**Comment by illwieckz** [comment]
@necessarily-equal while you're at it, you may want to look at this one too:

- https://github.com/Unvanquished/Unvanquished/issues/2026
