### ISSUE TITLE
0.54.0 release thread (stuff to do before the release)

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2016]
This issue is to track ideas to improve the release process, in foresight of next release. Please edit it at will.

Outstanding PR and issues ("must have"):
* [x] https://github.com/Unvanquished/Unvanquished/pull/2364 (bugfix)
* [x] https://github.com/Unvanquished/Unvanquished/pull/2355 (neat feature)

Milestones ("would have"):
* [x] https://github.com/Unvanquished/Unvanquished/milestone/25
* [x] https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/milestone/1
* [x] https://github.com/DaemonEngine/Daemon/milestone/3

Tasklist
* [ ] emit notices to server owners about the upcoming release to give them time to prepare instances
## Release process:

- Prepare blog post
  * [x] Gather the changes (list commits)
  * [x] Summarize the changes (for the redactor) -> ask afontain on IRC
  * [x] Write a blog post
  * [x] Proof read blog post
- [ ] Write release notes for server owners to ease the transition (includes things like how to update the build repos)
- Merge
  * [x] Merge remaining PRs (see above)
  * [x] Merge `0.54.0/sync` to master
- [x] Commit version numbers and push commits
- Tag release
  * [x] tag release
  * [x] tag every submodule of Unvanquished and UnvanquishedAssets with `unvanquished/0.54.0`
  * [x] tag Urcheon
  * [x] Push release tags
- Build release
  * [x] Rebuild engine binaries
    - [x] Linux (linux-amd64, linux-i686, linux-arm64, linux-armhf)
    - [x] Windows (windows-amd64, windows-i686)
    - [x] macOS (macos-amd64)
  * Rebuild dpks
    - [x]  Rebuild game nexes (amd64, i686, armhf)
    - [x] Rebuild data
    - [x] Package dpks
    - [x] Package unizip
  * [x] Build and upload benchmark demo
- Set up distribution
  * [x] Upload unizip to dl.unvanquished.net
  * [x] Convert unizip to torrent in cdn.unvanquished.net
  * [x] Make sure CDN mirrors mirrored
  * [x] Upload to GitHub
  * [x] Run script to set 0.54.0 default download
  * [x] Run script to publish torrent
- Update game servers
  * [x] unvanquished.net
  * [x] gg.illwieckz.net
- [x] Publish blog post
- Social medias
  * [x] Write and publish Facebook post
  * [x] Write and publish Twitter post
  * [x] Write and publish Reddit post
- [x] `@everyone` message on chat
- [x] Update flatpak recipe

## Post-release things:

- [x] Make sure FOSS Torrents knows about the release
- [x] Make sure Phoronix knows about the release
- [ ] Translate blog post for LinuxFr.org or make sure someone writes an article about the release
- [x] Upload to sf.net as a backup
- [x] Upload to IndieDB as a backup
- [ ] Copy blog post to IndieDB
- [x] Duplicate this issue for 0.54.1

**Comment by necessarily-equal** [comment]
The issue for 0.53 https://github.com/Unvanquished/Unvanquished/issues/1789

**Comment by necessarily-equal** [comment]
Note that there is also a milestone for 0.54, https://github.com/DaemonEngine/Daemon/milestone/3

**Comment by necessarily-equal** [comment]
Trouble with this release: bot are kinda borked on alien base on chasm and vega because of https://github.com/Unvanquished/Unvanquished/issues/2389. I would recommend removing those maps from map rotation for now.

**Comment by illwieckz** [comment]
This is how I made this release, not that some parts are totally optional so I commented them out, like running crazy zip optimizers (from https://github.com/illwieckz/datarepotools/ ) and making all files having the same date and other things like that.

Usually we don't rebuild every packages (even when we don't do delta packages), so not all packages has to be rebuilt and repositories tagged with version numbers.

This one is a complete release with all dpk being rebuilt and entirely rebuilt (no deltapaks) because all repositories were modified. Since every rebuilt dpkdir repository needs a new version tag (like `v0.54`) to produce a dpk version string, we needed to tag all the dpkdir. This is very rare.

Most of the time only a couple of packages were modified meaning,

- we have to copy older modifed paks we need from an older release, before doing the md5sum file.

Most of the time we do deltapaks on non-map packages, meaning,

- the urcheon build command uses `-r`  
 `urcheon build -r `unvanquished/0.53.0` */res-*.dpkdir */tex-*.dpkdir */unvanquished_src.dpkdir`
- we have to copy older paks we need as dependencies from an older release, before doing the md5sum file.

It is assumed the future branch is already merged to master. If not,

- we must make sure the merge will not add any commit,
- we should push the future branch anyway so the build script can pull it,
- and we should merge the future branch and push it after everything is done.

```bash
export TZ='GMT'
export GIT_AUTHOR_DATE='2023-01-29 18:30:00+00:00'
export GIT_COMMITTER_DATE="${GIT_AUTHOR_DATE}"

cd ~/dev/Unvanquished
git pull
git submodule update --init --recursive

./update-version-number.py 0.54.0
cd daemon
cd ..
git commit -am 'Update version number to 0.54.0'
git push
cd ..
git commit -am 'Update version number to 0.54.0'
git push

git submodule foreach git tag -am 'Unvanquished 0.54.0 beta' unvanquished/0.54.0
git -C pkg/unvanquished_src.dpkdir tag -d unvanquished/0.54.0

cd daemon
git tag -am 'Daemon 0.54.0 beta' v0.54.0
git submodule foreach git tag -am 'Unvanquished 0.54.0 beta' unvanquished/0.54.0
cd ..

git tag -am 'Unvanquished 0.54.0 beta' unvanquished/0.54.0
git tag -am 'Unvanquished 0.54.0 beta' v0.54.0

cd ~/Mapping/Unvanquished/UnvanquishedAssets
git pull
git submodule update --init --recursive

git submodule foreach git tag -am 'Unvanquished 0.54.0 beta' unvanquished/0.54.0

git tag -am 'Unvanquished 0.54.0 beta' unvanquished/0.54.0
git tag -am 'Unvanquished 0.54.0 beta' v0.54.0

# This can be optimized and partly automated.
# It's very rare we repackage (and then tag with version) all the packages.
# Usually we only rebuild and then tag with version a handful of packages so I never automated that.
# For maps I usually only bump patch version number because it's up to the mapper to decide the maps
# has a new version, given the changes that were done were like, doing minor fixes.
#
cd src/unvanquished_src.dpkdir
git tag -am 'Unvanquished 0.54.0 beta' v0.54.0
cd ../map-antares_src.dpkdir
git tag -am 'map-antares 1.0.3' v1.0.3
cd ../map-chasm_src.dpkdir
git tag -am 'map-chasm 1.2.3' v1.2.3
cd ../map-forlorn_src.dpkdir
git tag -am 'map-forlorn 0.15.3' v0.15.3
cd ../map-parpax_src.dpkdir
git tag -am 'map-parpax 2.7.3' v2.7.3
cd ../map-perseus_src.dpkdir
git tag -am 'map-perseus 1.0.3' v1.0.3
cd ../map-plat23_src.dpkdir
git tag -am 'map-plat23 1.13.4' v1.13.4
cd ../map-spacetracks_src.dpkdir
git tag -am 'map-spacetracks 1.1.3' v1.1.3
cd ../map-station15_src.dpkdir
git tag -am 'map-station15 1.1.3' v1.1.3
cd ../map-thunder_src.dpkdir
git tag -am 'map-thunder 1.3.5' v1.3.5
cd ../map-vega_src.dpkdir
git tag -am 'map-vega 1.4.3' v1.4.3
cd ../map-yocto_src.dpkdir
git tag -am 'map-yocto 1.0.3' v1.0.3
cd ../tex-all_src.dpkdir
git tag -am 'tex-all 2.3' v2.3
cd ../tex-common_src.dpkdir
git tag -am 'tex-common 2.3' v2.3
cd ../tex-ej01_src.dpkdir
git tag -am 'tex-ej01 1.3' v1.3
cd ../tex-exm_src.dpkdir
git tag -am 'tex-exm 1.3' v1.3
cd ../tex-ex_src.dpkdir
git tag -am 'tex-ex 1.3' v1.3
cd ../tex-pk01_src.dpkdir
git tag -am 'tex-pk01 1.3' v1.3
cd ../tex-pk02_src.dpkdir
git tag -am 'tex-pk02 1.3' v1.3
cd ../tex-space_src.dpkdir
git tag -am 'tex-space 1.3' v1.3
cd ../tex-tech_src.dpkdir
git tag -am 'tex-tech 1.3' v1.3
cd ../tex-trak5_src.dpkdir
git tag -am 'tex-trak5 1.3' v1.3
cd ../tex-vega_src.dpkdir
git tag -am 'tex-vega 1.4.3' v1.4.3
cd ../res-ambient_src.dpk
git tag -am 'Unvanquished 0.54.0 beta' v0.54
cd ../res-buildables_src.dpkdir
git tag -am 'Unvanquished 0.54.0 beta' v0.54
cd ../res-legacy_src.dpkdir
git tag -am 'Unvanquished 0.54.0 beta' v0.54
cd ../res-leveleditor_src
git tag -am 'Unvanquished 0.54.0 beta' v0.54
cd ../res-players_src.dpkdir
git tag -am 'Unvanquished 0.54.0 beta' v0.54
cd ../res-soundtrack_src.dpkdir
git tag -am 'Unvanquished 0.54.0 beta' v0.54
cd ../res-voices_src.dpkdir
git tag -am 'Unvanquished 0.54.0 beta' v0.54
cd ../res-weapons_src.dpk
git tag -am 'Unvanquished 0.54.0 beta' v0.54

cd ~/Mapping/Unvanquished/UnvanquishedAssets
urcheon clean src/*.dpkdir
urcheon prepare src/*.dpkdir
urcheon build src/*.dpkdir
urcheon package src/*.dpkdir

cd ~/dev/unvanquished-release-scripts
git pull

# This code is not merged yet
#
./docker-build --targets all --unizip --reference 2273533ed14d3df3a2d90db768c4f21fef1b859e

cd build
mkdir 0.54.0
cd 0.54.0

7z x ../release/unvanquished_0.zip
mv unvanquished_0 unvanquished_0.54.0
cd unvanquished_0.54.0
mv symbols_0.zip symbols_0.54.0.zip

cd pkg
cp -a ~/Mapping/Unvanquished/UnvanquishedAssets/build/pkg/*.dpk .

mkdir vm
cd vm
7z x ../vm_0.dpk

# Can use better zip options like -mx=9 if not bruteforcing.
#
7z -tzip a ../unvanquished_0.54.0.dpk *

cd ..
rm -r vm vm_0.dpk

rm md5sums

# Totally optional, and I usually do this only on modified files.
#
#	find . -exec touch --date="${GIT_AUTHOR_DATE}" {} \;

# Totally optional, bruteforce zip compression
#
#	find . -type f -name '*.dpk' -print0 | drt-multitask -0 -I{} -P$(nproc) drt-zipbrute --no-directories --touch --chmod -4 {}

# Overly complex for nice listing, this can be simpler:
#
#	md5sum --binary -- *.dpk > md5sums
#
( export LC_ALL; md5sum --binary -- *.dpk | sed -e 's/\.dpk$//' | sort -k2,2 -t' ' | sed 's/$/.dpk/' ) | tee md5sums

# Totally optional, and I usually do this only on modified files
#
#	find . -exec touch --date="${GIT_AUTHOR_DATE}" {} \;

cd ..

# Totally optional, bruteforce zip compression.
#
#	find . -type f -name '*.zip' -print0 | drt-multitask -0 -I{} -P$(nproc) drt-zipbrute --no-directories --touch --chmod -4 {}

# Totally optional
#
#	find . -exec touch --date="${GIT_AUTHOR_DATE}" {} \;

cd ..

# Can use better zip options like -mx=9 if not bruteforcing.
#
7z a -tzip unvanquished_0.54.0.zip unvanquished_0.54.0

# Totally optional, bruteforce zip compression
#
#	drt-zipbrute --no-directories --touch --chmod -4 unvanquished_0.54.0.zip

# Some code is not merged yet
#
git -C ~/dev/unvanquished-validate-release pull
~/dev/unvanquished-validate-release/validate_release.py unvanquished_0.54.0.zip

# Do a lot of testing!
#
# - Unpackaged the release in a clean file
# - use homepath for clean homedir folders
# - run Linux server and client on Linux, host a map, join a game with a separated client, add bots…
# - run Windows server and client on Wine or Windows, join a game
# - run macOS server and client on macOS, join a game

cd ~/dev/Unvanquished
git push --tags
git submodule foreach git push --tags

cd daemon
git submodule foreach git push --tags

cd ~/Mapping/Unvanquished/UnvanquishedAssets
git push --tags
git submodule foreach git push --tags

cd ~/dev/unvanquished-release-scripts/build/0.54.0
rsync -av unvanquished_0.54.0.zip unvanquished.net:

# Create a release.
# Upload unvanquished_0.54.0.zip
#
firefox https://github.com/Unvanquished/Unvanquished/releases/new

ssh unvanquished.net

	sudo -s
	mv ~illwieckz/unvanquished_0.54.0.zip /var/www/dl.unvanquished.net/release
	chown -R www-data.www-data /var/www/dl.unvanquished.net/release
	cd /var/www/tools/release

	# edit game_version
	vim configuration/current.conf

	cat README.md
	./cache-tracker-list
	./unpack
	./publish
	./announce
	/etc/init.d/nginx configtest && systemctl reload nginx

	exit
	exit

# Run the updater, update the game
#
~/.local/share/unvanquished/base/updater

cd ~/dev/Unvanquished/dist/scripts/record-benchmark-demo
./record-benchmark-demo ~/.local/share/unvanquished/base/daemon

mv benchmark.dm_86 unvanquished-benchmark_0.54.0.dm_86
touch --date="${GIT_AUTHOR_DATE}" {} unvanquished-benchmark_0.54.0.dm_86
xz -9 unvanquished-benchmark_0.54.0.dm_86

rsync -av unvanquished-benchmark_0.54.0.dm_86.xz unvanquished.net:

ssh unvanquished.net

	sudo -s mv ~illwieckz/unvanquished-benchmark_0.54.0.dm_86.xz /var/www/dl.unvanquished.net/benchmark/demos
	chown -R www-data.www-data /var/www/dl.unvanquished.net/benchmark/demos
	
	exit
	exit
```
