### ISSUE TITLE
Trailing zeroes in float cvar breaks text comparison in RmlUi

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2023]
As you can see flot cvars like the `cg_motionblur` one can be converted to text with trailing zeroes, meaning it doesn't match the default value and the drop down menu doesn't indicate the currently used option:

[![trailing zeroes in float cvar](https://dl.illwieckz.net/b/unvanquished/bugs/trailing-zeroes-in-float-cvar/unvanquished_2022-08-02_063029_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/trailing-zeroes-in-float-cvar/unvanquished_2022-08-02_063029_000.jpg)

[![trailing zeroes in float cvar](https://dl.illwieckz.net/b/unvanquished/bugs/trailing-zeroes-in-float-cvar/unvanquished_2022-08-02_063058_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/trailing-zeroes-in-float-cvar/unvanquished_2022-08-02_063058_000.jpg)

**Comment by necessarily-equal** [comment]
0.05 is special as it doesn't have an exact value in float. But the issue is different here, it's just extra 0 even in the 0.0 case
