### ISSUE TITLE
RmlUI to Master Issues

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#2030]
tracker for issues...

 - [x] Alien icon near evos not centered properly
 - [x] Human buy menu buy/upgrades not centered
 - [x] Don't see graphs on human buy menus
 - [x] Stuff not aligned properly on circlemenus
 - [x] server name on map loading screen isn't centered
 - [x] underwater oxygen bar isn't properly scaled and colored, can be tested as dretch in station15 pond.
 - [x] Circle menu buy numbers don't work
 - [x] Scoreboard icon not aligned correctly.
 - [x] The "TAB" key binding hint in the human buy menu is smushed against the tab title instead of being below it like before.
 - [x] badly scaled emoticon in chat print, scoreboard etc. especially visible with emoticon in file name
 - [x] no space between players name in spectator list on scoreboard
 - [x] screen resolution list isn't pre-selected (displays something blank for the current resolution)
 - [x] for some unknown reason `cg_crosshairSize` was set to `0.5` instead of `1.0` default (I never changed that myself).
 - [x] jetpack bar isn't styled (opaque white), reported by _lautre_.
 - [x]  the message about the issue of the game isn't centered anymore, (here “Evacuation”):

**Comment by illwieckz** [comment]
- [ ] underwater oxygen bar isn't properly scaled and colored, can be tested as dretch in station15 pond.

**Comment by slipher** [comment]
The "TAB" key binding hint in the human buy menu is smushed against the tab title instead of being below it like before.

**Comment by illwieckz** [comment]
- badly scaled emoticon in chat print, scoreboard etc. especially visible with emoticon in file name
- no space between players name in spectator list on scoreboard

**Comment by illwieckz** [comment]
- the message about the issue of the game isn't centered anymore, (here “_Evacuation_”):

[![rmlui to master](https://dl.illwieckz.net/b/unvanquished/bugs/rmlui-to-master/unvanquished_2022-08-11_080508_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/rmlui-to-master/unvanquished_2022-08-11_080508_000.jpg)
