### ISSUE TITLE
String escape bug in `listplayers` (possibly elsewhere?)

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2050]
This was discovered on Bunker server, names with certain characters seem to escape the formatter.

This is what I see ingame:
![image](https://user-images.githubusercontent.com/13281185/183307518-6f6e23d8-6f10-4bf6-b428-a06f026ef4ba.png)

This is what I see on the server:
![image](https://user-images.githubusercontent.com/13281185/183307529-c9389b36-30cd-4081-a9e3-b47ec77a10da.png)

This is the exact name I used to reproduce this: `{AE}[tyrant]^1o'neill`

**Comment by cu-kai** [comment]
Having a re-read of this issue, it could just be an overflow. But it does seem strange, the first time I witnessed it live on Bunker, I only got the first line while the rest was printed on the server:
`listplayers: 13 players connected:`

**Comment by necessarily-equal** [comment]
I would suspect it has something to do with `'`. I suppose the `Quote` function is the one used for that kind of escaping works. That's where I would be looking at.

**Comment by slipher** [comment]
Should be fixed by https://github.com/Unvanquished/Unvanquished/commit/f63588c3340a6865a55b718a65cb73b423cbe62f.
