### ISSUE TITLE
Some rocket gamelogic stuff in engine

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2052]
Can we move this:

https://github.com/DaemonEngine/Daemon/blob/aa772312a9fb277e8a5da1ba060c9a7692b4b5c0/src/engine/client/cg_api.h#L73-L102

```c++
enum class rocketVarType_t {
	ROCKET_STRING,
	ROCKET_FLOAT,
	ROCKET_INT,
	ROCKET_COLOR
};

enum rocketMenuType_t {
	ROCKETMENU_MAIN,
	ROCKETMENU_CONNECTING,
	ROCKETMENU_LOADING,
	ROCKETMENU_DOWNLOADING,
	ROCKETMENU_INGAME_MENU,
	ROCKETMENU_TEAMSELECT,
	ROCKETMENU_HUMANSPAWN,
	ROCKETMENU_ALIENSPAWN,
	ROCKETMENU_ALIENBUILD,
	ROCKETMENU_HUMANBUILD,
	ROCKETMENU_ARMOURYBUY,
	ROCKETMENU_ALIENEVOLVE,
	ROCKETMENU_CHAT,
	ROCKETMENU_BEACONS,
	ROCKETMENU_ERROR,
	ROCKETMENU_NUM_TYPES
};

enum rocketInnerRMLParseTypes_t {
	RP_QUAKE = 1 << 0,
	RP_EMOTICONS = 1 << 1,
};
```

From `Daemon/src/engine/client/cg_api.h` to `Unvanquished/src/cgame/cg_local.h` ?

**Comment by slipher** [comment]
Yes. Another one like that is entityType_t in q_shared.h

**Comment by DolceTriade** [comment]
@slipher I don't think we can move entityType_t out of the engine. entityType_t is used by entityShared_t which is used by our engine netcode. Theoretically we could make entityType_t eType into an int or something, but I'm not sure that's desirable.

**Comment by necessarily-equal** [comment]
I think this is fixed
