### ISSUE TITLE
profile system

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2053]
Currently in unvanquished, there is a single profile, that is, you setup your config and cross fingers that nobody will touch your session and play with their own settings.

The idea of profiles is *not* about securing things, but to have various profile names, with their own settings. One obvious use-case is for devs, when trying to reproduce a bug.
It is currently possible to indicate a different `-homepath` but I think this is not very practical, and a proper UI to select such a profile would be much better.
I'm not sure where this UI should be, though, maybe the launcher should be in charge of this? Or maybe cgame itself should be able to switch between profiles? Maybe this should also concern local sgame, so that there can be presets for local/LAN games?

**Comment by necessarily-equal** [comment]
Following discussions on IRC/Matrix I'm tempted to mark this as S-Wontfix. The reasons suggested were that

* one such system existed and was dropped
* it is quite difficult to implement correctly
* its usefulness is quite debatable over just using -homepath
* it complexifies the UI even more

For the "shared computer" usecase, it was argued that you probably should be using a different sessions instead. Separation of concerns lead to more maintainable software.

Do you still think it's worth implementing?

**Comment by DolceTriade** [comment]
I am not in favor of this.

**Comment by necessarily-equal** [comment]
Ok, so given the fact that you can use -homepath for a similar purpose, that it is difficult to implement correctly and may make development of other features more complicated; and given the fact that a similar feature was dropped, I think we can close this.
