### ISSUE TITLE
How should damage-entities behave?

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2054]
Linked to #2047 

* how should the UI behave? Should there be some hints about the destructible elements, or should a newcommer just have no clue about it?
* if a visual clue about those is needed, what to use?
* should dretches be able to damage them?

**Comment by DolceTriade** [comment]
Assuming damage entities are equivalent to destructible entities, I don't think there should be a UI for them from the game. I think it should be up to the creators of the damage entities to make it clear that they are such, or users can experiment themselves by shooting/attacking them.

I think it is disingenuous to suggest that new comers are idiots who are incapable of figuring out a door/window can be broken. If the mapper wants to make some secret destructible elements that they want the player to find, I think we shouldn't ruin that by making a UI/indicator for damage entities.

I also don't think dretches should be able to hurt them.

**Comment by bmorel** [comment]
> to suggest that new comers are idiots

Absolutely not what I was suggesting.

> If the mapper wants to make some secret destructible elements that they want the player to find

Well, then, we need to give mappers a way to disable minimaps, as they already participate at breaking secrets. But it's actually a good point.

**Comment by DolceTriade** [comment]
The mapper can simply remove the area from the minimap :). Minimaps are just images.

**Comment by bmorel** [comment]
AFAIK there's no easy way to ask q3map2 to ignore a part of the map. And no, they're not "just images", they're images generated by a tool, for now, which people suggested to replace with some kind of 3D stuff

**Comment by bmorel** [comment]
> Assuming damage entities are equivalent to destructible entities, I don't think there should be a UI for them from the game

Well, it seems they're actually different. See https://github.com/Unvanquished/Unvanquished/issues/1220 "func_destructable" so that's something different.

**Comment by cu-kai** [comment]
> I also don't think dretches should be able to hurt them.

I disagree with this, dretches should be able to bite damage entities (and this was the old behaviour in Tremulous too). 

I do not believe there should be any visible indication for entities which have a "health" value (this is what you are describing). I'm not sure why there's been so much discussion regarding desired behaviour of what is essentially a regression caused by CBSE.

See: https://github.com/Unvanquished/Unvanquished/issues/2047 also, which is a completely different issue (and a NEW feature which would need to be implemented, both in this game and in NetRadiant's entities.def file)

**Comment by bmorel** [comment]
> I'm not sure why there's been so much discussion regarding desired behaviour of what is essentially a regression caused by CBSE.

I'm probably one of the rare persons who tried to work on this since it was removed by the CBSE, and I do not know how tremulous handles those not remember how unvanquished did when I discovered it.
So the questions and answers here will help me to find some implementation that won't trigger months of discussions for nothing.

**Comment by bmorel** [comment]
There are branches with fixes for this. I'm going to close this now.
