### ISSUE TITLE
non-spinning minimap

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2056]
A player requested an option to stop the spinning of the minimap. Right now, the minimap's orientation always follows a player's view angle around the vertical axis. The proposed option would have "north" always pointing to the top of the screen. Of course, the arrow representing the player would have to rotate instead.

Two reasons why a player might want to enable that:

- When wallwaking the minimap can rotate crazily fast.
- On completely unfamiliar (or symmetric) maps, this could help in identifying the "global" directions.

**Comment by VReaperV** [comment]
Done in #3004.
