### ISSUE TITLE
<colorinput> does not color text

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#2066]
The <colorinput> element used for the player name option no longer colors the text according to color codes. Probably an RmlUi regression.

**Comment by DolceTriade** [comment]
It never did, iirc. It always displayed the unescaped regular view if you clicked on it and when the element lost focus, it would show the colored view. That's because it's non-trivial to teach RmlUI our color scheme. That's why we wrote the rocketChatInput in the first place.

**Comment by slipher** [comment]
OK, apparently I imagined that.
