### ISSUE TITLE
MWHEELUP and MWHEELDOWN don't always register

### ISSUE THREAD

**Issue by velociostrich** [Unvanquished/Unvanquished#207]
### Steps to reproduce

1. Bind MWHEELUP and/or MWHEELDOWN to some action.
2. Attempt to use said bind.
3. Observe that the bind does not always work; it may work not at all for a period of time or intermittently, but it does work for some fraction of the time.

### Notes

* I do not believe my mouse to be the culprit as I have never observed the mouse wheel *not* working in any other application on Windows or Linux.
* I have never noticed this issue at the in-game console.
* I find that sometimes, the bug is not reproducible. E.g., I might scroll the well a considerable number of times and every time it works, then suddenly it once again does not.
* I tested with a common Microsoft Wheel Mouse Optical, which is a standard two-button-with-scroll-wheel USB optical mouse. It has the capability of using a PS/2 adapter (via the [IMPS/2 protocol] (http://en.wikipedia.org/wiki/Mouse_%28computing%29#PS.2F2_interface_and_protocol), which is something SDL handles specially), but I used it as a USB mouse.

### Hardware / Software

| Release | v0.13.0
|:--|:--
| Operating System | Ubuntu 12.04 LTS
| Kernel Version | 3.2.0-38-generic
| Video Card | ATI Radeon HD 5670
| Driver Type | Proprietary (fglrx)
| OpenGL Version | 4.2.11903 Compatibility Profile
| Driver Version | 8.85-110419a118915C-ATI (Catalyst 11.5)
| Renderer | GL3

**Comment by Viech** [comment]
Closing as old and potentially fixed/invalid. Please reopen if this occurs again.
