### ISSUE TITLE
implement a way to share credits

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2071]
Request from a player: "implement /give". Obviously, not the current /give, since it's a cheat that creates stuff, but rather a way to give parts of owned credits to another player.

**Comment by slipher** [comment]
Not having this was a deliberate gameplay design decision. Some Tremulous servers had this and it was often the case that one or a few players were doing all the killing to feed the whole team with credits. We want to discourage this and require more participation of the whole team.

**Comment by bmorel** [comment]
Thanks, I wanted to know the exact reason why. To be honest, I suspected this already.

Still, the feature *could* be enabled, and it would even help the debugging. It could be made a cheat thing... I already made a PR to slightly improve the `/give` feature, but I think a more complete redesign could be done, in that regard.

**Comment by DolceTriade** [comment]
I don't think we want to upstream this feature for the reason slipher mentioned.

**Comment by bmorel** [comment]
Then this ticket can probably be closed. At least, now there's an issue to point people at :)
