### ISSUE TITLE
"You are at the front of the spawn queue" message stuck on screen after leaving team while in a spawn queue

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2085]
Noted just now on Bunker, where I left the team while in the spawn queue. Now I have the message stuck on my screen.

This doesn't go away until I join a team again and spawn. If I leave the team (even while spawned), the message reappears on my screen.

![unvanquished_2022-08-17_195142_000](https://user-images.githubusercontent.com/13281185/185220127-ad6ea5db-7c6d-443a-80dc-9de2286919f7.jpg)

**Comment by DolceTriade** [comment]
Yes I've seen this as well.
