### ISSUE TITLE
[Idea] More nuanced UI focus

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#2096]
Currently, we have two UI contexts: the HUD context and the Menu context. The HUD context receives no SDL2 input. It only displays what is updated by the gamelogic. The Menu context receives all input, however, it prevents input from being sent to the game. This means that if a menu is open, you cannot interact with the game while it is open.

This is problematic because often, you will want to perform a task that requires a menu, but if requiring a menu means you have to be a sitting duck or you have to find safety, that makes it hard to justify its use.

As we start creating more UIs for tasks that need to be done in game, it would be useful if the menu and the game could share input focus.

Some examples of where this can be useful are:
 - Vsay Menu
 - Beacon Menu
 - Build Menu
 - Admin menu
 - Navmesh editing menu
 - Buy/Evo menu

**Comment by slipher** [comment]
I think I wrote a proposal for this somewhere. There's an RmlUi API to see whether a key event was consumed or not that we can use. I know how to do it and just need to get around to implementing it.

**Comment by slipher** [comment]
Done, the `passthrough` keyword in the menu list configures a menu to allow binds.
