### ISSUE TITLE
people use [idea] in title instead of using tags

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2098]
This "[idea]" is just a T-Feature-request, except that it can not be easily filtered.

The answer to this is probably to build templates.
The alternative is to rely on volunteers to spend time triaging issues, instead of coding, playing, drawing models, creating animations, porting maps, etc.

Managing that kind of stuff is usually the "job" of leaders, of which we have several official ones. I understand it's not fun, but, official devs also do unfun stuff: refactoring of the codebase is where most of our time was spent since I'm official notably.

**Comment by Gireen** [comment]
Since the templates are manages in the git repository anyone can make a PR to add them.

A-Feedback is for feedback from the game to players not the other way around.

**Comment by slipher** [comment]
I haven’t seen this happen recently :)
