### ISSUE TITLE
Infinite scoreboard

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2099]
If a game ends while a player is still downloading packages for it, this player is stuck with the scoreboard shown infinitely on the next map, until doing /reconnect. This happens regularly and I suspect it happens every time.

**Comment by illwieckz** [comment]
I believe this is a duplicate of:

- https://github.com/Unvanquished/Unvanquished/issues/1102

And yes the bug is old, it's sad we didn't fixed it yet. 🤭️

**Comment by DolceTriade** [comment]
Were you already in the end game when this happened? Did you load the same map again after?

**Comment by DolceTriade** [comment]
Closing in favor of #1102
