### ISSUE TITLE
Fix or silence CM_AddFacetBevels...

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#2109]
```
Warn: CM_AddFacetBevels... invalid bevel 
Warn: CM_AddFacetBevels... invalid bevel 
Warn: CM_AddFacetBevels... invalid bevel 
Warn: CM_AddFacetBevels... invalid bevel 
Warn: CM_AddFacetBevels... invalid bevel 
Warn: CM_AddFacetBevels... invalid bevel 
Warn: CM_AddFacetBevels... invalid bevel 
Warn: CM_AddFacetBevels... invalid bevel 
```

Lots of our official maps have this warning. Why does it happen? Is it a valid warning? Is are there any negative side effects? Can we fix our official maps to not have this warning?  If we cannot, can we just silence this warning because no one cares about it?

**Comment by DolceTriade** [comment]
The warnings are introduced by https://github.com/illwieckz/Daemon/commit/38c97d4d5e32e9f86f06a7ab009c6b2b4c6794b1

**Comment by illwieckz** [comment]
Yeah, I wonder if some can safely turned into notices (like the ones that just does `continue`. I want to ask zturtleman some questions to understand more the meaning of them. Maybe with hope we can only keep the one doing a `return`.

Note: the commit you linked is for another unrelated warning and only affect a couple of maps, the one for `invalid bevel` that is affecting everything is there:

- https://github.com/DaemonEngine/Daemon/commit/8eaa75843328ff2aee8b84d29915c227e1704c82

From:

- https://github.com/DaemonEngine/Daemon/pull/275

**Comment by DolceTriade** [comment]
Reverting the workaround from following the comment thread in https://github.com/DaemonEngine/Daemon/issues/169 fixes the issue for me.

**Comment by illwieckz** [comment]
Reverting that workaround would just prevent some maps to load, and those are maps that are expected to load. So we have an engine bug to fix.

**Comment by illwieckz** [comment]
So, we're at a point where we can't workaround a warning happening at map load by reverting a workaround for a bug that breaks map loading. We've hidden the bug under the bed for too long.

**Comment by illwieckz** [comment]
Test map for https://github.com/DaemonEngine/Daemon/issues/169 is [there](https://dl.illwieckz.net/b/daemon/bugs/max-points-on-winding/map-moteof_0%2Bfinal2.dpk). One would need to set `g_neverEnd 1` to no get the game ends once loaded (but then it means the map is loaded, so it would be good anyway).

It's not a Tremulous/Unvanquished map but it just happened this is the first map I reproduced the bug with, so I have not spent time to test or document other maps that may reproduce it since this one is good enough for that. There is no reason to believe no one Tremulous map reproduce this bug or no one future Unvanquished will not reproduce this.. We have a bug in our engine.

**Comment by DolceTriade** [comment]
I'm messing around with this. Let's see if I get anywhere

**Comment by DolceTriade** [comment]
https://github.com/etlegacy/etlegacy/blob/00b35a7e14db6f0b73dd6fbf5fdfe7436a8ed776/src/qcommon/cm_patch.c#L1174 ET:Legacy comments it out. Maybe it's a regression from q3 -> ET

**Comment by bmorel** [comment]
@illwieckz "Test map for https://github.com/DaemonEngine/Daemon/issues/169 is [there](https://dl.illwieckz.net/b/daemon/bugs/max-points-on-winding/map-moteof_0%2Bfinal2.dpk)." it would be good to have things to reproduce bugs either directly hosted by the tracker, or in the list of test maps, just in case the other server goes down or remove data for one reason or another.
