### ISSUE TITLE
Allow layouts to change some cvars (those that maps can already change)

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2129]
Currently, maps can run commands to prevent the use of some equipment, and I guess, to change starting BPs of a team.
To allow layouts to do that would make it much easier to deploy scenario layouts.

**Comment by slipher** [comment]
> Currently, maps can run commands to prevent the use of some equipment, and I guess, to change starting BPs of a team.

No they can't. They can only change some specifically allowed cvars.

Allowing every kind of file format to run code is a bad thing. I don't want a PDF to be able to run arbitrary code when I open it; same goes for a layout.

Also we just added layout-specific map configs.

**Comment by bmorel** [comment]
> No they can't. They can only change some specifically allowed cvars.

That's more than enough.
What I'm talking about here is to forbid or allow equipment, classes, buildings, lock a team, and change initial BPs

**Comment by bmorel** [comment]
Let's rename the issue then.

**Comment by VReaperV** [comment]
All of this is already a thing with layout configs.
