### ISSUE TITLE
Using con_prompt with certain characters leads to undesirable results

### ISSUE THREAD

**Issue by velociostrich** [Unvanquished/Unvanquished#213]
Using con_prompt with characters that require escapement or require being quoted leads to the displayed prompt being quoted and the characters that would require escapement being prefixed with a backslash.

| con_prompt | Expectation | Actual result
|:--|:--|:--
| <code>$</code> | <code>$</code> | <code>"\$"</code>
| <code>"$ "</code> | <code>$ </code><sup>1</sup> | <code>"\$ "</code>
| <code>"> "</code> | <code>> </code><sup>1</sup> | <code>"> "</code>
| <code>"C:\\>"</code> | <code>C:\\></code> | <code>C:></code>
| <code>"C:\\\\>"</code> | <code>C:\\></code> | <code>C:\\\\></code>
| <code>\\</code> | <code>\\</code> | *symbol for line feed*
| <code>"\\\\"</code> | <code>\\\\</code> | <code>"\\\\"</code>
| <code>\\\\</code> | <code>\\\\</code> | <code>"\\\\"</code>

1. A trailing space is expected.

Note that it is impossible to get a single backslash; placing two backslashes results in two blackslashes, whereas placing one either results in the following character being (often unnecessarily) escaped, or a Unicode line-feed being displayed.

**Comment by Amanieu** [comment]
The escaping rules for the console have been reworked and are now consistent. This issue is not relevant anymore.
