### ISSUE TITLE
make bots understand the direction of their enemy

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2137]
Currently, alien bots strafe when they chase an enemy. This slows them a lot, and makes aliens a lot weaker than they should.
 @DolceTriade  I think you might be interested by this one.

This also applies to turret attacks.

**Comment by DolceTriade** [comment]
Interesting. Bots don't look at their enemy when they move?

**Comment by bmorel** [comment]
No, they don't. It's why dretches are that ineficient: they strafe when their enemy is running away from them. I guess I should create more issues for the stuff I know about AIs :)
