### ISSUE TITLE
reported crash: Unhandled exception out_of_range in basic_string

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2138]
```
<Sweet> a player had a client crash while playing on human team, and reports this as the last output line:
<Sweet> Warn: CGame VM: Unhandled exception (St12out_of_range): basic_string
<Sweet> the player cannot remember what he did before that
<Sweet> that is all i know, so i don't think i should write an issue for that
```

**Comment by necessarily-equal** [comment]
A backtrace would greatly help fixing this one, but afaik we haven't got any

**Comment by DolceTriade** [comment]
We added breadpad crashdumps for this very reason. I should stand up my `crash.unvanquished.net` server again.

**Comment by slipher** [comment]
Exceptions aren't actually crashes so there won't be any dumps. In IRC we discussed possibly turning off exceptions in the NaCl compiler to see if we could make throwing them result in a crash.

**Comment by DolceTriade** [comment]
Ahhh, this is a great find @sweet235 Thanks! This will make it much easier to fix it
