### ISSUE TITLE
view rotates when game does not have focus

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2141]
In 0.52, when the focus was removed from the game, the view would be static when user moved mouse around (on 2nd screen for example).
This is no longer true in 0.53, the view rotates despite the game being no longer focused.

**Comment by DolceTriade** [comment]
I wonder if this is related to SDL2. By view rotates, do you mean it rotates randomly or does it still follow mouse?

**Comment by bmorel** [comment]
Follows mouse.

**Comment by necessarily-equal** [comment]
Can this be related to your SDL version? When you say it worked on 0.52, is that with the same SDL version?

**Comment by bmorel** [comment]
This is definitely a SDL-related bug: upstream have the bug, and have SDL statically linked, but my local dev build which uses an older SDL library is not affected.

**Comment by necessarily-equal** [comment]
Then it sounds like using a more recent SDL release could fix this.

I can't reproduce your problem, for the record, with SDL 2.0.20

**Comment by bmorel** [comment]
Is there is any way to know which version of SDL is statically linked into daemon?

**Comment by slipher** [comment]
The one statically linked is 2.0.12. You can see it in external_deps/build.sh.

**Comment by bmorel** [comment]
Then it's not (directly?) related to SDL since I did not had this behavior in the past. It's still quite weird that running my local version does not exhibits this.

**Comment by necessarily-equal** [comment]
I don't have this issue with latest daemon and SDL2.0.20 on GNOME 42.4, both on wayland (expected) and on xwayland (even when focusing another X app, which isn't expected — sdl/daemon likely receives the event and filter them correctly).

**Comment by bmorel** [comment]
This means people have to use their own daemon executable to have this working correctly?
This is problematic, as I prefer to use the launcher, and I don't think the launcher will let me use my own build...

If the SDL version has not changed since 0.52, it's quite weird because it means it's a regression in our code, somehow.

**Comment by necessarily-equal** [comment]
Unfortunately if I can't reproduce the issue I can't fix it for you. I think if you can bisect and tell me what the commit is I can try to help, but otherwise you're on your own. I'm afraid I can't solve a problem I don't have.

**Comment by bmorel** [comment]
As it happens, I do not have this buggy behavior on the "map testing" mod.

**Comment by bmorel** [comment]
This seems to only happen with my local builds... it's weird that It didn't in the past though, I've not updated SDL2 since months. Still, it's likely irrelevant to keep that open.
