### ISSUE TITLE
`listplayers` is broken

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2152]
Sometimes it only lists 1 player: 
![2022-09-04-144657_1366x768_scrot](https://user-images.githubusercontent.com/1316300/188314278-52cb7410-7bee-41aa-aa5d-3ad20354f49e.png)

It seems that server side the correct content is printed according to @sweet235 

Other infos, in server console:

> console: it says: trap_SendServerCommand( 0, ... ) length exceeds 1022. 
console: and at the end: ... truncated

**Comment by cu-kai** [comment]
This is a duplicate of #2050

**Comment by bmorel** [comment]
Closing since duplicate. I edited original to make the command easier to see in title (with the '`' around)
