### ISSUE TITLE
Inconsistentency in name colors

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#2163]
Reported by @sweet235 :

![](https://p.mort.coffee/Z5g.png)

**Comment by illwieckz** [comment]
We don't have the related string to know if it's a bug on our side or not. If the string doesn't use the reset color code (`^*`) this is not a bug on our side, and if one wants to consider this a bug, the bug report has to be addressed to the people owning the nickname.

One can do `^7[^1!!!^7]gHostisLOL^1.LsD` to write everything that is not red in white, including the first character,

or do `[^1!!!^*]gHostisLOL^1.LsD` to write everything that is not red with the default color.

Note: we may have bugs with the way we reset the color.

**Comment by DolceTriade** [comment]
This is definitely a bug on our side. We should always use the string reset code before printing user generated content (ie, names or chat or whatever)

**Comment by illwieckz** [comment]
> This is definitely a bug on our side. We should always use the string reset code before printing user generated content (ie, names or chat or whatever)

We cannot since we have to print global, team and admin chat with a different color.

**Comment by DolceTriade** [comment]
We totally can. We can just terminate whatever color we want to print with a color reset code, or use CSS to make it white.

**Comment by necessarily-equal** [comment]
problem is that in some places the default is white and in others the default is gray. if someone wants to have a white name, they should use ^7 at the beginning. And if they want to reset the color to the default, then ^* would be adequate instead.

**Comment by illwieckz** [comment]
> if someone wants to have a white name, they should use ^7 at the beginning. And if they want to reset the color to the default, then ^* would be adequate instead.

Yes. If the user didn't used the reset code, the color being different before and after the red color is not a bug. We can't guess the color the user wants.

> We can just terminate whatever color we want to print […]

A string terminator cannot fix the color of the first character…

> […] with a color reset code

No reset color code can display another color than the default color (or it would be a bug, in fact).

**Comment by sweet235** [comment]
> the bug report has to be reported to the people owning the nickname

We cannot report bugs to users, it is the other way around.

**Comment by sweet235** [comment]
The name does not start with `^*`, it starts with `[`.
