### ISSUE TITLE
no UI to override system's i18n settings

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2166]
Related to #2165 but not a duplicate.

It should be possible to override systems settings regarding to i18n with the GUI.

**Comment by necessarily-equal** [comment]
I'm tempted to concentrate on fixing this one and close https://github.com/Unvanquished/Unvanquished/issues/2165 as S-Wontfix. The current behavior of listening to the system language on first run then having the setting in the option sounds good.

**Comment by slipher** [comment]
A UI to select language is obviously good in principle, but I guess we ought to have at least one language with significant translated content before making one.

**Comment by slipher** [comment]
Fixed in #2804.
