### ISSUE TITLE
Sometimes wrong per-layout config files get executed

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2176]
When having a per-layout config file like `karith/pve.cfg`, this might be executed when loading the map with its default layout. This seems to happen if and only if the last layout changed to was named `pve`.

I think the reason is this line:
https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_main.cpp#L561
It selects the config files to load based on the cvar `layout`. But this cvar seems to keep its value when maps are changed.

**Comment by DolceTriade** [comment]
Yes def a bug.

https://github.com/Unvanquished/Unvanquished/blob/591ea7eef14f3be087aa9b1bc82fcedcdc68736a/src/sgame/sg_buildable.cpp#L2393

We return early if you had a layout and switch to the builtin layout.

Thanks for reporting

**Comment by Gireen** [comment]
`layout` used to be reset by daemon on mapchange. That was changed cause unv had then no write access to the cvar.

```
trap_Cvar_Set( "layout", S_BUILTIN_LAYOUT );
```
Somewhere on map start should fix this

**Comment by sweet235** [comment]
Today I stumbled over this, we should fix it. The workaround I currently use is this in `config/map/default.cfg`:

```
undelay layoutfix
delay layoutfix 3000 layout *builtin*
```

That works, but is hardly a permantent solution.

**Comment by DolceTriade** [comment]
No, we should fix it for real. This slipped out from under my radar. Thanks for raising again.

**Comment by sweet235** [comment]
If I understand correctly, that commit has the same effect as my config hack. I noticed a problem with this approach: when voting for map_restart, the information about the layout is already lost. So this will always load the default layout.

**Comment by DolceTriade** [comment]
If you run `map_restart` does it not load the default layout?

**Comment by sweet235** [comment]
Doing `map_restart` does indeed load the default layout. But judging from feedback, this is not what users expect. Users expect `map_restart` to restart with the same layout and config that are used currently. I think I should open a new issue for that.

This is a minor problem.
