### ISSUE TITLE
r_allowResize is not properly supported

### ISSUE THREAD

**Issue by velociostrich** [Unvanquished/Unvanquished#218]
### Steps to reproduce
1. Start the game in windowed mode (or change to windowed mode after starting the game).
2. Set r_allowResize to a "true" value (e.g., 1).
3. Attempt to resize the window.
### Expected result

The window resizes.
### Actual result

The window is not resizable.
### Comments

The [SDL_RESIZABLE](http://sdl.beuc.net/sdl.wiki/SDL_SetVideoMode) flag **is** set in GLimp_SetMode() if r_allowResize evaluates to true. However, the documentation for SDL_SetVideoMode remarks that "when the window is resized by the user a SDL_VIDEORESIZE event is generated and SDL_SetVideoMode can be called again with the new size". The SDL_VIDEORESIZE **is** handled in IN_ProcessEvents(), but all that is done is r_mode, r_customWidth, and r_customHeight are set appropriately.

What needs to happen is SDL_SetVideoMode needs to be called again, which is done in GLimp_SetMode(). (I don't know why, but there are _two_ similar but different definitions of GLimp_SetMode(), one in sdl_glimp.c, and one in sdl_vid.c. I think GLimp_SetMode() should be refactored into two functions—one to handle changing resolution and one to handle changing bit depth—so that we can change the resolution without having to effectively do a full vid_restart.
### Hardware & Software

| Tag | v0.13.1 |
| :-- | :-- |
| Operating System | Ubuntu 12.04 LTS |
| Kernel Version | 3.2.0-38-generic |
| Video Card | ATI Radeon HD 5670 |
| Driver Type | Proprietary (fglrx) |
| OpenGL Version | 4.2.11903 Compatibility Profile |
| Driver Version | 8.85-110419a118915C-ATI (Catalyst 11.5) |
| Renderer | GL3 |

**Comment by illwieckz** [comment]
`r_allowResize` is currently considered unsupported, there are many things in the renderer that are not dynamic, like some values compiled as GLSL defines and not as variables. Like Fuma said, for now shader recompilation is required on resize…

Let's consider any improvement for `r_allowResize` to be part of a feature request for `r_allowResize` to begin with.

**Comment by slipher** [comment]
r_allowResize can be used, with the purpose of picking a resolution by drawing a box on your screen, as opposed to typing in numbers. Automatically issuing a vid_restart seems undesirable because it can take a long time and maybe the user isn't done tinkering with the size yet. Such an interface certainly doesn't feel polished (hence being disabled by default), but I don't see any prospects of improvement for now.
