### ISSUE TITLE
allow to use `cg_thirdperson` when following someone (spectating)

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2194]
There is no reason to prevent spectators to use this.

**Comment by necessarily-equal** [comment]
Wouldn't it be very confusing? You would observe your invisible… yourself? Why?

**Comment by bmorel** [comment]
`cg_thirdperson` as a spectator should allow to have a "chase view" of the player you're spectating. Ofc, the 3rd person view is not exactly nice as currently implemented, but it would  possibly be better in some situations than what we have (wallwalking and very fast movements can be pretty confusing as 1st person).

**Comment by necessarily-equal** [comment]
Ah ok, there has been a misunderstanding, I thought you meant as spectator in free flight, before joining a team. That could be useful yeah. I don't know how we could have UI for that though

**Comment by slipher** [comment]
You can already follow in 3rd-person, just not by using that cvar (when cheats are disabled). +attack3 switches 1st- and 3rd-person views while spectating. It's described in the tutorial text with "switch to chase-cam spectator mode"

**Comment by bmorel** [comment]
Indeed. Thanks for info. (tutorial lack the mouse wheel up info but different issue, and not sure it should be fixed)
