### ISSUE TITLE
Allow defining custom votes

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#2228]
Now that we have active severs, it's clear that it is not scalable to force C++ changes every time someone wants to add a vote. Instead, we should allow creating votes in a config file or something. Ultimately, votes don't need anything fancy:

Something like this in the admin.dat:

```
[vote]
vote = scenario
exec = setScenario.cfg
args = 1

[teamvote]
vote = slap
exec = slap
args = 1
```

The `args` flag would allow that many arguments to be passed to `callvote` and those arguments would be appended to the `exec` command in that order.

In .cfg scripts, we can reference these arguments using cvars `arg_0`, `arg_all`, and `arg_count` using cvar substitution. For example, setScenario.cfg could be something like:

```
set g_layout $arg_1$
exec $arg_1$.cfg
map_restart
pr -1 "^1Loading scenario: ^2$arg_1$"
```

**Comment by sweet235** [comment]
That would be useful indeed.

With existing votes, we have cvars to configure the percentages required for a vote to pass, so we could have something like this:
```
[vote]
vote = scenario
exec = setScenario.cfg
args = 1
percentage = g_scenarioVotesPercent
```
or even
```
percentage = 51
```
Perhaps a little more difficult: we should give proper error messages if a vote argument is invalid. Not sure how to do this in admin.dat.
