### ISSUE TITLE
Team lock is bypassed by autoselect

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2245]
Discovered today on Bunker, if a team is locked with the `/lock` command it may still be joined with the autoselect feature.

**Comment by DolceTriade** [comment]
```
	if ( !Q_stricmp( s, "auto" ) )
	{
		if ( level.team[ TEAM_HUMANS ].locked && level.team[ TEAM_ALIENS ].locked )
		{
			team = TEAM_NONE;
		}
		else if ( level.team[ TEAM_HUMANS ].locked || players[ TEAM_HUMANS ] > players[ TEAM_ALIENS ] )
		{
			team = TEAM_ALIENS;
		}

		else if ( level.team[ TEAM_ALIENS ].locked || players[ TEAM_ALIENS ] > players[ TEAM_HUMANS ] )
		{
			team = TEAM_HUMANS;
		}
		else
		{
			team = (team_t) ( TEAM_ALIENS + rand() / ( RAND_MAX / 2 + 1 ) );
		}
	}
```

We actually do take locked into account...

**Comment by cu-kai** [comment]
Yes but `g_teamBalanceCountBots` is `0` on bunker which means as far as the game is concerned, aliens is empty; humans always > aliens, which was locked. This exact scenario doesn't appear to be accounted for in the logic in that code.

**Comment by slipher** [comment]
#2246
