### ISSUE TITLE
Granger spit fire extinguisher gives free and infinite evos

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2247]
If you wallclimb as adv granger and spit on whatever you're clinging to, you receive a fractional evo as if you extinguished some fire (you also hear the "ding" confirming payment).

Setting `g_firefightReward` to `0` mitigates this but grangers will no longer be rewarded for extinguishing fires.

**Comment by bmorel** [comment]
Here is the problem: https://github.com/Unvanquished/Unvanquished/blob/master/src/shared/bg_public.h#L462-L468

The proper solution would be to stop stupidly overlapping bits, which is the fix I'll apply on my instances, but this would be rejected as it would break compat between cgame and sgame (which is a ridiculous requirement imo).

**Comment by slipher** [comment]
> The proper solution would be to stop stupidly overlapping bits, which is the fix I'll apply on my instances, but this would be rejected as it would break compat between cgame and sgame (which is a ridiculous requirement imo).

It's OK to break compat between cgame and sgame. We changed the rule.

**Comment by necessarily-equal** [comment]
Heh, that's hillarious. Great find. I'm ok with a PR for both options really.

**Comment by DolceTriade** [comment]
granger$ be rich
