### ISSUE TITLE
Bots have the chat typing indicator during gameplay

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2248]
I've recently rebased my fork on master which has introduced this bug; bots now have a typing indicator above them for no apparent reason. It's inconsistent and does not appear above every bot.

![unvanquished_2022-10-08_205109_000](https://user-images.githubusercontent.com/13281185/194725679-0dfe2bff-4b4a-4aa4-8aa8-e3fd7fb90192.jpg)

**Comment by DolceTriade** [comment]
I probably need to explicitly disable this feature for bots. Thanks for the report.

**Comment by DolceTriade** [comment]
lol wtf, I think it only happens if a bot kills you and the player types... At least that's the only way I repro'd it.

**Comment by slipher** [comment]
Fixed by #2249
