### ISSUE TITLE
Bots no longer attack structures

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2250]
Another bug observed on Bunker since the merge is that bots no longer attack structures. could this be to do with the recent entity iteration changes by @necessarily-equal?

![unvanquished_2022-10-09_200257_000](https://user-images.githubusercontent.com/13281185/194775199-5ddfc365-e8cf-48e2-9f30-9a0a09f7b19c.jpg)

**Comment by slipher** [comment]
This is believed to be fixed by #2251.
