### ISSUE TITLE
`heartbeat` not working under certain circumstances

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2261]
Symptoms include the server not showing on the serverlist and the `heartbeat` command having no output until a server restart. Automatic heartbeats are also not sent.

With @DolceTriade's help, I was able to debug this. 

Removing `sv_master2`'s value fixed this and the heartbeat was sent to the primary server (`master.unvanquished.net`)
Resetting the `sv_master2` cvar's value to default (`master2.unvanquished.net`) did not reproduce the bug.

**Comment by necessarily-equal** [comment]
I wonder if that's the bug @bmorel was hitting when a server of his was unreferenced.

**Comment by slipher** [comment]
I guess that could happen if `getaddrinfo` was blocking for a really long time... Can you produce a stack trace of all threads when this happens?

**Comment by slipher** [comment]
And what sv_masterN values did you set to produce a bug?

**Comment by DolceTriade** [comment]
Yes, the bug in question is something related to DNS. As soon as kai set sv_master2 to "", it said Starting DNS thread.

**Comment by slipher** [comment]
The DNS thread should be started the moment when `net_enabled` is nonzero, the sgame is running, and at least one master server cvar is nonempty.

**Comment by slipher** [comment]
I realized how to produce the symptoms of the DNS thread only starting when you change a master server address. This happens if the sgame crashes but afterward you start another game with a `map` command.

@cu-kai Did you have some configuration which starts a new map after an sgame crash (instead of the default behavior of exiting after the watchdog timer)?

**Comment by cu-kai** [comment]
I do not currently have a way to automatically restart after an sgame crash.

**Comment by slipher** [comment]
> Did you have some configuration which starts a new map after an sgame crash (instead of the default behavior of exiting after the watchdog timer)?

Never mind, I realized this can happen without any custom configuration!

https://github.com/DaemonEngine/Daemon/blob/125639b311efd94eb49c04de3e0f9a9d78c9c425/src/engine/server/sv_main.cpp#L1318-L1332

So the DNS lookups will stop working if your server uptime hits 23 days. Fix is at https://github.com/DaemonEngine/Daemon/pull/759.
