### ISSUE TITLE
Small regression about bot navigation around geometry

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#2263]
It seems making bot ignore geometry makes them hit corners from time to time when some navmesh imperfections trigger.

Examples of corners where they got stuck:

![Screenshot from 2022-10-15 00-57-46](https://user-images.githubusercontent.com/59283660/195957742-9c82763e-21dc-4e20-9909-81d5fe1a089f.png)

![image](https://user-images.githubusercontent.com/59283660/195958513-ff19f0cb-d5d3-459a-bcc6-35f2cee7b485.png)

I'm thinking the proper fix could be to merge the BotGetPathBlocker, (BotShouldJump?) and BotFindSteerTarget, first checking with map geometry, and without map geometry if it fails (for example in a vent where map geometry is detected everywhere, or in perseus' slope of hell where the roof is detected as a wall). This way we could have the correct corner-avoiding behavior that we had before (avoiding geometry), without reverting the improvements brought by https://github.com/Unvanquished/Unvanquished/pull/2259.

**Comment by necessarily-equal** [comment]
It happens fairly often actually. I think I'll want to have a fix for 0.55.

**Comment by necessarily-equal** [comment]
Note that this is also a problem when bot are fighting. This will need to be tested too before closing this issue.

**Comment by cu-kai** [comment]
Could this be directly related to the bots being stuck on boxes and other geometry on the map `utcs` with the new navmesh generator (0.54.0).

**Comment by necessarily-equal** [comment]
Kinda yes and kinda no. Kinda no because this is a different bug. But kinda yes in that fixing this would help hide the bug: bots would try to navigate around the box.
