### ISSUE TITLE
Bots do "tremble" from time to time [with reproducer]

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#2275]
Sometimes bot seem to move in-place, like if they had some kind of epilepsy crisis. I think when it happens they are most of the time on top of a buildable and I think they are trying to walk towards a point that is below the buildable, but they can't get closer by walking because the buildable is in the way. Eventually the unstick kicks in and they stop doing that.

A good way to reproduce the problem is using this chasm map layout: [chasm-prison2.tar.gz](https://github.com/Unvanquished/Unvanquished/files/9873385/chasm-prison2.tar.gz). It is based on another layout by bmorel.

Steps to reproduce:
* `/devmap chasm chasm-prison2` load the map with the layout
* `/bot fill 3 h` add human bots (but preferably no alien bots to avoid distracting them)
* wait, looking at the telenodes and turrets in the human base

This layout helps a fair bit reproducing because it forces bot to roam a lot. This also means that they will randomly choose a boint below a buildable more often, triggering the bug more often.

I feel now that I've found a way to reproduce the bug it may help a lot getting a fix.

**Comment by bmorel** [comment]
I still see this on @sweet235 's server. Not sure if the mod have this fix?

**Comment by necessarily-equal** [comment]
If you have a picture or a recording of the place I'm interested, because I've found that my patch did fix the issue consistently for the one reproducer that I've found :-/

I assume Sweet's server should have the commit

**Comment by bmorel** [comment]
No idea, I don't know which commits he had.
