### ISSUE TITLE
Possible bug with `func_train`

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2299]
While playing mission-mantis, we have come across a new entity bug. Sometimes the structures at the end of the map are randomly destroyed by an invisible crusher.

I am the author of mission-mantis and there are no invisible crushers on this map. Just a lot of func_train entities.

To reproduce: load mission-mantis on a server running master, go to the 2nd puzzle (with the grid of moving plates) and spam the 5 blue buttons repeatedly for around 2 minutes. You will see "Base under attack!" message and see a large log of destroyed buildables.

Here is the map: http://dl.zittrig.eu/pkg/map-mission-mantis_0.6.dpk

Here is a copy of the buildlog when @necessarily-equal, @bmorel and I were debugging on the Bunker server.

Note: the entity which destroys the base is ID 1022, which seems very odd to me.
![image](https://user-images.githubusercontent.com/13281185/199984105-f4f3a6cf-a987-41e6-bdc5-f6ed204195bc.png)

**Comment by cu-kai** [comment]
Further information: I've only been able to reproduce this in release builds. This bug does not occur with a debug build.

**Comment by cu-kai** [comment]
Have done some further testing on my local server.

Investigations suggest a func_train is going wildly off its path and destroying entities nowhere near it, its designated path, or any path_corner when it gets toggled by a button.

It is one of the plates in this part of the map:
![image](https://user-images.githubusercontent.com/13281185/200025736-8e496de9-2b54-480c-a1ef-468da1436dc7.png)

Here are the plates and their paths as they appear in NetRadiant:
![image](https://user-images.githubusercontent.com/13281185/200026094-a633d8f8-0f1d-43ea-80c3-37eb4b703ae2.png)

This leads me to believe it's an engine/game bug, not a map bug.

**Comment by necessarily-equal** [comment]
I could also reproduce the bug. It's really weird. Here's a layout with a human base + reactor at the wrong place: [mission-mantis-boom.dat.txt](https://github.com/Unvanquished/Unvanquished/files/9943319/mission-mantis-boom.dat.txt)

> I've only been able to reproduce this in release builds. This bug does not occur with a debug build. (CMAKE_BUILD_TYPE=Debug)

It seems the difference that causes this is -O0 vs -O2 or -O3. -O2 and -O3 are broken (I haven't tested other optimisation levels).

**Comment by DolceTriade** [comment]
Interesting! Might be a compiler bug then?

**Comment by necessarily-equal** [comment]
> Might be a compiler bug then?

It's very possibly a compiler bug IMO. Or maybe the code did rely on undefined behavior, and never was supposed to work but just didn't break anything yet. Beside regular optimisations with -O2/3, link time optimisations (LTO) (-flto) is well-known to break build that rely on undefined behavior.

Anyhow, I can't trigger the bug anymore. This is infuriating.

**Comment by necessarily-equal** [comment]
@cu-kai reportedly still have the bug after disabling LTO. So LTO is likely not at fault.

**Comment by necessarily-equal** [comment]
We found out that `-ffloat-store` makes the problem disappear. So this problem would be because of compiler optimisations in floating-point number behavior. This also explains why I couldn't reproduce the bug with asan/ubsan, since the extra bound checks etc probably forced the register optimisations to be less aggressive.

Here is the gcc documentation for `-ffloat-store`:

> This option prevents undesirable excess precision on machines such as the 68000 where the floating registers (of the 68881) keep more precision than a double is supposed to have. Similarly for the x86 architecture. For most programs, the excess precision does only good, but a few programs rely on the precise definition of IEEE floating point. Use -ffloat-store for such programs, after modifying them to store all pertinent intermediate computations into variables. 

and here is the gcc documentation for -fexcess-precision=

> This option allows further control over excess precision on machines where floating-point operations occur in a format with more precision or range than the IEEE standard and interchange floating-point types. By default, -fexcess-precision=fast is in effect; this means that operations may be carried out in a wider precision than the types specified in the source if that would result in faster code, and it is unpredictable when rounding to the types specified in the source code takes place. When compiling C, if -fexcess-precision=standard is specified then excess precision follows the rules specified in ISO C99; in particular, both casts and assignments cause values to be rounded to their semantic types (whereas -ffloat-store only affects assignments). This option is enabled by default for C if a strict conformance option such as -std=c99 is used. -ffast-math enables -fexcess-precision=fast by default regardless of whether a strict conformance option is used.
>
> -fexcess-precision=standard is not implemented for languages other than C. On the x86, it has no effect if -mfpmath=sse or -mfpmath=sse+387 is specified; in the former case, IEEE semantics apply without excess precision, and in the latter, rounding is unpredictable.

Since there is no g++ documentation on the issue, and we have the issue in C++ and the flag exists in g++, I assume that when they say C here, it also applies to C++ too. I also assume that when they say that "This option is enabled by default for C if a strict conformance option such as -std=c99 is used", this is also true for C++ standards.

So this problem seems pretty related to `-ffast-math`. I opened https://github.com/Unvanquished/Unvanquished/issues/2311 to discuss `-ffast-math`.

**Comment by necessarily-equal** [comment]
I asked @cu-kai to test without `-ffast-math`, and the flag seems to be responsible indeed.

> yes, removing both instances of -ffast-math from `DaemonFlags.cmake` seems to resolve this

**Comment by slipher** [comment]
I found a division by 0 condition in #2331. I can't say whether this fixes the structure crushing bug because I wasn't able to reproduce that with any configuration. I can produce the condition of `self->s.pos.trDuration` being assigned 0 in `Start_Train` (which is immediately used as a divisor in `SetMoverState`) about once every 15 seconds if I run around on the mission-mantis buttons with `/timescale 9`.

**Comment by necessarily-equal** [comment]
This is believed to be fixed by https://github.com/Unvanquished/Unvanquished/pull/2331

**Comment by slipher** [comment]
So has it been tested whether #2331 really fixes it?

**Comment by cu-kai** [comment]
Many of the games have been taking place recently on @sweet235's server, I am not sure if he has merged this yet (he had been compiling without `-ffast-math` to mitigate it I believe).

I mainly tested on `/timescale 10` on mission-mantis and managed to break it reliably every 15-30 seconds.

**Comment by sweet235** [comment]
My server uses this since today, but I removed mission-mantis from the rotation. It is not hard to crash the server by entity overflow even with firebomb disabled.

**Comment by cu-kai** [comment]
I consider this fixed after running some tests on the `0.54.0/sync` branch and being unable to reproduce it.
