### ISSUE TITLE
Bots don't honor FL_NOTARGET

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#2300]
Steps to reproduce:
* `/notarget` on a devmap
* get close to enemy bots
* notice bots will attack you while they shouldn't

**Comment by slipher** [comment]
Bots are supposed to be a stand-in for human players, and human players would be unaware of FL_NOTARGET. Seems working fine/as intended

**Comment by necessarily-equal** [comment]
I mean it seems buildables do ignore FL_NOTARGET entities? Why wouldn't bots?

**Comment by slipher** [comment]
Because it applies to non-client entities.

**Comment by necessarily-equal** [comment]
I don't think FL_NOTARGET happens when this is not a debug server (with cheats enabled) anyway, so the real question is "would having bots honor FL_NOTARGET help debugging?". To that question I would answer yes, because I wanted to do that for several reasons recently.

A first reason would be that I wanted to test tremship's door, what I did was `/noclip; notarget; god` and then I wondered for a while why the human bots didn't pass through the door. Well it wasn't that the navmesh was broken. It was that they wanted to stay afar from me.

![image](https://user-images.githubusercontent.com/59283660/200174530-6420a86b-118c-4879-9110-5cf56471730f.png)

I've come again against this problem recently, when I wanted to test beacons. It's a case where I wanted to be on a team because it allows seeing the beacons as that team sees them; but I didn't want to interfere while moving around.

Generally speaking, it would be good not to have to choose between having no interaction power on the world at all (by playing but spectating) or being able to participate but having to participate and interfering (by playing but disturbing bots)

**Comment by slipher** [comment]
OK, makes sense.
