### ISSUE TITLE
Joining a local server with dll cgame doesn't work with a dpkdir

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#2307]

**Comment by slipher** [comment]
Did you set `client.allowRemotePakDir`?

**Comment by necessarily-equal** [comment]
Yes

**Comment by slipher** [comment]
And? What happened?

**Comment by necessarily-equal** [comment]
It was still broken with the flag. I've also tried patching the value to 1 manually without success

**Comment by DolceTriade** [comment]
What do you mean by broken? Does it disconnect you? Crash?

**Comment by necessarily-equal** [comment]
By broken, I mean that fails to connect and gets you back to the main menu.

It seems it is only broken when the server uses a local dpkdir, and works otherwise :thinking:

**Comment by necessarily-equal** [comment]
This is now fixed, I assume by https://github.com/DaemonEngine/Daemon/pull/789. Thanks!
