### ISSUE TITLE
Spectator name list in scoreboard grows only vertically

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2320]
I rebased on master today, and noticed this:

![a](https://user-images.githubusercontent.com/110394607/205365566-acc8041e-95c1-4406-b52b-2fce75f397a9.png)

The names were placed horizontally in earlier versions, or weren't they?

(I'm not sure which repo is responsible, so I'll report it here)

**Comment by necessarily-equal** [comment]
@illwieckz merged a commit to make <div> display: block by default recently. It looks like a very good culprit.

So we basically just have to add display: inline, or better, to turn the <div> into <span>

**Comment by illwieckz** [comment]
Ah yes, `div` are expected to be `block`, if a `div` was used with the expectation to not be a block without any instruction to tell it should not be a `block`, that `div` is a bug.

**Comment by slipher** [comment]
> Ah yes, `div` are expected to be `block`, if a `div` was used with the expectation to not be a block without any instruction to tell it should not be a `block`, that `div` is a bug.

Really? I see `<div>` as a meaningless tag that's used whenever you need to have a tag to hang things on for technical reasons. And `<p>` is used for making a new block. The change adding `display: block` to div seems bad to me.

**Comment by slipher** [comment]
I mean maybe div is supposed to be a block element by HTML standards, but changing it is probably going to cause a lot of bugs in our UI...

**Comment by necessarily-equal** [comment]
I agree that a div being used implicitely in inline context is a bug, but I think I've seen other parts of the UI relying on that kind of stuff. like speedometer/position_indicator relying on its children `<span>` being `display: block;` :see_no_evil:
