### ISSUE TITLE
Blockiness on flames with dynamic lights

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#2343]
When there are several flamers and lucis being used and dynamic lights are enabled, the flame sprites may take on a blocky appearance.

GPU: NVIDIA GeForce GTX 1050 Ti

![unvanquished_2022-12-19_020647_000](https://user-images.githubusercontent.com/7809431/209057997-a9cf1902-c7b0-474b-9b11-5aaaf012275f.jpg)

[Demo producing the issue](https://github.com/Unvanquished/Unvanquished/files/10283811/blocky.flames.demo.zip)

**Comment by slipher** [comment]
Another problem on Nvidia is that the dynamic lights are way too bright. Here's a single blaster shot:

![unvanquished_2022-12-23_032314_000](https://user-images.githubusercontent.com/7809431/209310021-789c10a2-5f74-4c5e-8236-36e19765b9de.jpg)

**Comment by DolceTriade** [comment]
Noticed this as well. Super annoying imo.

**Comment by necessarily-equal** [comment]
Think this is also a bug on not-nvidia. Except I guess that it could trigger more easily if things are overly bright.

**Comment by illwieckz** [comment]
I assume the blocky light sprite bug affects all GPUs.

I have noticed the  “dynamic light is too bright” bug on Quadro K2100M Kepler and I assume this one is a separate bug that is Nvidia-specific.

**Comment by cu-kai** [comment]
I am sure the blocky lights aren't exclusive to Nvidia, I see the same on AMD;
![unvanquished_2022-12-25_195005_000](https://user-images.githubusercontent.com/13281185/209973966-f27e4f51-bc97-4afd-8602-1c13f6bc3bc3.jpg)

**Comment by slipher** [comment]
OK I made #2351 for the dynamic lights issue.

**Comment by necessarily-equal** [comment]
I've removed this from the 0.54 milestone, and pinned the sister https://github.com/Unvanquished/Unvanquished/issues/2351 for 0.55 since illwieckz thinks it would be more important to fix that one. (They can be fixed in any order of course)

**Comment by illwieckz** [comment]
This issue is less visible after https://github.com/DaemonEngine/Daemon/pull/784 was merged, but we can still reproduce it with weapons like the pulse rifle:

[![light blockiness](https://dl.illwieckz.net/b/unvanquished/bugs/light-blockiness/unvanquished_2023-01-19_145745_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/light-blockiness/unvanquished_2023-01-19_145745_000.jpg)

**Comment by slipher** [comment]
Closing this since the really bad issues with flames are fixed. For the more subtle blocking see https://github.com/DaemonEngine/Daemon/issues/791
