### ISSUE TITLE
Dynamic lights too bright on Nvidia

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#2351]
On Nvidia that the dynamic lights are way too bright. Here's a single blaster shot:

![unvanquished_2022-12-23_032314_000](https://user-images.githubusercontent.com/7809431/209310021-789c10a2-5f74-4c5e-8236-36e19765b9de.jpg)

GPU: NVIDIA GeForce GTX 1050 Ti

**Comment by illwieckz** [comment]
I consider this issue to have more priority than #2343, as #2343 just makes the game look “less good” on an aesthetic point of view.

This one affects gameplay and can bring a different gameplay given you own this or that hardware.

For example this bug may bring an advantage to players using Nvidia hardware when playing darky maps like hangar28, using a flamer to lit the environment.

**Comment by illwieckz** [comment]
It is believed to be fixed by https://github.com/DaemonEngine/Daemon/pull/784 , please reopen if you reproduce it after merging https://github.com/DaemonEngine/Daemon/pull/784 .
