### ISSUE TITLE
Flooding protection behaves differently when game is paused

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2362]
It is more restrictive when the game is paused. I'm not sure if this is a feature. But I know that players tend to talk more when the game gets paused. The server makes it hard for them.

To reproduce, start a server and do this on a client with default level 0 permission:
```
]/say a; delay 1s say a; delay 2s say a; delay 3s say a; delay 4s say a 
[S] level0player: a 
[S] level0player: a 
[S] level0player: a 
[S] level0player: a 
[S] level0player: a
```
Then restart the server (to be sure), and do this:
```
pause: console paused the game. 
]/say a; delay 1s say a; delay 2s say a; delay 3s say a; delay 4s say a 
[S] level0player: a 
[S] level0player: a 
[S] level0player: a 
You are flooding: please wait 1s before trying again 
You are flooding: please wait 3s before trying again
```

Edit:
In practice, the player talking an admin into pausing the game will be censored even more, as they will have some recent talking on their account already. This creates the unfortunate situation that they cannot explain what they expect to be fixed.

**Comment by bmorel** [comment]
I can reproduce.
This is clearly a bug, as [this](https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_cmds.cpp#L4739-L4785) does not shows any direct relation with pause. Even if it was a feature, I would fail a lot to see the rationale behind it.
I guess this is the same kind of problems which led to make the auto pause of servers when starting a game opt-in instead of opt-out, and generates a bunch of other problems when changing the pace of the game.

Maybe you can work around the flood protection by changing the value of g_floodMinTime, which defaults to 2s.

**Comment by necessarily-equal** [comment]
I agree this is a bug. Fixing this may be as simple as replacing level.time with another value, such as Sys::Milliseconds.

**Comment by sweet235** [comment]
I noticed another problem: when you have permission for `pause`, but not `NOCENSORFLOOD`, the flooding protection will prevent you from unpausing.

**Comment by necessarily-equal** [comment]
I'm not sure I understand the implications of this

Le 8 février 2023 10:57:27 GMT+01:00, sweet235 ***@***.***> a écrit :

**Comment by DolceTriade** [comment]
> I noticed another problem: when you have permission for pause, but not NOCENSORFLOOD, the flooding protection will prevent you from unpausing.

Should be fixed by this change right?

> I'm not sure I understand the implications of this

Implication is that if you paused the game and are the sole admin, you won't be able to unpause the game.

**Comment by sweet235** [comment]
> I'm not sure I understand the implications of this

It means that on your server, I might have to wait for some time until i can unpause. :)

**Comment by necessarily-equal** [comment]
Ok then I shouldn't be a breaking behaviour. I won't have time to fix this now, you may want to open an issue so we don't forget about it.

Le 20 février 2023 09:59:14 GMT+01:00, sweet235 ***@***.***> a écrit :

**Comment by sweet235** [comment]
lgtm
