### ISSUE TITLE
RmlUi dropdown widget doesn't show the currently selected item

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2378]
RmlUi dropdown widget doesn't show the currently selected item. The issue can be reproduced with the screen resolution list in graphics settings and with the map list in server creation form.

**Comment by illwieckz** [comment]
@DolceTriade maybe you'll know how to track down this?

**Comment by DolceTriade** [comment]
I could have sworn I fixed this...

**Comment by DolceTriade** [comment]
f5d89ca840ae9dea4e85a0abb9f8ce270766f1aa I think was the fix... Maybe this is another issue

**Comment by DolceTriade** [comment]
Ah, this affects specifically `<dataselect/>` elements, which look the same as regular drop downs, but are not the same :smile:

**Comment by DolceTriade** [comment]
Hm, idk what's going on. Even if I set the value by clicking on it, it doesn't stick. As far as I can tell, the datasources are getting their values set correctly...

**Comment by illwieckz** [comment]
Fixed by:

- https://github.com/Unvanquished/RmlUi/pull/5
