### ISSUE TITLE
license text missing in some files

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#238]
g_weapon.h is the first example I have find.

**Comment by gineadai** [comment]
Is daemon under BSD and GPLv3+, or just GPLv3+?

**Comment by mbasaglia** [comment]
The older code is GPL and the newer code is BSD. So, as a whole is GPL (BSD is compatible with the GPL but not the other way round).

**Comment by Viech** [comment]
The idea is to keep the gamelogic GPL and move the engine to BSD bit by bit.
