### ISSUE TITLE
Bases' beacons ("home" and "tents") are wrongly all "home" icons

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#2390]
The effect are different on a team or as a spectator, but it's still wrong in both cases.

A good map to test this is mission-mantis because the default layout is huge. (You can find the map on Sweet's server for example)

**Comment by necessarily-equal** [comment]
Mission-mantis example:

![Screenshot from 2023-01-30 13-08-19](https://user-images.githubusercontent.com/59283660/215473236-b59c17c9-1e3c-424b-9a41-67ab7867cc7b.png)
![image](https://user-images.githubusercontent.com/59283660/215473191-6f085642-8c4a-4c8f-9fb6-fc1d67237906.png)

**Comment by necessarily-equal** [comment]
I should add that reverting bf49b64e4059c68b7578ce11d08ec579f22f156b doesn't fix this

**Comment by slipher** [comment]
This is because `eFlags` is recorded as a 24-bit field in the entityState_t netcode table but EF_BC_BASE_OUTPOST is the 25th bit. As you know well, changing the entityState_t netcode still requires a Daemon release :upside_down_face:

**Comment by bmorel** [comment]
If fixing this requires a daemon update, I guess the issue can be re-milestoned for 0.55.

**Comment by slipher** [comment]
Well we could potentially fix it with a judicious choice of overlapping flag values. 6cf828ab64ebe26ea1fb38a4f4090fbfdb3cb45b is the culprit.

**Comment by bmorel** [comment]
this seems ugly. Is the bug important enough so that it requires doing it until we get to 0.55?

**Comment by slipher** [comment]
We could swap with EF_TYPING since the typing bubble feature is currently disabled.

**Comment by bmorel** [comment]
Makes sense.

**Comment by slipher** [comment]
Actually no, EF_TYPING *already* overlaps with beacon bits.
