### ISSUE TITLE
possibly wrong lastCombatTime update

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2399]
https://github.com/Unvanquished/Unvanquished/blob/1449f3c9bca3787462a8dc997700916020c43c1d/src/sgame/components/HealthComponent.cpp#L148

This line really only updates the entity receiving damages. I'm pretty sure the intent is to update both attacker and defender's values.

**Comment by bmorel** [comment]
A quick test shows that there is no delay when taking or receiving damages from a building. Need to test with AIs to see what is the current behavior and then decide if this is really what is expected

**Comment by slipher** [comment]
This was resolved with #2875.
