### ISSUE TITLE
Build error with JPEG

### ISSUE THREAD

**Issue by Heic0** [Unvanquished/Unvanquished#2400]
https://pastebin.com/htw2MBEQ

[ 97%] Building CXX object daemon_build/CMakeFiles/client-objects.dir/src/engine/renderer/tr_image_jpg.cpp.o
/home/home/Unvanquished/daemon/src/engine/renderer/tr_image_jpg.cpp: In function ‘void LoadJPG(const char*, unsigned char**, int*, int*, int*, int*, int*, byte)’:
/home/home/Unvanquished/daemon/src/engine/renderer/tr_image_jpg.cpp:121:2: error: ‘jpeg_mem_src’ was not declared in this scope; did you mean ‘jpeg_stdio_src’?
  121 |  jpeg_mem_src( &cinfo, reinterpret_cast<const unsigned char*>(data.data()), data.size() );
      |  ^~~~~~~~~~~~
      |  jpeg_stdio_src
daemon_build/CMakeFiles/client-objects.dir/build.make:1109: Error

**Comment by slipher** [comment]
The support for some old libjpeg versions was removed in https://github.com/DaemonEngine/Daemon/pull/769. Can you install a newer version? Alternatively you could try reverting the linked patch.

**Comment by necessarily-equal** [comment]
This is apparently fixed by replacing `reinterpret_cast<const unsigned char*>(data.data())` with `reinterpret_cast<unsigned char*>(&data[0])` [in tr_image_jpg.cpp](https://github.com/DaemonEngine/Daemon/blob/master/src/engine/renderer/tr_image_jpg.cpp#L121). `.data()` has to be const it seems :-/

**Comment by necessarily-equal** [comment]
This bug was affecting the old "1.4.2-0ubuntu3.4" version of libjpeg-turbo as packaged in Ubuntu 16.04. Since this version is antique, I think this is fair to say that Unvanquished should not have to provide a fix in the main repo so I'm going to close this as "not planned". You can find a workaround on the previous comment.
