### ISSUE TITLE
consider disabling bots to use flamer

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2411]
Previously, flamer was usable in 1 vs 1 fight (even if this would often end up badly for the flamer user), this is no longer the case.
I think @illwieckz said that the current flamer is a specialized weapon to attack bases.

Bots are unable to plan a proper attack on a base (they're unable to plan anything anyway), to obey to a plan (in vanilla, I know some mods implement that), or even to move in group (again, I know some mods implement changes in that area), hence I think bots should be prevented to use the flamer at all, as this makes them easy, high value preys, breaking AI balance (alien bots do not use weapons they don't know how to use properly).

[This](https://github.com/Unvanquished/Unvanquished/blob/b957b985d5450a5e028fd2bfe048fa2546534847/src/sgame/sg_main.cpp#L257) is the only line that would need to be changed.
I would recommend server owners to at least disable it though configuration files as long as this is not done upstream. This might notably interest @sweet235  and @cu-kai

**Comment by cu-kai** [comment]
I've had the flamer disabled on Bunker for bots for some time now, and I think @sweet235 might also too.

Flamer is quite useless anyway, even against bases. I outright disabled it through `g_disabledEquipment` on the PvE maps on Bunker.

**Comment by sweet235** [comment]
> and I think @sweet235 might also too

Yes.

**Comment by necessarily-equal** [comment]
I honestly feel like the right solution here would be to buff back the the flamer damage to make it usable anew. It's nerfed too hard now IMO

**Comment by DolceTriade** [comment]
I liked @bmorel's change where he give it clips and buffed damage. I think we can adopt something similar.

**Comment by bmorel** [comment]
Actually, I *nerfed* the direct damages flamer dealt. In the end, it was still too powerful though, it requires more nerfing. Still, the (very slow: 4s) reloading time made the flamer behaving as a heavy weapon, which is quite fitting imo, especially considering the damages it does.
You also need to remember that this change was accompanied by a huge creep buff, which I think would make a real alien base much more flamer-resilient.
Last of the changes I had there is a nerf for ground flames, which is still very needed in unvanquished imo.

But all this is out-topic. The topic here is: since bots are totally unable to use the flamer, I think upstream should disable bots buying this weapon by default, until bots learn how to use the flamer, being the current one or a future modified version.
