### ISSUE TITLE
lock team-selection pop-up

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2413]
Currently the team-switching pop-up can be moved, pretty easily and often by accident (I don't see any reason to do that except by accident actually).
![2023-02-05](https://user-images.githubusercontent.com/1316300/216833142-b08c5049-2a91-479e-9129-39afe5a371d4.png)
It notably can be moved when clicking on the "choose your starting form", which is where can click when trying to respawn faster.

I think this window being floating brings nothing good to unvanquished.

**Comment by DolceTriade** [comment]
Seems reasonable. Is probably a one liner CSS change, but idk.

**Comment by bmorel** [comment]
[Those](https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/blob/35aee1ef6d3a6c6a018f7a87ac69c754547913c4/ui/shared/window.rml#L94-L102) lines are what is responsible for the annoying behavior it seems.

But ofc changing this would affect all windows, and the only ones I that shuold be pinned are the in-game ones, so: not good.

Scoreboard does also depends on this, but lack the usual decoration of windows, so clearly it should be possible to fix without duplicating the template.
Just removing the `template="window"` is not good neither, as it prevents quitting by using "esc" key, and removes all the styling (as for scoreboard basically).

**Comment by illwieckz** [comment]
See: https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/179

**Comment by bmorel** [comment]
fixed by said PR
