### ISSUE TITLE
allow `cg_thirdPerson` for spectators

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2438]
There is no reason to protect `cg_thirdPerson` for spectators when cheat mode is not enabled. The benefits this would bring is that it would be much easier to report AI bots by taking more readable screenshots.

**Comment by DolceTriade** [comment]
Can you middle click or something to go into third person as a spec?

**Comment by bmorel** [comment]
Oh! You're right, middle click works. Tutorial does not mentions it though, and the command says this is cheat protected...
