### ISSUE TITLE
AI balance in broken in 0.54

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2439]
While in 0.53 AI games had a reasonable difficulty with default settings, and teams were even rather balanced if I remember correctly the measurements I did back in time, in 0.54 alien bots win all the time, in few minutes (less than 5 minutes). This is what happened in 0.51, when human bots were totally useless.

SK5 alien bots are also very hard to fight, even for seasoned players.

**Comment by bmorel** [comment]
One of the things that make it particularly hard to fix is that bots now have a "semi-random" skill, randomness being based on bot's naming, apparently.
If I have to explain why this is a terrible idea, I'll just say that it makes it impossible to actually balance things without renaming bots.
Names are *not* something you want to be related to skills.

**Comment by sweet235** [comment]
> Names are not something you want to be related to skills.

The code is still there, but not used by default.
