### ISSUE TITLE
reimplement or find in deep history the trail file "models/weapons/lev2zap/lightning"

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2446]
I know this is probably not the correct place for this issue, but not sure where to place it so that people would see it...

Several (non-official) maps rely on a trail system named `models/weapons/lev2zap/lightning`, which was removed at some point in time, probably in early unvanquished's releases. Even the tremulous-gpp stuff I could find around does not mention it.
My guessing is that in a long forgotten past, advanced marauder's zap effect was implemented as a [trail system](http://tremmapping.pbworks.com/w/page/22453202/Trail%20System), and few maps reused it to have nice graphical lightnings on elements, probably pure eye-candy.

I've tried asking around and searching for any clue about this, but could not find anything, so this issue is kind of my last resort.

**Comment by bmorel** [comment]
Ok, I have found what needs to be done.
A trail file needs to be added, with this content:

```
models/weapons/lev2zap/lightning
{
  beam
  {
    shader        models/ammo/tesla/tesla_bolt

    segments      5   
    width         16.0 16.0
    color         { 0.8 0.8 0.8 } - 

    textureType   repeat front 100.0

    jitter        4.0 200 
    jitter        1.0 20
  }

  beam
  {
    shader        models/ammo/tesla/tesla_bolt

    segments      8   
    width         5.0 5.0 
    color         { 0.5 0.8 1.0 } - 

    textureType   repeat back 50.0

    jitter        2.0 150 
    jitter        1.0 30
  }
}
```

and a file `models/ammo/tesla/tesla_bolt.jpeg` has to be added. Png works too, and makes it easier to have transparency. Here is the original image used:
![tesla_bolt](https://user-images.githubusercontent.com/1316300/218191070-7d1fbc8f-ac68-41e2-adbe-651a6ada4c71.jpg)

All this stuff could probably be added to res-tremulous package. What do you think about it, @illwieckz ?

**Comment by bmorel** [comment]
Ok, even better, use this for the trail:

```
models/weapons/lev2zap/lightning
{
  beam
  {
    shader        gfx/weapons/reactor/bolt

    segments      9   
    width         8 8 
    color         { .75 .5 1 } - 

    textureType   repeat front 100 

    jitter        12 200 
    jitter        2 20
  }

  beam
  {
    shader        gfx/weapons/reactor/bolt

    segments      9   
    width         8 8 
    color         { .5 .8 1 } - 

    textureType   repeat back 50

    jitter        12 150 
    jitter        2 30
  }
}
```

This will reuse the game's reactor's blast, also used for current marauders zap and probably in it's time by the last tesla defenses.

**Comment by DolceTriade** [comment]
Looks very nice

**Comment by bmorel** [comment]
Gave a quick test at adding this content in a file named `scripts/tesla.trail`, but this prevents it to be loaded by unvanquished. Apparently, the file **MUST** be named like the map to be loaded, which makes it impossible to just add support to all maps using `models/weapons/lev2zap/lightning` by simply adding a file into res-tremulous: all maps must be updated, or res-tremulous must be updated to duplicate this file for all maps using it.
Considering the files sizes, updating res-tremulous is still the better from a user's PoV though, despite being ugly. It would, though, allow to fix future breaks or changes in a better way. Supposing that this does not break anything, of course.

**Comment by slipher** [comment]
> Apparently, the file **MUST** be named like the map to be loaded, which makes it impossible to just add support to all maps using `models/weapons/lev2zap/lightning` by simply adding a file into res-tremulous

Are you sure? The code looks like this:
```
numFiles = trap_FS_GetFileList( "scripts", ".trail",
	                                fileList, MAX_TRAIL_FILES * MAX_QPATH );
```
It would seem to read any `scripts/*.trail` in the VFS

**Comment by illwieckz** [comment]
This was a misundestanding because @bmorel did not manage to add a working `tesla.trail` file. The reason why his `tesla.trail` file didn't work was that we still had a `tesla.trail` file but with content not providing tesla stuff.

See https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/pull/14

**Comment by bmorel** [comment]
Yes, I was mistaken. I don't know much about all those details, so all this required quite the guesswork. I renamed the file to `tremulous-gpp-compat.trail` in res-tremulous, and things work nicely.

**Comment by bmorel** [comment]
I do not know if I can fix this? From my end, I ended up with a desired effect, but it's not really related to unvanquished... @illwieckz can you remind me where is the repo for res-tremulous? So that this change can be pushed and issue closed.

**Comment by bmorel** [comment]
fixed by a commit in res-tremulous I think
