### ISSUE TITLE
Walking into a "disabled" `trigger_teleport` causes rendering issues

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2447]
Unsure whether this is a Daemon bug or can be fixed in the gamelogic.

When walking into a trigger_teleport which has been disabled, the "Hall Of Mirrors" effect is present until you exit the trigger volume. You are not teleported to the destination, so the toggle itself works correctly.

I have tried using `env_afx_teleport` but it seems it cannot be toggled (that seems worthy of its own new issue?)

You can test this with map-mission-control_0.4.dpk by entering the alien base, noclipping just past the invisible wall at the start, then standing above the first three lines of eggs. Make sure to trigger the invisible trigger just inside the door to the alien base too.

Example of what I see:
![unvanquished_2023-02-12_224958_000](https://user-images.githubusercontent.com/13281185/218342073-d7d3f7a2-a939-4550-be69-770fb13be664.jpg)

**Comment by DolceTriade** [comment]
Definitely a bug _somewhere_, so good issue

**Comment by bmorel** [comment]
Reminds me of the bug on nintendo-land, now that I see a screenshot of it.

**Comment by illwieckz** [comment]
Something to notice is that on my end `r_clear` was enabled (which is now the default since a couple of releases), meaning the hall of mirrors is not only painted for the only reason we would see the void (if we do).

**Comment by illwieckz** [comment]
@cu-kai I don't know how to reproduce the bug with mission-control, would you try to reproduce it with this patch?

- https://github.com/DaemonEngine/Daemon/pull/813

Maybe there are two bugs and only one is fixed.

**Comment by illwieckz** [comment]
Yeah, it looks like there was two bugs talked about there.

**Comment by cu-kai** [comment]
P.S. the easiest way to reproduce the bug in mission-control is to open all 4 doors and enter the alien spawns room normally, then noclip to just behind the invisible wall to the first row of eggs. That is where you encounter this.

**Comment by illwieckz** [comment]
Do you have a `viewpos`? Because I fail to reproduce any glitch even with 0.54.

**Comment by cu-kai** [comment]
The attached map will help to debug this. Remove the .zip extension and place the .dpk in your pkg directory.

[map-test-teleporters_0.1.dpk.zip](https://github.com/user-attachments/files/15859371/map-test-teleporters_0.1.dpk.zip)
