### ISSUE TITLE
translation.cpp:180:101: error: no matching function for call to ‘tinygettext::DictionaryManager::DictionaryManager(<brace-enclosed initializer list>)’

### ISSUE THREAD

**Issue by DanielcoderX** [Unvanquished/Unvanquished#2458]
Abusing Error with **`tinygettext`** library while trying to build.
```
Unvanquished/src/cgame/translation.cpp:180:101: error: no matching function for call to ‘tinygettext::DictionaryManager::DictionaryManager(<brace-enclosed initializer list>)’
     static tinygettext::DictionaryManager trans_manager{ "UTF-8", Util::make_unique<DaemonFileSystem>() };
                                                                                                     ^
In file included from Unvanquished/libs/tinygettext/include/tinygettext/tinygettext.hpp:24,
                 from Unvanquished/src/cgame/translation.cpp:40:
Unvanquished/libs/tinygettext/include/tinygettext/dictionary_manager.hpp:98:3: note: candidate: ‘tinygettext::DictionaryManager::DictionaryManager(const tinygettext::DictionaryManager&)’
   98 |   DictionaryManager (const DictionaryManager&);
      |   ^~~~~~~~~~~~~~~~~
Unvanquished/libs/tinygettext/include/tinygettext/dictionary_manager.hpp:98:3: note:   candidate expects 1 argument, 2 provided
Unvanquished/libs/tinygettext/include/tinygettext/dictionary_manager.hpp:61:3: note: candidate: ‘tinygettext::DictionaryManager::DictionaryManager(const std::string&)’
   61 |   DictionaryManager(const std::string& charset_ = "UTF-8");
      |   ^~~~~~~~~~~~~~~~~
Unvanquished/libs/tinygettext/include/tinygettext/dictionary_manager.hpp:61:3: note:   candidate expects 1 argument, 2 provided
make[2]: *** [CMakeFiles/cgame-native-dll.dir/build.make:580: CMakeFiles/cgame-native-dll.dir/src/cgame/translation.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:349: CMakeFiles/cgame-native-dll.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
OS: Arch Linux
Kernel: 6.1.10-arch1-1
Compiler Version: 12.2.1

**Comment by illwieckz** [comment]
Hmmm, our source tree provides `tinygettext` so the code should be compatible with itself, maybe you also have a system-installed `tinygettext` that conflicts with it?

**Comment by DanielcoderX** [comment]
Nope, No `tinygettext` available on my system and that's just available in the project modules library

**Comment by DanielcoderX** [comment]
> Hmmm, our source tree provides `tinygettext` so the code should be compatible with itself, maybe you also have a system-installed `tinygettext` that conflicts with it?

Nope, No `tinygettext` available on my system and that's just available in the project modules library

**Comment by slipher** [comment]
The lines excerpted in the compiler error messages (61 and 98) don't match the `dictionary_manager.hpp` in our tree. Line 61 is `public:` and line 98 is empty in our version. And the public constructors have 0 or 2 arguments, not 1. How did you get the source code?

**Comment by DanielcoderX** [comment]
> The lines excerpted in the compiler error messages (61 and 98) don't match the `dictionary_manager.hpp` in our tree. Line 61 is `public:` and line 98 is empty in our version. And the public constructors have 0 or 2 arguments, not 1. How did you get the source code?

I've got the source by `git submodule update --init --recursive` 
Let me repull them and try again

**Comment by DanielcoderX** [comment]
I don't understand what the hell was happening with my system, but now the building process was well and nothing wrong happened.
