### ISSUE TITLE
"Teams are imbalanced" message is spammy

### ISSUE THREAD

**Issue by VReaperV** [Unvanquished/Unvanquished#2468]
The "Teams are imbalanced. Humans/Aliens have mroe players" message gets sent 3 times when someone joins a team with more players, caused by: https://github.com/Unvanquished/Unvanquished/blob/6e6ec8b26536da0801fac1ebc8389a6ce730974d/src/sgame/sg_team.cpp#L576-L601 There's no need to spam it, especially since, to my knowledge, no other message gets duplicated like that. Furthermore, it only gets sent when there's more than 2 players difference, which I think should be changed to more than 1.

**Comment by DolceTriade** [comment]
yeah, probably true. I don't think it's especially a useful message either.

**Comment by sweet235** [comment]
We could simply remove it. If we want balanced teams, there is always `g_teamForceBalance`.

**Comment by bmorel** [comment]
Agree that this message is useless. OTOH it's possible to "disable" it already by doing that: `/g_teamImbalanceWarnings 32000`. 32000 should be pretty safe, as it can be held into a `short`. Then, sure, it's possible to have a game lasting for almost 9H, but I'd say the event is rare enough to make this a pretty reliable fix :)
