### ISSUE TITLE
dretches emits some noise when close enough to a func_door or func_button

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2470]
I believe this is linked to the changes to re-introduce damage entities. This does not happens on 0.54 servers, only on servers that are close enough to master.
To reproduce with an official map, go as dretch on one of spacetracks' elevators doors. You'll hear the dretch doing some noise.

**Comment by cu-kai** [comment]
The dretch now reflexively bites all door and button entities following the fix in #2449. In a similar fashion, Dragoons can now "pounce" on doors regardless of whether they take damage (you hear the landing bite when you touch them at the end of your pounce now).
