### ISSUE TITLE
`EV_WARN_ATTACK` message may contain an incorrect location

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2472]
I have observed on both Bunker and Sweet's server on the map `operation-dretch` - the location marker for a base which is under attack is sometimes incorrect, displaying a location nowhere near where the base is being attacked. This does not always happen and the locations it occurs in are inconsistent. 

This may be reproducible on operation-dretch by opening the 2nd forward base and letting the alien bots destroy the armoury within. The game reports that the final Overmind room is under attack, and although that room is nearby (but separated by a thick wall), there are closer location markers than the Overmind room.

The other location I saw this occur was near the end of the final halls on that map, an armoury was destroyed and the server reported "Under attack - 1st large room" which is at the opposite end of the map.

**Comment by slipher** [comment]
Maybe it's a clustering thing? Like the buildables in two rooms are assigned to the same base cluster and then the attack is reported at the center of the cluster regardless of which buildable in the cluster was attacked

**Comment by cu-kai** [comment]
There are no other human buildables in the vicinity of the armoury on that map. There are two medistations underneath a glass wall but they are right next to it.

**Comment by cu-kai** [comment]
Can confirm this is happening on other maps, `mission-mantis` and `rush-station` are two I know for sure.

**Comment by cu-kai** [comment]
A good candidate for testing this is also `grangermaze` - confirmed broken on there too.

**Comment by illwieckz** [comment]
After an intensive testing session with @cu-kai it really behaves like if the game would use a wrong index in an entity array, printing location of a random entity. The more entities there is in a room, the more this room has chance to be displayed as a location where something happens. And when a reported location is empty… we discover there is an intermission camera in it.
