### ISSUE TITLE
dialogs do not close when one uses "resume action"

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2484]
![2023-03-11](https://user-images.githubusercontent.com/1316300/224474787-725b2cf1-78a8-49eb-93a5-301ab186c778.png)

To reproduce: start a game, use "escape" key to show menu, open a dialog, clic on "resume action".

**Comment by DolceTriade** [comment]
What is "resume action"? I've never seen it before.

**Comment by bmorel** [comment]
![2023-03-12](https://user-images.githubusercontent.com/1316300/224536924-627c06da-64bc-4f06-b171-ad005efff7b3.png)

**Comment by DolceTriade** [comment]
I have never seen that button in my entire life...

This is a trival fix tho: https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/blob/15b9c0f0a8681a98e3dbe3b4197a8d02e87bca97/ui/menu_ingame.rml#L24

Just change that to blurall or something to hide *all* windows.

**Comment by bmorel** [comment]
I don't say the fix is hard, I just reported the bug while I noticed it. The GUI stuff is not my fun, though, and I have other fixes for map entities on the TODO list for now

**Comment by DolceTriade** [comment]
of course. Just noting it for whoever finds time to fix it :D
