### ISSUE TITLE
Should we integrate non-intrusive experimental features as compilation flags?

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2490]
Working on long-standing projects, such as the navmesh generator merge in-game or the lua integration in gamelogic is a difficult task, and keeping it in sync with the main codebase just adds insult to the pain.

I think development could be easier if using opt-in build flags to enable them, and when judged reliable enough, invert the switches for one major version, and then removing the option in the next-next. Basically having some kind of deprecation system and would help fixing bugs with them without impacting "production" (master) reliability too much.

This is only about such big features that does not modify gameplay though. For the core mechanics.

**Comment by DolceTriade** [comment]
I'd prefer them to be runtime controls...I don't think compilation flags are really a good way to manage "experimental" features that are meant to be not optional in the future.

It makes sense for things that are truly optional like mumble support or theora support...

**Comment by bmorel** [comment]
It also make sense for internal mechanism. I was thinking specifically about your lua patches, here: it would likely be easier to have them in the codebase, but disabled by compile time: I would expect this to reduce the amount of git conflicts you will have. I'm half tempted to do some heavy work on map entities too, and this could be useful too.
The only con I see is that there is some half dead code in the game in the meantime, but said code being enclosed in #ifdef / #endif would make it easy to spot and remove if the stuff is not finished. COmpile-flag allows to reduce the problems injected in the codebase when the experiment is disabled.

**Comment by illwieckz** [comment]
I would also prefer some cvar-enabled stuff, because with `ifdef` for work-in-progress code just leads to dead code, and we never know when we break compatibility with the work-in-progress code, so we don't know since when it's dead for real.

**Comment by DolceTriade** [comment]
I think I'd prefer code to be in a somewhat usable state before its merged. Then we can add more features iteratively.

**Comment by slipher** [comment]
Looks like answer is “no”.
