### ISSUE TITLE
color bleed in logged infostring

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2513]
When the game starts, the game will print something like `InitGame: \g_maxGameClients\0\g_needpass\0\g_BPBudgetPerMiner\50\g_BPInitialBudget\80\sv_hostname\bot testing: ...` and here, starting with `bot testing: average` the text is suddenly printed in yellow instead of white.

**Comment by DolceTriade** [comment]
Since we just print the info string as is and the console print function either escapes everything or nothing, I think this is probably an acceptable thing. Closing won't fix.
