### ISSUE TITLE
geometry do not kill spawns when they birth

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2515]
To reproduce, load map `tranc3`: the game will flood `Warn: Spawn blocking entity has oldEnt == nullptr`

**Comment by DolceTriade** [comment]
We should either kill these spawns or silence the warning

**Comment by bmorel** [comment]
Silencing the warning won't fix the problem that people are unable to use the spawn.

**Comment by bmorel** [comment]
Related: 
![2023-03-20](https://user-images.githubusercontent.com/1316300/226351829-c05814cf-cba3-417a-95bc-8bcfbcee65b3.png)

map is `orion`.

**Comment by illwieckz** [comment]
> Related: ![2023-03-20](https://user-images.githubusercontent.com/1316300/226351829-c05814cf-cba3-417a-95bc-8bcfbcee65b3.png)
> 
> map is `orion`.

About this one we may want to reduce that specific bbox, that's not the only one map that can be affected, even our official Spacetracks map was distributed like this in some of our official releases the past.

**Comment by bmorel** [comment]
BBox size is unrelated to the actual bugs, and I guess would have to be in the gameplay tracker. But yes, the current bbox of telenodes is only a source of frustration and problems.

**Comment by illwieckz** [comment]
This specific telenode case looks definitely like a regression from Tremulous. While some buildables have been modified in clearly incompatible ways (like the armoury), I see no reason to break compatibility with Tremulous telenode.

But yes, whatever the cause of those mismatches, the game should handle them if possible.

**Comment by cu-kai** [comment]
This sounds like it could also be related to the issue of a team having spawns available even when they don't, because said spawns were embedded in a wall by the mapper or the map geometry significantly changed since last layout.
