### ISSUE TITLE
trying to spawn with a ckit when it's disabled gives wrong message

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2517]
It gives: `Unknown starting item`.

For a start, the option should be disabled one way or another, but also the error message should say the item is forbidden, not unknown.
I had this on map `siege`

**Comment by sweet235** [comment]
> I had this on map siege

Probably because the map wants to disable something we do not have (anymore). Changing `g_disabledEquipment` should fix this.

**Comment by bmorel** [comment]
Can changing `g_disabledEquipment` change error messages?
