### ISSUE TITLE
useless warning in `func_door_rotating`

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2519]
In tremship:

```
Warn: func_door_rotating at (672 -336 64) with no rotatorAngle set. 
Warn: func_door_rotating at (480 -336 64) with no rotatorAngle set. 
```

Those warnings are imo quite dumb, as it makes sense to just default on the Z (height) axis, which is what the game does anyway.
To me, emitting this warning is bug.

**Comment by DolceTriade** [comment]
Is it a bug or more of a "lint" warning for mappers? (To be clear, I'm no mapper so I don't know...)
