### ISSUE TITLE
Commented-out missile attribute parse warnings

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2565]
Opening the discussion in case there is indeed a problem there, out of PR #2545 which had fixing this kind of stuff ouf of scope. Ping @illwieckz 

https://github.com/Unvanquished/Unvanquished/blob/eb5f67b8b4d5b3991ae1437661f098085d138e41/src/shared/bg_parse.cpp#L2331-L2334

https://github.com/Unvanquished/Unvanquished/blob/eb5f67b8b4d5b3991ae1437661f098085d138e41/src/shared/bg_parse.cpp#L2048-L2055

**Comment by slipher** [comment]
The warnings have been uncommented.
