### ISSUE TITLE
optionally only block aim in circle menus

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2579]
it would be nice if circle menus could optionally only block aiming. While this would prevent the use of keybinds, it would allow mouse users to be able to still move while trying to place beacons, for example.

Reopened here because put in wrong repo: https://github.com/DaemonEngine/Daemon/issues/817

@illwieckz said there:

> …or place buildables with non-toggled wallwalk.

**Comment by slipher** [comment]
Did this. Circle menus other than armory allow key binds (and optionally “aiming” too).
