### ISSUE TITLE
The medistation base does not visually power down.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#2598]
**Current behavior:** When the medistation has no power or was just destroyed, then the cross disappears but the little lights and the screen on its base remain on.

**Expected behavior:** The glowing parts of its texture should be turned off, like is the case for the Armoury (when powered down or destroyed) and Telenode and Reactor (when destroyed).

**Comment by bmorel** [comment]
Could we have a picture describing this? It makes things easier to check after few weeks/months/years if the bug has been fixed.

**Comment by Viech** [comment]
Powered:
![unvanquished_2023-04-07_162511_000](https://user-images.githubusercontent.com/3780206/230628386-7b51aba3-ffde-4a08-80f1-b857107edecb.jpg)

Unpowered (note the armory in the background):
![unvanquished_2023-04-07_162522_000](https://user-images.githubusercontent.com/3780206/230628389-c8fa31a3-b00f-4e22-ad47-fb1522ae0967.jpg)

**Comment by bmorel** [comment]
The fix it to patch https://github.com/UnvanquishedAssets/res-buildables_src.dpkdir/blob/master/scripts/medistat.shader so that:

```
diff --git a/scripts/medistat.shader b/scripts/medistat.shader
index 0416dd2..c704b9b 100644
--- a/scripts/medistat.shader
+++ b/scripts/medistat.shader
@@ -8,10 +8,24 @@ models/buildables/medistat/medistat
                specularMap models/buildables/medistat/medistat_s
                specularExponentMin 10
                specularExponentMax 25
-               glowMap models/buildables/medistat/medistat_a
        }
 }
 
+models/buildables/medistat/medistat_off
+{
+       qer_editorImage models/buildables/medistat/medistat_d
+       imageMinDimension 128
+       {
+               diffuseMap  models/buildables/medistat/medistat_d
+               normalMap   models/buildables/medistat/medistat_n
+               specularMap models/buildables/medistat/medistat_s
+               specularExponentMin 10
+               specularExponentMax 25
+       }
+       when unpowered models/buildables/medistat/medistat_off
+       when destroyed models/buildables/medistat/medistat_off
+}
+
 models/buildables/medistat/rings2
 {
        imageMinDimension 128
```

Not doing the PR since I think @illwieckz have something prepared already

**Comment by necessarily-equal** [comment]
Is this fixed now ?

**Comment by Viech** [comment]
Yes.

**Comment by necessarily-equal** [comment]
Thanks!
