### ISSUE TITLE
allow to jump to a rotation depending on the day/time

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2604]
It would be nice to allow selecting rotations depending on day, day of the week, or hour.

There can be several use cases:

* april's fools, christmas, halloween, etc
* "theme of the $period", as in, have several rotation, which only contains maps that follow a theme, and after a rotation (or in middle, it's actually possible even if not convenient, but let's keep things simple), a new one would be selected depending on the period (i.e. day of the week)

I got this idea when doing a 2nd pass over all the maps I want to put in a rotation. In the end, I still have ~90 maps, which is a lot. All of them can be classified in various themes (space, Egypt-like, dirty industrial, shiny science, for the graphical ones. Then there's also the atcs-like, symmetric maps, story-based, ...) and I thought it would be an interesting way to let players familiarise with a rotation if those were small chunks of the whole selection. It would also be easier to maintain (adding maps that I excluded for now, removing some people don't like, moving them between rotations, ...).
But then, one have to switch between rotations, and i'd rather avoid doing this manually.

I think the most (only?) useful points here would be:

* day of the week
* week in month number
* day in month + month number (as in: 1224 for christmas, 0401 for april's fools, etc). This also would allow per-month rotations

**Comment by Gireen** [comment]
I think this and other complex rotations should be better covered by lua.

Else we also need feature requests to have rotations of maps that start with a specific letter, contain certain words or have a specific name length.

**Comment by bmorel** [comment]
This issue is not about discussing the implementation details, it's about discussing the feature.

Lua or whatever, this is not important.

**Comment by slipher** [comment]
> I think this and other complex rotations should be better covered by lua.
> 
> Else we also need feature requests to have rotations of maps that start with a specific letter, contain certain words or have a specific name length.

That's the rotation author's job to build these lists :stuck_out_tongue: 

I think we could do
- `time` (in UTC) from `0000` to `2359`
- Date `month`, `day`, `year`
- `weekday` (the usual 0 to 6 I guess)

**Comment by bmorel** [comment]
> That's the rotation author's job to build these lists ￼

Indeed. Author only needs to tools to make this convenient, such as the feature I asked here.

Time being in UTC should only depend on how the system is configured. I don't think we should explicitly support timezones: that's the OS's problem. So, agree. Same, minute granularity is more than enough, considering the time a typical game lasts.

I'm not sure the year is useful, but I don't see any reason to not have it if it's not complicated to have.

As for weekday, I think it's a bit weird to start with 0. 0-based index is something I don't really use in life outside of code, but maybe that's used in other countries? In any case, it's a minor detail.
