### ISSUE TITLE
Step-by-step guide to restore history from unvanquished dpkdir branches

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#2627]
My branch https://github.com/Unvanquished/Unvanquished/tree/buildtime includes many submodule-update commits refering to distinct commits in https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/tree/buildtime. I would like to restore a proper (ideally: original commit times, original commiter) history for the first branch, including all changes to the latter branch within the appropriate commits (where previously the submodule was updated). Could you walk me through this?

Also @sweet235 appears to have a similar issue.

**Comment by sweet235** [comment]
After a quick look at your branches, I think that my problem is not as big as yours. That is because I have fewer interdependencies between the two branches, and your branches are more serious.

**Comment by illwieckz** [comment]
Hi @Viech, you can now cherry-pick translated commits from [`dpkdir/buildtime`](https://github.com/Unvanquished/Unvanquished/tree/dpkdir/buildtime) branch. 😉️

**Comment by illwieckz** [comment]
@sweet235 just tell me what branch name you want to recover. 🙂️

**Comment by Viech** [comment]
@illwieckz thanks but I assume that I also need to remove the submodule updates from the commits of the original branch in the parent repo? Is there a simple way to rewrite those as well? I'd otherwise try to do that with partial reverts and an interactive rebase. (The latter I should do anyway after the cherry-picks.)

_@Viech feels like he's reciting dialog of a fictional nerd character created from densely packed but meaningless tech phrases._

**Comment by illwieckz** [comment]
Yeah, you would have to revert the submodule update changes. I actually wonder if that can be semi-automatized by rebasing on the tree that removed the submodule, and then solving the conflict on every commit by choosing the deletion as merge solution.

**Comment by Viech** [comment]
Using this issue as a notepad with references:

- old parent = rebased parent (→ old child = converted child)
1. 42f7e9b = bc55485 → f3a0477 = b24fd73
2. 245f4cf = a39a536
3. 5f964ce = dec1e54
4. 9092e45 = 109dcad
5. e7b0563 = b1fa888 →1363e5e = f305ccb
6. caf71e6 = 0a1fba7
7. e24df2f = 03628e1
8. 67d5433 = 72b7b9f → 0f1f86d = d7d489d
9. 4cf828c = 65d8b2f
10. 4fb3bc0 = 38b4704
11. 6552ca2 = 0793cd4 → ec09346 = c507da4
12. 8c7700b = 4e0869e → cf18d07 = fb8693d

**Comment by Viech** [comment]
`buildtime2` is `buildtime` rebased on current `master` as proposed (this worked rather well).

**Comment by Viech** [comment]
`buildtime3` now points to the final rewrite. I'll leave all three branches for now to be on the safe side.

**Comment by illwieckz** [comment]
Done for:

- [`dpkdir/juggernaut/deploy`](https://github.com/Unvanquished/Unvanquished/tree/dpkdir/juggernaut/deploy)
- [`dpkdir/tutorial/sync`](https://github.com/Unvanquished/Unvanquished/tree/dpkdir/tutorial/sync)

I haven't found any branch named like this in my translated repository:

- `further-ui-work`
- `tweak-unstick-behavior`

This one not being on upstream was not translated in the migration process:

- `necessarily-equal/rmlui-debugger`

**Comment by illwieckz** [comment]
I imported and translated:

- [`dpkdir/further-ui-work`](https://github.com/Unvanquished/Unvanquished/tree/dpkdir/further-ui-work)

**Comment by necessarily-equal** [comment]
Ok, I've updated my post above to have a todo somewhere for when I'll come back to it. Closing again I guess
