### ISSUE TITLE
Reload the game on game restart (next map is same map)

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2651]
Quote by @slipher from https://github.com/Unvanquished/Unvanquished/pull/2650#issuecomment-1523101444 :

> But more recently we have done down the path of requiring DLL unloading to work correctly, so that we can have a truly fresh start on each game.

I agree with that, better unload the binaries and let the kernel do the clean-up than keeping traces of everything.

Anyway we still have at least one big occurrence where unloading is not done is when someone restarts the game with `restart`, or when the game ends but there is no map rotation and then the game restarts one the same map.

Some of the "division by zero” errors I have patches for are actually only needed because the game isn't unloaded on restart. Also some other bugs like the persistent scoreboard on restart come from the fact everything isn't entirely reloaded from scratch.

**Comment by slipher** [comment]
We don't want to reload the cgame on `map_restart`. Then it wouldn't be usable for making a warmup period.

**Comment by illwieckz** [comment]
Ah, the warmup relies on `restart`?

Then maybe we may only restart when not doing warmup? But anyway if we need to restart for warmup, we need to keep all the annoying code for making a difference between map time and game time…

**Comment by DolceTriade** [comment]
We definitely do not want to reload all the time. Map loads are long and annoying. That's why `/restart` is a thing in the first place.
