### ISSUE TITLE
MSAA is not implemented, r_ext_multisample is not used

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#267]
| Release | v0.20.0 |
| :-- | :-- |
| Operating System | Archlinux 64 bit |
| Kernel Version | 3.11.4-1-ARCH |
| Video Card | Nvidia GTX 460 |
| Video Driver | NVIDIA 325.15 |
| Maps tested | atcshd, parpax |
| Renderer used | GL3 |

Compiling with USE_SDL2 enabled leads to r_ext_multisample having no visual effect or performance impact. I tested values 0 (for reference), 2, 4, 8 and 16.

Compiling with USE_SDL2 disabled results in both a performance decrease and visual impact for non-zero versions, as expected. All other settings (cmake, invocation, ingame) unchanged.

**Comment by illwieckz** [comment]
By reworking the GL init code (see https://github.com/DaemonEngine/Daemon/pull/478 ) I noticed the value of `r_ext_multisample` is never used.

**Comment by illwieckz** [comment]
MSAA does not work on my end since many years, and according to my previous comment it seems to not be implemented at all.

We probably forgot something when porting to SDL2 or something like that.

**Comment by illwieckz** [comment]
This is assumed to not be Linux specific, let's remove the `Linux` tag. If people gets anti-aliasing on other OS, that's likely thanks to their driver overriding it.

**Comment by illwieckz** [comment]
Using `r_glAllowSoftware` with `r_ext_multisample` does not enable MSAA on my end, I would have been surprised anyway since the value of `r_ext_multisample` is never used to begin with.

**Comment by slipher** [comment]
Closing in favor of https://github.com/DaemonEngine/Daemon/issues/532.
