### ISSUE TITLE
CMake looks for `daemon/` submodule even if `DAEMON_DIR` is set when modifying the compiler

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2685]
CMake looks for `daemon/` submodule even if `DAEMON_DIR` is set when modifying the compiler.

This only happen on first cmake call setting `CMAKE_C_COMPILER` or `CMAKE_CXX_COMPILER`, next call is fine.

So basically doing this will try to look for daemon/ submodule on second cmake call:

```sh
git clone git@github.com:Unvanquished/Unvanquished.git
git clone git@github.com:DaemonEngine/Daemon.git
mkdir build && cd build
# Fine
cmake ../Unvanquished -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DDAEMON_DIR=../Daemon
# Error at looking for daemon/ submodule
cmake ../Unvanquished -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DDAEMON_DIR=../Daemon
# Fine
cmake ../Unvanquished -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DDAEMON_DIR=../Daemon
```

I assume that changing the compiler forces CMake to reset the `CMakeCache.txt` file and then forget `DAEMON_DIR`, even if used in the same command line as the `CMAKE_XXX_COMPILER` option. Next call will not reset the cache since the compiler is the same, and then the DAEMON_DIR option will be used.

This may be a CMake design flaw, and while I caught this bug by using that specific `DAEMON_DIR` option, this may happen with any Unvanquished build option: only the second call after changing the compiler gets all the options.

**Comment by slipher** [comment]
> # CMAKE_\<LANG>_COMPILER
>
> The full path to the compiler for LANG.
>
> This is the command that will be used as the <LANG> compiler. Once set, you can not change this variable.

From https://cmake.org/cmake/help/v3.26/variable/CMAKE_LANG_COMPILER.html. Note the last sentence.
