### ISSUE TITLE
Implement numbered argument specifiers for Str::Format

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#2696]
For translatable strings with more than one printf-style format specifier, we would like to be able to specify arguments by number rather than assuming that each input is used in the same order in every language. We can hack tinyformat to add numbered arguments like `%1$s` as described in the [POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html).

**Comment by illwieckz** [comment]
Yes! That's needed for obituaries!

**Comment by bmorel** [comment]
I don't know for which lang it's necessary for obituaries, but this might lead to moving obituaries into config files to make code simpler.
