### ISSUE TITLE
`revert` doesn't properly deconstruct some buildings, but especially spawns

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2747]
We have observed this on Bunker today and been able to reproduce.

Using revert leaves behind the beacons of any removed buildable.

If you revert the building of a spawn, that spawn will become a "ghost" spawn and will be counted by `/teamstatus` and at the end of the game when all real spawns are dead and the team with the ghost spawn can never lose, even after admitting defeat. The team with the ghost spawn will be forever stuck in a spawn queue with _n_ spawns remaining.

**Comment by cu-kai** [comment]
To add, this looks like a CBSE mess, the entity doesn't seem to be removed properly.

**Comment by slipher** [comment]
Fixed by #2763.
