### ISSUE TITLE
bots fall through ground

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2751]
![2023-07-04](https://github.com/Unvanquished/Unvanquished/assets/1316300/5809f7c8-6895-4c74-9755-139af57d2f4a)

It's a bit hard to see on the screenshot, but position is, for example, 866, 106, -126

I'm currently seeing 2 bots in that area, and don't see how they could end up in there.
I'm afraid the geometry can leak big entities the same way it can leak missiles. map is ethereal.

**Comment by Gireen** [comment]
In that map is a place where players can go under the floor. If we talk about the same room, thats no bug or glitch but desired.

**Comment by bmorel** [comment]
Yes, paying more attention to it now, there's tiny places with holes to go down (and no easy way to go up for humans, thankfully unvanquished have wallrunning mechanics!). "not a bug" I agree, or at least, not an unvanquished one :D

Well, bots going down there *is* an unv bug, but it's already reported (ignoring navmeshes in fight).
