### ISSUE TITLE
There are no granger navmeshes anymore

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2787]
`daemonmap` used to emit `*-builder.navMesh` files, which I suppose could be used for grangers. These are nowhere to be found since the game creates the navmeshes. I think that is very unfortunate, as it seems grangers pretend to be dretches or mantisses, and even use dretch/mantis navcons. Of course, they get stuck if they are too fat or cannot climb a wall.

**Comment by sweet235** [comment]
As has been pointed out to me, a promising place to look at is this: https://github.com/Unvanquished/Unvanquished/blob/405c559b9cb19a9bb9b9438399c87476a67e1c8d/src/shared/bot_nav_shared.h#L275

**Comment by slipher** [comment]
You can manually generate them if you want using the `navgen` admin command. They are not generated by default because bots do not spawn as granger and cannot be instructed to by the BT.

**Comment by sweet235** [comment]
I can indeed create granger navmeshes with `navgen builder`. But it seems they are not loaded without changing the C++ code.

**Comment by slipher** [comment]
Granger navmeshes are enabled in master.
