### ISSUE TITLE
regression: perseus is not rendered corrected

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2802]
This is the levelshot of perseus, likely taken from some older daemon version:

![2023-10-04](https://github.com/Unvanquished/Unvanquished/assets/1316300/8326b7fb-f3cd-4ae4-b9b4-ff4efadbc58b)

This is what it looks like currently:

![2023-10-04](https://github.com/Unvanquished/Unvanquished/assets/1316300/014da29a-105f-4bdb-a58e-8d0ffaac861d)

**Comment by illwieckz** [comment]
Is it about the C8 texture?

If yes we can close this issue, that was a bug in a tool used by Urcheon when producing release dpk that made mistakes when converting some image format, such bug will disappear when re-releasing the map.

**Comment by slipher** [comment]
Well illwieckz says it's fixed. Reopen if you keep seeing it next release.

**Comment by illwieckz** [comment]
The bug is fixed in the code, but we have not released the fixed textures yet.

There is no need to reopen the issue as releasing the game will release the fix, so we don't have to remind that issue, we only have to remind to release the game (which is another issue).
