### ISSUE TITLE
Make CBSE not a submodule

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#2812]
The concept of CBSE is well-known in game dev under the name "ECS" (entity-component system). Our implementation of it is quite bare-bones; meanwhile there are many alternative implementations. So it is quite unlikely that other developers will want to use it. It would be more expedient to have the CBSE generator in the Unvanquished repository so we can easily make changes.

I would move it from `src/utils/` to the top-level `tools/` I guess.

**Comment by DolceTriade** [comment]
sgtm.

**Comment by illwieckz** [comment]
> The concept of CBSE is well-known in game dev under the name "ECS" (entity-component system). Our implementation of it is quite bare-bones; meanwhile there are many alternative implementations. So it is quite unlikely that other developers will want to use it. It would be more expedient to have the CBSE generator in the Unvanquished repository so we can easily make changes.

This is also consistent with the idea of having Unvanquished being the upstream for other games.

CBSE is more tied to Unvanquished than to the engine.

> I would move it from `src/utils/` to the top-level `tools/` I guess.

In fact I would move everything from `src/utils/` to the top-level `tools/`, even the translation scripts are not specific to `src/`.
