### ISSUE TITLE
Banned users' names aren't shown during attempted connection

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2816]
When a banned player connects, admins are notified of this by an admin chat message, however the banned player's netname is never shown.

The output is:
`AdminMsg: -1 "console": Banned player  tried to connect from 127.0.0.1 (ban #2) `

For some reason, although `ent` is valid (and other fields are valid within), the netname is an empty string so `G_user_name` also fails to fall back to the ban name. The solution could be to exclusively use the name they had when they were banned however I think it preferable to display netname if possible.

**Comment by slipher** [comment]
In ClientConnect() the G_admin_ban_check is called early on. The netname is set in G_namelog_connect or ClientUserinfoChanged which are further down in ClientConnect

**Comment by DolceTriade** [comment]
Any reason we shouldn't call these functions earlier? (or check for ban later?)

**Comment by slipher** [comment]
> Any reason we shouldn't call these functions earlier? (or check for ban later?)

Probably. For example booting off a client with the same GUID is done between these two things. 

If it's so important to see what name the player is attempting to connect with, just peeking the userinfo would be safer
