### ISSUE TITLE
is C++17 really not supported?

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2821]
When compiling with clang on debian, I have this:

```
Unvanquished/src/sgame/sg_buildpoints.cpp:107:17: warning: hexadecimal floating literals are a C++17 feature [-Wc++17-extensions]
        if (interval > 0x1.0p27f) return;
```

So perhaps rmlui actually *can* be updated instead of maintaining a fork.

**Comment by illwieckz** [comment]
It's possible that the clang compiler used to compile nexe binaries don't fully support c++17 while implementing some of the features?

**Comment by DolceTriade** [comment]
Correct. Pretty sure nacl's clang compiler will hold us back. This was the motivation for us moving from QVM to NaCL (being able to rewrite gamelogic in C++ and have dynamic allocations instead of writing limited C).

This might end up being the driving factor for moving from NaCL to WASM if we ever do it...

**Comment by illwieckz** [comment]
> WASM apparently is much slower than NaCl

Even if Wasm was 50 time slower than NaCl, speed is irrelevant: time is spent in IPC between gamecode and engine while painting alien creep.

It's technically possible to upgrade to Saigo which is a nexe compiler based on very latest Clang (and then supports the very latest C++), but this will drop the pexe support allowing us to build a single pexe then translate it to nexe for every architecture, the toolchain would have to be ported to rebuild the entire game nexe for every architecture.

**Comment by DolceTriade** [comment]
While annoying, it really only matters for releases? Dev iteration happens via shared objects anyways?

**Comment by illwieckz** [comment]
Yes, but mod releases are done more frenquently than game release. 😅️

**Comment by illwieckz** [comment]
Anyway, I would prefer to see someone investigate the viability of [WAMR](https://github.com/bytecodealliance/wasm-micro-runtime) for a migration to Wasm than to spend time on dealing with Saigo (we would need to rewrite some of our CMake code, and Saigo isn't packaged…). WAMR is said to be more multiplatform than NaCl and looks to be faster than NaCl (see that [comment](https://github.com/DaemonEngine/Daemon/issues/757#issuecomment-1769041733)), and the toolchain and the vm is easy to build (unlike NaCl).

Anyway, working on Saigo or Wasm with WAMR is for after 0.55 release.

**Comment by bmorel** [comment]
> While annoying, it really only matters for releases? Dev iteration happens via shared objects anyways?

Please, take some time to consider how much the release servers are actually played compared to mods. I have hard time refraining myself to make fun of how buggy sais release is, but I'll allow myself to say, better to play previous release than current one. To the point that official server does not even dare to host current, and this, for months! Please devs, play to the game before talking about it.

**Comment by illwieckz** [comment]
> I have hard time refraining myself to make fun of how buggy said release is

Making fun of current release doesn't contribute to any newer release.

> To the point that official server does not even dare to host current, and this, for months!

The fact the `unvanquished.net` server is currently down is not a failure but a feat of strength as a team.
Let's explain myself:

1. For years my `gg.illwieckz.net` server was considered an EU official server, but it's not named `unvanquished.net`, right? 
2. When we had bugs in release, or when next release was late, I hosted fixes and backports on `gg.illwieckz.net` and this was not considered a win from myself against the project. It was the solution we brought to players as a team. Sometime I also uploaded to `unvanquished.net` the same fixes and backports I was running on `gg.illwieckz.net`. This was not considered as a win from myself against the team.
3. In the last years, the team grown and new talent came. We currently have two servers hosting fixes, backports and gameplay experiments: kai's and Sweer's servers. Both Kai and Sweet are part of the team. It means their server are maintained by the team.

Thanks to those efforts now being done by other members of the team, I don't have to do those backports myself. This is a sign of an achievement as a team: the team is stronger and I have less things to do myself. This is a feat of strenght as a team: we are able to provide a playable game online even if I'm not available to do backports. This is not Kai and Sweet winning against the team, this is the team being stronger, more resilient, and achieving a success.

**Comment by slipher** [comment]
We have issues tracking [updating to a newer NaCl toolchain](https://github.com/DaemonEngine/Daemon/issues/795) or [migrating to Wasm](https://github.com/DaemonEngine/Daemon/issues/227). The actual question was answered: C++17 is really not supported. So I'll close this.
