### ISSUE TITLE
There is no known method to report problems with the general infrastructure

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2824]
For example: right now, unvanquished.net is down. How are we supposed to report this? I tried to report this in the usual IRC channels. But strangely, these channels do not allow me to say anything without voice. Which I cannot obtain, because I do not have my credentials around. The forum is not reachable. Creating a discord account requires a phone number, which I do not have right now.

I guess we are lucky that the master server is not running on unvanquished.net.

**Comment by slipher** [comment]
https://github.com/Unvanquished/unvanquished-infrastructure/issues
