### ISSUE TITLE
Patch meshes are no longer fully nonsolid on one side

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#2848]
Encountered this bug after rebasing today. To test this, use map rush-station and try to walk through the nonsolid side of the forcefields on that map. You will get stuck like a fly to a cobweb.

Whatever changed in the last month has broken rush-station and potentially other maps that rely on such behaviour.

**Comment by cu-kai** [comment]
Reverting this commit to Daemon Engine fixes the problem: https://github.com/DaemonEngine/Daemon/commit/29b991b637b7241651d2ccdb3b335125167f6755

**Comment by slipher** [comment]
I'll take a look. When working on those changes I added a [unit test](https://github.com/DaemonEngine/Daemon/blob/8a660392b4cc1549c4e2634852f2d3ba26f61c02/src/common/cm/unittest.cpp#L109) for going through the back side of a patch, but it starts completely on the nonsolid side. I guess the behavior inadvertently changed for the case of starting inside it.

**Comment by sweet235** [comment]
More maps: tremship, analmango

**Comment by cu-kai** [comment]
This also makes the breakage on rotcannon-garbage worse because you cannot get back in bounds once you break out of the map through the curved cannon tunnel.

**Comment by illwieckz** [comment]
> There is also the well-copied version of map usstremor, where you can escape not into the void, but below the basement floor; and build there for ultimate safety from anyone not an insider. The map's author reports their surprise about that.

If I'm right this issue is older than the one discussed in this thread and reported to have been introduced on October 8th of this year, so it would be another one and deserve its own thread.
