### ISSUE TITLE
Auto-detected language displays as "Custom value" even if available

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#2867]
The engine's language detection code supplies a language plus a country in the language string for example `es_AR`.  The translation language selection dialog only recognizes a language string if it is written exactly the same way as in the dialog. The dialog has a hard-coded country in each language string, for example `es_ES` for Spanish. So then `es_AR` is described as "Custom Value" rather than "Español".

I guess the easiest hacky fix would be to get rid of the country in the engine's detection code and put only e.g. `es`, assuming we aren't going to have multiple translations per language.

**Comment by illwieckz** [comment]
I'm not against the idea of not having multiple translations per languages, but this can bring funny things.

For example if I'm right we can say in Spanish of Spain « tomar un autobús » (to take the bus), but in some South American countries this may mean « have sex with the bus ».

If I'm right Microsoft faced a similar issue where the word used for « women » in a country was the word for « prostitute» in another one.

So, we must be prepared for drama. 😂️

**Comment by slipher** [comment]
> For example if I'm right one can say in Spanish of Spain « tomar un autobús » (to take the bus), but in some South American countries this may mean « have sex with the bus ».

You mean *coger* un autobús. Yeah, this one provides a lot of amusement.

**Comment by illwieckz** [comment]
Yes I fixed while you were writing your comment. My memory was old. 😃️

**Comment by illwieckz** [comment]
I don't find the reference about the Microsoft women/prostitute story anymore because the web is full of other unrelated Microsoft stories with other things translating to prostitute [1](https://www.windowscentral.com/lumia-spanish-prostitute), [2](https://news.softpedia.com/news/how-a-microsoft-exec-talked-about-prostitutes-without-even-knowing-it-501616.shtml). 🤭️
