### ISSUE TITLE
Brazilian portuguese (pt-br)

### ISSUE THREAD

**Issue by marcoaureliocardoso** [Unvanquished/Unvanquished#2886]
Can you enable brazilian portuguese (pt-br) on Weblate?

**Comment by illwieckz** [comment]
Hi, if I'm right you can add a new language yourself by clicking the big “+” button on the [Weblate project page](https://hosted.weblate.org/projects/unvanquished/unvanquished/), here is a direct link to the page to add a language: [add new](https://hosted.weblate.org/new-lang/unvanquished/unvanquished/).

![Capture d’écran du 2023-12-30 09-06-50 1](https://github.com/Unvanquished/Unvanquished/assets/2311649/8f1f00ea-cb36-4af6-ad21-894ee05ca87f)

Note that for now the game only supports one variant of a language and will make no difference between Portuguese and Brazilian portuguese. So I recommend to contribute to the Portuguese language to begin with.

**Comment by marcoaureliocardoso** [comment]
Thanks for the quick response.

That translation present on Weblate has already been started with Portuguese from Portugal and, considering the differences with the Brazilian language, I believe that players from Brazil would be much happier with the game in their language.

Regarding your suggestion, I could even collaborate with the existing translation on Weblate, but I don't completely master the nuances of Portuguese as spoken in Portugal.

**Comment by marcoaureliocardoso** [comment]
I completed the translation to pt_BR.
https://hosted.weblate.org/projects/unvanquished/unvanquished/pt_BR/

I hope it is useful for the project. 😉

**Comment by slipher** [comment]
We can't automatically detect country variants for now, but I think they could be added for selection in the menu.
Like `pt` -> Portuguese (Portugal), `pt_BR` -> Portuguese (Brazil). (Assuming that tinygettext maps `pt` to the Portugal variant; it could be the other way around).

Given that pt_PT is mostly incomplete, we could just disable it for now and make pt_BR the only one.
