### ISSUE TITLE
Leech/Drill gets deconstructed when moving a structure

### ISSUE THREAD

**Issue by RedSkyByte** [Unvanquished/Unvanquished#2907]
A peculiar behavior of unwanted deconstruction of drill/leech. To reproduce:

1. Have all your BP spent (so deconstruction for building will be required).
2. Mark a structure that you want to move.
3. Mark one of active drills/leeches.
4. Replace structure.

Leech/drill marked in step 3 will be also removed, leaving you with negative BP.

**Comment by DolceTriade** [comment]
seems like a bad bug

**Comment by VReaperV** [comment]
We'd probably just need to change https://github.com/Unvanquished/Unvanquished/blob/58ba8a8e43f899daca4fcd733eec3c992e0305f5/src/sgame/sg_buildable.cpp#L1195
to add a check for miners. There can be legit cases where you want to deconstruct miners though. One possible solution is to check how much BP you'd have if you removed that building.

**Comment by VReaperV** [comment]
There can still be issues in some situations, e. g. you have a drill that gives you 50 BP and you want to move base, but at the new location you need to replace it with 2 drills that give 25 BP each, so replacing the first drill would leave you at 25 BP less. We can combine the 2 checks and do something like: if replacing this miner would put you into negative BP, leave it there, otherwise replace (or if the limit is reached).

**Comment by RedSkyByte** [comment]
> There can be legit cases where you want to deconstruct miners though.

I don't think I understand what that cases would be in this context. You have no extra BP and want to move a structure so deconstruct drill while you at it? I'm not even saying even to move the structure in place of drill. Just move it anywhere else, the drill will be deconstructed.

The only application I see for such if you have a forward booster/egg and a leech and you want to deconstruct them at once to deny momentum. With marked booster and leech, to move forward base, just build booster elsewhere (and then place leech wherever).
The funny thing currently is that's the only way you can move leeches/drills at all. At this point just let me mark and move leeches normally and make me suffer the consequences of difference in BP.

By the way, if the new structure is replaced in place of old one everything works as it should: drill isn't removed in the process (provided it isn't touching the drill of course).

**Comment by sweet235** [comment]
I would say the best thing to do is never to replace any drill/leech, except if its own space is occupied by the new building. Indeed, this used to be the behavior a while ago. This is easier for players to understand and will prevent any unwanted deconstruction reliably.

If we allow for replacement of drills/leeches, there will be power shortages while the new drill/leech is constructing. These will be during critical phases, and it is likely the team will suffer from them.

**Comment by sweet235** [comment]
To elaborate: selecting drills/leeches to replace is rather difficult to automate, and to understand for players. Let's say you have 3 marked drills, and you attempt to build a new one. Which of the old drills should be removed? Assume for the sake of argument that two of them shall be replaced. How do you select these?

Maybe we would look at the 3 combinations and replace such that the resulting BP is a maximum. But with 4 marked drills, there are already 6 combinations to replace two of them. This will likely result in something you did not want to do.

Now imagine someone marks another drill while you are running to your new base. Then nobody has any idea what will happen.

We should avoid complicated behavior like this.

**Comment by VReaperV** [comment]
> If we allow for replacement of drills/leeches, there will be power shortages while the new drill/leech is constructing. These will be during critical phases, and it is likely the team will suffer from them.

Good point, it can just be limited to when you get to the miner limit, for example if you have 5/5 drills and want to move them, so you don't need to decon, then run back, then construct a new one (this can have some negative effects if someone marked a miner that shouldn't have been marked and you didn't know you were already at the limit).

**Comment by sweet235** [comment]
> I'd also add that's a slight tangent to the issue: which is definitely a bug and not a feature.

Well, yes. A bug would be very quickly resolved by going back to the old behavior.

>  for example if you have 5/5 drills and want to move them, so you don't need to decon, then run back, then construct a new one

That makes sense. But is it really worth the complexity? Notice there is no feedback on how many drills are marked. The best we could do without UI extension is to signal that you hit the maximum and no drill is marked.

**Comment by Gireen** [comment]
Another middle way could be to only allow one drill to be marked at the same time.
