### ISSUE TITLE
Entity parsing does not support overriding specific keys

### ISSUE THREAD

**Issue by VReaperV** [Unvanquished/Unvanquished#2913]
Per documentation for entities, it should be possible to use certain keywords that changes the same values in conjunction. For example, in misc_portal_camera: <angles key="angles" name="angles">Camera orientation. 3rd component is ignored in favour of &quot;roll&quot;. (vec3_float (yaw pitch roll))</angles>. Currently only "angles" is interpreted (we didn't actually interpret "roll" at all before #2910), and simply adding "roll" to the parser results in whichever key was last overwriting it. #2910 introduces a hack to make sure that "angles" doesn't override "roll", but a proper solution would be to make sure that parser can properly work with multiple keywords modifying the same value.

**Comment by slipher** [comment]
Can we close this? The portal thing was solved another way and partially-overlapping fields for the entity parser doesn't seem like a good thing to have.

**Comment by VReaperV** [comment]
Yeah, this isn't needed anymore.
