### ISSUE TITLE
Someone was angry

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2919]
Look at how the powers that be closed this PR: https://github.com/Unvanquished/Unvanquished/pull/2901

Also, notice that the most powerful people here spend their time blocking progress where they can. That is the reason why I refuse to make any more PRs. Someone should do something about this.

**Comment by Grise3** [comment]
Hello
Really all, we are loosing a lot of devs.
Before it was Freem, now it is @sweet235, who will left because of this mess next time?
>Someone should do something about this.

Yes. But I think that unfortunately it will take a lot of time to change....

@sweet235 do you remember what do you said to me in PM on irc?

Really, all this have to change. The sooner the better.

Is UNV dying?

**Comment by DolceTriade** [comment]
Unv isn't dying... that said we do need to streamline reviews among other things that we are discussing privately.

**Comment by sweet235** [comment]
> That is the reason why I refuse to make any more PRs

That was an improper generalization. I wanted to say: I will not continue to spend insane amounts of time defending PRs.

> Really all, we are loosing a lot of devs

I'm still here.

> Is UNV dying guys?

We are running out of testers. That is: if someone writes some code on airport or whatever, it is unclear who will test it.

**Comment by Grise3** [comment]
>I will not continue to spend insane amounts of time defending PRs.

Like freem.
As you said 1 hour of code 2 to talk 😕

>We are running out of testers. That is: if someone writes some code on an airport or whatever, it is unclear who will test it.

I can help test, but if I'm left with code I don't know...
I mean I don't 'know' the C++then I can't help to find a bug. But if we are searching for a result and that it don't work....

**Comment by Grise3** [comment]
>Players do not care about refactorings that bring nothing new, and might introduce new bugs. But players do care about improvements, even about small ones.

True

The best would be to have a good master branch :)

**Comment by sweet235** [comment]
I said this elsewhere:

```
<Sweet> i have learned that this is read by more people that i thought
<Sweet> the drama i have caused has irritated some people
<Sweet> i would like to apologize
<Sweet> dev team has always been very friendly to me
```

**Comment by illwieckz** [comment]
I responded this elsewhere:

```
<illwieckz> pardon is granted
```

🙂️

**Comment by Gireen** [comment]
To sum it up:
slipher made an alternative PR that sweet also approved.
the misunderstanding was that slipher thought that his merged PR did cover all functionality of sweets PR and closed the lather.
sweet misunderstood sliphers closing of his PR as a single-handedly decided rejection of the unmerged functionality.

While this problem could have been solved more peacefully with less drama, or been avoided by asking for clarifications. It revealed a undefined area in the handling of PRs.

illwieckz wrote new guideline that should prevent this misunderstandings in the future. 
https://wiki.unvanquished.net/wiki/Contributing/Merge#Closing_an_unmerged_pull_request_from_someone_else

If no one objects, i would say with that this issue would be resolved.

**Comment by sweet235** [comment]
> the misunderstanding was that slipher thought that his merged PR did cover all functionality of sweets PR and closed the lather.

No. My PR is very specifically about making the Advanced Granger bots climb as the dretch and mantis do it. Re-enabling navmeshes that perturbed had disabled was just a consequence (but is sensible even by itself). My PR is https://github.com/Unvanquished/Unvanquished/pull/2901, the title is quite clear about what it does.

After I caused some drama, we have new rules that do not allow this. But honestly: why would you ever close someone else's PR?

**Comment by sweet235** [comment]
Consequently, I left a team with some members that have the power to simply dismiss other members' contributions without consultation or discussion or vote or whatever.
