### ISSUE TITLE
Needs manual intervention for Chinese language support

### ISSUE THREAD

**Issue by NaitLee** [Unvanquished/Unvanquished#2938]
I’d like to contribute some variants of Chinese translation, but I’ve found some problems.

After analyzing I came up with fixes. Pick one of these:

## The easy way

We *need* specific Chinese variants, namely `zh_CN`, `zh_HK` and `zh_TW`, but Weblate platform doesn’t have these:
(As for why *need*… see explanations later)
![Screenshot_20240302_124913](https://github.com/Unvanquished/Unvanquished/assets/47078558/f99127de-35f4-439c-a9e3-a298125e1baf)
![Screenshot_20240302_125006](https://github.com/Unvanquished/Unvanquished/assets/47078558/305b53ba-91af-4bd1-89de-3d8d612f5bae)

In the mean while, weblate says:
> This list includes only basic languages. Please contact project maintainers to add others.

So if maintainers are able to add those variants manually (and I can access them) the problem is solved.

## The hard way

As shown in screenshots above, Weblate do has Chinese variants called `zh_Hans`, `zh_Hant_HK`, and `zh_Hant`.
They loosely corresponds to `zh_CN`, `zh_HK` and `zh_TW`.

But the *code* doesn’t allow us to use `zh_Han*` correctly.

To fix, we need to patch (or vendor) the tinygettext library:
- Add `zh_Han*` variants to [`language.cpp`](https://github.com/Unvanquished/Unvanquished/blob/ae89e2591c1bf52ab8311e1f9dd43efd6cf9b65c/libs/tinygettext/src/language.cpp#L281):
```cpp
  { "zh", "Hans",     nullptr, "Chinese (simplified)"        },
  { "zh", "Hant_HK",  nullptr, "Chinese (Hong Kong)"         },
  { "zh", "Hant",     nullptr, "Chinese (traditional)"       },
```
- Work out a way to let the helper function [`convertFilename2Language`](https://github.com/Unvanquished/Unvanquished/blob/ae89e2591c1bf52ab8311e1f9dd43efd6cf9b65c/libs/tinygettext/src/dictionary_manager.cpp#L269) to don’t capitalize so-called “country specification” in these cases (`zh_HANS` is wrong, and makes all [matches](https://github.com/Unvanquished/Unvanquished/blob/ae89e2591c1bf52ab8311e1f9dd43efd6cf9b65c/libs/tinygettext/src/dictionary_manager.cpp#L136) score the same, all variants will use a same `.po` file)
  - In my mind, matching after making both filename and contrycode lowercase should be ok

## The unofficial way

I could also keep Chinese translations by myself in a git repository as a community effort.
(see [one of my similar work](https://github.com/NaitLee/xon-zh-grand-l10n), quality guaranteed 😉)
For this case you can have a dedicated dpk for distribution, if that’s acceptable.

**Comment by sweet235** [comment]
> I could also keep Chinese translations by myself in a git repository as a community effort.

If you spend the time translating the game, we would rather include your translation in the official release.

We will contemplate which solution is the best.

**Comment by illwieckz** [comment]
If the language code names used b Weblate are standard, maybe the tinnygettext patch is a good idea (we may even upstream it).

**Comment by NaitLee** [comment]
They are standard, many international sites uses it too.

It reminds me that almost all operating systems use `zh_CN` ones, so complying `zh_Hans` ones adds a bit difficulty for language detection.

For this reason the easy way is still considerable, even if we are going to use this patch.

**Comment by NaitLee** [comment]
My last request for this would be to add the `zh_Hant_HK` translation manually on Weblate, since it can't created by me.

**Comment by illwieckz** [comment]
> My last request for this would be to add the `zh_Hant_HK` translation manually on Weblate, since it can't created by me.

https://hosted.weblate.org/projects/unvanquished/unvanquished/zh_Hant_HK/

**Comment by illwieckz** [comment]
> It reminds me that almost all operating systems use zh_CN ones, so complying zh_Hans ones adds a bit difficulty for language detection.

What would happen if a Linux system has `LANGUAGE=zh_CN` but we provide `zh_Hans` po file? Will the game display zh_Hans strings or english ones?

**Comment by NaitLee** [comment]
> Done: https://hosted.weblate.org/projects/unvanquished/unvanquished/zh_Hant_HK/

Thanks :)

> What would happen if a Linux system has `LANGUAGE=zh_CN` but we provide `zh_Hans` po file? Will the game display zh_Hans strings or english ones?

afaik unv can't detect the "country code" as for now, but it does detects the language. For this case, it will pick a `zh` variant that is matched first (all `zh_Han*` would score the same against `zh_CN`, all other language being zero)

If I'm going to implement contry detection I'd alias them and have a canonical one (and other languages can have alias too, e.g. `en_US` vs `en`, or vice versa). That's a different issue.

**Comment by illwieckz** [comment]
> afaik unv can't detect the "country code" as for now, but it does detects the language. For this case, it will pick a `zh` variant that is matched first (all `zh_Han*` would score the same against `zh_CN`, all other language being zero)

Ah yes I forgot about it.

> If I'm going to implement contry detection I'd alias them and have a canonical one (and other languages can have alias too, e.g. `en_US` vs `en`, or vice versa). That's a different issue.

Yes, that's definitely a different issue and is even dependent on another issue to be solved first as you pointed out.

So all is good for now (within our actual limitations). Great. 👍️
