### ISSUE TITLE
[suggestion] Fill bots only when there are real players on server?

### ISSUE THREAD

**Issue by NaitLee** [Unvanquished/Unvanquished#2943]
My points:
- A server with only bots gives no fun to people and strains server resource.
- The occupied cpu could used by other tasks of the server instead.
- A new player joining a match progressed by bots could be overwhelmed and probably leave the game.

Games like Xonotic does this, and additionally pauses timing etc.

**Comment by NaitLee** [comment]
For a real case, my server is like this overnight:
![image](https://github.com/Unvanquished/Unvanquished/assets/47078558/7ecde208-8159-45ec-b374-d12bd1bc644d)

**Comment by sweet235** [comment]
Try `/set g_autoPause on`.

**Comment by illwieckz** [comment]
Yes if I'm right `g_autoPause` is what you look for, but we have not enabled it by default yet because some time still pass while the game is paused, and then things like build points may be computed from the whole game time, not counting the paused time.

**Comment by NaitLee** [comment]
> Try `/set g_autoPause on`.

Thanks, I’d try later.

> Yes if I'm right `g_autoPause` is what you look for, but we have not enabled it by default yet because some time still pass while the game is paused, and then things like build points may be computed from the whole game time, not counting the paused time.

If that’s the case, I think I may set a time limit per round as for now. In the case of Xonotic, a half-way round continues timing, although bots are gone. Only fresh new round pauses timing for new players to join.

**Comment by NaitLee** [comment]
`/set g_autoPause on` works for saving resources.

As for timing problem, I see default server config also have `g_emptyTeamsSkipMapTime` set.

**Comment by DolceTriade** [comment]
Sounds like this can be closed?

**Comment by NaitLee** [comment]
Yes :)
