### ISSUE TITLE
Tiny "Loading" on loading screen

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#2953]
The world "Loading" is written in very small letters in the top left of the screen during map load. There is markup in `transition_loading.rml`:
```
 <title><translate>Loading</translate></title>
```
I assume that is responsible. This should be made larger and centered, or nuked.

**Comment by illwieckz** [comment]
Yeah, I don't know why it's there.

**Comment by DolceTriade** [comment]
It's there to show that the map is loading....
