### ISSUE TITLE
The `Shift+Escape` shortcut to open console doesn't work on `for-0.55.0/sync` branch

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2982]
For some unknown reason the `Shift+Escape` shortcut to open console doesn't work on `for-0.55.0/sync` branch, instead it cycles the main menu (like one would get by simply pressing the `Escape` key).

**Comment by illwieckz** [comment]
Another input problem happening with the `for-0.55.0/sync` branch is that sometime when alt-tabbing the game freezes for some time then the console prints hundreds of `Com_QueueEvent: overflow ` log lines.

**Comment by slipher** [comment]
Fixed by https://github.com/DaemonEngine/Daemon/pull/1134
