### ISSUE TITLE
Bots: missing check for "upward" navcons?

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#3002]
The `BotMaybeAttackWhileClimbing` function does an assertion that the last taken navcon should be "upward" (endpoint z coordinate >= start point z coordinate). However the function may be entered without any check that a navcon is active. BotMaybeAttackWhileClimbing is called only by BotClimbToGoal, which is called only by BotMoveUpward. If the bot is a Mantis, BotMoveUpward checks that a navcon is active before calling BotClimbToGoal. But if it is a Dretch, no such check is performed.

**Comment by sweet235** [comment]
I think I forgot to delete this assertion. In an earlier version, there was no wall climb activation. The mantis would try to leap to the higher place.

I guess we can simply delete it.
