### ISSUE TITLE
[0.55.0] When using say chat box, chatbox doesn't disappear after enter

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#3113]
On 0.54.1, when chatting, after pressing enter, the say box disappears. On 0.55.0RC1, the chatbox lingers. You need to press escape to remove this.

Suspicion is that the menu changes caused this. By default, we bind enter to something and that conflicts with the chatbox closing.

**Comment by DolceTriade** [comment]
Unbinding enter reverts to old behavior. This is problematic because enter is bound by default to something.

**Comment by slipher** [comment]
Fixed by https://github.com/DaemonEngine/Daemon/pull/1359.
