### ISSUE TITLE
[0.55RC2] Switching language in UI doesn't work

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#3115]
As a first step, I tried switching to French in the UI.

![image](https://github.com/user-attachments/assets/ec7fb21b-192e-4d8f-9796-2e908b77a03b)

While I could select the option in the list, clicking on the validation button didn't do anything (no feedback at all). Even restarting the game didn't register the change.

**Comment by necessarily-equal** [comment]
I think I actually have two problems here:
* [ ] clicking the "Change language" button doesn't do anything, it also doesn't set the `language` cvar (not sure if that's the right one)
* [ ] changing the `language` cvar manually, and restarting the game reverts back to "en_GB" which is my system locale.

**Comment by necessarily-equal** [comment]
Ok, so this does work, including across restarts

```
/language fr_FR
/updatelanguage
```

Then this is only an UI problem.

**Comment by slipher** [comment]
I managed to reproduce. It seems that the following conditions are required:
1. Upon starting, there is an archived value for `language` that is not in the list (so it says `Custom value (xxx)`).
2. You select a value in the list exactly once.

Doesn't happen without the custom value and it works if you click an option in the list a second time.

**Comment by necessarily-equal** [comment]
Thanks
