### ISSUE TITLE
The `r_materialSystem` cvar is not remembered

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#3120]
On my end when I build current `for-0.55.0-branch`, the `r_materialSystem` cvar is not remembered after I quit the game, it's always disabled at startup.

**Comment by DolceTriade** [comment]
I've noticed this for many cvars, like log supression.

**Comment by VReaperV** [comment]
Do we just need to mark them as `CVAR::ARCHIVE`?

**Comment by DolceTriade** [comment]
No, our system should automatically mark things as cvar archive when they are modified.

**Comment by slipher** [comment]
Fixed by https://github.com/DaemonEngine/Daemon/pull/1367.
