### ISSUE TITLE
Random package to load - crash

### ISSUE THREAD

**Issue by AWxxx** [Unvanquished/Unvanquished#3147]
Windows 11, UNV 0.55
1) Open game
2) Press Local/Lan ganem button
3) Choose random map
4) Put numeber 10 to "random package to load"
5) Crash + you cannot shutdown game
6) Extra window " Could not load extra pak 10."
7) Nothing you can do

**Comment by sweet235** [comment]
I get the same, but no crash.

**Comment by AWxxx** [comment]
"You really don't have any problems with crashes? My game always crashes. I assume that even if I put anything there, it "could crash", but a Windows system error will appear, which doesn't affect gameplay.

**Comment by sweet235** [comment]
> You really don't have any problems with crashes?

Not in this case, on Linux. Of course we are used to the occasional crash during development.

**Comment by slipher** [comment]
We display the same sort of error dialog on "real crashes" like segfaults, and other errors like a missing package. You guys are probably seeing the same thing and just using different terminology.

**Comment by AWxxx** [comment]
> We display the same sort of error dialog on "real crashes" like segfaults, and other errors like a missing package. You guys are probably seeing the same thing and just using different terminology.
I agree its like error blocking entire game. Windows 11.
![image](https://github.com/user-attachments/assets/1647e160-a1b4-4387-8eb6-5948012e2954)

**Comment by slipher** [comment]
Fixed by #3153
