### ISSUE TITLE
The "extra packages to load" input field for LAN games influences connecting to online servers

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#3151]
I noticed this wile reading https://github.com/Unvanquished/Unvanquished/issues/3147. Enter `10` as extra package to load, do not start a LAN game, close the dialog instead. Try to connect to any online server. You get the error message that package `10` cannot be loaded.

**Comment by slipher** [comment]
Maybe `fs_extrapaks` shouldn't be in the UI.

**Comment by DolceTriade** [comment]
Maybe we should clear fs_extrapaks before connecting to a server. We need to clear a lot of cvars before connecting. For example, the download bug: https://github.com/Unvanquished/Unvanquished/issues/3114
