### ISSUE TITLE
Windows Reinstallation

### ISSUE THREAD

**Issue by AWxxx** [Unvanquished/Unvanquished#3159]
I manually removed UNV from my PC since I couldn’t find an option in Windows 11 to uninstall it automatically. UNV doesn’t appear in Control Panel > Programs and Features, so there’s no direct way to remove the game there. Now, when I try to reinstall the game, I get the following error:
![UNV](https://github.com/user-attachments/assets/83d30235-b1ba-47d0-97a2-1d229801a31f)

**Comment by slipher** [comment]
We are aware of this problem: https://github.com/Unvanquished/updater/issues/136

What you can do to fix it now is click the gear icon in the upper right corner of the small window that appears when the launcher starts. Then you can reinstall.

**Comment by sweet235** [comment]
Someone said that, in order to fix this, you need to delete:

- the `Unvanquished` directory in `Program Files`
- and the `Unvanquished` directory in `Documents\My Games`

Sadly, I cannot test this right now.

**Comment by VReaperV** [comment]
> Someone said that, in order to fix this, you need to delete:
> 
> * the `Unvanquished` directory in `Program Files`
> * and the `Unvanquished` directory in `Documents\My Games`
> 
> Sadly, I cannot test this right now.

You'd need to delete some registry entries too. The problem is that it thinks the daemon executable is there when it's actually not.

**Comment by AWxxx** [comment]
> We are aware of this problem: [Unvanquished/updater#136](https://github.com/Unvanquished/updater/issues/136)
> 
> What you can do to fix it now is click the gear icon in the upper right corner of the small window that appears when the launcher starts. Then you can reinstall.

Works. Thanks!
