### ISSUE TITLE
Shotgun and SMG, no sound effect when reloading

### ISSUE THREAD

**Issue by AWxxx** [Unvanquished/Unvanquished#3175]
Shoutgun and smg have no sound effect when reloading gun.

**Comment by slipher** [comment]
Is there *any* gun that has a reloading sound?

**Comment by VReaperV** [comment]
I don't think so.

**Comment by DolceTriade** [comment]
But certainly something we should add

**Comment by Gireen** [comment]
duplicate of #1164
