### ISSUE TITLE
An exit message is printed in-between maps.

### ISSUE THREAD

**Issue by Sixthly** [Unvanquished/Unvanquished#318]
At the end of the game an exit message is sent to all clients, as expected. However, a second, incorrect exit message is sent to all clients when the server is changing maps

For example, a draw vote passes and the game finishes, the following message is (correctly) printed:
> Evacuation ordered

However, when the map is unloaded and a new one is loaded, the server unnecessarily spits out another message:
> Humans win

The expected result is only one exit message. Find out what is causing the second exit message and remove it.

**Comment by Amanieu** [comment]
I just tested this and the message is only printed once (I am manually triggering wins with /alienWin and /humanWin). Can anyone reproduce this issue?

**Comment by Viech** [comment]
No input for over a month, closing.
