### ISSUE TITLE
Opening a circle menu doesn't focus and select a button

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#341]
When a circle menu opens, the cursor isn't centered on any button (it should be centered on the big button in the middle). Even if the cursor happens to spawn on top of a button, the button isn't selected and can't be used before the mouse hasn't been moved.

Furthermore, right-clicking anywhere and potentially also left-clicking on non-interactable space should close the menu.

**Comment by slipher** [comment]
The big button in the middle is now centered under the mouse cursor.

**Comment by illwieckz** [comment]
Maybe that removes the need for focusing a button we would have to determine (at least, close is focused).

**Comment by bmorel** [comment]
As said, starting position is now fixed, and it is no longer necessary to move cursor to be able to do something (clicking cancels, since it's on that button).
