### ISSUE TITLE
"when unpowered/destroyed" shader directives don't work with telenode

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#353]
The shader directive that changes the shader of a buildable model while the buildable is unpowered or about to explode works with the drill and the new armoury (both iqm models), but doesn't seem to work with the telenode (an md5 model). When destroyed, the glow map would still be active.
### Telenode shader

```
models/buildables/telenode/telenode_dead
{
    diffuseMap  models/buildables/telenode/telenode_d
    normalMap   models/buildables/telenode/telenode_n
    specularMap models/buildables/telenode/telenode_spec
}

models/buildables/telenode/telenode_full
{
    diffuseMap  models/buildables/telenode/telenode_d
    normalMap   models/buildables/telenode/telenode_n
    specularMap models/buildables/telenode/telenode_spec
    glowMap     models/buildables/telenode/telenode_glow

    when unpowered models/buildables/telenode/telenode_dead
    when destroyed models/buildables/telenode/telenode_dead
}
```
### Drill shader

```
models/buildables/drill/drill_dead
{
    diffuseMap  models/buildables/drill/drill_d
    normalMap   models/buildables/drill/drill_n
    specularMap models/buildables/drill/drill_s
}

models/buildables/drill/drill
{
    diffuseMap  models/buildables/drill/drill_d
    normalMap   models/buildables/drill/drill_n
    specularMap models/buildables/drill/drill_s
    {
        map models/buildables/drill/drill_a
        blend add
        rgbGen wave inversesawtooth 0.3 0.8 0.0 0.5
    }

    when unpowered models/buildables/drill/drill_dead
    when destroyed models/buildables/drill/drill_dead
}
```

**Comment by Viech** [comment]
> Is this still true?

I don't know. Probably.

> How to reproduce?

Destroy a Telenode. Its lights are supposed to go out.

**Comment by bmorel** [comment]
Then I confirm it's still true (I never noticed those lateral lights btw).

**Comment by bmorel** [comment]
It seems this has been fixed in current master (running on nightly):

![2022-07-16-021406_1366x768_scrot](https://user-images.githubusercontent.com/1316300/179326604-fa6a6500-68bf-4030-a3cf-6908637312c2.png)
![2022-07-16-021421_1366x768_scrot](https://user-images.githubusercontent.com/1316300/179326607-4091a557-e5aa-4728-b5ed-f37b5033ceb0.png)
