### ISSUE TITLE
libRocket menus catch the mouse cursor, even in window mode

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#358]
I'm on Linux, X11 window system, i3 window manager.

This issue is especially frustrating in the main menu, where keeping the cursor inside the window borders has no practical use. I'd argue that even in a running match the cursor should not be prevented from leaving the Unvanquished non-fullscreen window whenever a menu is open, as was possible before the move to libRocket.

In i3, switching to another desktop with a key combination frees the cursor.

**Comment by Veyrdite** [comment]
Fixed somewhere in alpha 45 (maybe 2f27aac or 1f7b22e ?)
