### ISSUE TITLE
Optimize PostFX

### ISSUE THREAD

**Issue by Kangz** [Unvanquished/Unvanquished#361]
Rendering post processing effects usually necessitates taking the current FBO as an input texture. Our engine is being really stupid in that it renders to the default framebuffer, blits the framebuffer in a texture and renders the postFX in the default FB again (IIRC same thing for heat haze). We are doing a lot unnecessary blits here, what should happen is that we ping pong between two FBOs and in the last PostFX pass render to the default FB.

The only advantage of the current method is that MSAA is resolved for us automatically in the first blit (but postFX) and we would need to resolve it explicitely when using our own FBOs (maybe?)
- Mentor: Kangz (gimhael, Fuma?)
- Knowledge: OpenGL
- Difficulty: 6

[Mentored projects on the Unv wiki](http://unvnet.net/wiki/index.php/Mentored_Coding_Project)

**Comment by illwieckz** [comment]
@Kangz, I experimented with sRGB framebuffers recently and did not managed to get something right, do you think it can be related to this useless ping-pong with frame-buffers?

**Comment by illwieckz** [comment]
The link is now: https://wiki.unvanquished.net/wiki/Mentored_Coding_Project

**Comment by illwieckz** [comment]
> The only advantage of the current method is that MSAA is resolved for us automatically in the first blit (but postFX) and we would need to resolve it explicitely when using our own FBOs (maybe?)

We don't have a working MSAA anymore anyway.

**Comment by bmorel** [comment]
so, what should we do?

**Comment by slipher** [comment]
Looks like this was done. Heat haze, motion blur, and FXAA ping-pong between the two FBOs of `tr.mainFBO` as described. And the cameraEffects shader outputs to the default frame buffer, also as described.
