### ISSUE TITLE
Playernames in score-screen flicker

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#371]
- Start/join a game
- Hold down TAB
- Observe that playernames in the list flicker every now and then (upon update)?

**Comment by neumond** [comment]
Not sure can I close this bug. Small lists don't flicker anymore. But big lists flicker near the end, while the rest of rows behave perfect.

**Comment by DolceTriade** [comment]
At the end? Like the bottom or at the end of the update?

**Comment by neumond** [comment]
Yeah, bottom of both lists.

**Comment by bmorel** [comment]
I do not see any flickering in there, are there examples of lists in which there is still flickering?

**Comment by bmorel** [comment]
Pinging this. If no answer next time I see it (and in more than few days, obviously), I think I'll close it, since there was no input on this since 6 years.
