### ISSUE TITLE
Errant spaces in inline styles cause error messages

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#377]
This error message:
`WARNING: Invalid property declaration at :0`
Is caused by having an errant space after inline style definitions.  Eg

```
<infopiece style="text-align: right; width: 7em; ">  ----- Bad
<infopiece style="text-align: right; width: 7em;">   ----- Good
```

**Comment by Viech** [comment]
In addition to the bug, the error message doesn't even yield that it's about the UI.

**Comment by DolceTriade** [comment]
Error message is from librocket D:

**Comment by Viech** [comment]
And how does that message appear on our console? :stuck_out_tongue:

**Comment by DolceTriade** [comment]
We give librocket an interface to print messages, but I don't actively monitor them.I guess I can not print INFO messages.

**Comment by Viech** [comment]
We should give it a special interface that prepends information, in particular the bit that the message is generated by librocket. After nacl-cgame and the librocket move there should be a more powerful debug interface for this, too.

**Comment by bmorel** [comment]
Need to check about this in 0.53, since libRocket will no longer be used.

**Comment by slipher** [comment]
Doesn't happen in RmlUi.
