### ISSUE TITLE
/me command no longer works

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#391]

**Comment by Kangz** [comment]
So it seems there are many different say commands for admin, area, vsay, team say and many combinations of them and /me is like another flag except you put it at the front of the message. So I'm thinking of regrouping all of that under a /chat commands that can take a number of flags then a message. Aliases would be defined to keep the regular /say /say_team etc.

This would help simplify logic on the server, and the client too.

**Comment by Kangz** [comment]
I want with the simple fix because I got lazy when I realizd I would need to add support for binary messages.
