### ISSUE TITLE
UI: player-name colour reset ^* turns colour to red

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#397]
Expected behavior: stop changing colours, go back to parent style, etc

**Comment by mbasaglia** [comment]
Does this still happen after the color refactor?

**Comment by harmonise** [comment]
I can confirm that ^* acts like ^8 (white) under Alpha 45. Both in setting player name and in player chat.

**Comment by Kangz** [comment]
Sounds like it has been fixed.

**Comment by harmonise** [comment]
I should clarify that it is not acting as a reset character but as ^7 (white). In some contexts (EG talking ingame) the 'default/parent' colour should be green not white.

Unless this is intended behaviour I think we should re-open.

**Comment by DolceTriade** [comment]
Note that it will probably default to the CSS color of the text element and not the starting color. Personally, I'm a fan of using CSS as the final say, but that might be less intuitive for others.

**Comment by Viech** [comment]
The starting color needs to be set via CSS then.
