### ISSUE TITLE
Armoury model is culled while still in sight

### ISSUE THREAD

**Issue by MZ-Alex** [Unvanquished/Unvanquished#401]
the new armory in 0.30 release dissapears when seen from certain angle:

here's 2 screens, before and after dissapearing.
http://imgur.com/aeZcD8n,Ptdnl6g

this was tested on universal zip on Windows 7 64 bits  Intel + ATI 4670 GPU

**Comment by DolceTriade** [comment]
Still happen?

**Comment by Viech** [comment]
I'm not able to reproduce on current master.
