### ISSUE TITLE
Alien HUD displayed briefly on respawn screen

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#408]
After dying or joining the human or alien team, CG_OnPlayerWeaponChange is called, where the weapon has a value of 1. This causes the alien HUD to be displayed for a moment. Shortly afterward the weapon changes back to 0. It can be easily seen by adding a breakpoint in the aforementioned function.
![alienclawswhiledead](https://cloud.githubusercontent.com/assets/7809431/3925126/a8e50cc2-23e4-11e4-91a2-e622e47aadee.png)

**Comment by Viech** [comment]
Haven't seen this in a while, does it still happen?

**Comment by DolceTriade** [comment]
Haven't seen in a while. Re-open if it appears again.
