### ISSUE TITLE
Disappearing weapon models

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#409]
The human first-player weapon models randomly disappear. They stay gone until you change weapon.
Me holding a shotgun:
![unvanquished_2014-08-14_155845_000](https://cloud.githubusercontent.com/assets/7809431/3925991/72a4c6b2-23ed-11e4-88d8-9191f5ad5b2b.png)

**Comment by enneract** [comment]
Weapon inertia was reimplemented, so the bug should be fixed.

**Comment by illwieckz** [comment]
Pulse still has a problem.

Though, Viech said this:

> It doesn't happen for me, except with the weapons that have a bogus rendering bounding box (e.g. the pulse rifle) which makes them disappear depending on the animation and probably the field of view. Never continuously though.

**Comment by illwieckz** [comment]
Pulse rifle is tracked in #1393.
