### ISSUE TITLE
Soften all (close/big/relevant/…) particles automatically

### ISSUE THREAD

**Issue by Kangz** [Unvanquished/Unvanquished#415]
Particles with hard clipping on walls are ugly, fix this.

http://blog.wolfire.com/2010/04/Soft-Particles

**Comment by Viech** [comment]
From what I know @gimhael is already working on this.

**Comment by Viech** [comment]
This is implemented render-wise now but it seems that the particle shaders need to be updated. Please read the [forum thread](https://forums.unvanquished.net/viewtopic.php?f=4&t=1807) that reports the issue.

**Comment by bmorel** [comment]
Was this fixed since then?

**Comment by slipher** [comment]
Automatic fading for all particles (other than ones that don't use alpha blending, where a depth fade is calculated but has no effect) was implemented back in 2015. In retrospect, it may have been a bad idea: many weapon hit effects became completely invisible when viewed straight on. Now I am reverting it and adjusting all the shaders manually :) https://github.com/DaemonEngine/Daemon/pull/1281
