### ISSUE TITLE
Tesla Animation Broken

### ISSUE THREAD

**Issue by MZ-Alex** [Unvanquished/Unvanquished#450]
Unvanquished 0.31.0 on Windows 7 64bits:

http://snag.gy/IXqSG.jpg

Tesla animation don't play, and look as if they were unpowered... it actually plays randomly for a couple of seconds (random amount of seconds) then stops for a random time, and plays again later... but most of the time they look unpowered as in the screenshot.

**Comment by DolceTriade** [comment]
Tesla removed. Thanks lamefun for pointing this out.
