### ISSUE TITLE
"CM_InlineModel: bad number" when joining a team on plat23 locally

### ISSUE THREAD

**Issue by MZ-Alex** [Unvanquished/Unvanquished#460]
platform: windows 7 64 bits - ATI 4670
release: unvanquished 0.23

I delete my profile (%mydocuments%\my games\unvanquished)
/map plat23
join any team and the following error appears:
![unvanquished_2014-10-12_181150_000](https://cloud.githubusercontent.com/assets/8269820/4607593/ae2b863a-5255-11e4-8bbf-56505d365d12.jpg)

**Comment by Viech** [comment]
So, close this? Or can anyone still reproduce?

**Comment by DolceTriade** [comment]
Yeah, these commits were the cause and the revert was intrtoduced in alpha 34.
