### ISSUE TITLE
Create a multiplatform launcher/auto-updater

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#461]
We want an open source, standalone, multi-platform launcher that keeps track of the game version and updates it iteratively via the torrent protocol.

In short, the idea is to present to the torrent library the old game files as an incomplete/corrupted copy of the new game files. The torrent protocol will then "fix" the data, resulting in an iterative upgrade to the new version, integrity check included. This has proven to work using the aria2 CLI torrent client; See the [download-pk3-torrent.sh](https://github.com/Unvanquished/Unvanquished/blob/master/download-pk3-torrent.sh) script for a shell version of the requested mechanics. The torrent distribution network is already up and running and has been powering the Arch Linux packages for some months now.

In addition to the core update functionality, the launcher needs a nice interface with a minimal set of user-friendly and unobtrusive settings (where to install, download speed limit, etc. – potentially in a seperate window the user can toggle) while an "advanced" section for people familiar with the torrent protocol may be added but hidden by default to avoid any determent from changing the basic configuration. The stretch-goal is a basic web widget, RSS reader or the like that lets us provide patch notes and other information to the user.

Always keep in mind that the launcher needs to suit the needs of people who just want to "download that launcher executable and run it to launch the game", without reading up on anything. If you played an auto-updating online game before it is likely that you saw a good example of this.

I will follow the development process and answer any design or technical questions you may have.

**Comment by DolceTriade** [comment]
Discussion for this should continue here.

https://github.com/Unvanquished/updater
