### ISSUE TITLE
Surfaces not drawn on intel graphics

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#465]
Key | Value
----|------
Operating System | GNU/Linux
Kernel | Linux 3.16.4-1-ARCH
Architecture | x86_64
Processor |  Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
GPU |                        Intel 3rd Gen Core processor Graphics Controller

On v0.32.0 and current master of 5a219bc, some surfaces are not drawn on Intel HD driven by Mesa 10.3.1:

![Screenshot](http://i.imgur.com/aaKQ9I9.jpg)

![Screenshot](http://i.imgur.com/Y3tJSUK.jpg)

A similiar issue seems to be #445. Pinging @gimhael to have a look.

**Comment by DolceTriade** [comment]
Fix is comitted. http://cgit.freedesktop.org/mesa/mesa/commit/?id=c633528cbac007a73a066f269b3c9a25daf1e21a

**Comment by Viech** [comment]
For reference as I keep looking at this issue, Mesa 10.3.* and 10.4.0 are affected, 10.2.* and 10.5.* are not. Unsure about 10.4.n for n > 0.
