### ISSUE TITLE
Not enough room to evolve!

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#480]
When you're trying to evolve and you keep getting the message that there's not enough room because you're standing near a wall in a large open area, so you jump away and try again and now you're near a booster and so you get the message again.

It's like trying to herd a bunch of cats around in an orderly fashion after they've eaten catnip laced LSD shrooms.

Can we just agree that if there's enough room to evolve, IE, you're not stuck in a little pipe or something, then you evo and your body gently gets pushed away from the wall or obstacle?

Thanks!

**Comment by Amanieu** [comment]
How about simply delaying evolution until enough room is available? A warning should be shown on the screen, and every frame the game will check if enough room is available.

**Comment by overvolting** [comment]
Amanieu that might actually make a good improvement.

**Comment by Veyrdite** [comment]
+1 for Amanieu's idea.
