### ISSUE TITLE
recursive error 'program tried to execute code outside VM' after: R_SetupLightView: Bad rlType

### ISSUE THREAD

**Issue by guillaume-uH57J9** [Unvanquished/Unvanquished#483]
Hello,

unvanquished 0.33 produces the following error when joining a game
> recursive error 'program tried to execute code outside VM' after: R_SetupLightView: Bad rlType. See "/home/guillaume/.unvanquished/crashlog.txt" for details.

crashlog.txt available at http://pastebin.com/rKqYFWkS

**Comment by Viech** [comment]
@Kangz commit or reason for closing?

**Comment by Kangz** [comment]
Was a duplicate of #497 no?

**Comment by illwieckz** [comment]
yes I can't reproduce.

**Comment by Kangz** [comment]
Thanks for confirming :)
