### ISSUE TITLE
explosions in your face instead of where they should be

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#485]
Sometimes you snipe a turret or other object and run into another room and the explosion graphic appears right in front of you.

**Comment by bmorel** [comment]
The video has likely been lost since (I can't access it). Did anyone seen that in the recent versions (0.50 and newer)? I certainly never seen what is described here.

**Comment by necessarily-equal** [comment]
I've never seen this issue. I think it most likely has been fixed one day. Please reopen or comment here if you notice it.
