### ISSUE TITLE
Reactor doesn't zap alien standing right next to it.

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#487]
Hrmm was sitting there eating my spawns and turrets RIGHT NEXT to the reactor and not one zap went off. Not sure if it's because reactor can't zap through buildings.

**Comment by Viech** [comment]
Yes, it can't zap through buildings, which is intended. I don't think there is a bug that would prevent zaps from working as long as there is a clear line of sight. If you think there is, please reopen with a screenshot or demo.
