### ISSUE TITLE
Alpha 35 Assets

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#495]
Tick these off when a properly versioned pk3 download link exists and post that link as a comment. Mark this closed when all assets found their way into the release (assignee). Edit this issue description to add more required assets if allowed, otherwise post your wishes (or complete packages) in a comment. Don't post assets here that require additional modeling, animation or implementation work, this is just a checklist so we don't forget to include stuff that is either ready or trivial to create (e.g. icons).

- [x] ej01 texture packages (crunched)
- [x] Updated tex-all package that loads the ej01 textures
- [x] Forlorn Alpha 10
- [x] Parpax Delta 4
- [x] Mantis arms
- [x] Marauder arms
- [x] Improved Turret
- [x] Rocket Pod

**Comment by Viech** [comment]
EmperorJack doesn't want to release a Forlorn update yet but his texture packages are crunched and ready for shipping, as is the new `tex-all` package. All of them can be found [here](http://files.viech.name/assets/for-0.35.0/).

**Comment by Viech** [comment]
Grab everything from [here](http://files.viech.name/assets/for-0.35.0/).

**Comment by DolceTriade** [comment]
http://unvanquished.net/~modi/mara_2015-01-04-0247.pk3
http://unvanquished.net/~modi/mantis-arms_2015-01-04-0247.pk3
