### ISSUE TITLE
warped battlesuit+chainsaw combinations leading to cgame numBones spam

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#503]
"Playing" on chasm on the dev server with the tty client on current master of c5bb4b5 during the dev game gave me a continuous stream of `[skipnotify]WARNING: cent->pe.legs.skeleton.numBones != cent->pe.torso.skeleton.numBones` spam.

**Comment by Amanieu** [comment]
If this only occurs in the tty client then I suspect it is an issue with the null_renderer.cpp interface. Some fields must not be defined correctly.

**Comment by Kangz** [comment]
I was not expectig to close this, @Viech I was not able to repro but if you use the tty client in the next dev games can you tell me if it worked?

**Comment by Viech** [comment]
I'll check and report back.

**Comment by Viech** [comment]
Couldn't reproduce it so far, will re-open in case it happens again.

**Comment by t4im** [comment]
This is not limited to TTY clients, but the messages are only printed to debug builds of cgames (which might have only applied to your tty client). However the more pressing issue is likely the affected model being warped.
In particular battlesuits while using saws seem to trigger this issue at the moment.

**Comment by illwieckz** [comment]
dat bug!

can it be related to 7870f49 (_bsuit: Horrible hack to stop gun clipping_) ?

**Comment by illwieckz** [comment]
it looks like the bug only occurs when the painsaw is firing.

**Comment by slipher** [comment]
Fixed by #1105.
