### ISSUE TITLE
The web server list does not handle extended color code

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#510]
Hi, the [web server list](http://unvanquished.net/servers) does not handle the reset color code as described on the [wiki page about color codes](http://wiki.unvanquished.net/index.php?title=Colours)  (`^*`). This is not the code is misinterpreted, it is not interpreted at all, the code is printed as-is.

For demonstration purpose, I've written this reset code on my server name so you can see it yourself on the list: http://unvanquished.net/servers

**Comment by illwieckz** [comment]
You can see the uninterpreted `^*` in this screenshot:
![web server list](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished.net_20150107%20010630_001.png)

**Comment by illwieckz** [comment]
Same problem with the `^<` green advanced color code, as we can see on the “Public - ITA” server name displayed “Public - ^<ITA”. It's probably a generic problem about advanced color codes.

**Comment by Veyrdite** [comment]
Is this still an issue?  I believe colour code has been touched in the last couple of releases.

**Comment by mbasaglia** [comment]
Now the page listing servers is this: https://www.unvanquished.net/?page_id=340
I think that page is generated by some external tool that talks to the master server, it will definitely need to be extended to include the new color codes.

Does anyone know what is being used by that page? I can fix it myself if needed

**Comment by Viech** [comment]
@dsalt made this and it seems to be using resorces from his server `moreofthesa.me.uk`…

**Comment by mbasaglia** [comment]
Now tat page uses this wordpress plugin: https://github.com/mbasaglia/Xonpress
