### ISSUE TITLE
/map command fails with "the pipe has been ended"

### ISSUE THREAD

**Issue by MZ-Alex** [Unvanquished/Unvanquished#513]
Unvanquished 0.35.1 
windows 7 64bits ATI Radeon 4670 

I launch daemon, type /map yocto (or any other map) and I get this:
http://snag.gy/JTOos.jpg

**Comment by Viech** [comment]
Try to add `+reset vm_cgame +reset vm.game.type` to your `unvanquished`/`daemon` command line. Also, make sure to update to `0.35.1`.

**Comment by MZ-Alex** [comment]
I just tried, but I get the same result

**Comment by Viech** [comment]
Please make sure `listPaths` shows `unvanquished_0.35.1` in addition to all older packages. Then you can try to append `+set vm.game.type n`, where n is `2`, `4` and `5`. If one value works for you, please let us know which one. You can then store it to configuration by replacing `+set` with `+seta`.

**Comment by MZ-Alex** [comment]
mode 0, and 5 gives the same error
mode 2 gives: VM: Could not create child process: The system cannot find the file specified
mode 4: works just fine.. using this from now on

does this happen to everyone? or just windows users? or just me? :P

**Comment by Viech** [comment]
It could happen to every windows user, we need more input from other users to find out. Pinging @Kangz and @Amanieu to take over this issue.

Do you compile from source or do you use the multi-platform package?

We recently changed the default value of `vm.game.type` from `2` to `0`. It's odd that `2` doesn't work either.

**Comment by Kangz** [comment]
It seems that 2 doesn't work because we did not ship game-native-exe. 0 and 5 not working is a big problem, I'll investigate.

**Comment by MZ-Alex** [comment]
I did download from universal zip package

**Comment by Amanieu** [comment]
Try running with vm.game.type 0 and vm.game.debugLoader 1. This should produce a game.sel_ldr.log file in your homepath which should contain more details about what went wrong.

**Comment by MZ-Alex** [comment]
Amanieu, here it is:

[13620,6652:10:45:15.521000] NaClHostDescOpen: CreateFileA(path=C:\Program Files (x86)\unvanquished/irt_core-x86_64.nexe, desired_access=0xa0000000, share_mode=ALL, security_attributes=NULL, creation_disposition=3, flags_and_attributes=16777217, template_file=NULL)
sel_main: No error
sel_ldr argument list:
C:\Program Files (x86)\unvanquished/sel_ldr64.exe -v -B C:\Program Files (x86)\unvanquished/irt_core-x86_64.nexe -e -i 100:1180 -- C:\Users\Alex\Documents\My Games\Unvanquished/game-x86_64.nexe 100
Cannot open "C:\Program Files (x86)\unvanquished/irt_core-x86_64.nexe".

**Comment by Amanieu** [comment]
Does C:\Program Files (x86)\unvanquished/irt_core-x86_64.nexe exist?

**Comment by MZ-Alex** [comment]
nope, it's missing.

**Comment by Amanieu** [comment]
Well that's an issue with the packaging. In the meantime, you can grab a copy of it from the linux package.

**Comment by MZ-Alex** [comment]
Found the irt_core-x86_64.nexe in the universal zip inside linux64.tar.xz
copied it from there, and now it loads maps with vm.game.type 0

**Comment by Viech** [comment]
@DolceTriade please provide and advertise a hotfix (or hotfix release) for Windows users. This should affect up to 50% of our user base and is really urgent.

**Comment by Viech** [comment]
A workaround has been posted in the release article.
