### ISSUE TITLE
Some kill messages have an invalid source or target.

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#516]
Hi, you may have noticed, sometimes the rocket that kills aliens are named "noname" with a green bullet, as in this screenshot:

![killed by noname](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-10_042322_001.png).

> ●[BOT] Morgan was killed by ●noname

But I see something similar on the “Battle Mod Server”, a human bot was identified with green bullet and without name when it was killed:

![noname was barbed](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-11_141534_000.png)

> ● was barbed by ●Alien3's Dragoon; ●Alien2 assisted

**Comment by Viech** [comment]
I can confirm this and it has been around for a while. I can also confirm that it happens more frequently with the rocket pod. Not sure what causes this though (but didn't look into it either).

**Comment by illwieckz** [comment]
It seems to happen when many events happen at the same time.

Multiple rockets pods launch multiple rockets at the same time, and one alien can be killed by multiple rocket at the same time.

Also, the “Battle Mod Server” is a kind of “Last Man Standing” mod, and many bots spawn as Advanced Dragoon or Tyrant or Battlesuit directly, it's common to see 6 alien bots on the same human bot or two human bots killed at the same time by the same aliens, it's common to see multiple bots killed at the same time by the same bots.

Perhaps something fools the “who is who” system when there are lots of similar events at the same time.

**Comment by Viech** [comment]
As the gamelogic is currently not concurrent at all, the killer is always clearly defined, even if two sources would deal lethal damage in the same server frame. One of the attacks would just not have a living target and fail.

**Comment by illwieckz** [comment]
I don't know if it's related, but during dev game I see that:

![Server command overflow](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-11_225151_002.png)

> `<username> Server command overflow`

**Comment by illwieckz** [comment]
Just to answer myself: “_<username> Server command overflow_” means “_player timeout_”, so it's not related to the other bugs above, this one is just a language issue.

**Comment by Viech** [comment]
I'll just assume the entire issue was fixed in ebb7012, reopen if this happens again.
