### ISSUE TITLE
The web server list does not give correct player info

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#519]
See this screenshot:

![player list](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished.net_20150107%20010630_001.png)

The web page list 3 players on my server, but only 1 human, 1 alien, and 0 spectator, so 2 players.

**Comment by cu-kai** [comment]
The server list has since been updated/replaced. Have you noticed any other issues with the current list? If not, can this be closed?
