### ISSUE TITLE
Switching window (alt+tab) while a map is loading does not release the mouse pointer

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#520]
When you try to switch window with <alt+tab> while a map is loading, the window is switched, but the mouse pointer remains captured.

I noticed this bug on X11/Linux, I don't know if other systems have this bug too.

**Comment by illwieckz** [comment]
Now I have the opposite problem: the pointer is so free that clicks while map is loading are transmitted to the windows below. XD

**Comment by DolceTriade** [comment]
Cannot reproduce.

**Comment by Viech** [comment]
@illwieckz do you use fullscreen or window mode? Can you provide more info about your setup, e.g. your window manager and the way that you switch windows?

**Comment by illwieckz** [comment]
I think it was fullscreen, it was on Ubuntu 14.10 with radeonsi driver.

For the moment I can't run the current build so I can't test to reproduce it.

**Comment by DolceTriade** [comment]
We may have fixed the bug. Could you try again?

**Comment by illwieckz** [comment]
I will try for sure when a new release will not freeze my graphic driver (I know this another bug is already handled, this is why I have not reported it here). :stuck_out_tongue_winking_eye:

**Comment by Veyrdite** [comment]
Mouse is definitely no longer captured during map loading.
I cannot reproduce the mouse click pass-through (dual-monitor, i3, open-source ATI, r_fullscreen 0 or 1)

Please re-open and comment if this comes up again/you can reproduce.
