### ISSUE TITLE
Allow filling up a team with bots dynamically.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#522]
Currently, bots need to be added and removed indivudally and manually. This can stay as an option for development, but for production, bots should be added and removed dynamically by the server, so that they guarantee a minimum player count per team. The command could be `bot fill <team> <minPlayers>`. Bots added manually shouldn't be affected by the fill logic.

When working on this, there are quite a few more things that could be cleaned up. For example, bots as spectators don't make any sense at all, yet this is possible and there is even a `spectatebots` vote. Please also read #492.

This feature is crucial for regular server administration and is thus a Beta requirement.

**Comment by illwieckz** [comment]
As said on IRC, the syntax `bot fill <num> [team]` is also a good idea, filling both teams by default.

Setting explicit team will be useful for tutorials for example.

**Comment by slipher** [comment]
Completed by #981.
