### ISSUE TITLE
Mouse doesn't work with XWayland

### ISSUE THREAD

**Issue by guillaume-uH57J9** [Unvanquished/Unvanquished#530]
Hi, 
I gave Unvanquished a try with XWayland and found a notable issue: the mouse does not work.

The pointer is not visible, and the mouse seem completely inactive so it's no possible to use the menu, or join a game from the GUI. 
While it's possible to join a game with the CLI, once in-game the mouse still does not work. The player immediately looks straight down (-90°) and rotates on itself.

Otherwise, the game is able start on XWayland, the engine works and seem to render correctly at 40Hz on an integrated Intel GPU. 

Guillaume

**Comment by illwieckz** [comment]
We did some deep rework of the mouse, so maybe this issue is completely obsolete, it must have to be checked again.

**Comment by necessarily-equal** [comment]
Also, XWayland got a long way since the day it could not capture pointer devices. I think this is now fixed.

**Comment by necessarily-equal** [comment]
See also: https://github.com/DaemonEngine/Daemon/issues/482
