### ISSUE TITLE
Recover from "AL lib: (EE) stream_state_callback2: Received stream failure!" (soundcard temporary unavailable)

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#534]
Hi, sometimes I lost sound while I play to Unvanquished and I must restart Unvanquished to have the sound again. I just got the bug right now with some debug output activated and I got this message:

```
AL lib: (EE) stream_state_callback2: Received stream failure!
```

I think the real cause is on the hardware side (and in fact, on the AC side which is not stable these days and my soundcard seems to not like that), but it will be nice if Unvanquished knows how to recover from an event like this kind of temporary unavailability.

In fact, If I manually unplug and replug my soundcard, I get the same error message, and Unvanquished don't try to reopen the audio channel after a temporary failure.

So, it's seems to not be a bug in Unvanquished, in a perfect world, this kind of event never happens, but it could be very nice if Unvanquished knows to recover from this kind of error.

So this issue is more a feature request than a bug report.

**Comment by Kangz** [comment]
Does snd_restart fix the audio when that happens? IIRC it reopens an OpenAL device.

**Comment by illwieckz** [comment]
Yes, `snd_restart` fixes the audio when that happens, but it reload the whole map if you are playing (like `vid_restart`).

I noticed that if I lost sound while I am on the main menu with background music, using `snd_restart` restores the sound (since if I load a map next, sound is here) but the background music never return. So, on main menu screen, `snd_restart` reopens the OpenAL device but does not restart the background music playing. If I do `snd_restart` then `vid_restart` on the main menu screen, background music restart: `snd_restart` reopens the OpenAL device and `vid_restart` restarts the background music.

On map, only `snd_restart` is sufficient to restore sound.

**Comment by illwieckz** [comment]
FYI, if Unvanquished shutdowns after having experienced a “`AL lib: (EE) stream_state_callback2: Received stream failure!`” error, it prints “`AL lib: (EE) alc_cleanup: 1 device not closed`”, if no error happened, it prints something like “`AL lib: (WW) FreeDevice: (0xb153830) Deleting 1 Buffer(s)`”.

**Comment by Kangz** [comment]
I don't thing the engine should be able to deal with the audio device disappearing. However I would like to be able to restart the sound, seamlessly and without having to restart the map. Created #585 for this.

Closing at won't fix.

**Comment by illwieckz** [comment]
Yes, if I can reload the sound without restarting the map, it's cool. But this problems shows that there is some cases when calling `snd_restart` does not cleanup the previous device. It's not critical, but it's good to know. :smiley: 

(And I will try to buy an UPS)
