### ISSUE TITLE
Spectator bind key for “+movedown” command can't be changed

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#536]
Hi, by default the bind “`C`” is used to:

`+movedown` as alien: _wallwalk_
`+movedown` as human: _crouch_
`+movedown` as spectator: _move down_

This bind can be changed for alien wallwalking and human crouching, but is not changeable for spectator moving down. I think there is no need to add a menu entry for that, a good idea is to use the same bind key as human crouching, so when someone change the human crouching bind key, change the spectator move down key too.

What do you think about it?

**Comment by Viech** [comment]
Linking spectator to human binds sounds like hackish special casing to me, I'd rather have a binding menu that is strictly divided by the three "species". (Either one where all standard commands are listed and can receive a binding or a "bindings editor" where for every species, you can add a key to a list and assign that key any command (either arbitrarly set or picked from a list).)

**Comment by illwieckz** [comment]
It was only a suggestion to not overload the option window. But your solution will be the best if it fixes the issue. :wink:

**Comment by DolceTriade** [comment]
This is fairly trivial code wise. What other keys could spectators use? Otherwise, I'll just shove this with another subcategory.

**Comment by Viech** [comment]
I doubt the bindings editor is trivial to create but I think we should go for that as an upcoming feature. I'm also still in favor of making spectators a team of their own, bindings wise, and have a forth category for shared defaults. Once we have that split so nicely we don't need any hackish ambiguous commands anymore and can declare the end of the `vim keybindings.cfg` era.

**Comment by DolceTriade** [comment]
Spectators can have their own binds. Codewise it is trivial since it is basically adding
<keybind cmd="+movedown" team="spectators" /> somewhere in the file. The question is where to put it. Making another section is easy, so we could make a spectator section and include it there.

**Comment by Viech** [comment]
As far as I know, spectator binds and default binds are the same technically, which is bad. Also, I don't know what kind of "sections" you are talking about. So far there are no sections for alien, human, spector *or* default binds, just a horribly incomplete bindings meu that incorporates all two/three species into logical sections like movement and chat, with some options being able to share keys (e.g. wallwalk and duck). This needs to be redone from scratch, ideally according to my proposal above.

**Comment by DolceTriade** [comment]
My point is that implementing your proposal isn't especially difficult if we have a fully fleshed out proposal with a list of which binds should be included.
