### ISSUE TITLE
LTO crashes the game

### ISSUE THREAD

**Issue by kharnov** [Unvanquished/Unvanquished#537]
To reproduce:
1. Compile with LTO;
2. /devmap parpax;
3. Add ~6 bots to both teams;
4. Press tab a few times to get the scoreboard.

**Comment by Amanieu** [comment]
I've noticed bugs with LTO before (on mingw builds). We may have some sort of undefined behavior that happens only with LTO.

**Comment by bmorel** [comment]
I use LTO and never had such consistent crash.

**Comment by necessarily-equal** [comment]
LTO is known to worsen some cases of undefined behavior quite badly. I would not be surprised if this is now fixed.

**Comment by illwieckz** [comment]
Our official builds now use LTO since at least 0.52 and no one complains.
