### ISSUE TITLE
builtin server list confuses server entries

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#543]
Hi, sometime, the server name displayed and clicked in the server list is not the one opened, as you can see in this screenshot, I click on my server running forlorn:

![gg.illwieckz.net server](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-28_042335_000.png)

Then Unvanquished loads Matth's server running parpax:

![MATS server](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-28_042342_000.png)

**Comment by DolceTriade** [comment]
Why is this a website bug? Should be UI. I'll look into it.

**Comment by illwieckz** [comment]
Yes it's a UI bug.

**Comment by bmorel** [comment]
never seen that. Has it been seen recently?

**Comment by illwieckz** [comment]
I haven't experienced that in a while, let's close it for now and reopen it if it reappears.
