### ISSUE TITLE
Marauder speedhack

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#546]
Pressing forward and left or right together and slowly turning mouse in the same direction makes marauder accelerate much faster.

Marauder walking speed: 384.
Marauder jumping speed: about 480.
Marauder cheathacking speed: 1000+.

I think this should be removed and replaced with an intuitive movement system.

**Comment by Viech** [comment]
Sorry, this is a gameplay request, which aren't discussed on the issue tracker.
