### ISSUE TITLE
Disappearing fences in UTCS

### ISSUE THREAD

**Issue by Sherif89** [Unvanquished/Unvanquished#547]
There are fences in UTCS, which only appear, if I look at them from a specific angle. I can't pass those fences. Look:
![bug1](https://cloud.githubusercontent.com/assets/8778976/5994204/fd4fae9c-aa72-11e4-92e6-60265b3cff17.png)
![bug2](https://cloud.githubusercontent.com/assets/8778976/5994207/1532a4e2-aa73-11e4-8f35-319ae55bbfa8.png)

**Comment by Viech** [comment]
Can you reproduce this in devmap mode using `r_showTris`?

**Comment by Sherif89** [comment]
>Can you reproduce this in devmap mode using r_showTris?

How to do it?
Can I do it with alpha 36?

**Comment by Viech** [comment]
Yes, any alpha works. After launching the game, open the console (`shift`+`esc` for me) and enter `/devmap utcs`. This lauches a local game with cheats enabled. In the game go to the same position to reproduce the missing fences, then open the console again and type `/set r_showTris 1`. Make a screenshot of the result. Then we can tell whether this is a geometry or shader issue.

**Comment by Viech** [comment]
@Sherif89: Any updates?

**Comment by Veyrdite** [comment]
UTCS is no longer used AFAIK.  This could have either been an engine issue or a VIS calculation (map export) issue.  Unless the latter is proved I don't think we should keep this issue open.

Closing.  Please feel free to re-open if we find another example of this.

**Comment by Viech** [comment]
I do think it could have been an engine issue given that UTCS used some special shader to make the fences look shiny without using specular mapping. I agree with closing this though, as such a feature would be deprecated anyway.

**Comment by Sherif89** [comment]
I'm sorry. I've forgotten this issue. After 2 or 3 versions, I hope it's now fixed.
