### ISSUE TITLE
Make shared command buffer awesome

### ISSUE THREAD

**Issue by Kangz** [Unvanquished/Unvanquished#550]
We need a bunch of things to have awesome command buffers, this is a tracking bug to see what is still needed (as well as a few related changes).

- [x] Add error when message size is too big to fit in the buffer
- [x] Move in IPC/CommandBuffer
- [x] Cvar to control buffer size (useful for testing buffers filling up)
- [x] Debug log in both engine and VM
- [x] Comment IPC/ code
- [x] Simplify Channel
- [x] Circular buffers
- [x] Moar stuff using the command buffer

**Comment by Viech** [comment]
Well done!
