### ISSUE TITLE
deformVertexes is broken (Water rendering bugs)

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#552]
There is a now well-known water bug on Station15 map:

![station15 water bug](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-03_052821_000.jpg)

But we can see the exact same bug on the unofficial nexus6 map, so it is not a specific station15 issue and perhaps it is not a map issue but a renderer issue.

![nexus6 water bug](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-03_053329_001.jpg)

As you see, the more time we wait, the more ugly the bug becomes:

![nexus6 water bug](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-03_053410_001.jpg)

![nexus6 water bug](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-03_053410_000.jpg)

Glitches increase with time, and it could be worse depending of the point of view:

![station15 water bug](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-03_055811_003.jpg)

![nexus6 water bug](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-03_054533_001.jpg)

The glitches can be visible in other rooms separated by walls and closed doors:

![station15 water bug](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-03_065910_000.jpg)

It can affect lights too (water broken texture illuminated by lights or reflecting lights):

![station15 water bug](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-03_070135_002.jpg)

The bug was already here in alpha 35.

**Comment by illwieckz** [comment]
It's seems to affect all textures using a water and lava keywords, the problem appears on citadel (water), vega (water), ancient remains (lava). All maps I tested with water/lava textures failed to render it correctly, with the same glitches.

Also, the glitches pass through all the map.

Vega (water):

![vega](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-21_211455_005.jpg)
![vega](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-21_211353_000.jpg)
![vega](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-22_171234_000.jpg)

Citadel (water):

![citadel](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-21_235746_003.jpg)

Ancient Remains (lava):

![ancient remains](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-22_171544_002.jpg)
![ancient remains](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-22_171726_001.jpg)

Pulse (water):

![pulse](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-22_173220_002.jpg)
![pulse](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-22_172528_003.jpg)

In fact, when we are inside the water/lava; the wobbly effect that affects vision is here, if there is some fog in water, it works too. Tut the surface of the water/lava is not here, and this is this surfaces which is buggy.

Usually the water surface makes wave (deforms itself vertically), and the lava surface deforms itself horizontally. These two effects are broken.

The only map with working water is Cleanser, but the surface does not have waves like water nor horizontal deformations like lava, so it seems it works because the mapper does not used the keyword “water”, it's just a texture like a wall texture.

![cleanser](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/shots/unvanquished_2015-02-22_173917_000.jpg)

**Comment by illwieckz** [comment]
commenting out _deformVertexes_ lines in shaders fixes many issues, this one is used to do wave from example, on water surface, on tree leafs, or duplicating flames in some angles…

**Comment by illwieckz** [comment]
This bug does not affect only water, but enhanced fire and animated leafs. Textures transverse all the map and reflects light badly. Also, leafs appears on bullet impact,

**Comment by Viech** [comment]
@gimhael, any idea?

**Comment by gimhael** [comment]
Yes, all deforms are broken. I have a fix on my lokal particles branch, but have to clean it up a bit. Expect a fix in the next days.

**Comment by illwieckz** [comment]
Awesome! Too bad this happen right after the release. :stuck_out_tongue_closed_eyes: Thanks for your work!

**Comment by illwieckz** [comment]
The current gimhael's sprites branch fix all these issues (and fix the “moving cloud” skybox bug too).

**Comment by Viech** [comment]
Sweet, then this can be closed with a commit reference once it reaches `master` or a `for-*` branch.

**Comment by illwieckz** [comment]
Hi, do you know if the _sprites_ branch will be merged before tomorrow's release?

**Comment by Viech** [comment]
`origin/for-0.38.0..origin/sprites` is empty right now, so it seems that it was merged and will be in the release.

**Comment by illwieckz** [comment]
nice !
