### ISSUE TITLE
spiker

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#555]
I know viech will love this.

Spikers are not very effective. Mostly because they don't fire in the vast majority of the places you could position them. When they do fire they often miss and there seems to be long reload. Also their range is tiny. Most players don't bother using them.

**Comment by Viech** [comment]
Gameplay related → not being discussed on the tracker. You'll like to hear that I'm working on this anyway. :stuck_out_tongue_winking_eye:
