### ISSUE TITLE
Training server layouts are terrible since teslas removed

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#556]
Lets be honest, they were always terrible, but now they're child's play because turrets are nurfed and teslas don't exist.

Please fix layouts.

Also, please consider putting reactors and OM inside the map, it makes the tactics more interesting.

**Comment by Kangz** [comment]
For the OM and RC,  I think the problem is that bots won't rebuild it so the goal would basically be "destroy the RC/OM" and not "wipe them out of the map".

Otherwise, it seems you are volunteering to make new training server layouts :)

**Comment by overvolting** [comment]
sure, point me to a link that explains the process and I might try it.

**Comment by Viech** [comment]
The training server has been unmaintained for a while. It needs a new administration as well as layout contributors. @overvolting could you come to IRC or Forums and discuss layout creation there? I wouldn't want issues of modded servers to be discussed here, especially not while there are so many open issues related to the game as such. :wink:

**Comment by DolceTriade** [comment]
overvolting = murderer on IRC
