### ISSUE TITLE
toggled sprinting untoggles

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#557]
When you toggle sprinting on, for various reasons it gets untoggled.
For example when buying from the armory or building from the menu.

**Comment by overvolting** [comment]
Here's an example 
seta walk1 "+sprint c;bind z vstr walk2;echo Sprint On"
seta walk2 "-sprint c;bind z vstr walk1;echo Sprint Off"

**Comment by DolceTriade** [comment]
We have toggle sprint as an option. Also, when we switch focus from the game to the UI, we clear keys. This is intentional.

**Comment by overvolting** [comment]
So, if I use the official toggle sprint, it will only deactivate when I do it purposefully?

**Comment by DolceTriade** [comment]
Theoretically.

**Comment by Viech** [comment]
@overvolting could you check whether the "official" toggle feature works?

**Comment by overvolting** [comment]
Sure, I will report back.

**Comment by overvolting** [comment]
Ok, using the game option to bind sprint and toggle sprint. It definitely works better and it doesn't get turned off by menus. However as I'm running around aliens for a while sprinting, there are times when it does seem to turn itself off, maybe it's when I run out of stamina, maybe other times.

**Comment by Viech** [comment]
Running out of stamina means sprint stops and can only be re-enabled when stamina reaches a threshold again. I'm not sure if it's better when the sprint control is toggled off or stays on so that the sprint is resumed as fast as possible. I wouldn't consider either behavior a bug though.
