### ISSUE TITLE
Add ability to rescale UI 

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#558]
The game text doesn't seem to scale with resolution.
People playing on high end monitors can't read anything.

**Comment by DolceTriade** [comment]
Hm, I think it might be necessary to create a new font measurement...

**Comment by overvolting** [comment]
If you check quake 3, I believe their fonts all scaled perfectly no matter what resolution.

**Comment by Kangz** [comment]
Yes, everything was based off a 640x480 virtual screen in q3 but librocket has fixed size fonts, for now.

@DolceTriade is there a CSS property that could help here, I can't seem to think of any :/

**Comment by overvolting** [comment]
I would call this an accessibility type.

**Comment by DolceTriade** [comment]
@Kangz Not sure, that's why I think I might need to add one.

**Comment by Veyrdite** [comment]
Renaming the issue to the broader feature.  Having a slider in the UI config for this would be useful.

I think @DolceTriade mentioned something about a scalable unit (or I dream't it, I've been around too long to remember).

**Comment by DolceTriade** [comment]
I just mentioned it above in the same issue :p 

https://github.com/Unvanquished/Unvanquished/issues/558#issuecomment-72773502
>Hm, I think it might be necessary to create a new font measurement...

**Comment by slipher** [comment]
@illwieckz reworked the UI to make everything based on em units instead of px, so it scales to higher resolutions.
