### ISSUE TITLE
Evo / buy / build menus don't show up (rare)

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#560]
I'm reporting this just for completeness, I'm not sure if it's already fixed, but in previous versions (older than 0.35 maybe?) the radial menus would sometimes (rarely) break and seemed to activate as empty menus when used, the only fix was to /reconnect.

I can't confirm if it still occurs because it's a rare bug.

**Comment by Viech** [comment]
I can confirm this (local `devmap`, `vid_restart` fixes). Seen this quite a bit in Alpha 35 but I don't know either how to reproduce.

**Comment by DolceTriade** [comment]
I got this too during the devgame. No idea what's up.

**Comment by Veyrdite** [comment]
Does this still trigger for people?

**Comment by DolceTriade** [comment]
Should be fixed.
