### ISSUE TITLE
“There are N spawns remaining” text does not disappear while switching team.

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#567]
Hi, if you try to switch team while Unvanquished is printing “There are N spawns remaining”:

![alien spawns remaining](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_085423_000.jpg)

Go to spectators for example, the text does not disappear:

![spectators spawns remaining](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_085753_000.jpg)

**Comment by illwieckz** [comment]
#561 and #567 combo: 

As human, I build 6 spawns, destroyed one (with my gun), then I rejoin, Unvanquished says there is 6 spawns (instead of 5):

![5 or 6](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_090405_000.jpg)

Then I switch team to aliens, Unvanquished says there is 6 spawns (instead of 4), so the human value is not wiped:

![5 or 6](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_090416_000.jpg)

After joining alien and rejoin, the alien spawn count is ok:

![4](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_090444_000.jpg)

**Comment by Viech** [comment]
Merging this into #561.
