### ISSUE TITLE
Menu music selection is broken

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#575]
It only ever uses heartbeat1 track.

**Comment by Viech** [comment]
Can you please elaborate? I don't understand your issue from title and description.

**Comment by lamefun** [comment]
It only ever uses heartbeat1.ogg. heartbeat.ogg and heartbeat2.ogg aren't used.

**Comment by Viech** [comment]
You mean, the same menu music plays all the time after launching the client? I think I can confirm this. Maybe the PRNG isn't initialized properly at this point?

**Comment by Kangz** [comment]
Yes, the PRNG is not initialized on CG_ROCKET_INIT while it is on CG_INIT. Fixed in nacl-cgame/main that will be merged for next release.
