### ISSUE TITLE
Behaviour of 'Escape' key when in menus/dialogs

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#576]
1. Open menu in game using Esc.
2. Open some configuration dialog.
3. Press Esc to close the dialog.
4. Pressing Esc should close the menu now, but it doesn't.

**Comment by illwieckz** [comment]
Yes, I confirm, some windows can be closed with ESC, other can't, it's weird.

**Comment by overvolting** [comment]
I can confirm, it seems like the pop-up windows have an invisible focus.
If you click off them and select anywhere else on the screen, escape doesn't close them. If you click back into their window bar, escape works again.

**Comment by DolceTriade** [comment]
This is working as intended. A feature request would be to have escape close all open windows. That's TODO :)

**Comment by lamefun** [comment]
Seriously?

**Comment by DolceTriade** [comment]
Yes, but I will address the issue later. I had a temporary fix earlier, but now I was searching for a better way.

**Comment by Veyrdite** [comment]
Hitting Esc as of now (alpha 45, probably changed earlier) closes all open UI dialogs and drops you back to the game.

@DolceTriade @lamefun do you instead want these windows to re-appear when you hit esc again, or do you think the current solution is more elegant?

**Comment by DolceTriade** [comment]
Close. Pressing escape should close all the windows, not hide them.
