### ISSUE TITLE
Maps load twice

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#583]
Sometimes the map loads, and then it loads again.

**Comment by Viech** [comment]
I can confirm that this happens client-side when connected to the Dev Server (didn't check others).

**Comment by Veyrdite** [comment]
Does this still happen?  I've only encountered it when the server changes map/resets.

**Comment by DolceTriade** [comment]
Probably, though I haven't seen it since Tremulous.

**Comment by Kangz** [comment]
Closing as won't fix, as we don't have enough information.
