### ISSUE TITLE
Spiker spikes don't seem to point at the correct direction

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#586]
Instead of flying like this:

![spikegood](https://cloud.githubusercontent.com/assets/433585/6149599/e3b07318-b21a-11e4-9649-598254372c33.png)

They fly like this:

![spikebad](https://cloud.githubusercontent.com/assets/433585/6149590/d57ce312-b21a-11e4-9d21-647c341c36af.png)

**Comment by Viech** [comment]
I can confirm this. They point in the right direction initially but the rotation isn't updated as the spike follows its trajectory.

**Comment by overvolting** [comment]
Haha. How can you even see this? I've never even seen a spike they're too fast for me.
