### ISSUE TITLE
server listing in client, buttons have no effect

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#588]
Server listing in the client. Fetch new list and refresh list buttons don't seem to do anything.

**Comment by DolceTriade** [comment]
How do you fetch the server list then?

**Comment by overvolting** [comment]
It happens automatically. The buttons to refresh didn't.

I can report that now the buttons seem to work, they just don't work consistently.

**Comment by DolceTriade** [comment]
I'm pretty sure they aren't broken, but I'll take a look anyways.

**Comment by DolceTriade** [comment]
Nope, they definitely do something.

**Comment by Viech** [comment]
Atleast the ping field is never updated on "Refresh list", not sure about the others.
