### ISSUE TITLE
Segfault from server selection screen

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#591]
When I'm on a server and I pull up the server selection screen and double click another server I often segfault.

**Comment by DolceTriade** [comment]
Can you find a way to reproduce this constantly? I haven't been able to reproduce this.

**Comment by Viech** [comment]
Maybe this is related to the one-off error where one would connect to a different server than the one selecet? It may be that this can trigger an out-of-bounds access, too.

**Comment by DolceTriade** [comment]
Yes, this is likely.

**Comment by guillaume-uH57J9** [comment]
I also experiences very regular crashes when from the server selection screen (80% of the times).
So much so I've stopped using this GUI, and started the game by providing server IP by the command line. It still crashes during loading, but less often. 

Callstack : http://pastebin.com/cqnK099W
Command line and standard output: http://pastebin.com/edibD1NL

### Hardware / Software

| Release | 0.36, 0.37
|:--|:--
| Operating System | Debian GNU/Linux 8 (testing)
| Kernel Version | 3.16.0-4-amd64
| Video Card | Intel(R) Ivybridge Mobile
| Driver Type |  i965 (OpenSource)
| Driver Version | Mesa 10.4.2-2
| OpenGL Version | 3.0 Mesa 10.4.2
| Map tested | Allmost all of them
| Renderer used | default setting (ie not sure)

**Comment by DolceTriade** [comment]
]Failed to open BO for returned DRI2 buffer (1920x1080, dri2 back buffer, named 11).
This is likely a bug in the X Server that will lead to a crash soon.

This seems like a driver bug... There is also likely a bug unvanquished side somewhere else for a different type of crash.

**Comment by guillaume-uH57J9** [comment]
I'm not certain that my crash is the one reported here, but the symptoms are really similar. 

With more details maybe we could see if there are a single or different issues.

@overvolting, could you please provide more details on your graphic card, drivers, and if possible the crash logs?
Thanks,

**Comment by overvolting** [comment]
I can do better than that, here's a backtrace:

#0  0x0000001f0000001c in ?? ()                                                                                  
Python Exception <type 'exceptions.ValueError'> Cannot find type const Rocket::Core::PropertyNameList::_Rep_type:                                                                                                                 
#1  0x00000000005d1e28 in Rocket::Core::Element::OnPropertyChange (this=0xfe91970,                               
    changed_properties=std::set with 1 elements)                                                                 
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1447                           
Python Exception <type 'exceptions.ValueError'> Cannot find type const Rocket::Core::PropertyNameList::_Rep_type:                                                                                                                 
#2  0x0000000000644931 in Rocket::Core::ElementStyle::DirtyProperties (this=this@entry=0xfe91f30,                
    properties=std::set with 1 elements, clear_em_properties=clear_em_properties@entry=true)                     
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/ElementStyle.cpp:691                       
#3  0x00000000006459b7 in Rocket::Core::ElementStyle::SetPseudoClass (this=0xfe91f30, pseudo_class=...,          
    activate=activate@entry=false)                                                                               
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/ElementStyle.cpp:160                       
#4  0x00000000005cd37f in Rocket::Core::Element::SetPseudoClass (this=<optimized out>, pseudo_class=...,         
    activate=activate@entry=false)                                                                               
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:619                            
#5  0x00000000004d4792 in ~SelectableDataGrid (this=0x9a40860, __in_chrg=<optimized out>)                        
    at /tmp/buildd/unvanquished-0.37.0/src/engine/client/rocketSelectableDataGrid.h:54                           
#6  SelectableDataGrid::~SelectableDataGrid (this=0x9a40860, __in_chrg=<optimized out>)                          
    at /tmp/buildd/unvanquished-0.37.0/src/engine/client/rocketSelectableDataGrid.h:57                           
#7  0x00000000005d0847 in Rocket::Core::Element::OnReferenceDeactivate (this=<optimized out>)                    
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1685                           
#8  0x00000000005ce156 in Rocket::Core::Element::ReleaseElements (this=this@entry=0x9a403a0,                     
    released_elements=std::vector of length 0, capacity 2)                                                       
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1807                           
#9  0x00000000005d0984 in Rocket::Core::Element::~Element (this=this@entry=0x9a403a0, __in_chrg=<optimized out>) 
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:137                            
#10 0x00000000005d0b29 in Rocket::Core::Element::~Element (this=0x9a403a0, __in_chrg=<optimized out>)            
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:150                            
#11 0x00000000005d0847 in Rocket::Core::Element::OnReferenceDeactivate (this=<optimized out>)                    
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1685                           
#12 0x00000000005ce156 in Rocket::Core::Element::ReleaseElements (this=this@entry=0x9a600f0,                     
    released_elements=std::vector of length 0, capacity 2)                                                       
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1807                           
#13 0x00000000005d0984 in Rocket::Core::Element::~Element (this=this@entry=0x9a600f0, __in_chrg=<optimized out>) 
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:137                            
#14 0x00000000005d0b29 in Rocket::Core::Element::~Element (this=0x9a600f0, __in_chrg=<optimized out>)            
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:150                            
#15 0x00000000005d0847 in Rocket::Core::Element::OnReferenceDeactivate (this=<optimized out>)                    
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1685                           
#16 0x00000000005ce156 in Rocket::Core::Element::ReleaseElements (this=this@entry=0x9a47db0,                     
    released_elements=std::vector of length 1, capacity 2 = {...})                                               
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1807                           
#17 0x00000000005d0984 in Rocket::Core::Element::~Element (this=0x9a47db0, __in_chrg=<optimized out>)            
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:137                            
#18 0x0000000000663270 in ~ElementTabSet (this=0x9a47db0, __in_chrg=<optimized out>)                             
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Controls/ElementTabSet.cpp:40                   
#19 Rocket::Controls::ElementTabSet::~ElementTabSet (this=0x9a47db0, __in_chrg=<optimized out>)                  
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Controls/ElementTabSet.cpp:42                   
#20 0x00000000005d0847 in Rocket::Core::Element::OnReferenceDeactivate (this=<optimized out>)                    
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1685                           
#21 0x00000000005ce156 in Rocket::Core::Element::ReleaseElements (this=this@entry=0x9a5e630,                     
    released_elements=std::vector of length 1, capacity 2 = {...})                                               
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1807                           
---Type <return> to continue, or q <return> to quit---                                                           
#22 0x00000000005d0984 in Rocket::Core::Element::~Element (this=this@entry=0x9a5e630, __in_chrg=<optimized out>) 
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:137                            
#23 0x00000000005d0b29 in Rocket::Core::Element::~Element (this=0x9a5e630, __in_chrg=<optimized out>)            
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:150                            
#24 0x00000000005d0847 in Rocket::Core::Element::OnReferenceDeactivate (this=<optimized out>)
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1685
#25 0x00000000005ce156 in Rocket::Core::Element::ReleaseElements (this=this@entry=0x9c2fbf0, 
    released_elements=std::vector of length 2, capacity 4 = {...})
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1807
#26 0x00000000005d0984 in Rocket::Core::Element::~Element (this=this@entry=0x9c2fbf0, __in_chrg=<optimized out>)
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:137
#27 0x00000000005d0b29 in Rocket::Core::Element::~Element (this=0x9c2fbf0, __in_chrg=<optimized out>)
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:150
#28 0x00000000005d0847 in Rocket::Core::Element::OnReferenceDeactivate (this=<optimized out>)
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Element.cpp:1685
#29 0x00000000005fa109 in Rocket::Core::ElementReference::operator= (this=0xfe95bd8, _element=0x0)
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/ElementReference.cpp:65
#30 0x00000000005c9e94 in _Destroy<Rocket::Core::ElementReference> (__pointer=0xfe95bd8)
    at /usr/include/c++/4.9/bits/stl_construct.h:93
#31 __destroy<Rocket::Core::ElementReference*> (__last=<optimized out>, __first=0xfe95bd8)
    at /usr/include/c++/4.9/bits/stl_construct.h:103
#32 _Destroy<Rocket::Core::ElementReference*> (__last=<optimized out>, __first=<optimized out>)
    at /usr/include/c++/4.9/bits/stl_construct.h:126
#33 _Destroy<Rocket::Core::ElementReference*, Rocket::Core::ElementReference> (__last=0xfe95bf8, 
    __first=<optimized out>) at /usr/include/c++/4.9/bits/stl_construct.h:151
#34 ~vector (this=0xa38d2d8, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/stl_vector.h:424
#35 Rocket::Core::Context::~Context (this=0xa38d260, __in_chrg=<optimized out>)
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Context.cpp:78
#36 0x00000000005c9ee9 in Rocket::Core::Context::~Context (this=0xa38d260, __in_chrg=<optimized out>)
    at /tmp/buildd/unvanquished-0.37.0/src/libs/libRocket/Source/Core/Context.cpp:98
#37 0x00000000004ccef8 in Rocket_Shutdown () at /tmp/buildd/unvanquished-0.37.0/src/engine/client/rocket.cpp:418
#38 0x00000000004f4263 in CL_ShutdownCGame ()
    at /tmp/buildd/unvanquished-0.37.0/src/engine/client/cl_cgame.cpp:361
#39 0x000000000050e5ef in CL_Disconnect (showMainMenu=155277696, showMainMenu@entry=1)
    at /tmp/buildd/unvanquished-0.37.0/src/engine/client/cl_main.cpp:1641
#40 0x000000000050efa7 in CL_Connect_f () at /tmp/buildd/unvanquished-0.37.0/src/engine/client/cl_main.cpp:1883
#41 0x00000000004305cc in Cmd::ExecuteCommand (command=..., parseCvars=parseCvars@entry=false, 
    env=env@entry=0x0) at /tmp/buildd/unvanquished-0.37.0/src/engine/framework/CommandSystem.cpp:215
#42 0x0000000000430a51 in Cmd::ExecuteCommandBuffer ()
    at /tmp/buildd/unvanquished-0.37.0/src/engine/framework/CommandSystem.cpp:91
#43 0x0000000000459079 in Com_Frame () at /tmp/buildd/unvanquished-0.37.0/src/engine/qcommon/common.cpp:1989
#44 0x000000000041af15 in main (argc=<optimized out>, argv=0x7fffffffe0a8)
    at /tmp/buildd/unvanquished-0.37.0/src/engine/framework/System.cpp:744

**Comment by cweagans** [comment]
Just got this with the most recent release on Mac OS Yosemite. It happens every time I try to select a server from the list. Happy to screenshare with somebody if you want to attempt to debug.

**Comment by Viech** [comment]
@DolceTriade do you still have this issue on your radar?

**Comment by DolceTriade** [comment]
Cannot reproduce on linux or mac...

**Comment by Viech** [comment]
And the backtrace isn't helpful either? Do you need a full backtrace maybe?

**Comment by DolceTriade** [comment]
The backtrace shows it is a segfault in cleaning up librocket, but I'm not entirely sure what it is doing.
