### ISSUE TITLE
Show keybinding next to vote/poll options.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#601]
Even when people know the vote keys, they will usually use the global vote keys for team votes, resulting in a "no vote in progress" warning. Displaying the proper keys to vote yes or no with every vote would mitigate this.

**Comment by DolceTriade** [comment]
We display keys if and only if cg_tutorial is enabled. Would you like to change it so that vote keys are displayed regardless of cg_tutorial value?

**Comment by Viech** [comment]
Yeah, I guess I would do that.
