### ISSUE TITLE
bad skeleton reflexion in mirrors

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#603]
OK, this issue is almost a joke, I'm posting it only because @overvolting wrote all the tickets I wanted to write and this issue is **currently the last** in my _TOREPORT_ list. :stuck_out_tongue: 

This issue is very minor because it affects skeleton rendering, which is a cheat and can't be used by average players on normal games.

As you see, this man have 6 skeleton arms and 6 skeleton hands in the mirror:

[![mirror skeleton issue](https://dl.illwieckz.net/b/unvanquished/bugs/unvanquished_2015-02-04_011824_000.png)](https://dl.illwieckz.net/b/unvanquished/bugs/unvanquished_2015-02-04_011824_000.png)

But this bug only appears on mirrors, if you just spectate another, it's fine:

[![normal skeleton](https://dl.illwieckz.net/b/unvanquished/bugs/unvanquished_2015-02-05_091510_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/unvanquished_2015-02-05_091510_000.jpg)

This bug is very minor but I report it anyway because maybe this can reveal other problems, or perhaps it can be linked to some other issues or explain other issues.

**Comment by Viech** [comment]
This is intended. The mirror shows his *real* form. Did you never wonder how he can carry a grenade and a blaster that don't show up *anywhere on the body*?

**Comment by illwieckz** [comment]
It seems that we are seeing skeletons from first-person view: both third-person view, right handed first-person view and left handed first-person view.
