### ISSUE TITLE
Graphical glitches when someone is using a jetpack

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#604]
Hi, since the alpha 0.36.0 release I experience some random graphical glitches. After having played a lot, I've noticed that it seems to occurs only when someone use a jetpack (flying) in your area as you see in these screenshots: (red arrow: someone flying with a jetpack):

![jetpack glitche](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-10_221952_001.jpg)

![jetpack glitche](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-10_230226_001.jpg)

Visually, the glitches look like the water bug (see #552), but I don't know if it's the same bug or another. This jetpack bug appeared in 0.36.0 while the water bug were already there in 0.35.0.

**Comment by Viech** [comment]
@illwieckz, please add your graphics card and drivers as well as your OS to both threads, given that this may be a rendering bug.

**Comment by illwieckz** [comment]
OK, I will do that later (I'm not at home right now). Perhaps this jetpack issue is related to my system since I read nobody talking about that while playing, but for the water bug on spacetracks, every body experiences it whatever the system (it's why I removed this map from the rotation list on my server).

**Comment by illwieckz** [comment]
My system:

```
$ inxi -GS
System:    Host: myhost Kernel: 3.16.3-031603-generic x86_64 (64 bit) Desktop: Gnome 3.14.3 
           Distro: Ubuntu 14.10 utopic 
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
           Display Server: X.Org 1.16.0 drivers: ati,radeon (unloaded: fbdev,vesa) FAILED: fglrx
           Resolution: 1920x1080@60.0hz
           GLX Renderer: Gallium 0.4 on AMD TAHITI
           GLX Version: 3.0 Mesa 10.6.0-devel (git-3f1e128 2015-02-13 utopic-oibaf-ppa)

$ glxinfo | grep ' renderer\| rendering'
direct rendering: Yes
OpenGL renderer string: Gallium 0.4 on AMD TAHITI

$ lspci -mm -v -k -s 01:00.0
Slot:	01:00.0
Class:	VGA compatible controller
Vendor:	Advanced Micro Devices, Inc. [AMD/ATI]
Device:	Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
SVendor:	Hightech Information System Ltd.
SDevice:	Tahiti XT2 [Radeon HD 7970 GHz Edition]
Driver:	radeon

$ grep DRI2 /var/log/Xorg.0.log
[   147.043] (II) glamor: EGL version 1.4 (DRI2):
[   148.113] (II) RADEON(0): [DRI2] Setup complete
[   148.113] (II) RADEON(0): [DRI2]   DRI driver: radeonsi
[   148.113] (II) RADEON(0): [DRI2]   VDPAU driver: radeonsi
[   149.057] (II) GLX: Initialized DRI2 GL provider for screen 0

$ dpkg -l | grep 'libgl1-mesa-dri\|libglu1-mesa\|libdrm-radeon\|libosmesa\|xserver-xorg-video-radeon' | awk '{print $2 " " $3}' | column -t
libdrm-radeon1:amd64                2.4.59+git1502130630.dbc8b1~gd~u
libdrm-radeon1:i386                 2.4.59+git1502130630.dbc8b1~gd~u
libgl1-mesa-dri:amd64               10.6~git1502130730.3f1e12~gd~u
libgl1-mesa-dri:i386                10.6~git1502130730.3f1e12~gd~u
libgl1-mesa-dri-experimental:amd64  10.2~git1404181931.7489f3~gd~s
libglu1-mesa:amd64                  9.0.0-2
libglu1-mesa:i386                   9.0.0-2
libosmesa6:amd64                    10.6~git1502130730.3f1e12~gd~u
libosmesa6:i386                     10.6~git1502130730.3f1e12~gd~u
xserver-xorg-video-radeon           1:7.5.99+git1501140731.c80ea1~gd~u
```

**Comment by illwieckz** [comment]
It looks like it was fixed some release ago, probably related to the transform stuff.
