### ISSUE TITLE
Bad feedback while redirecting autodownload to sv_wwwFallbackURL

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#606]
Hi, on my server I've configured http autodownload like that:

```
set sv_wwwBaseURL "dl.unvanquished.net/pkg"
set sv_wwwFallbackURL "gg.illwieckz.net/dl/unvanquished/pkg"
```

The official server is BaseURL because I noticed that sometime, people are trying to connect to my server while they are missing some official assets, so, they can get all missing assets before playing from the official repository. But if I host a non official pk3 (like my minimap update for Station15), Unvanquished try first on the official server then on my server (as intended), but the console prints that:

```
clientDownload: 7 : beginning "map-station15_1.0+1_2b19f08d"
Redirecting client 'illwieckz [granger]' to dl.unvanquished.net/pkg/map-station15_1.0+1.pk3
clientDownload: 7 : beginning "map-station15_1.0+1_2b19f08d"
clientDownload: sending client 'illwieckz [granger]' to fallback URL 'gg.illwieckz.net/dl/unvanquished/pkg'
Redirecting client 'illwieckz [granger]' to dl.unvanquished.net/pkg/map-station15_1.0+1.pk3
```

As you see, the last line must be:

```
Redirecting client 'illwieckz [granger]' to gg.illwieckz.net/dl/unvanquished/pkg/map-station15_1.0+1.pk3
```

**Comment by Kangz** [comment]
At least should be. Not bothering to make a nicer fix here as the download code is a huge mess that we'll nuke at some point.
