### ISSUE TITLE
Update OpenAL Soft on Windows

### ISSUE THREAD

**Issue by Kangz** [Unvanquished/Unvanquished#607]
We use OpenAL soft 1.15.1 on Windows, version 1.16.0 has a fix for a race condition in alCreateDevice on Windows.

**Comment by Kangz** [comment]
Not sure why you assigned me since you said you built the external deps for Windows.

**Comment by Amanieu** [comment]
I'm waiting for the Mac deps to be built before merging into master

**Comment by Kangz** [comment]
Heh.

**Comment by Kangz** [comment]
Merged into master and uploaded tarballs for mac.
