### ISSUE TITLE
Buy tyrant with 9.9 evos

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#608]
Sometimes I can buy a tyrant with 9.9 evos, etc. Looks like either counting problem or display problem (ie. I have 10 evos but it still shows 9.9).

**Comment by DolceTriade** [comment]
Yeah, rounding error most likely.

**Comment by illwieckz** [comment]
And sometime we can't earn more than 19.9 evo.

**Comment by Viech** [comment]
Didn't check, *could* be an UI error, too.

**Comment by DolceTriade** [comment]
Yeah, it's just a problem with how it is displayed. Internally, everything is stored correctly.

**Comment by overvolting** [comment]
Also, sometimes I can't get above 19.9 evos stored.
