### ISSUE TITLE
Can't use semicolons or slashes as content in chat prompt without escaping them.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#610]
For example typing `sorry ;)` would chat `sorry ` and print a warning about the command `)` being unknown. Also, `\` is treated as an escape character, which is really of no use when you want to chat. Clearly, text entered into the chat prompt is passed to the console, without any escaping.

~~Note that the proper solution is to **not pass chat to the console at all** but to pass it directly to a function dedicated to handling chat. Escaping chat content and passing it to the console is likely to break.~~

There is also the feature that lets you insert commands into the chat prompt by prefixing the line with `/` or `\`, which is more annyoing than helpful, for example if a user wants to type `\o/` or tell someone else the path to a file. There is `message_command` in case someone really prefers to use a prompt to insert a command, which no one has any reason to anyway, given that the console has auto-completion, output that isn't limited to four lines and scrolling…

All in all, this issue is about making *every* character entered into the chat prompt be treated as chat content. For all else there's the console and bindings.

**Comment by DolceTriade** [comment]
We can do this now by adding a VM_Call or waiting until we move librocket into the cgame. A stopgap solution would be to escape strings passed to the console.

**Comment by Viech** [comment]
Your call, I don't mind either. If you go for the stopgap solution leave the issue open though.

**Comment by DolceTriade** [comment]
Stop gap for now. Proper solution once librocket is in cgame.

**Comment by Amanieu** [comment]
Just call Cmd::Escape on the contents of the chat box before passing it to the command system.

**Comment by DolceTriade** [comment]
ya, that was my stopgap solution

**Comment by Viech** [comment]
Well, if there is a proper escape function (one that's guaranteed to work in the future and won't break if we change the command syntax) I'm fine with using that as a permanent solution, too. I'm just strictly against writing an ad-hoc function outside the Cmd namespace (a local workaround just for chat).

**Comment by Amanieu** [comment]
Cmd::Escape is guaranteed to work in the future and for all input strings. It will result in the exact passed string being parsed as a single argument for a command.

**Comment by Viech** [comment]
The issue isn't fully resolved; `/` and `\` still start a command sequence. Tested on ed48a17 which is a fix to the fix.

**Comment by Amanieu** [comment]
Fixed by 16731aba45a936232336ca3f7b35bc3e2a1e52a4
