### ISSUE TITLE
layoutload and game over

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#613]
If a layout is saved when the game is over, every time it is loaded it will end the game immediately.

eg.

wait for game to end. /layoutsave a1 Then start a new game and type /layoutload a1. The game starts and ends.

**Comment by Kangz** [comment]
Maybe there should be a sanity check for spawns when saving a layout?

**Comment by Viech** [comment]
That just removes an option which may have its uses (have another look at the winning team's base). For mappers it is also nice to be able to launch a map with no spawns. At some point I'd like to get rid of the builtin layout and ship a (number of) default layout file(s) instead. This requires users to enter a devmap match as a builder when there is no spawn, though.

@overvolting are you fine with me transforming this issue into "Allow loading a map with no spawns via devmap."? During a live non-devmap match, there's no point in loading such a layout, anyway.

**Comment by slipher** [comment]
The `g_neverEnd` cvar was added to solve this issue.
