### ISSUE TITLE
Spikers kill human buildings

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#614]
Spikers will try to kill human buildings if there are any in range. Other defenses don't.

**Comment by overvolting** [comment]
Oh this is most certainly an intended feature and not a bug. And if it wasn't it should be :)

**Comment by Viech** [comment]
It's actually not intended but a bug. Buildables shouldn't attack other buildings; Just imagine a rocket pod clearing an entire alien base in under a minute. Wait, this actually sounds like fun™… Then again, it isn't intended *so far*. :stuck_out_tongue_winking_eye:

**Comment by overvolting** [comment]
I posted a suggestion on the forum that aliens needed an offensive building to break human camps :X
