### ISSUE TITLE
Lucifer cannon behaviour: requires double-click after an overcharge

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#624]
1. Overcharge a Lucifer cannon.
2. Release mouse and click again immediately.
3. It won't charge.

**Comment by DolceTriade** [comment]
This isn't a bug. It's to punish you for overcharging. You need to click twice to charge again.

**Comment by overvolting** [comment]
lol what?! It should at least make a special malfunctioning sound then, since I thought it was a bug also.

**Comment by DolceTriade** [comment]
Probably. It's in the code though that you intentionally have to click again before you fire.

**Comment by overvolting** [comment]
Also a malfunctioning animation and message could be great.

**Comment by Viech** [comment]
Why bother with an animation and a sounds when you already get a lot of damage as a punishment. I'd say we should remove this.

**Comment by bmorel** [comment]
I think this was fixed, since I do not need a double click after overcharging. Needs confirmation thuogh.

**Comment by bmorel** [comment]
I confirm it myself, after new verification and nobody else confirming.
