### ISSUE TITLE
Don't replace the last egg that supports other structures without replacing them first/also.

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#625]
Sometimes I mark an egg for replacement and build something only to find this was the last egg supporting a lot of buildings, and they die.

**Comment by illwieckz** [comment]
Yes, replacing an egg with an acide tube (for example), and 5 acide tubes, 5 trappers and 10 hives die. :anguished: 

No need to be the last egg, only the last egg in this area.

**Comment by lamefun** [comment]
I can also Alt+E deconstruct the last egg supporting a bunch of structures.

**Comment by illwieckz** [comment]
gameplay changes actually in pipe makes this issue obsolete: with these changes unpowered buildables are just unpowered and ineffective, but not destroyed.

**Comment by DolceTriade** [comment]
I haven't tested to confirm whether this is accurate for aliens.

**Comment by illwieckz** [comment]
I confirm that removing eggs can't destroy any alien creep anymore. Change introduced makes all alien buildables alive if the overmind is alive, and makes the buildables shutdown (not destroyed, alive but ineffective). The other case where an alien buildable shutdown is when they depended on leech build point pool and nearly leech was destroyed/removed, but in that other case, the nearby buildables are not destroyed too, they are just unpowered.

Human behavior is the same.

By releasing 0.51.0 this issue will be fixed.

**Comment by illwieckz** [comment]
mmmh, is that code in master or in devgames branch? if in master we can close this issue.

**Comment by illwieckz** [comment]
I confirm the code is in `for-0.51.0` branch, hence this issue is fixed.
