### ISSUE TITLE
Improve buy/sell behaviour for all human upgrade slots.

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#627]
When you have an expensive weapon, you can always buy a cheaper weapon instead, it automatically sells the expensive weapon even if you have 0 credits left.

When you have a greande and 0 credits left, you can't buy firebomb, even though to buy it you'd need to sell your grenade anyway.

Same with armors and backpacks.

**Comment by illwieckz** [comment]
still true

**Comment by bmorel** [comment]
I think this has been fixed.

**Comment by bmorel** [comment]
Yes, I tried all the reported changes, and it's definitely fixed.
