### ISSUE TITLE
Under-construction structures invisible

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#628]
Human structures under construction are sometimes invisible. So are the greenish images showing where a buildable will be placed, for either team.

I observed the bug playing on internet servers on Windows 7 with a Radeon card.
I did not observe the bug in a local game
I did not observe the bug on Windows 8 with an NVIDIA card (but possibly compiled on a different commit).
![unvanquished_2015-02-22_193222_000](https://cloud.githubusercontent.com/assets/7809431/6337647/b6d2f528-bb70-11e4-82de-f87895349b10.jpg)

*Repeater under construction*

**Comment by Kangz** [comment]
It could be a gamelogic mismatch, are you running the same version of the gamelogic as the server?

**Comment by slipher** [comment]
I last merged master on February 8. Is that too old to have been compatible with the most recent dev game?

**Comment by Viech** [comment]
It shouldn't be as that date was one week after the current release, which is comptable with the Dev Server (and so should master be, if no one broke it). As it doesn't happen locally I would assume there's some kind of version mismatch anyway. Maybe you run a specific self-compiled gamelogic as opposed to the one send by the server in the pk3? (I heard this is still possible through manually setting `vm.game.type`, which would be a bug.)

**Comment by Viech** [comment]
@slipher: Any update on this?

**Comment by Viech** [comment]
There is an unreported bug where you would load a self-compiled VM while playing on a remote server. This could be the cause of the problem. @slipher can you start unvanquished, then `reset cm.sgame.type; reset vm.cgame.type`, then restart it and connect to the Dev Server to see if this solves the problem? Make sure you're not passing one of these cvars at startup.

**Comment by Viech** [comment]
@slipher please report back within a week, otherwise we'll assume this was a version mismatch. In either case, @Kangz or @Amanieu can you handle forcing clients to load the gamelogic from a pk3 when connected to a remote server (or open an issue for it)? Also, `vm.sgame.type` and `vm.cgame.type` can be archived and thus prevent unvanquished from loading, which is a related issue.

**Comment by slipher** [comment]
I can no longer reproduce this problem.
