### ISSUE TITLE
Under construction structures die without indication

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#630]
There's no indication that they've died. Aliens can waste ammo and time on them after they're dead.
Then invisible air explodes.

**Comment by Viech** [comment]
This should've been fixed by df666ab, which is part of Alpha 36. Are you sure this still happens in the current version (what server did you play on)? Does it happen for structures other than turrets?

**Comment by overvolting** [comment]
ILL check

**Comment by overvolting** [comment]
seems fixed
