### ISSUE TITLE
Add visual spiker warning

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#633]
So Viech doesn't have to spam spiker usage all the time.

![spiker-warning](https://cloud.githubusercontent.com/assets/433585/6370633/962444b4-bd03-11e4-8dc8-1d145a2e62a0.png)

**Comment by Viech** [comment]
Agreed, some feedback as to when or why the spiker doesn't shoot is necessary.

**Comment by illwieckz** [comment]
why not just disable the spiker if it will be ineffective? and marking the zone as unbuildable while building?

**Comment by lamefun** [comment]
I think the spiker should always shoot and withhold only the spikes that have a high chance of killing or seriously damaging friendly structures. It should be possible to combine spikers with other defenses, or else they won't be very useful.

**Comment by Viech** [comment]
#1051 does exactly what lamefun proposes, among other things.

**Comment by bmorel** [comment]
Even if spiker only partially shoot, I think this bug is still true as the builders do not have clues about how it will shoot. I suppose a cone of effect like what there is for trapper would help, and likely allow to close this.

**Comment by Viech** [comment]
I do think the original issue was resolved by #1051. You should now be able to put spikers arbitrarily close to as many friendly buildings as you like and it should still shoot (though I have not tested this recently). It's also not really hard to imagine that it will shoot (randomly) in a cone which roughly matches the visual spikes.
