### ISSUE TITLE
Animations aren't very smooth

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#635]
No interpolation, it seems.

**Comment by Viech** [comment]
Please provide more details. For me it does spin rather smoothly, there's only an error when the reactor enters its "dying" state. Even when the error occurs, the head would interpolate smoothly (but it can turn both backwards and forwards with unregular speed).

**Comment by DolceTriade** [comment]
I've said this for the longest time but no one believes me. It's in the idle state.

**Comment by Viech** [comment]
Is there one jerk at a certain point of the rotation or does it jerk all the time? (I can kind-of reproduce the latter but this could be a screen-refresh issue as well, given that I'm on a 60 fps IPS panel.)

**Comment by Amanieu** [comment]
This might be the infamous svs.time bug when a server has been running too long. The server time becomes huge and loses precision when it is converted to a float. This float is used for animations in the renderer.

**Comment by Viech** [comment]
We worked around this by reseting the time if I remember correctly.

**Comment by lamefun** [comment]
It seems that all new animations are affected: I can see this in repeater, trapper, acid, hive (when I look closely on limbs). It doesn't degrade over time.

**Comment by Viech** [comment]
> Is there one jerk at a certain point of the rotation or does it jerk all the time?

**Comment by lamefun** [comment]
All the time. Kind of like 30 FPS instead of 60 FPS.

**Comment by Viech** [comment]
Fair enough. Someone should check how the animation frames are selected, maybe this is an aliasing artifact where interpolation during two or more game frames is done between the same animation frames. @lamefun What's your average framerate? Are you using vsync?

**Comment by lamefun** [comment]
60 FPS with V-Sync, 120-130 without V-Sync. With V-Sync looking around is smooth, but model animations become ugly, without V-Sync model animations become better, but looking around is ugly.

**Comment by slipher** [comment]
Poor animation interpolation was fixed in #895.
