### ISSUE TITLE
Buildable range marker intersection/frontline don't display.

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#638]
As a thicker line like this:

![Range Indicator](https://i.ytimg.com/vi/mR14gzhcAoI/maxresdefault.jpg)

**Comment by Viech** [comment]
The feature exists and I have seen old screenshot with these lines but it never worked for me. For me both `cg_rangeMarkerDrawIntersection` and `cg_rangeMarkerDrawFrontline` clearly have an impact on performance but no visual impact at all.

Could you experiment with the  `cg_rangeMarker*` cvars and see if you can get the frontline and intersection features to work? In either case, please name your OS, GPU and drivers.

I'm using official nvidia 346.35 as a driver for my GeForce GTX 460 under Arch Linux 64 bit.

**Comment by DolceTriade** [comment]
It's also very expensive

**Comment by Viech** [comment]
From memory:

>     * is the feature implemented but not working?

Yes, as I wrote in 2015, the feature was working for some users at some time given that there were screenshots showing it.

>     * or is the feature too slow?

I would expect it be slow given that it renders large translucent surfaces. That wouldn't be the bug.

>     * or is the feature (still?) implemented at all?

I don't know. I cannot recall it being explicitly removed.

**Comment by slipher** [comment]
Frontlines and intersections both clearly draw something when turned on. You can easily see them in a base by setting `/cg_rangeMarkerBuildableTypes all` (since most buildings have range markers off by default). `cg_rangeMarkerDrawFrontline` draws a brighter line at the edges (as projected onto the player's view) of the surfaces shown by `cg_drawSurface`. `cg_rangeMarkerDrawIntersection` draws lines in the same style as the frontlines in places where two surfaces intersect.

**Comment by illwieckz** [comment]
You have to be a builder to see them (being a granger or carrying a ckit), we have an option to enable the feature in Graphics / Gameplay option (“Building ranges”). Unlike the buildable range the “support” only option (default) is very hard to notice if you don't enable the frontline option (we don't have UI for this). I assume support is for Reactor / Overmind, we may want to display this one for every player.

Note that currently it looks like the frontline is only rendered if the buildable is actually rendered or something like that, so the front line would appear or disappear given the way you look at it.

**Comment by illwieckz** [comment]
Also the “support” frontline may have less use today since it was probably the area where you were able to build human buildables without having to build a repeater, but now humans can build everywhere without repeater.

**Comment by slipher** [comment]
I guess we can close this since they do display. It's just a matter of settings.
