### ISSUE TITLE
Keyboard layout differs between console and ingame, the latter is incorrect.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#639]
When I open the console and type `bind -` the same key sequence appears on the console and I can verify that I bound `team spectator` to `-`. However, when I press the same key ingame I get the message `Unknown command messagemodec`. The (outdated) command `messagemodec` is bound to `/`. So ingame, my `-` key is treated incorrectly as `/`. It should be noted that on my german keyboard, `-` is in the location where `/` is on an en_US keyboard. Apparently the keyboad is handled incorrectly ingame.

I suspect the issue could be introduced by bcf8107. Pinging @slipher and @DolceTriade.

Note that I tested on for-0.37.0 at 51ee5f8.

**Comment by DolceTriade** [comment]
https://github.com/Unvanquished/Unvanquished/commit/319647454e260da2701e6e13e53e1d08979188d9
