### ISSUE TITLE
extension independent sound file path to be able to update res-packages with new format

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#642]
Hi, it's not a bug, it's a feature request! :smiley: 

You know, the texture shader path is extension independent. You can ship a `tex-package_1.pk3` containing shaders with `.tga` extension then you can replace it by a `tex-package_2.pk3` with shaders with `.crn` extension without breaking maps that depend on this shaders.

But if you ship a `tex-package_1.pk3` with `.wav` sound files, then you replace it with a  `tex-package_2.pk3` with `.opus` sound files, you must rebuild all the maps that depends on it because the sound file path is extension dependant.

I read somewhere that you want to have sound shaders, but before that and without that, having a extension independant sound file path will be a great improvement :+1:

**Comment by Viech** [comment]
Do not put .wav files in a `tex-` package, the prefix is for texture packages only. (Actually it should only be used for well-formated texture packages as we might be more strict about the file hierarchies inside `map-` and `tex-` packages in the future.) Maybe use `res-` as a prefix for generic map resources.

**Comment by illwieckz** [comment]
hmmm, OK, because I need to create a common packages with many files, not only textures, and they are messy like Tremulous was…

**Comment by illwieckz** [comment]
We need this to be able to build against lossless assets and ship lossy assets without having to patch the _entities_ lump inside the bsp.

Building against lossless assets is needed in some case (like _alphashadow_ textures), so it better to allow it in general. All convert-able assets must be extension independent.
