### ISSUE TITLE
0.37.0 does not build (undeclared identifiers)

### ISSUE THREAD

**Issue by hasufell** [Unvanquished/Unvanquished#646]
```
/var/tmp/paludis/games-fps-unvanquished-0.37.0/work/unvanquished-0.37.0/src/engine/client/cl_main.cpp:424:75: error: use of undeclared identifier 'CG_VOIP_STRING'; did you
      mean 'CS_VOTE_STRING'?
                                const char *players = (char*) VM_ExplicitArgPtr( cgvm, VM_Call( cgvm, CG_VOIP_STRING, 0 ) );
                                                                                                      ^~~~~~~~~~~~~~
                                                                                                      CS_VOTE_STRING
/var/tmp/paludis/games-fps-unvanquished-0.37.0/work/unvanquished-0.37.0/src/engine/client/../qcommon/../../common/cm/../../engine/renderer/../../engine/botlib/../../gamelogic/shared/bg_public.h:72:3: note: 
      'CS_VOTE_STRING' declared here
  CS_VOTE_STRING = CS_VOTE_TIME + NUM_TEAMS,
  ^
/var/tmp/paludis/games-fps-unvanquished-0.37.0/work/unvanquished-0.37.0/src/engine/client/cl_main.cpp:424:60: error: use of undeclared identifier 'VM_Call'
                                const char *players = (char*) VM_ExplicitArgPtr( cgvm, VM_Call( cgvm, CG_VOIP_STRING, 0 ) );
                                                                                       ^
/var/tmp/paludis/games-fps-unvanquished-0.37.0/work/unvanquished-0.37.0/src/engine/client/cl_main.cpp:445:27: error: use of undeclared identifier 'CG_CROSSHAIR_PLAYER'
                                        val = VM_Call( cgvm, CG_CROSSHAIR_PLAYER );
```

**Comment by Amanieu** [comment]
It seems VOIP support is broken, you can disable it in cmake.

**Comment by DolceTriade** [comment]
cd8d89c9accac6fcddb3be8d62ba6efd3be67deb This commit removed it.

**Comment by Kangz** [comment]
VOIP is broken anyway... do we really want to fix compilation with USE_VOIP?

**Comment by Viech** [comment]
Well that's why it's either a build bug or a missing audio feature. :wink: 

I *really* want ingame VoIP in the long run, but I think we might be better off doing that from scratch, anyway.

**Comment by Kangz** [comment]
I'd like to leave the code for now, would removing the option from the CMakeLists.txt be enough?

**Comment by Viech** [comment]
If the code is broken, maybe it would be better to remove it and revert the removal on a topic branch?

**Comment by harmonise** [comment]
What was the decision regarding ingame VOIP? I've noticed that the option for enabling VOIP in CMake is still available.

**Comment by Kangz** [comment]
The decision was to not use it, but keep the code around as long as it is convenient, as a model for a possible future implementation.

**Comment by Viech** [comment]
That would be best on a topic branch though, were there's a revert of a commit made to master where the code is being removed. Let's not store old and unused code in master's HEAD.

**Comment by Kangz** [comment]
Makes sense, I'll do that

**Comment by Kangz** [comment]
Done in 4ec51b54c5579674d28c9d8562ea6073dedb8f7f

**Comment by Viech** [comment]
@Kangz is now known as NUKEMASTER 2000!
