### ISSUE TITLE
Packaging Engine Binaries

### ISSUE THREAD

**Issue by Infini7y77** [Unvanquished/Unvanquished#648]
I am working on packaging an rpm of alpha 37, can you provide a list of the 'helper' binaries/libraries needed for the game engine? (and if possible, a simple description of each)

So far, including:
* cgame-native-dll.so
* sgame-native-dll.so

And wondering about:
* irt_core-x86_64.nexe
* nacl_helper_bootstrap
* nacl_loader
* cgame-native-exe
* cgame-x86_64-stripped.nexe
* cgame-x86_64.nexe
* sgame-game-native-exe
* sgame-x86_64-stripped.nexe
* sgame-x86_64.nexe

**Comment by Amanieu** [comment]
The .so files should not be packaged, they are only used for development. Here is the list of files included in the archlinux package, which is a good reference since it is maintained by one of the developers:
```
/etc/conf.d/unvanquished.conf
/etc/unvanquished/maprotation.cfg
/etc/unvanquished/server.cfg
/usr/bin/unvanquished
/usr/bin/unvanquished-tty
/usr/lib/systemd/system/unvanquished.service
/usr/lib/unvanquished/daemon
/usr/lib/unvanquished/daemon-tty
/usr/lib/unvanquished/daemonded
/usr/lib/unvanquished/irt_core-x86_64.nexe
/usr/lib/unvanquished/nacl_helper_bootstrap
/usr/lib/unvanquished/nacl_loader
/usr/share/applications/unvanquished.desktop
/usr/share/icons/hicolor/128x128/apps/unvanquished.png
/usr/share/licenses/unvanquished/COPYING.txt
/var/lib/unvanquished-server/config/server.cfg
/var/lib/unvanquished-server/game/maprotation.cfg
/usr/share/unvanquished/pkg/map-antares_a04+1.pk3
/usr/share/unvanquished/pkg/map-antares_a04.pk3
/usr/share/unvanquished/pkg/map-chasm_b1+2.pk3
/usr/share/unvanquished/pkg/map-forlorn_a12.pk3
/usr/share/unvanquished/pkg/map-parpax_d05.pk3
/usr/share/unvanquished/pkg/map-perseus_b5a+1.pk3
/usr/share/unvanquished/pkg/map-plat23_b13+1.pk3
/usr/share/unvanquished/pkg/map-spacetracks_1.0+1.pk3
/usr/share/unvanquished/pkg/map-station15_1.0+1.pk3
/usr/share/unvanquished/pkg/map-station15_1.0.pk3
/usr/share/unvanquished/pkg/map-thunder_b3+2.pk3
/usr/share/unvanquished/pkg/map-yocto_b2c+1.pk3
/usr/share/unvanquished/pkg/md5sums
/usr/share/unvanquished/pkg/md5sums0.37
/usr/share/unvanquished/pkg/tex-all_2.0.pk3
/usr/share/unvanquished/pkg/tex-common_2.0.pk3
/usr/share/unvanquished/pkg/tex-ej01-clean_1.0.pk3
/usr/share/unvanquished/pkg/tex-ej01-common_1.0.pk3
/usr/share/unvanquished/pkg/tex-ej01-ice_1.0.pk3
/usr/share/unvanquished/pkg/tex-ex_1.0.pk3
/usr/share/unvanquished/pkg/tex-exm_1.0.pk3
/usr/share/unvanquished/pkg/tex-pk01_1.0.pk3
/usr/share/unvanquished/pkg/tex-pk02_1.0.pk3
/usr/share/unvanquished/pkg/tex-space_1.0.pk3
/usr/share/unvanquished/pkg/tex-tech_1.0.pk3
/usr/share/unvanquished/pkg/tex-trak5_1.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.35.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.36.0.pk3
/usr/share/unvanquished/pkg/unvanquished_0.37.0.pk3
```
On 32-bit x86, the only difference is that irt_core-x86.nexe is included instead of irt_core-x86_64.nexe.

/usr/bin/unvanquished and /usr/bin/unvanquished-tty are simple wrapper scripts that call the engine with the correct paths as parameters. You can find all of these files in the archlinux directory in our git repository.

**Comment by Viech** [comment]
The configs and starters shipped with Arch Linux can be found [here](https://github.com/Unvanquished/Unvanquished/tree/master/archlinux). Have a look at the PKGBUILDs for the [game](https://aur.archlinux.org/packages/un/unvanquished/PKGBUILD) and its [assets](https://aur.archlinux.org/packages/un/unvanquished-data/PKGBUILD), too. Note that for the former there's also an install script in the [tarball](https://aur.archlinux.org/packages/un/unvanquished/unvanquished.tar.gz) that changes a few file permissions, among other things.

There's no need to ship `[cs]game-native-dll.so` or any other `[cs]game-*` binary in a release version as the gamelogic is already shipped in the latest `unvanquished_*.pk3` in the form of a NaCl container. You can disable compilation of the gamelogic by passing `-D BUILD_GAME_NACL=OFF -D BUILD_GAME_NATIVE_DLL=OFF -D BUILD_GAME_NATIVE_EXE=OFF` to cmake.

**Comment by Infini7y77** [comment]
Thank you, this helps.  

I had included the *.so in alpha 36 package as the other vm.game.type's where not working.
I have since partially resolved the issue, which seems to be in the building of the "irt_core-x86_64.nexe", where the build service is stripping /tweaking it, thus 'corrupting' it.  As when I overwrite with the unversal zip version, all works.  

Is there any special flags to consider for this binary's compiling, to possibly mitigate this (I also figuring out how to possibly disable the stripping)?

**Comment by Amanieu** [comment]
irt_core-x86_64.nexe is not compiled, it is copied from the NaCl SDK. It is generated by a special compiler, and therefore should be treated as a data file rather than a binary, and it should definitely not be stripped.

A similar problem occurred for the Arch Linux package, so we had to disable automated stripping for the entire package since the package format did not allow selectively disabling stripping. Ideally only irt_core-x86_64.nexe should be excluded from stripping.

**Comment by Infini7y77** [comment]
Then, if I may recommend, can this be packaged in the .pk3 like the cgame-x86_64.nexe files as data, and that will remove the concern and issue for future packaging?

**Comment by Viech** [comment]
@Amanieu: Any response?

**Comment by Amanieu** [comment]
While we could put them in pk3s, it would be a bad idea for several reasons:
- The nexes will have to be extracted anyways before being executed
- The irt_core version is strongly tied to the version of sel_ldr/nacl_loader being used. A mismatch will result in a crash.
- We package the sgame/cgame nexes in pk3s to allow them to be distributed through auto-download, but this does not make sense for irt_core since it is strongly tied to the engine.

**Comment by Infini7y77** [comment]
From a packaging POV, a few things you may consider:
* For openSUSE build service, statically linked binaries are frowned upon, as such, it is preferred to build all binaries from source (for multiple reasons, like security, deduplication, future maintenance or review)
* I have to tweak the build against the standard build 'lint' procedures.
* The NaCl vm is an odd middle ground, but if not built from source code, is to be considered as 'data', even if closely tied to engine. However, the build or packaging does stongly consider and provide version dependency to any (shared) component package.
* If the NaCl loader and core are put into a, say, vm.pk3 that is engine version dependent, the game engine extracts with a version check (a text file in .pk3) and runs or errors out.  This way the distribuition packaging is not concerned with what NaCl files are needed, but just a .pk3

**Comment by harmonise** [comment]
Closing. Please consider re-opening if any specific actions need to be taken.
