### ISSUE TITLE
Upgrade to Unity engine

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#651]
- It's PROprietary.
- It has JavaScript and C#.
- Fully dynamic lighting with real-time ambient occlusion.
- Proper, human-orientated level editor.

**Comment by illwieckz** [comment]
```
02-28 23:07:09 <lamefun>     Upgrade to C#!
02-28 23:08:05 <lamefun>     Upgrade to Unity engine! It has C#! And JavaScript! And proper level editor!
03-01 00:18:48 <Ziginox>     oh god unity
03-01 00:18:53 <kharnov>     lol
03-01 00:56:03 <spudwebb>    lamefun needs to stop trolling
```

So, you already had your answer. But you can [try that if you want](https://github.com/Unvanquished/Unvanquished/fork).
