### ISSUE TITLE
Broken Gravity

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#652]
Every map config I have, specified g_gravity as 800. 

This is just in case I decide to insert a  low gravity map in the rotation.

Sometimes when a map loads, gravity behaves as if set to zero. I check on rcon and g_gravity is 800.
Changing it has no effect. This issue is very infrequent, but disruptive.

Thanks.

**Comment by Viech** [comment]
In fact, `g_gravity` is used so inconsistently that the only option I see is to completely remove it. We can consider adding it back once our physics code has been refactored. (Just like water, really.)

**Comment by overvolting** [comment]
Hi, I've noticed this ONLY happens on spacetracks.
Odd.

**Comment by overvolting** [comment]
It's still happening in 0.39. Everytime on spacetracks.

**Comment by ckol** [comment]
Additionally: The gravity setting doesn't seem to affect the gravity of a grenade or firebomb at all. Someone can set gravity to 0 and the bombs drop as usual.

**Comment by Viech** [comment]
That's what I mean with it's used so inconsistently. Some "physics" uses it, some doesn't. It's ridiculous. The only future of `g_gravity` is getting deleted.

**Comment by slipher** [comment]
Fixed by #1503.
