### ISSUE TITLE
Ready icon doesn't show

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#653]
At the end of the game, since 0.37, nobody can ready-up.

**Comment by DolceTriade** [comment]
So you must wait the full 30seconds to proceed to the next map or the "ready" icon doesn't show?

**Comment by overvolting** [comment]
The ready icon doesn't show.

**Comment by Viech** [comment]
Setting `A-Engine` since assignment implies that this may be NaCl related, though this pretty much looks like a UI bug.

**Comment by neumond** [comment]
Please recheck this issue still affects you.

**Comment by Viech** [comment]
@neumond, did you fix this? If yes please close the issue with a reference to the commit (you can do this from within the commit message, too, just add a line that says `This fixes #653.`). I didn't experience the issue during the dev game, which where held on

**Comment by neumond** [comment]
I didn't fix it intentionally, just made cleanup of scoreboard updating code along with flickering issue. Time of opening this issue is a bit later of my commit push, I thought this issue caused by my changes. But since you and I don't experience any problems here, I'm closing this bug.
