### ISSUE TITLE
Scoreboard is empty or shows bad content.

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#654]
Sometimes the game end scoreboard is empty and shows no players even though they are on the server.

It might have happened because I was holding the shift key to pull up the scoreboard when the game ended or it might be unrelated.

**Comment by Viech** [comment]
Have a look at #668 for more scoreboard problems.

**Comment by Viech** [comment]
Could this be a regression with Alpha 37? Or did you experience this earlier, too?

**Comment by overvolting** [comment]
These symptoms began with 0.37

**Comment by Viech** [comment]
In that case it can be an engine issue, poking @Kangz and @Amanieu.

**Comment by Kangz** [comment]
I don't see how it would be related to NaCl :S

**Comment by DolceTriade** [comment]
Does this still happen?

**Comment by overvolting** [comment]
ill keep an eye out.

**Comment by overvolting** [comment]
I haven't seen it happen again, closing.
