### ISSUE TITLE
Debian packages ate my config files

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#655]
When the debian packages are installed, they delete existing config files.

I lost server.cfg and maprotation.cfg

**Comment by lamefun** [comment]
That's the price you pay for "freedom". Use PROprietary software!

**Comment by Viech** [comment]
I'll leave this open for a while as the package maintainer was assigned but I'd prefer if distribution issues that the active Unvanquished team can't do anything about were handled at the respective sites (i.e. debian or by mailing the maintainer) as this fills our trackers with issues we can't resolve.

**Comment by overvolting** [comment]
1. I might disagree with the statement: 'the active Unvanquished team can't do anything about'.
2. These aren't official debian packages, not associated with debian.

**Comment by DolceTriade** [comment]
He's not really responsive.

**Comment by Viech** [comment]
If the debian package deletes/resets files on update that's entirely a problem in the packaging and not in the Unvanquished code. If the package maintainer isn't an active memeber of the Unvanquished team, then the active Unvanquished team really can't do anything about this, except contacting the package maintainer. :stuck_out_tongue:

**Comment by Viech** [comment]
Got to close this to reduce the issue heap. Please contact @dsalt directly about this.
