### ISSUE TITLE
Noclip and travelling off map blinds you

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#660]
Refer to: http://postimg.org/image/z4e2on30l/

preferred behavior is you can still see everything.

**Comment by Kangz** [comment]
It isn't a bug for many reasons:
1 - we do not clear the sceen each frame as an optimization, although it is debatable given recent GPU architectures have 0 bandwidth clears
2 - We do not have vis data outside of the map
3 - Noclip outside of the map isn't a supported feature, it is a cheat to be used for development only

Closing as won't fix.

**Comment by Viech** [comment]
`r_clear` still exists but defaults to off. As a mapper I'd prefer if everything was in vis if outside map boundaries but I think/agree that we shouldn't afford an issue for this right now.
