### ISSUE TITLE
sensor_player entity is broken (currently maps must stick on deprecated definitions instead)

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#663]
Hi, as revealed [in this thread](http://forums.unvanquished.net/viewtopic.php?f=9&t=1767&p=15686#p15686), only the deprecated entity code work.

Since 2014-04-30  `sensor_player` is known to not fire since it's written in a comment in [this code here](https://github.com/Unvanquished/mapeditor-support/blob/bcf6e68406142b37deea009fcfe5576afb6cc412/src/entities/entities.yaml#L1882) and I can reproduce this bug today.

[This file references the obsolete code](https://github.com/Unvanquished/mapeditor-support/blob/e95f2501c3b074fc36e3f8ddc7835efaa5fe4e44/src/entities/entities.yaml#L1521), and if I replace entity code like `trigger_multiple` by the new one `sensor_player`, the map logic (door opening for example) is broken.

**Comment by illwieckz** [comment]
As seen in #664, this new entity code is not used by official maps, so new code is dead code, which is not good at all.

**Comment by Viech** [comment]
If you could help us to port the new maps we (you?) could remove the deprecated code and we could find and fix the remaining bugs. :grinning: 

To be honest in the [last map upgrade batch](https://forums.unvanquished.net/viewtopic.php?f=67&t=1444) I coordinated I didn't have the energy left to also include the entities. We really owe this to @t4im though.

**Comment by t4im** [comment]
It's probably just a slip in https://github.com/Unvanquished/Unvanquished/blob/master/src/gamelogic/sgame/sg_spawn_sensor.cpp#L492
Can't test it atm, but looks like that should be `qtrue`

**Comment by Viech** [comment]
Omg you live! :3

**Comment by illwieckz** [comment]
yes, qtrue at this line fix many issues, but I have one remaining bug in pulse map. When I touch the texture to trigger the main door opening, the opening sound is heard, but the door does not open…

**Comment by Kangz** [comment]
@t4im we have C++ in the gamelogic now :3

**Comment by illwieckz** [comment]
The main door opening bug in pulse is probably related to the “wait” keyword.
