### ISSUE TITLE
in preferences window, height and width must be changed before going fullscreen

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#666]
How to reproduce bug:

* Launch unvanquished windowed with non standard full screen resolution (it's ok since you are not full screen)
* Open preferences
* Change resolution to full screen standard resolution (it will be done only after the user validates the form)
* Tick the full screen toggle (done immediately)

So Unvanquished reopens itself fullscreen with a non-standard resolution (so you can break your screen). If you are unlucky, the non(standard resolution prevent the game to be displayed so you can't validate the resolution you have typed.

The only fix is to kill unvanquished then edit `autogen.cfg`, unless that, unvanquished will reopen badly next time since the bad screen resolution was not changer and unvanquished is now configured to open full screen.

It's good to not have `r_fullscreen` needing `vid_restart` since it's good to be able to do `<Alt-Enter>` when we are fullscreen without doing `vid_restart`, but the preference menu must wait the height and the width to be known before going fullscreen.

**Comment by lamefun** [comment]
Unvanquished should behave like sane software: W/H setting only used for fullscreen, allow free resizing & remember position when not in fullscreen.

**Comment by DolceTriade** [comment]
Well, I think Unvanquished will try safemode or something if there is a visual crash. Not sure if that still happens.

**Comment by illwieckz** [comment]
Hi, this is what happen to my screen when I tick full screen tick box before applying new resolution:

[![Unvanquished bad screen](http://dl.illwieckz.net/r/Kelehe5r/20150405-222337.unvanquished-bad-screen.thomas-debesse.720.jpg)](http://dl.illwieckz.net/r/Kelehe5r/20150405-222337.unvanquished-bad-screen.thomas-debesse.jpg)

**Comment by DolceTriade** [comment]
yikes. Does vid_restart fix?

**Comment by illwieckz** [comment]
Yes, doing that fix the display:

```
set r_customWidth 1920
set r_customHeight 1080
vid_restart
```

The problem is the GUI allows to do that:

```
set r_customWidth 1920
set r_customHeight 1080
set r_fullscreen 1
vid_restart
```

So the game goes fullscreen before `vid_restart`, so the games goes fullscreen before switching resolution.

**Comment by DolceTriade** [comment]
Interesting. It should be a latched value :-/

**Comment by Viech** [comment]
Still not as fun as the bug where I saw parts of a browser window as a wall texture ingame.
