### ISSUE TITLE
Can't join a game - bad 'snapshot number'

### ISSUE THREAD

**Issue by feresum** [Unvanquished/Unvanquished#674]
On a Visual Studio build (Windows 7) from master, I can't join any type of game, regardless of `vm.cgame.type`. It quits around the time the map finishes loading. It errors on cg_snapshot.cpp:384, after checking an apparently uninitialized value (0xcccccccc).

    Error: CGame VM: CG_ProcessSnapshots: n (-858993460) < cg.latestSnapshotNum (0)

Commenting out the error line did not help either :)

**Comment by Amanieu** [comment]
Fixed by 55e479a

**Comment by Kangz** [comment]
Thanks @gmcode for finding the rootcause!
