### ISSUE TITLE
Debian unvanquished-server script pass +args before user -args

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#676]
Hi, if you do something like that:

```
unvanquished-server -homepath /path
```

The script will do something like that:

```
unvanquishedded +exec server.cfg -homepath /path
```

So, the user can't change the homepath.

Easy fix:

```diff
> exec /usr/lib/games/unvanquished/unvanquishedded -libpath /usr/lib/games/unvanquished -pakpath /var/games/unvanquished/pkg +exec server.cfg "$@"
< exec /usr/lib/games/unvanquished/unvanquishedded -libpath /usr/lib/games/unvanquished -pakpath /var/games/unvanquished/pkg "$@" +exec server.cfg
```

**Comment by Viech** [comment]
Going to leave this open for a month, if it's not fixed by the next release please contact darren directly.

**Comment by Viech** [comment]
It should be noted that these engine limitations are kind of senseless. :stuck_out_tongue:

**Comment by Kangz** [comment]
They are, otherwise +set foo -a is ambiguous.

**Comment by Viech** [comment]
That's why posix makes use of `--`, `" "` and `\`. You could also go with `--enqueue "set foo -a; echo bar"` in addition to `--exec server.cfg` (and short forms of `-e` and `-x`) to avoid the confusing `+`/`-` distinction alltogether.

**Comment by Kangz** [comment]
I would be ok with changing command line args to be more like posix, yeah but I don't consider it to be that important. @Amanieu opinion on all this?

**Comment by Amanieu** [comment]
The main issue here is that +command are familiar to most people, I think they might get annoyed if we change the command-line arguments yet again.

A simple fix is to remove +command entirely and just have a -cmd "exec server.cfg" flag to execute arbitrary commands.

**Comment by Viech** [comment]
Let's change it one more time to be posix compliant, instead of fixing our own standard bit by bit. 50% of our users and 90% of the server operators will already know how it works…

**Comment by Amanieu** [comment]
In that case I have no objection

**Comment by Viech** [comment]
Created new issue #679 for the POSIX-compliance.

**Comment by Viech** [comment]
@dsalt hasn't been active on GitHub for three months now and the last time we could reach him via IRC is even longer ago. There seem to be quite a few issues with his packages and someone who uses debian and understands them should really send him a mail. Closing.
