### ISSUE TITLE
Can't see any server listings or scoreboard

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#678]
This just started, I have a feeling it might be linked to the debian package that just updated to version ~1.

I can see the empty windows, but no information for server listings (either internet or local lan) and for scoreboards.

Unvanquished is giving no errors or warnings on the cli or in console.

**Comment by overvolting** [comment]
This error fixed itself and I have no idea why.

**Comment by Viech** [comment]
Same version? Or did you update the client in between?

**Comment by overvolting** [comment]
no changes that i'm aware of
