### ISSUE TITLE
Don't show beacons above things that aren't behind walls

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#685]
It only makes the game ugly.

**Comment by illwieckz** [comment]
What makes the game ugly is also the fact they are too big, perhaps smaller beacons will be acceptable even if thing is visible.

**Comment by Viech** [comment]
I removed beacon occlusion handling for the time being to make them more visible for beacon development, which isn't complete yet. The visualization can certainly be improved further, but the current one is not a bug either. Please keep in mind that artistic and gameplay development aren't discussed on the issue tracker in general.
