### ISSUE TITLE
Buildable model and bounding box can mismatch severly.

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#688]
Sometimes when you build near a stairstep, it builds a fake building while the real building is invisible on top of the stair step.

**Comment by Viech** [comment]
This needs a better title, description and screenshots with visible bounding boxes (and I don't feel like doing it this time).

**Comment by lamefun** [comment]
Well... I'm frankly surprised that you still haven't noticed or got a report on that, this happens all the time. Eg. murderer's nano training layout has fake spikers.

![Fake Acid Tube](https://cloud.githubusercontent.com/assets/433585/6924433/2f7163fc-d7e1-11e4-8fdd-d6e4ff834aac.jpg)
![Fake Telenode](https://cloud.githubusercontent.com/assets/433585/6924437/337f261e-d7e1-11e4-9944-4a1fe7ead9c6.jpg)

**Comment by illwieckz** [comment]
Wow, impressive ! I never noticed that before. :open_mouth: 

But I remember one time when I was not able to deconstruct a structure near to a step while aiming it, I was only able to descontruct it while standing atop the step and aiming to my feet (so, through the invisible box between me and the rendered object.

**Comment by Viech** [comment]
I noticed it quite a lot and I was confused this wasn't yet reported but I didn't want the report as such to be an imprecise one-liner either. :stuck_out_tongue:
