### ISSUE TITLE
infinite funds bots don't buy >= chaingun

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#691]
I know bot code is not actively worked on however this may be an easy fix.
When g_bot_infinite_funds 1 is set, and the bots have full momentum, they buy bsuits but only buy chainguns.

Expected behavior would be to have them buy higher level weapons up to and including luci cannons.

**Comment by Viech** [comment]
I'm really sorry, bots are so unfinished we can't afford to track minor issues for them. (I'm pretty sure this isn't easy to fix as they don't yet know how to use the lucifer cannon to begin with…)
