### ISSUE TITLE
Offset mapping

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#692]
Xonotic has offset mapping that makes textures look more real:

![Offset mapping](http://images.gamedev.net/gallery/20a62f6a97574c7499e6eec1e2f020d2_3.jpg)

Cyrsis 3 even has some magic algorithm that allows bump map to transcend polygon boundaries (look at the gaps between bricks).

![Magic](http://www.abload.de/img/24ifub.jpg)

**Comment by Kangz** [comment]
We have parallax mapping and tessellation (what is in crysis) is not something we will implement in the foreseeable future
