### ISSUE TITLE
Dynamic lighting

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#693]
Unvanquished looks outdated because while the models look modern, buildings don't cast shadows, when you build or move right next to a wall, reactor lights don't cast real light, etc.

https://www.youtube.com/watch?v=Wzar-a91Qkc

https://www.youtube.com/watch?v=FUYUNgr22m8 (this is open-source even!)

**Comment by Kangz** [comment]
Thank you for the links; GI is not something we will have in the foreseeable future and dynamic lights are planned, in some form.
