### ISSUE TITLE
Particle auto-softening not working for alll particles.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#695]
Please read the [forum thread](https://forums.unvanquished.net/viewtopic.php?f=4&t=1807) that reports the issue. It seems that we need to update our particle shaders.

**Comment by lamefun** [comment]
Isn't there a bug for it already: https://github.com/Unvanquished/Unvanquished/issues/415 ?

**Comment by Viech** [comment]
Yep, you're right, closing as a duplicate.
