### ISSUE TITLE
0.38 flickering UI and moving walls

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#698]
After about 5 minutes of play with version 0.38, all my UI elements start flickering[1] and the walls and floors start *breathing* and I can see gaps in the seams.

It is not playable since none of the UI can be seen properly.

* Breathing means this. Imagine there is a dog lying on the ground sleeping. You are a small flea sitting on it's chest. As the dog breathes, the chest distorts in a curved sort of way and then becomes flat again. Once every couple of seconds.  That's the 'breathing' effect I see for every floor and wall surface. They distort from flat to slightly spherical and bulging out and then back again, in synchronized fashion, once every 2 seconds or so. When their shape distorts, cracks emerge between them.

**Comment by kharnov** [comment]
I get this same thing. The way I can trigger this is by loading up Station15. Afterwards, it will happen on any other map.

**Comment by Viech** [comment]
I couldn't find `T-Hilarious-Feature` so I labeled this a bug.

It would be ideal if one of you could make a video or if @kharnov could link the screenshot sequence he did. Poking @gimhael since this may be related to recent renderer work by him.

**Comment by overvolting** [comment]
http://unvtraining.pw/breathing1.mp4

**Comment by Viech** [comment]
Should be fixed by 4f7fb33.

**Comment by Viech** [comment]
#700 says this isn't yet fixed.

**Comment by overvolting** [comment]
Here's an apitrace as requested by dolce. It's 600mb so I compressed it down to 207mb using xz.
http://unvtraining.pw/daemon.trace.xz

**Comment by gimhael** [comment]
The shaders in that trace file are still the pre-4f7fb33 shaders.

**Comment by Viech** [comment]
@DolceTriade there's your trace.

**Comment by Kangz** [comment]
@overvolting can you check with current master? It seems you didn't have the fix when recording that trace.

**Comment by overvolting** [comment]
How can I check? Because I did a 'git pull' to get the master, went into the Unvanquished/build dir and ran 'cmake ..' and 'make -j 10'.

I then proceeded to use traceapi to run this command line: ./daemon -libpath /usr/lib/games/unvanquished -pakpath /var/games/unvanquished/pkg -homepath /home/user/.unvanquished/ -libpath ./

**Comment by DolceTriade** [comment]
Ah do this in your build dir
```
mkdir pkg
ln -s ../main git_git.pk3dir
./daemon -libpath /usr/lib/games/unvanquished -pakpath /var/games/unvanquished/pkg -pakpath pkg -homepath /home/user/.unvanquished/ -libpath ./
```

**Comment by overvolting** [comment]
Ok, i've done a git pull, make clean, cmake, make -j, and linked main into the build dir as suggested. It still occurs I'm compressing the trace now.

**Comment by Viech** [comment]
I think it's missing a `cd pkg` and `cd ..` before and after the `ln -s ../../main git_git.pk3dir` (note the added `../`) but since the `-set fs_extrapaks git` doesn't throw an error it seems that somehow dæmon found the pk3dir anyway. Your third line looks weird @DolceTriade, why setting `libpath` to `/usr/lib/games/unvanquished` first? `./daemon -pakpath /var/games/unvanquished/pkg -set fs_extrapaks git` should really be all that's needed.

**Comment by DolceTriade** [comment]
I copied his command and added my extra flags. but yes, I am missing the cd pkg and cd ..
Thanks, fixed.

**Comment by Viech** [comment]
You didn't actually fix it. :stuck_out_tongue:

**Comment by DolceTriade** [comment]
Why not? I fixed the relative path or do symlinks not work like I think they do.

**Comment by Viech** [comment]
Sorry, was looking for `cd` commands.

**Comment by overvolting** [comment]
Ok this seems to be fixed, closing.
