### ISSUE TITLE
weird behavior from /dir

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#706]
Not sure if it is intended, however sometimes I do a /dir /maps and I see maps,
sometimes I do a /dir /maps and it tells me no such dir found.

In fact this error happens frequently with all sorts of directories that I know exist.

**Comment by Viech** [comment]
It would depend on what pk3(dir)s are currently loaded. Check `listPaths` to see if the source that contains your directory is loaded. For example, in the main menu no map is loaded until you open the "Start local/LAN game" menu. Please report back if that explains your issue or not.

**Comment by overvolting** [comment]
but I have a /maps in every one of my unvanquished directories.. shouldn't /dir provide a listing of local maps not in pk3s?

**Comment by Kangz** [comment]
After trying I think what happens is the following:
 - ```/dir /maps``` never works
 - ```/dir maps``` works ingame but not when in the main menu. I think this is the expected behavior as when you do ```/listPaths``` in the main menu you see that no map pk3 is loaded.

So unless there is something else, I think this is the expected behavior; if you want to see a list of maps you can tab complete ```/map ```

**Comment by Viech** [comment]
> but I have a /maps in every one of my unvanquished directories.. shouldn't /dir provide a listing of local maps not in pk3s?

I'm not even sure if loose files not in pk3(dirs) are loaded at all. If they are, but `dir` doesn't list them, that would be an issue. If they aren't, then everything works as expected and you would need to put your loose files into pk3dirs and load those explicitly. Can you load any of these "loose" maps @overvolting?

**Comment by overvolting** [comment]
]/dir / 
In Paks: 
-------- 
ERROR: Path does not exist 
 
 
In Homepath 
----------- 
game-x86_64.nexe 
conhistory 
demos/ 
lock 
pkg/ 
cgame-x86_64.nexe 
sgame-x86_64.nexe 
hunkusage.dat 
conhistory_server 
crashlog.txt 
game/ 
daemon.log 
maps/ 
config/ 
screenshots/ 
pubkey 
]dir maps 
In Paks: 
-------- 
ERROR: Path does not exist 
 
 
In Homepath 
----------- 
]

**Comment by overvolting** [comment]
It seems to me I see a message telling me that maps/ exists in Homepath, however a dir maps does not work. Is that not inconsistent?

**Comment by overvolting** [comment]
Ok I'll check it out in more detail when I have more time.

**Comment by bmorel** [comment]
The `dir maps` command shows the content of the currently loaded mods, I believe. To me, it seems to work as intented.
