### ISSUE TITLE
Regression in commit e882322f9 

### ISSUE THREAD

**Issue by aslaq** [Unvanquished/Unvanquished#708]
After commit e882322f9, I cannot start a LAN server or join any server.

Here is the log for runs after this commit http://pastebin.com/aLVCBesz

Am not sure am not missing something but the game runs without errors in the previous commits

**Comment by Viech** [comment]
Hello, thanks for the report!

We just found out that said commit breaks gamelogic/engine compatibility. As a workaround to start a local game you can load a self-compiled gamelogic: Make sure `BUILD_GAME_NACL_NATIVE_DLL` is enabled in (c)cmake, then after compilation launch daemon with `-set vm.cgame.type 3 -set vm.sgame.type 3` as arguments (and `-set vm.cgame.debug 1  -set vm.sgame.debug 1` if you want to attach a debugger). Note that this won't let you connect to remote servers. If this still gives you any errors, please report back!

**Comment by Viech** [comment]
Fixed in 46fa390.

**Comment by aslaq** [comment]
Thanks and sorry, apparently am not receiving notifications on email but anyways :)
