### ISSUE TITLE
Texture moving on Intel GPU

### ISSUE THREAD

**Issue by Faelian** [Unvanquished/Unvanquished#709]
I have an Intel HD 5000, and most of the textures appears broken.
I am running elementray OS freya beta (based on Ubuntu 14.04).
I dont really know how to explain so here is a link with a screencast that show the effect.

https://drive.google.com/file/d/0B-Zgdy7JIRncaFNNMlA1OWNxUDQ/view?usp=sharing

It's not a new bug, I think it has appears near decembre 2013, with the alpha that brings a lot of changes like a "natural selection" styled menu, and all that good stuff. But I never taked time to report it.

log :
http://0bin.net/paste/okabr7PWvHAj4mWz#MtTrOe2m2BxOFLE+Wt2+0gNvr9hCMab7pd2y8XwcSW6

Feel free to ask me more info if you need.

**Comment by Kangz** [comment]
Thanks for the report!

From the logs, everything seems to be fine. You could try updating Mesa, 10.3 is a bit old. Otherwise it seems some of the map's textures are rendered only once and then what we see would be the bloom, slightly broken and ping-ponging of render targets?
Could you take a video with r_clear set to 1? I should replace the crazy moving background to be black and would make it more readable so we can better see what is not being drawn.

FYI issue will be tricky to fix so we will probably need some back and forth to solve it.

**Comment by Faelian** [comment]
Sure,

2 questions : 
- how do I install a more recent version of mesa ?
apt-get update && apt-get upgrade didn't change it and I don't know what to pick in apt-cache search mesa : 
http://0bin.net/paste/xTsG4i8c72J0ce7w#9L5XJrFP2-juZMm7QhMQfLhQOgVVmmqWKEilrNQgI+1

How do I set r_clear to 1 ?

**Comment by Viech** [comment]
Mesa 10.3 is known to be broken in Unvanquished and produces errors similiar to yours. Upgrading Mesa to 10.5 (potentially also 10.4.n for a certain n > 0) or downgrading to 10.2 should fix your problem. See #465 for the original report.

Unfortunately I wouldn't know how to upgrade Mesa on your platform, maybe you can ask the community of your OS about it.

To enable `r_clear` temporarily, open the console ingame (`SHIFT`+`ESC`, maybe also `^` and/or `~`) and enter `set r_clear 1`.

Please report back whether upgrading Mesa fixed your problem!

**Comment by Schroeffu** [comment]
Upgrade to MESA 10.6.0+ with ElementaryOS Freya should be possible this way: https://elementaryforums.com/index.php?threads/how-to-upgrade-mesa.197/

**Comment by Faelian** [comment]
I will be able to test that in a few weeks. And I will tell you then.
It looks "a lot" like #465, I tend to think it's the same bug.

**Comment by Viech** [comment]
Yeah I'm pretty sure it's that, too. I'm just going to close this, feel free to re-open if the issue persists on newer mesa, no need for you to report back otherwise.
