### ISSUE TITLE
Can't cross-compile from Linux to Windows using MinGW

### ISSUE THREAD

**Issue by maek** [Unvanquished/Unvanquished#713]
Following the instructions in the Readme I obtain the following error:

```
[  0%] Generating CMakeFiles/cgame-nacl.dir/unzip.o
/tmp/Unvanquished/external_deps/mingw32-3/pnacl/bin/pnacl-clang.bat: line 1: @echo: command not found
/tmp/Unvanquished/external_deps/mingw32-3/pnacl/bin/pnacl-clang.bat: line 2: syntax error near unexpected token `('
/tmp/Unvanquished/external_deps/mingw32-3/pnacl/bin/pnacl-clang.bat: line 2: `:: Copyright (c) 2012 The Native Client Authors. All r'ghts reserved.
CMakeFiles/cgame-nacl.dir/build.make:697: recipe for target 'CMakeFiles/cgame-nacl.dir/unzip.o' failed
make[2]: *** [CMakeFiles/cgame-nacl.dir/unzip.o] Error 2
CMakeFiles/Makefile2:91: recipe for target 'CMakeFiles/cgame-nacl.dir/all' failed
make[1]: *** [CMakeFiles/cgame-nacl.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

I suppose the build process shoudn't try to run a .bat in Linux, so I changed the CMakeLists.txt at line 154:

```
-   set( PNACL_BIN_EXT ".bat" )
+   set( PNACL_BIN_EXT "" )

```

Now the error is:

```
[  0%] Generating CMakeFiles/cgame-nacl.dir/unzip.o
pnacl-clang: Could not find PNaCl host directory for clang
CMakeFiles/cgame-nacl.dir/build.make:697: recipe for target 'CMakeFiles/cgame-nacl.dir/unzip.o' failed
make[2]: *** [CMakeFiles/cgame-nacl.dir/unzip.o] Error 255
CMakeFiles/Makefile2:91: recipe for target 'CMakeFiles/cgame-nacl.dir/all' failed
make[1]: *** [CMakeFiles/cgame-nacl.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

Any suggestion?

**Comment by Amanieu** [comment]
Building the NaCl gamelogic is not supported while cross-compiling. You can disable it by turning off BUILD_GAME_NACL in cmake.

**Comment by Viech** [comment]
The gamelogic is platform-independent, shouldn't it be built anyway? Otherwise, what you just said should be printed as the error.

**Comment by maek** [comment]
> Building the NaCl gamelogic is not supported while cross-compiling. You can disable it by turning off BUILD_GAME_NACL in cmake.

I confirm that disabling the gamelogic passing `-DBUILD_GAME_NACL=0` to cmake makes the cross-compilation work on Linux. I would suggest you to update the Readme in order to reflect this.

**Comment by maek** [comment]
> The gamelogic is platform-independent

@Viech Do you mean I can use the one compiled natively on Linux also for Windows?

**Comment by Amanieu** [comment]
The NaCl gamelogic uses a custom compiler that is located in external_deps/ and generates a platform-independent executable. Unfortunately the Windows version of the compiler (which is used when you cross-compile) will not run on Linux. This isn't a big problem because these can be generated using the Linux-native compiler.

**Comment by Viech** [comment]
So this is something that could be done in cmake? In that case this is either a *missing* (cmake should really do that given that the gamelogic is needed) or *verbosity* type (the error doesn't explain what you need to do) of issue.

**Comment by Viech** [comment]
Is that really a fix, given that the gamelogic is missing? Can't it be produced by the local toolchain? I'd agree when it comes to `BUILD_GAME_NATIVE_DLL` and/or `BUILD_GAME_NATIVE_EXE`.

**Comment by Amanieu** [comment]
You'll need to use a native build to build the nacl gamelogic, but you can still cross-compile the native exe/dll versions of the gamelogic.

**Comment by Viech** [comment]
Sounds good enough to me. May need a mention in the readme though.
