### ISSUE TITLE
Warning XML parse error on line 1 of .

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#714]
Warning XML parse error on line 1 of .

I'm having this spammed, so was another player. It got less common after a while, then triggered at random.

**Comment by DolceTriade** [comment]
This would be a librocket error. What HUD is visible when this happens?

**Comment by lamefun** [comment]
I've had the same thing. Aside from the spam, everything worked normally.

**Comment by DolceTriade** [comment]
But, which HUD is visible? It basically means there is a syntax error with some of the HUD elements.

**Comment by overvolting** [comment]
we were on the human team

**Comment by DolceTriade** [comment]
Anything else you can describe about what was going on? Weapon? Location on the map? Items? etc?

**Comment by overvolting** [comment]
Map: chasm
Layout: custom
Weapon: any
Location: various
Items: any
players: at least 2 in the same game at different times.

I'll report back if I notice it again.

**Comment by harmonise** [comment]
Can we confirm that users are still experiencing this issue?

**Comment by Viech** [comment]
I haven't heard this was witnessed again, closing.

**Comment by illwieckz** [comment]
I just reproduced it, I've bound the `<` key as _sprint_ key and I guess this continuously warning displayed, of course that character is not displayed in the key option window.

The bind works, I guess it's just an issue of this character not being converted to `&lt;` before being displayed. I guess the same issue would occur with `>` and we would have to convert it to `&gt;` before displaying ti.

**Comment by DolceTriade** [comment]
hm, ok. maybe we need an HTML escape function or something

**Comment by slipher** [comment]
I don't get any problem now with binding `char:<` (and tutorial on). Possibly fixed by d2aaff7245b29e5943d09eb510be14915837771b which turned on escaping in more places. 

To future readers: 
If you see `Warning XML parse error on line 1 of .`, that just means there is an error anywhere in the markup. It is probably not related to past errors with this message. Open a new issue instead of recycling this one.
