### ISSUE TITLE
Everything is white

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#720]
I can't see the map or players and everything is white, as of May 8 on master. It looks like this: http://imgur.com/cXuYBs6

After a `vid_restart` things will render normally for a few seconds, but then it all goes white again. Only a few random things were visible like shadows, 2d graphics, the skybox, and the new overmind.

I'm using Radeon on Windows 7.

**Comment by Viech** [comment]
@gimhael please have a look.

**Comment by DolceTriade** [comment]
Do you think you could get an API trace?

**Comment by slipher** [comment]
I updated the driver and the issue no longer appears.
