### ISSUE TITLE
Error: File "map-parpax_d04_d73404b8" not found on server for autodownloading.

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#722]
Start a 0.39 client.
Type /devmap plat23 (or any map name)

Get this error:
Error: File "map-parpax_d04_d73404b8" not found on server for autodownloading.

Then I get booted to the main screen again.

**Comment by Amanieu** [comment]
can you give a console log?

**Comment by overvolting** [comment]
See below for a couple of occurrences. Also note I cannot reproduce it anymore.

readconfig: could not open admin config file admin.dat                                                                   
Warning: "colorGrade" deprecated. Please use "gradingTexture"                                                            
==== Bot Navigation Initialization ====                                                                                  
 loading navigation mesh file 'maps/plat23-builder.navMesh'...                                                           
 loading navigation mesh file 'maps/plat23-level0.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-level1.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-level2.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-level2upg.navMesh'...                                                         
 loading navigation mesh file 'maps/plat23-level3.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-level3upg.navMesh'...                                                         
 loading navigation mesh file 'maps/plat23-level4.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-human_naked.navMesh'...                                                       
 loading navigation mesh file 'maps/plat23-human_bsuit.navMesh'...                                                       
0 groups with 0 entities                                                                                                 
maprotation.cfg file not found.                                                                                          
-----------------------------------                                                                                      
-----------------------------------                                                                                      
clientDownload: 0 : beginning "map-parpax_d04_d73404b8"                                                                  
clientDownload: 0 : "map-parpax_d04_d73404b8" file not found on server                                                   
Error: File "map-parpax_d04_d73404b8" not found on server for autodownloading.
                                                                                                                         
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/git_git.pk3dir/'...                              
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/unvanquished_0.39.0.pk3'...                      
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.38.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.37.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.36.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'...                                                     
----- Server Shutdown -----                                                                                              
==== ShutdownGame ====                                                                                                   
IP: 127.0.0.1                                                                                                            
IP: 10.0.0.4                                                                                                             
IP6: ::1                                                                                                                 
IP6: 2601:6:5e00:40e8:21f:bcff:fe02:94e6                                                                                 
IP6: fe80::21f:bcff:fe02:94e6%eth0                                                                                       
Opening IP6 socket: [::]:*                                                                                               
Opening IP socket: 0.0.0.0:*                                                                                             
---------------------------                                                                                              
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/git_git.pk3dir/'...                              
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/unvanquished_0.39.0.pk3'...                      
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.38.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.37.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.36.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'...                                                     
Extracting VM module cgame-x86_64.nexe from /home/zod/downloads/unvanquished/Unvanquished/build/pkg/unvanquished_0.39.0.pk3...                                                                                                                 
Loading VM module cgame-x86_64.nexe...                                                                                   
][14749,3952662336:20:10:38.448725] Native Client module will be loaded at base address 0x00001a4100000000               
Loaded VM module in 53 msec                                                                                              
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf).                                                         
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf).                                            
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf).                                                     
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf).                                                   
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf).                                         
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf).                                       
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/git_git.pk3dir/'...                              
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/unvanquished_0.39.0.pk3'...                      
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.38.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.37.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.36.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'...                                                     
Calling GetRefAPI…                                                                                                       
                                                                                                                         
GL_VENDOR: X.Org                                                                                                         
GL_RENDERER: Gallium 0.4 on AMD CYPRESS                                                                                  
GL_VERSION: 3.0 Mesa 10.4.2                                                                                              
GL_SHADING_LANGUAGE_VERSION: 1.30                                                                                        
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16384                                                                                   
Using GPU vertex skinning with max 256 bones in a single pass                                                            
Extracting VM module cgame-x86_64.nexe from /home/zod/downloads/unvanquished/Unvanquished/build/pkg/unvanquished_0.39.0.pk3...                                                                                                                 
Loading VM module cgame-x86_64.nexe...                                                                                   
][14753,152434496:20:10:39.107176] Native Client module will be loaded at base address 0x000047d300000000                
Loaded VM module in 55 msec                                                                                              
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf).                                                         
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf).                                            
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf).                                                     
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf).                                                   
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf).                                         
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf).                                       
Loading pak '/home/zod/.unvanquished/pkg/map-karith_trem+3.pk3'...                                                    
Loading pak '/home/zod/.unvanquished/pkg/map-methane-beta1_trem+3.pk3'...                                             
Loading pak '/home/zod/.unvanquished/pkg/map-sirius_trem.pk3'...                                                      
Loading pak '/var/games/unvanquished/pkg/map-chasm_b1+2.pk3'...                                                          
Loading pak '/var/games/unvanquished/pkg/map-hamunaptra_trem.pk3'...                                                     
Loading pak '/home/zod/.unvanquished/pkg/map-orion_trem+5.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/map-perseus_b5a+1.pk3'...                                                       
Loading pak '/var/games/unvanquished/pkg/tex-all_2.0.pk3'...                                                             
Loading pak '/var/games/unvanquished/pkg/tex-common_2.0.pk3'...                                                          
Loading pak '/var/games/unvanquished/pkg/tex-ej01-clean_1.0.pk3'...                                                      
Loading pak '/var/games/unvanquished/pkg/tex-ej01-common_1.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/tex-ej01-ice_1.0.pk3'...                                                        
Loading pak '/var/games/unvanquished/pkg/tex-ex_1.0.pk3'...                                                              
Loading pak '/var/games/unvanquished/pkg/tex-exm_1.0.pk3'...                                                             
Loading pak '/var/games/unvanquished/pkg/tex-pk01_1.0.pk3'...                                                            
Loading pak '/var/games/unvanquished/pkg/tex-pk02_1.0.pk3'...                                                            
Loading pak '/var/games/unvanquished/pkg/tex-space_1.0.pk3'...                                                           
Loading pak '/var/games/unvanquished/pkg/tex-tech_1.0.pk3'...                                                            
Loading pak '/var/games/unvanquished/pkg/tex-trak5_1.0.pk3'...                                                           
Loading pak '/var/games/unvanquished/pkg/map-spacetracks_1.0+1.pk3'...                                                   
Loading pak '/home/zod/.unvanquished/pkg/map-nexus6_trem+3.pk3'...                                                    
Loading pak '/home/zod/.unvanquished/pkg/map-nano_trem+3.pk3'...                                                      
Loading pak '/home/zod/.unvanquished/pkg/map-atcshd_trem.pk3'...                                                      
Loading pak '/var/games/unvanquished/pkg/map-yocto_b2c+1.pk3'...                                                         
Loading pak '/var/games/unvanquished/pkg/map-antares_a04+1.pk3'...                                                       
Loading pak '/var/games/unvanquished/pkg/map-antares_a04.pk3'...                                                         
Loading pak '/home/zod/.unvanquished/pkg/map-arachnid2_trem+3.pk3'...                                                 
Loading pak '/var/games/unvanquished/pkg/map-forlorn_a13~1.pk3'...                                                       
Loading pak '/home/zod/.unvanquished/pkg/map-veddak_trem.pk3'...                                                      
Loading pak '/home/zod/.unvanquished/pkg/map-parpax_d05.pk3'...                                                       
Loading pak '/var/games/unvanquished/pkg/map-plat23_b13+1.pk3'...                                                        
Loading pak '/home/zod/.unvanquished/pkg/map-station15_1.0+1.pk3'...                                                  
Loading pak '/var/games/unvanquished/pkg/map-station15_1.0.pk3'...                                                       
Loading pak '/var/games/unvanquished/pkg/map-thunder_b3+2.pk3'...                                                        
Loading pak '/home/zod/.unvanquished/pkg/map-tremor_trem+4.pk3'...                                                    
Loading pak '/home/zod/.unvanquished/pkg/map-niveus_trem+5.pk3'...                                                    
Loading pak '/home/zod/.unvanquished/pkg/map-utcs_trem+3.pk3'...                                                      
[skipnotify]23 arenas parsed                                                                                             
----- Server Initialization -----                                                                                        
Server: plat23                                                                                                           
Calling GetRefAPI…                                                                                                       
                                                                                                                         
GL_VENDOR: X.Org                                                                                                         
GL_RENDERER: Gallium 0.4 on AMD CYPRESS                                                                                  
GL_VERSION: 3.0 Mesa 10.4.2                                                                                              
GL_SHADING_LANGUAGE_VERSION: 1.30                                                                                        
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16384                                                                                   
Using GPU vertex skinning with max 256 bones in a single pass                                                            
Extracting VM module cgame-x86_64.nexe from /home/zod/downloads/unvanquished/Unvanquished/build/pkg/unvanquished_0.39.0.pk3...                                                                                                                 
Loading VM module cgame-x86_64.nexe...                                                                                   
][15094,3033569088:20:12:53.395099] Native Client module will be loaded at base address 0x0000279200000000               
Loaded VM module in 53 msec                                                                                              
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf).                                                         
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf).                                            
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf).                                                     
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf).                                                   
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf).                                         
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf).                                       
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/git_git.pk3dir/'...                              
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/unvanquished_0.39.0.pk3'...                      
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.38.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.37.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.36.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'...                                                     
IP: 127.0.0.1                                                                                                            
IP: 10.0.0.4                                                                                                             
IP6: ::1                                                                                                                 
IP6: 2601:6:5e00:40e8:21f:bcff:fe02:94e6                                                                                 
IP6: fe80::21f:bcff:fe02:94e6%eth0                                                                                       
Opening IP6 socket: [::]:27960                                                                                           
Opening IP socket: 0.0.0.0:27960                                                                                         
WARNING: NET_IPSocket: bind: Address already in use                                                                      
Opening IP socket: 0.0.0.0:27961                                                                                         
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/git_git.pk3dir/'...                              
Loading pak '/home/zod/downloads/unvanquished/Unvanquished/build/pkg/unvanquished_0.39.0.pk3'...                      
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.38.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.37.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.36.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.35.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.34.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.33.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.32.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.31.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.30.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.29.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.28.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.27.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.26.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/unvanquished_0.25.0.pk3'...                                                     
Loading pak '/var/games/unvanquished/pkg/map-plat23_b13+1.pk3'...                                                        
Loading pak '/var/games/unvanquished/pkg/tex-common_2.0.pk3'...                                                          
Loading pak '/var/games/unvanquished/pkg/tex-pk02_1.0.pk3'...                                                            
Loading pak '/var/games/unvanquished/pkg/tex-space_1.0.pk3'...                                                           
Extracting VM module sgame-x86_64.nexe from /home/zod/downloads/unvanquished/Unvanquished/build/pkg/unvanquished_0.39.0.pk3...                                                                                                                 
Loading VM module sgame-x86_64.nexe...                                                                                   
][15099,4065748800:20:12:54.489369] Native Client module will be loaded at base address 0x000070b100000000               
Loaded VM module in 51 msec                                                                                              
------- Game Initialization -------                                                                                      
gamename: base                                                                                                           
gamedate: May  9 2015                                                                                                    
readconfig: could not open admin config file admin.dat                                                                   
Warning: "colorGrade" deprecated. Please use "gradingTexture"                                                            
==== Bot Navigation Initialization ====                                                                                  
r_debugSurface is cheat-protected.                                                                                       
 loading navigation mesh file 'maps/plat23-builder.navMesh'...                                                           
 loading navigation mesh file 'maps/plat23-level0.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-level1.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-level2.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-level2upg.navMesh'...                                                         
 loading navigation mesh file 'maps/plat23-level3.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-level3upg.navMesh'...                                                         
 loading navigation mesh file 'maps/plat23-level4.navMesh'...                                                            
 loading navigation mesh file 'maps/plat23-human_naked.navMesh'...                                                       
 loading navigation mesh file 'maps/plat23-human_bsuit.navMesh'...                                                       
0 groups with 0 entities                                                                                                 
maprotation.cfg file not found.                                                                                          
-----------------------------------                                                                                      
-----------------------------------                                                                                      
timescale is cheat-protected.                                                                                            
clientDownload: 0 : beginning "map-parpax_d04_d73404b8"                                                                  
clientDownload: 0 : "map-parpax_d04_d73404b8" file not found on server                                                   
Error: File "map-parpax_d04_d73404b8" not found on server for autodownloading.

**Comment by Viech** [comment]
Maybe related to #314 and general cvar badness?

**Comment by Viech** [comment]
@Amanieu, @Kangz, can you imagine that the required file list is saved to `autogen.cfg` or some other location? @overvolting can you share relevant parts of your `autogen.cfg` (be sure to strip any password and other private fields)?

**Comment by Viech** [comment]
No input for a year, closing.

**Comment by illwieckz** [comment]
Other similar issues were closed, no one reported any new occurrence.
See https://github.com/Unvanquished/Unvanquished/issues/767#issuecomment-151160476 for explanations about the bug and the fix.
