### ISSUE TITLE
Unable to connect to some servers with no error/reason shown.

### ISSUE THREAD

**Issue by ckol** [Unvanquished/Unvanquished#725]
Platform: Arch Linux 64bit, latest updates.
Desktop: xfce4
Version: all > 0.28 at least.
Currently: 0.39

Trying to connect to i.e. Non-Official Training server. Other players seem to be active there.
New maps get downloaded. When game is supposed to start unv jumps back to the intro
screen, no error is shown. Other servers work.

Reproducible: once it happens, it happens always with that server until it somehow gets fixed
by some admin?

**Comment by ckol** [comment]
Console log attached...

There is one Error shown:
Error: CGame VM: IPC: Unexpected end of message 

[admin@black ~]$ unvanquished
Unvanquished 0.39.0 Linux x86_64 May 14 2015
cmdline: -libpath /usr/lib/unvanquished -pakpath /usr/share/unvanquished/pkg
^3Warn: Ignoring path /home/admin/.unvanquished/pkg: No such file or directory 
Home path: /home/admin/.unvanquished 
Pak search path: /usr/share/unvanquished/pkg 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.38.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.37.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.36.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
execing 'default.cfg' 
Couldn't read conhistory. 
Loaded 9 languages 
Set language to English 
----- Client Initialization ----- 
Loading RSA keys from pubkey 
Daemon RSA public-key file not found, regenerating 
Regenerating RSA keypair; writing to pubkey 
Daemon RSA keys generated 
----- Client Initialization Complete ----- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL Version 2.0.3 
]ATTENTION: default value of option force_s3tc_enable overridden by environment.
SDL using driver "x11" 
Initializing OpenGL display 
Display aspect: 1.778 
...setting mode -2: 
 2048 1152 
The change will take effect after restart. 
The change will take effect after restart. 
Using 24 Color bits, 24 depth, 8 stencil display. 
Using GLEW 1.12.0 
Using enhanced (GL3) Renderer in GL 2.x mode... 
Available modes: '2048x1152 ' 
GL_RENDERER: Gallium 0.4 on AMD CYPRESS 
Detected graphics driver class 'Mesa' 
Detected graphics hardware class 'AMD Radeon DX10-class' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...using GL_ARB_fragment_shader 
...using GL_ARB_vertex_shader 
...using GL_ARB_shading_language_100 
...found shading language version 130 
...using GL_ARB_depth_texture 
...using GL_ARB_texture_cube_map 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_ARB_texture_rg 
...ignoring GL_ARB_texture_compression 
...ignoring GL_EXT_texture_compression_s3tc 
...using GL_ARB_texture_non_power_of_two 
...using GL_SGIS_generate_mipmap 
...using GL_EXT_texture_filter_anisotropic 
...using GL_ARB_vertex_buffer_object 
...using GL_ARB_half_float_vertex 
...using GL_EXT_framebuffer_object 
...using GL_EXT_framebuffer_blit 
...using GL_ARB_shader_objects 
...using GL_ARB_occlusion_query 
...using GL_ARB_draw_buffers 
...GL_GREMEDY_string_marker not found 
...GL_ARB_get_program_binary found, but with no binary formats 
...using GL_ARB_buffer_storage 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
 
GL_VENDOR: X.Org 
GL_RENDERER: Gallium 0.4 on AMD CYPRESS 
GL_VERSION: 3.0 Mesa 10.5.5 
GL_SHADING_LANGUAGE_VERSION: 1.30 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16384 
Using GPU vertex skinning with max 256 bones in a single pass 
Extracting VM module cgame-x86_64.nexe from /usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3... 
Loading VM module cgame-x86_64.nexe... 
][11535,1791530816:00:44:11.394984] Native Client module will be loaded at base address 0x00004fdd00000000
Loaded VM module in 58 msec 
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf). 
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf). 
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf). 
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf). 
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf). 
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf). 
--- Common Initialization Complete --- 
Loaded GeoIP data: IPv4 IPv6 
IP: 127.0.0.1 
IP: 192.168.88.4 
IP: 192.168.90.1 
IP6: ::1 
IP6: fe80::4a5b:39ff:fe4d:1499%enp4s0 
Opening IP6 socket: [::]:* 
Opening IP socket: 0.0.0.0:* 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.38.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.37.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.36.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.38.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.37.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.36.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/map-spacetracks_1.0+1.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/tex-common_2.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/tex-ex_1.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/tex-exm_1.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/tex-pk01_1.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/tex-pk02_1.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/tex-tech_1.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/tex-trak5_1.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/tex-space_1.0.pk3'... 
Calling GetRefAPI… 
 
GL_VENDOR: X.Org 
GL_RENDERER: Gallium 0.4 on AMD CYPRESS 
GL_VERSION: 3.0 Mesa 10.5.5 
GL_SHADING_LANGUAGE_VERSION: 1.30 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16384 
Using GPU vertex skinning with max 256 bones in a single pass 
Extracting VM module cgame-x86_64.nexe from /usr/share/unvanquished/pkg/unvanquished_0.38.0.pk3... 
Loading VM module cgame-x86_64.nexe... 
][11541,1785489216:00:44:23.105286] Native Client module will be loaded at base address 0x00007cd300000000
Loaded VM module in 51 msec 
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf). 
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf). 
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf). 
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf). 
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf). 
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf). 
Error: CGame VM: IPC: Unexpected end of message 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.38.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.37.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.36.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.38.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.37.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.36.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
Extracting VM module cgame-x86_64.nexe from /usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3... 
Loading VM module cgame-x86_64.nexe... 
][11545,950916928:00:44:23.921403] Native Client module will be loaded at base address 0x000049a100000000
Loaded VM module in 61 msec 
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf). 
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf). 
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf). 
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf). 
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf). 
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf). 
Calling GetRefAPI… 
 
GL_VENDOR: X.Org 
GL_RENDERER: Gallium 0.4 on AMD CYPRESS 
GL_VERSION: 3.0 Mesa 10.5.5 
GL_SHADING_LANGUAGE_VERSION: 1.30 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16384 
Using GPU vertex skinning with max 256 bones in a single pass 
Extracting VM module cgame-x86_64.nexe from /usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3... 
Loading VM module cgame-x86_64.nexe... 
][11549,1621538624:00:44:24.593241] Native Client module will be loaded at base address 0x0000716200000000
Loaded VM module in 48 msec 
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf). 
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf). 
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf). 
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf). 
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf). 
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf). 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.38.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.37.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.36.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3'...

**Comment by DolceTriade** [comment]
Non-Official server doesn't seem to be updated to the latest release.

**Comment by overvolting** [comment]
Still in version 0.38. Waiting for debian packages.

**Comment by Amanieu** [comment]
The debian packages are no longer maintained, use the universal zip instead.

**Comment by hunternet93** [comment]
The Debian packages updated to 0.39 just fine for me as of a couple hours ago, using Debian Jessie.

**Comment by Viech** [comment]
Closing in favor of #726.
