### ISSUE TITLE
can't use ~ from my bépo keyboard

### ISSUE THREAD

**Issue by bioinfornatics** [Unvanquished/Unvanquished#729]
Dear,

I try from the release 0.39 to open the terminal by using ~ or ` that do not work. I have a bépo keyboard.

~ -> <kdd>altgr</kdd>+<kdd>k</kdd>
` ->  <kdd>shift</kdd>+<kdd>%</kdd>

**Comment by Viech** [comment]
Try `SHIFT`+`ESC`. Also you can probably bind any key … once you've opened the console to do so. :stuck_out_tongue:

**Comment by Kangz** [comment]
Maybe we should just remove the binding to the ~ key and just keep shift + esc, it is more convenient for everyone.

**Comment by Viech** [comment]
Indeed. If `SHIFT`+`ESC` works for @bioinfornatics I'd just close this and call it the main key combination.

**Comment by bioinfornatics** [comment]
yes `SHIFT+ESC` works fine
