### ISSUE TITLE
Long name breaks column alignment in scoreboard

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#732]
A long player name causes the scoreboard's Score, Time, and Ping columns to break alignment, and the rightmost column to be cut off along the edge. Expected behavior: end of player name is cut off instead.

The following screenshot is taken at 1600x900 resolution:
[![screenshot](https://i.imgur.com/8nlqS9z.jpg)](https://imgur.com/8nlqS9z)

**Comment by illwieckz** [comment]
I tried to add many "overflow: hidden" styles in many places but have not yet managed to solve it. :-/

**Comment by DolceTriade** [comment]
This will need to be a librocket fix.

**Comment by illwieckz** [comment]
This issue is a duplicate of #541 “_libRocket: too long strings displaces table elements_”.
