### ISSUE TITLE
server drop third player who connect to main screen

### ISSUE THREAD

**Issue by Undreamed** [Unvanquished/Unvanquished#738]
only me and one other player can connect to my server... the next player who try to connect drops to main screen.
No errors in my server-shell, and my server.cfg is copied from git...

**Comment by Viech** [comment]
Without any error output, this is incredibly hard to debug. If you just copied the `server.cfg` from the `archlinux` folder, there should be enough free client slots. Does the third player see any error messages?

**Comment by Viech** [comment]
No input for a year, closing.
