### ISSUE TITLE
Microsoft compiler crash

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#748]
In [this commit](https://github.com/Unvanquished/Unvanquished/commit/faee5bae3576085e01775e61cb3b754e08fbc6ae) the placement new was changed to use brace-initialization, because MSVC did not default-initialize the fields when the  form with parentheses was used. Now I am once again experiencing the joy of Microsoft: the line `new(&cg) cg_t{};` (cg_main.cpp:1617) apparently crashes the compiler (Visual Studio 2013), as the following program also does:

    #include "src/gamelogic/cgame/cg_local.h"
    cg_t c;
    void foo() {
        new (&c) cg_t{};
    }

So, any ideas for yet another workaround that could avoid these compiler bugs?

**Comment by DolceTriade** [comment]
I thought that line of code was added specifically for MSVC. Perhaps upgrade to more recent MSVC versions?

**Comment by gavlig** [comment]
my favorite kind of bug, omnomnom

**Comment by Viech** [comment]
@slipher, why the close? Does it work with a more recent MSVC?

**Comment by slipher** [comment]
@Viech, correct.
