### ISSUE TITLE
Anytime we abort early in a function, there should be logging that it happens.

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#752]

**Comment by Kangz** [comment]
Not sure what classes of functions you are talking about.

**Comment by DolceTriade** [comment]
Mainly functions in which we load things. Models, images, etc. For instance, if we stop loading a crunch file because we don't support the image format, we need to log that we don't support that image format before we return early from the load function or else you'll need a debugger and need to step through the loading process to find out why we aborted early. this is both tedious and unnecessary.

**Comment by slipher** [comment]
I think we've gotten a lot better with that. This issue is not very specific so I'll close it.
