### ISSUE TITLE
Creep is generally gone but reappears sometimes.

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#753]

**Comment by Viech** [comment]
Poking @enneract, I think he wanted to fix this.

**Comment by Viech** [comment]
@DolceTriade reason for closing?

**Comment by DolceTriade** [comment]
I think creep showed up again all of a sudden. I forget why I closed it.

**Comment by bmorel** [comment]
Are there steps to reproduce?

**Comment by bmorel** [comment]
I have played countless hours, and could never spot this bug. I think it can be closed now.

**Comment by Viech** [comment]
Agreed.
