### ISSUE TITLE
Game doesn't run: built-in shaders failed

### ISSUE THREAD

**Issue by danielballack** [Unvanquished/Unvanquished#758]
When I try to run daemon.exe, an error window pops up, saying "Built-in shaders failed: Couldn't compile fragment shader: ssao"
Installing SwiftShader 3.0 did not solve the issue.
I tried to run the game with "+set r_recompileShaders 1". The outcome was the same.
Any way to fix this and be able to play?

**Comment by Viech** [comment]
This may be fixed on current master. @gmcode?

**Comment by DolceTriade** [comment]
This is fixed on master.

**Comment by danielballack** [comment]
I see the file "Fix to not try to use sso if driver does not support it." Bur how exactly do I use it to get the game running? I might need some pretty clear and simple instructions.
Thanks for the help!

**Comment by DolceTriade** [comment]
You would need to build from source. I will post an updated version soon.

**Comment by gmcode** [comment]
Sorry I didn't see this message earlier. You could try putting -set r_ssao 0 on the command line and see if that works if you can't build from source.
