### ISSUE TITLE
keybinding editor show action instead of keys, can't bind unbinded action

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#763]
Hi, the keybinding editor shows the action instead of the key.

It's possible to change keys while clicking on the action name.
But it's not possible to change keys for actions that were never binded (like _"Beacon menu"_ in this screenshot) because we can't click nowhere.

![keybinding editor](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-07-07_195110_000.png)

**Comment by illwieckz** [comment]
Same problem on vote display (to the left):

![vote shows internal stuff](http://dl.illwieckz.net/b/unvanquished/bugs/unvanquished_2015-07-19_221210_000.jpg)

**Comment by illwieckz** [comment]
thanks, does it fix the poll display too?

**Comment by DolceTriade** [comment]
Poll display? Example? (I doubt it.)

**Comment by illwieckz** [comment]
on the left, the “Remove all bots” poll: http://dl.illwieckz.net/b/unvanquished/bugs/unvanquished_2015-07-19_221210_000.jpg
