### ISSUE TITLE
Unvanquished displays names' carets while aiming someone/something

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#766]
Hi, I don't know what is the name of this thing, but now Unvanquished displays the name of what your are aiming in the right of the screen. It works well except the carets are not filtered:

![in-game carets](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-07-07_230839_000.jpg)

**Comment by DolceTriade** [comment]
Likely fixed in my beacon HUD element port to C++.
