### ISSUE TITLE
allow server to rescan packages while running

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#777]
Currently, if a map was already there at startup, we can update the map and at the next load, the new one will be used automagically. But is seems we can't add a map that were unknown at startup, we need to  restart the server (and drop players), it could be very nice to have a command to rescan packages at runtime!

This issue is a feature request! :smile:

**Comment by DolceTriade** [comment]
Are you sure loading another map doesn't work?

**Comment by illwieckz** [comment]
Ah, you mean doing that:

* launch unvanquished with map A in homepath
* load map A
* put map B in homepath
* load map A
* load map B

?

I've only tried that:

* launch unvanquished with map A in homepath
* load map A
* put map B in homepath
* load map B

**Comment by DolceTriade** [comment]
Yes, that's what I mean.

**Comment by illwieckz** [comment]
I tested it, it works if I load an existing map before the new one. Is there no way to load directly the new one?

**Comment by Amanieu** [comment]
Fixed by f6d86d5

**Comment by illwieckz** [comment]
thanks !
