### ISSUE TITLE
Poll display do not interpret smiley so it does not display “check” and “cross” icons

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#779]
Poll display does not interpret smiley so it does not display “check” and “cross” icons

See (on the left):
![poll](http://dl.illwieckz.net/b/unvanquished/bugs/unvanquished_2015-07-26_213138_000.jpg)

**Comment by DolceTriade** [comment]
Is this still a bug in master?

**Comment by illwieckz** [comment]
Yes:

![poll](http://dl.illwieckz.net/b/unvanquished/bugs/unvanquished_2015-07-27_051827_000.jpg)

The carrets are now fixed, but not the smileys.

**Comment by illwieckz** [comment]
wait, my master was not uptodate, I'm retrying.

**Comment by illwieckz** [comment]
yes, the bug is still there in current master.
