### ISSUE TITLE
Duplicate GUIDs are generated by Windows computers.

### ISSUE THREAD

**Issue by cu-kai** [Unvanquished/Unvanquished#781]
It seems myself and others on windows, across various machines, are still generating duplicate GUIDs; my friend joined a server and was shown as "Registered" as another user who uses windows. 

I join the same server and am shown as registered as the very same user, using any GUID generated by Windows.

**Comment by Amanieu** [comment]
Should be fixed by b69c1f2fb8efc6efd2a99fc53c3f0bb81951cdf2.

Mingw doesn't implement std::random_device properly so it was generating the same random numbers for everyone when build a pubkey.
