### ISSUE TITLE
Internal lightmaps have blending issue and light spill out

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#782]
Hey, I found a strange bug, lightmap rendering is wrong when they are loaded from the bsp, when they are loaded as external files (tested with png), the map looks good.

There is many bugs a simple lightmap externalization can fix, some blending issue, and some light spill out on edges.

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005525_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005819_000.jpg)

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005533_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005832_000.jpg)

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005545_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005850_000.jpg)

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005613_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005923_000.jpg)

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005622_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005936_000.jpg)

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005626_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_010053_000.jpg)

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005640_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_010131_000.jpg)

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005654_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_010156_000.jpg)

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_005706_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_010216_000.jpg)

internal:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_011616_000.jpg)

external:  
![lightmap](http://dl.illwieckz.net/b/unvanquished/bugs/lightmaps/unvanquished_2015-07-30_011834_000.jpg)

**Comment by DolceTriade** [comment]
Nice evidence. @gimhael, think you could take a look at this?

**Comment by illwieckz** [comment]
FYI, these guys have experienced similar issues (but the opposite one) with another engine (don't know which one, probably ioquake3 or quakelive):
https://github.com/TTimo/GtkRadiant/issues/66

The got the opposite bug: they got light bleeding when using external lightmaps (internal are ok), since we get bleeding when using internal lightmaps (external ar ok). That other issue is an issue for q3map2, but it looks like a renderer issue on our side (btw, I don't have the source for the map above, so only renderer can fix).

There is absolutely no urge at all to fix this bug and I'm ok if it's not fixed since external lightmaps are working well (so, we just need to tell people to not use internal lightmap), and internal lightmaps must be avoided since it does not allow compression. But I thought that info would be useful, perhaps it can reveal or help to understand some related issues to.

**Comment by Viech** [comment]
@illwieckz is this the only map that you tested though? Maybe the compiler was just misconfigured.

**Comment by illwieckz** [comment]
Hum, since this topic old, I do not remember if I tested other maps back in time, btw, no one official map have internal lightmap so maps with internal lightmaps are all contributed ones, so it's hard to know if the problem comes from the map itself (and if the map was build the good way) or from another component…

**Comment by cmf028** [comment]
I've seen this problem before when the driver compresses textures by itself, usually when configured for "maximum performance". There isn't anything we can do about that if true.

**Comment by illwieckz** [comment]
Those two issues are now tracked elsewhere:

- DaemonEngine/Daemon#326 (_Blend issue with internal lightmap_)
- DaemonEngine/Daemon#327 (_Spilling out internal lightmap_)

Closing this one.
