### ISSUE TITLE
NaClMprotect() failed with noexec /run/shm on Debian testing

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#784]
Keziolio from `#unvanquished` gets a `MakeDynamicCodePageVisible: NaClMprotect() failed` error with Unvanquished 0.42.0 (unizip) on Debian testing 64bit : http://pastebin.com/atr1cXqN

This trick fixed it:

```sh
mount -o remount,exec /run/shm
```

**Comment by DolceTriade** [comment]
Will update the unizip.

**Comment by DolceTriade** [comment]
Fixed the deps a while back.
