### ISSUE TITLE
Remove the grep command.

### ISSUE THREAD

**Issue by mbasaglia** [Unvanquished/Unvanquished#786]
Here is a list of parts of the code that could be removed:
- [x] Everything regarding VOIP (Search code/cmake for USE_VOIP): when enabled doesn't even compile.
- [ ] The grep command: rumors say it will be replaced at some point and its current incarnation should be removed.
- [x] Censorship stuff: no one has ever used and it isn't clear how it's supposed to work (if it does at all). (Search "censors" in the code to find it) Removing it might also give slight performance improvements.
- [x] The "test" command (in sg_cmds.cpp) and related Cmd_Test_f, which does nothing at all.

If I find more I'm going to expand this list.

**Comment by Veyrdite** [comment]
The IRC client might also be slatable, but it does not appear to be heavily intertwined into the game:

    $ grep -Rl 'IRC' 
    engine/client/cl_irc.cpp
    engine/client/client.h
    engine/client/cl_main.cpp

**Comment by Viech** [comment]
I'd keep IRC support for know. We might want to use it later for some lobby feature.

**Comment by mbasaglia** [comment]
Looks like most of this has been removed, there just a couple references to VOIP in comments and translations.

https://github.com/Unvanquished/Unvanquished/blob/e8bd27c32eefaf859b3f897a6f2bcc62888f73d7/daemon/src/engine/qcommon/qcommon.h#L321-L335

**Comment by Viech** [comment]
@Kangz did you nuke voip completely by now? @mbasaglia wanna take a look at removeing the grep?

**Comment by mbasaglia** [comment]
I think there are still some references to VOIP stuff:
```
$ ack VOIP
src/engine/qcommon/qcommon.h
311:  svc_voip, // not wrapped in USE_VOIP, so this value is reserved.
325:  clc_voip, // not wrapped in USE_VOIP, so this value is reserved.

src/engine/client/client.h
583:  KB_VOIPRECORD,
```

Before we remove Grep we should define a better way to search through the console output.
We could have a find feature that scrolls you to the nearest match or something like that.

**Comment by illwieckz** [comment]
See #972 about that.

**Comment by slipher** [comment]
The grep command is helpful and there is no replacement, so closing.
