### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by hasufell** [Unvanquished/Unvanquished#797]
with parallel build, you get the build failure earlier, probably related to #794 
https://gist.github.com/hasufell/94e4aaca2461a1879a2b

without parallel build, it still fails
https://gist.github.com/hasufell/516bd2ca634c6323940a

**Comment by hasufell** [comment]
oh, I tested against 0.42.0

**Comment by DolceTriade** [comment]
Probably due to the fact we enabled -Werror.

**Comment by Amanieu** [comment]
Could you try compiling master?

**Comment by harmonise** [comment]
Neither gists are still available. Are you still experiencing this issue or can we close?

**Comment by hasufell** [comment]
I stopped trying.
