### ISSUE TITLE
[Feature Request] add a `savepos` and `restorepos` ocommand

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#798]
An awesome thing would be to be able to save your current position in the map (x, y, z, a1, a2) and to restore it. It would be awesome for mappers.

For example you build your map:

```
$ make
```

You launch your map and explore it:

```
$ unvanquished +devmap transit
```

You find a wrong thing in your map, you edit the map to fix it, you rebuild the map:

```
$ make
```

You reload the map at the exact same position:

```
$ unvanquished +savepos +devmap transit +restorepos
```

Since now every new unvanquished call pass the command to the existing instance, we can imagine the command `savepos` and `restorepos`  write/read a cvar `playerpos` that can also be set on command line like that:

```
$ unvanquished -set playerpos x,y,z,a1,a2 +restorepos
```

So, the map editor can drive the player's camera in unvanquished running a previous build while he edits his map.

Obiously, this functionality must work only when running a map with `devmap`.

**Comment by illwieckz** [comment]
OK, @DolceTriade said Unvanquished already have a `viewpos` command to read coords, and `setviewpos` to set coords, the only thing missing is a way to save/restore the viewpos, to be able to do `save; devmap; restore` without having to write down coords. :+1:

**Comment by Amanieu** [comment]
I added /saveviewpos in c50aea9. Use it like this:
/saveviewpos
/setviewpos $cg_savedviewpos$

**Comment by illwieckz** [comment]
wow awesome :+1:
