### ISSUE TITLE
Add a soft timelimit to prevent servers being stuck on a map.

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#800]
Hi, I don't like timelimit because it's very frustrating when you hit the timelimit after hours of hard play just before you win or lose, that's why I disabled it on my servers.

But, I want to prevent games going endless just because bots are playing alone and they are all stuck. The worst thing is when all the spawn points are destroyed but there is still some bot alive in each team, so the game goes endless and no real player connecting to the server can join the game.

So, what do you think about a `softtimelimit` boolean cvar, if this cvar is set to true, the game is ended when gametime > timelimit if there is no real player connected to the server. So, if the `softtimelimit` is set to true, the `timelimit` is only used to rotate the maps while waiting for real players.

**Comment by illwieckz** [comment]
This issue is dedicated to the Atari 800:

![Atari 800](https://upload.wikimedia.org/wikipedia/commons/3/35/Atari_800.jpg)

**Comment by DolceTriade** [comment]
Fixed by #854

**Comment by illwieckz** [comment]
Awesome \o/ Thanks a lot!
