### ISSUE TITLE
Don't use evil libwebp (Windows)

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#801]
The latest build script on Windows downloads a version of libwebp which causes runtime errors. This issue has occurred before and can be solved by using the older version which was in `external_deps/msvc32-2`.

**Comment by DolceTriade** [comment]
Do we still use the evil webp?

**Comment by Viech** [comment]
Remember to ping the opener of a stale issue, being @slipher.

**Comment by slipher** [comment]
How does the 64-bit Windows application load the libwebp code? After switching from compiling in 32-bit to 64-bit, some of the DLLs that are usually in the same directory as daemon.exe are no longer placed there, so I'm not sure where to change the file to test it.

**Comment by Viech** [comment]
Is there still a problem with the current windows build? @slipher?

**Comment by slipher** [comment]
Maybe close for now as I don't remember enough about the issue to reproduce it.
