### ISSUE TITLE
Armory / Build menus cancel button is broken

### ISSUE THREAD

**Issue by guillaume-uH57J9** [Unvanquished/Unvanquished#807]
Once the armory / builder menu is open, clicking on the cancel button does nothing.

Hitting escape allows to exit the build menu, as a workaround.
But I found no way to exit the armory menu, such that the games gets blocked once the armory is used.

unvanquished 0.43 (universal zip)
Debian GNU/Linux testing
Linux 4.1.0 amd64

**Comment by DolceTriade** [comment]
https://github.com/Unvanquished/Unvanquished/commit/3d4665eac57f44898d547806401bf16e0f1f78b9
