### ISSUE TITLE
Escape is hardcoded to keyboard position

### ISSUE THREAD

**Issue by TheLastProject** [Unvanquished/Unvanquished#809]
I just downloaded Unvanquished for 64-bit Linux from the website (which is Alpha 0.43, somehow?) and noticed that the Escape key is hardcoded to the top left of the keyboard, instead of to what is defined as the escape key.

As I have Escape and Caps Lock swapped in my KDE settings, I should be able press the physical Caps Lock key to open the Escape menu. However, I have to press the physical Escape key, which means I also enable caps lock.

**Comment by DolceTriade** [comment]
Our keyboard layout system needs some rethinking.

**Comment by Viech** [comment]
I'm not sure if this is a valid enhancement request (or even a bug). It depends on what the KDE settings do. Maybe they are not capable of or not even supposed to change key mappings in SDL applications that behave differently than your average graphical text editor window, in which case Dæmon/Unvanquished can do nothing about it.

**Comment by bmorel** [comment]
I wonder if this is still true?

**Comment by necessarily-equal** [comment]
On GNOME+Wayland (with unvanquished running in XWayland), the swapped escape key is handled correctly. I'm closing this, but please reopen or comment if some other configuration is still witnessing the issue.

`gsettings set org.gnome.desktop.input-sources xkb-options "['caps:swapescape']"`
