### ISSUE TITLE
Asset download URL for version 0.44 is 404

### ISSUE THREAD

**Issue by ckorn** [Unvanquished/Unvanquished#811]
download-pk3.sh fails to download the assets:

$ LANG=C wget http://downloads.sourceforge.net/project/unvanquished/Assets/md5sums0.44
--2015-10-16 20:17:49--  http://downloads.sourceforge.net/project/unvanquished/Assets/md5sums0.44
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-10-16 20:17:50 ERROR 404: Not Found.

**Comment by DolceTriade** [comment]
Whoops. Fixed.
