### ISSUE TITLE
CBSE merge cleanup

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#812]
- [x] Make CBSE.py 2.7 compatible
- [x] Add pip_deps file to simplify CBSE toolchain dep installation 
- [x] Update CMake to run CBSE toolchain scripts to create auto generated code
- [x] Delete autogen'd code from repo
- [x] Detect missing python deps somehow...
- [x] Update README to include submodule documentation
- [ ] Fix travis

**Comment by Kangz** [comment]
+cc

**Comment by Viech** [comment]
@Kangz, +cc?

**Comment by DolceTriade** [comment]
He wants to be notified of changes.

**Comment by DolceTriade** [comment]
Not happening this release. Should be mostly ready, but not sufficient testing performed. Plus, travis still broken.
