### ISSUE TITLE
Keyboard Revamp

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#813]
We need to make our input code support alternative layouts better.

**Comment by Viech** [comment]
Compatibility was used for compat breaking commits so far. Do we need a tag for hardware support?

**Comment by Viech** [comment]
This issue seems to be linked to #809.

**Comment by DolceTriade** [comment]
Yes, among many others.

**Comment by illwieckz** [comment]
See DaemonEngine/Daemon#43 “_Redesign key bind handling, to support Unicode among other things_” on engine side.

**Comment by Viech** [comment]
I'm closing this since it's an engine thing foremost, feel free to open another issue when it becomes necessary to adapt Unvanquished to the engine change.
