### ISSUE TITLE
Upload builds to GitHub, not SourceForge

### ISSUE THREAD

**Issue by kharnov** [Unvanquished/Unvanquished#827]
- [ ] Modify `download-pk3.sh` to remove SourceForge support and make `dl.unvanquished.net` the default download location.
- [ ] Write a script that uploads releases to GitHub.

**Comment by Viech** [comment]
Fixed the issue description for you. You just need to fill in the `???`…

**Comment by Kangz** [comment]
I think he is talking about the [release](https://github.com/Unvanquished/Unvanquished/releases) feature of Github that doesn't have a size or bandwidth limit.

**Comment by harmonise** [comment]
This might be a good idea as SF is difficult to navigate for non-technical users (way too many download options). Whatever is decided the user experience should be as simple as possible.
