### ISSUE TITLE
Make MSVC 2015 compile right out of the clone

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#834]
Also, modify appveyor to use msvc 2015 to fix that build.

**Comment by Viech** [comment]
Can we either fix this soon or disable appveyor?

**Comment by TimePath** [comment]
Appveyor is fixed and using msvc2015

**Comment by Kangz** [comment]
I have changes on my Windows that fix parts of MSVC 2015

**Comment by mbasaglia** [comment]
Appveyor builds master just fine now, does MSVC have remaining issues?

**Comment by slipher** [comment]
It builds OK but there's a small issue with compiler flags not getting through from Cmake.

**Comment by slipher** [comment]
Everything is fine at this point.
