### ISSUE TITLE
/screenshotJPG causes black screen under OS X

### ISSUE THREAD

**Issue by harmonise** [Unvanquished/Unvanquished#835]
Running OS X 10.11.1 with Intel Iris Pro 1536 MB (MacBookPro11,2) and retina screen. Issue can be reproduced by launching Unvanquished, opening the console and entering the command /screenshotJPG. Result is a black screen (music still playing in background) and requires the app to be killed with cmd-alt-esc. Note: the jpg image is not saved.
 
Relevant error message is:

`Error: Output buffer for encoded JPEG image has insufficient size of 3888000 bytes`

Full log is available [here](https://gist.github.com/harmonise/aeb8486d43dd2c68ccfe)

**Comment by DolceTriade** [comment]
https://github.com/Unvanquished/Unvanquished/issues/836 have the same root cause, I believe. libjpeg on OSX doesn't work right.
