### ISSUE TITLE
Skyboxes are pink

### ISSUE THREAD

**Issue by harmonise** [Unvanquished/Unvanquished#836]
Running OS X 10.11.1 with Intel Iris Pro 1536 MB (MacBookPro11,2) and retina screen. Issue can be reproduced by launching Unvanquished and starting any map (tested on platform 23 - b13). Antares, Platform 23, chasm, forlon, Parpax and Vegas Industries have an additional issue where the loading screen has a pink overlay.

![unvanquished_2015-11-12_160331_000](https://cloud.githubusercontent.com/assets/1488360/11111575/70858a24-895e-11e5-81ec-8f50fa18514a.png)
![unvanquished_2015-11-12_165459_000](https://cloud.githubusercontent.com/assets/1488360/11111574/70852ae8-895e-11e5-833a-aa25bd9c3033.png)

**Comment by DolceTriade** [comment]
Using the old libjpeg fixes this issue.

**Comment by Kangz** [comment]
Should we changes the external_deps for that?

**Comment by DolceTriade** [comment]
Probably. Kinda a PITA for something so small.
