### ISSUE TITLE
Correct "layer" is not refocussed when /rocketDebug is disabled

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#840]
Run /rocketDebug once to turn it on.  Run it again to turn it off.

If disabled in the **main menu:**  mouse cursor disappears, nothing becomes clickable.  User is stuck unless they use the console or close the game.

If disabled **in-game whilst playing**: nothing bad happens

If disabled **in-game with a menu open**: focus returns to normal gameplay, mouse cursor disappears so the UI cannot be closed.  This can be fixed by toggling the menu again.

**Comment by bmorel** [comment]
Rocket. Move to RMLui in 0.53. To check.

**Comment by DolceTriade** [comment]
I think rocket debug generally works.
