### ISSUE TITLE
Acid tubes attack players in limbo after they change team

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#842]
## How to reproduce

1) Start a game on 'Forlon - Alpha 14' (comes with unvanq alpha 45).
2) Join aliens

You are now at the the spawn/limbo state I am talking about:
![](http://i.imgur.com/wXafujQ.jpg)
Note that nothing wrong is happening yet.

3) Switch to the human team
4) Spawn as a human
5) Switch back to the alien team

You are now back at the limbo view for aliens.  Note that the acid tube next to the OM is now trying to attack you.

## Notes
- If you spawn as an alien and die again, the acid tube will not attack you in the limbo menu.
- If you switch from humans to aliens directly from the human limbo menu (ie without spawning) the acid tube will not attack you.

This behaviour suggests the player is being treated as 'on the human team' while in the alien limbo menu if they've just switched from being an actual alive human.

**Comment by Viech** [comment]
I think this may be related to [this TODO](https://github.com/Unvanquished/Unvanquished/blob/7f1612e5b289aee362ab851dd45c2c56bc5aef14/src/sgame/sg_client.cpp#L1504). At the time where the client is a spectator, it's still the last CBSE entity it was when it lived.

**Comment by DolceTriade** [comment]
No longer happens.
