### ISSUE TITLE
Damage-triggered doors don't work.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#843]
Reproduce: Attack the grating between the pipe shafts and the side storage room on Parpax.

The reason is that damage is done in the CBSE-part of the gamelogic now and map entities do not yet have CBSE entities attached to them. The proper solution is to port all map entities to the CBSE logic, which is a tremendous task. (Hi @t4im, what's up!? :grinning: )

**Comment by Kangz** [comment]
In the meantime we can make one CBSE entity for all the map entities and call the relevant callback if present?

**Comment by Viech** [comment]
I guess such a wrapper could work, yes.

**Comment by illwieckz** [comment]
Is this bug could be related to that other one?

> pulse [map] has another bug, when I trigger the main door, the sound is heard, but the door does not open. Normally the door happen some time after the sound is heard, so perhaps the bug is on the delay mechanic. 
-- [forum post](https://forums.unvanquished.net/viewtopic.php?f=9&t=1767&p=15868#p15868)

I thought first there was a problem in the delay mechanism, but perhaps the sound is triggered properly but not the opening mechanism (so it fails before the delay) ?

Pulse map with old entities works, not with newer entities.

**Comment by Viech** [comment]
This issue is about a regression introduced with the CBSE gamelogic, in particular my implementation of the HealthComponent. Doors are still *old* entities without any components so they can't receive the new damage messages yet. Your bug seems unrelated, except if the door on pulse was triggered by being shot at.

**Comment by bmorel** [comment]
Those entities can be opened, but not the way they are intended to, by using the "use" key ('q' letter for qwerty, 'a' letter for azerty)

**Comment by bmorel** [comment]
Said behavior stopped "working" starting with ad158323bc57e5a3f87e29a0d03d1e24f13af0e1

**Comment by bmorel** [comment]
There are 2 branches which fix that, one being a "compact" version of the 2nd for modders to pick and 2nd with more fine-grained commits:

* https://github.com/Unvanquished/Unvanquished/tree/fix-damage-ents
* https://github.com/Unvanquished/Unvanquished/tree/fix-damage-ents-compact

Since the only official map using those entities no longer uses them, I ran tests on several maps, including the testing maps @cu-kai made for that purpose. Those changes also fix func_destructable.
