### ISSUE TITLE
0.46.0 fails to build

### ISSUE THREAD

**Issue by ckorn** [Unvanquished/Unvanquished#852]
```
[ 45%] Generating CBSE entities for /«PKGBUILDDIR»/src/sgame/entities.yaml
cd /«PKGBUILDDIR»/src/utils/cbse && /usr/bin/python /«PKGBUILDDIR»/src/utils/cbse/CBSE.py -s -o /«PKGBUILDDIR»/src/sgame/ /«PKGBUILDDIR»/src/sgame/entities.yaml
/usr/bin/python: can't open file '/«PKGBUILDDIR»/src/utils/cbse/CBSE.py': [Errno 2] No such file or directory
make[3]: *** [../src/sgame/backend/CBSEBackend.cpp] Error 2
```

http://zulu309.server4you.de/build/logs/unvanquished_0.46.0-1~getdeb1-i386-20151207-2112

**Comment by DolceTriade** [comment]
Hm, interesting, I was pretty sure that our build system will init the submodule for you. Try initialize the submodule manually with git submodule init --recursive.

**Comment by ckorn** [comment]
The submodule is missing in the source tarball on the release page.

**Comment by Viech** [comment]
As far as I know this is a GitHub limitation. Note that the toolchain isn't strictly necessary to compile and play the game given that the gamelogic is shipped within the release pk3. Just disable `BUILD_GAME` and `BUILD_CMAKE` to compile everything apart from the gamelogic and it should be loaded from the latest pk3.

**Comment by mbasaglia** [comment]
It's a limitation on git archive.
I think we should provide the whole source tree in the tarball, it shouldn't be hard to add a build target that generates an archive including submodules.

**Comment by DolceTriade** [comment]
We do have a tarball.sh script that's supposed to generate a tarball. Probably needs to be uploaded, but I can probably adjust the github script to handle that.

**Comment by DolceTriade** [comment]
This one isn't really on us. I suppose we could distribute a tarball each release. Alternatively, you could modify the script to download two tarballs instead of one.
