### ISSUE TITLE
Port spectator handling to CBSE.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#855]
Currently, spectating clients seem to keep the entity type they had when they were last playing. This means that
- incorrect information about the spectated client can be displayed to the spectator and
- the gamelogic may react badly to spectators (#842 may be related).

See also comments on 6a9b17b.

Ideally, spectators should get an entity type of their own that uses as few components as possible, so that the gamelogic is less liekly to react to them in any way. A `SpectatorComponent` could handle sending the correct player state of the spectated client.

**Comment by Viech** [comment]
Poking @Kangz for input and proposals.

**Comment by DolceTriade** [comment]
A spectatorcomponent would probably work. Currently, we copy over the playerstate here: https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_active.cpp#L2303 

What could work is, we run HandleNetCode on all nonspecs. Afterwards, we sort spectators based on who they are spectating (ie, if a spectator is spectating another spectator, and then run HandleNetCode on those players where we basically do the copy/save/overwrite stuff in the SpectatorClientEndFrame function. Would that work?

**Comment by DolceTriade** [comment]
Turns out I was wrong. WE don't need to special case spectators spectating a spectator. I misunderstood the purpose of cg_stickySpec 1. I wrote a simple proposal for comment:https://github.com/Unvanquished/Unvanquished/pull/857

**Comment by Viech** [comment]
Thank you for the PR. See my comments there.
