### ISSUE TITLE
Unvanquished locks mouse even if out of game

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#862]
If you load a map and switch away from unvanquished, when Unvanquished loads, it will look the mouse to the center of the screen. You have to go to Unvanquished and open console or open a menu to unlock the mouse.

**Comment by mbasaglia** [comment]
This should get fixed once #821 is implemented.

**Comment by DolceTriade** [comment]
Could we try to get this in for this release?

**Comment by mbasaglia** [comment]
Looks like the fact that the loading screen doesn't handle any form of input might cause some issues (ie: you can't detect that you lost focus during loading)

Keeping focus detection at every input frame would allow the cursor to be unlocked right away if at the map start the window doesn't have focus but this will happen after the locking occurs. So the mouse will be free but jumps at the center of the game window.
