### ISSUE TITLE
compilation is broken

### ISSUE THREAD

**Issue by vitamins** [Unvanquished/Unvanquished#866]
A header file seems to be missing.

libs/libRocket/Source/Core/ElementUtilities.cpp:31:10: fatal error: 'Rocket/Core/FontFaceHandle.h' file not found Rocket/Core/FontFaceHandle.h
         ^
1 error generated.

**Comment by mbasaglia** [comment]
The file seems to be where it should https://github.com/Unvanquished/Unvanquished/blob/master/libs/libRocket/Include/Rocket/Core/FontFaceHandle.h

**Comment by vitamins** [comment]
The file is there, but the preprocessor can not find it.

**Comment by DolceTriade** [comment]
Are you using Arch Linux? Try downgrading CMake to an older version. There is some funkiness with newer CMake versions.

**Comment by vitamins** [comment]
Yes. After downgrading cmake i get a symbol lookup error when running cmake.
I think i will just switch to ubuntu for working with unvanquished and wait for the bugs in the archlinux version to get fixed. I have edited the title to reflect that the problem only happens with archlinux.

**Comment by DolceTriade** [comment]
That symbol look up error is also Arch Linux specific :D In CMake, change the lua library from whatever it is to /usr/lib/liblua.so and then everything will build fine.

**Comment by vitamins** [comment]
Ok so i switched to ubuntu, which has an older CMake version, and now i get the following error during cmake:

-- ttyclient
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)

I have installed the packages lua and lua5.3 in ubuntu.
I don't know anything about cmake, so it would be great if you could update the cmake configuration in git to provide a configuration that works on at least one distribution.

**Comment by vitamins** [comment]
I think if found the issue: In the file /CMakeLists.txt, the statements
set(LUA_INCLUDE_DIR ${DEPS_DIR}/pnacl_deps/include)
set(LUA_LIBRARY ${DEPS_DIR}/pnacl_deps/lib/liblua.a)
need to be moved out of the if(), because they are not set otherwise when calling cmake without further options.

**Comment by vitamins** [comment]
Compliation is still broken , though. When running make:
[ 35%] Building CXX object CMakeFiles/cgame-native-dll.dir/daemon/src/engine/qcommon/q_unicode.cpp.o
Linking CXX shared module cgame-native-dll.so
../daemon/external_deps/linux64-4/pnacl_deps/lib/liblua.a: error adding symbols: Unknown filetype.
collect2: error: ld returned 1 exit status

**Comment by DolceTriade** [comment]
That line is correct. That liblua.a file is specifcally for NaCl builds and won't work for native builds. Make sure you install the dev packages for ubuntu. If you have them installed use ccmake .. and the advanced menu to specify paths manually.

**Comment by vitamins** [comment]
I have compiled it successfully now, what was missing is installing liblua5.2-dev . After that cmake found the lua library on its own without further configuration. This wasnt mentioned on the wiki page about compilation.
Thank you for your replies.
