### ISSUE TITLE
Question: How to change player orientation on client side

### ISSUE THREAD

**Issue by vitamins** [Unvanquished/Unvanquished#870]
I would like to do the same thing that happens when the player is moving the mouse, using a function from the code:
change the direction in which the crosshair is pointing
change the direction in which the player is shooting(and walking) in the same way
Input: delta pitch and delta yaw as angles
When the resulting pitch would become too high or low after applying the change, pitch is set to the maximum/minimum pitch automatically, so that the player looks straight up or down.
Most importantly, the change should persist forever without needing to save and apply the previous changes at each frame.
So the experience for the user would be like someone else moved the mouse for a bit. The change can be undone by a player by moving the mouse in the opposite direction.
Finally, i would like to do this at each frame in a function that has access to the clients time in miliseconds, to make it a smooth movement over time.
I already looked into OffsetFirstPersonView and changing viewangles, but that does not work this way.

**Comment by Veyrdite** [comment]
Please use the forums, not the issue tracker, for questions

**Comment by vitamins** [comment]
I can not register to the forum because the registration is broken and in IRC you would need to stay online until some one answers so that is not an option.
