### ISSUE TITLE
mouse does not control camera while using noclip

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#892]
Hi, while using `noclip`, moving the mouse does not move the camera on screen.

In fact, if you do that:
- look in front of you
- noclip (activation)
- move the mouse like if you want to look down (the display does not change at all, the camera is still looking in front of you)
- noclip (deactivation) (the display show your feet)

Pethaps it's updating the angles on the server but it isn't sending them back to the client or something like that.

**Comment by illwieckz** [comment]
Melanosuchus said:

> looks like that even if you do +left it doesn't change angles so it might be an issue with noclip

**Comment by Viech** [comment]
@illwieckz is this reproducible locally for you? Also, can you actually noclip through a wall even when you cannot change your view angle? (If not there might be some desync where the client thinks it may cheat but the server says no, see #314.)

**Comment by illwieckz** [comment]
I don't know why, but I'm not able to reproduce the bug, even on 0.50.0 and master.

**Comment by DolceTriade** [comment]
There is a good chance that I fixed this with https://github.com/Unvanquished/Unvanquished/commit/55b9eeb8b3e21504ef0b7102e5d8a707fbdc8266

And the commit to convert spectators into CBSE.

**Comment by Viech** [comment]
Closing, then.
