### ISSUE TITLE
Geometry disappears after guns are fired

### ISSUE THREAD

**Issue by gdm413229** [Unvanquished/Unvanquished#899]
Topic | Contents
--------|--------------
OS | Ubuntu 12.04
RAM | 8GB DDR3-1333
Kernel | Linux 3.2
CPU Architecture | i686
GPU | AMD Radeon HD 6790
GPU Memory | 1GB GDDR5
GPU Bus | PCI Express 2.1
GPU Clock | 840MHz
Max GL Version | OpenGL 4.4
Driver Type | Proprietary
Driver | AMD Catalyst 14.10.1006.1001-140505a-171583E

There is an annoying glitch that appears every moment I use a gun in Unvanquished.  Discovered using the latest Git sources.  Any solutions and I'm happy to see the geometry stay intact even when guns are used - disappearing map geometry and entities are annoying when you just compiled from source.  Tested using the gl and gl3 settings on the cl_renderer console variable and the geometry disappears on both of these choices - fighting aliens while blind requires a fix.  Tested using both windowed and fullscreen modes.

**Comment by DolceTriade** [comment]
The cl_renderer variable shouldn't exist. Could you give us a full log?

**Comment by gdm413229** [comment]
I think that's a driver incompatibility.  Investigate the source code of the rendering system and track the culprit of disappearing geometry down - if it's a bug in the application, not the driver.  Has anyone else experienced the same glitch I've experienced?  Log enclosed.

[daemonlog.txt](https://github.com/Unvanquished/Unvanquished/files/129500/daemonlog.txt)

**Comment by DolceTriade** [comment]
Try running it in devmap with r_nocull 1

**Comment by gdm413229** [comment]
Gun fired after r_nocull is enabled, gometry still disappears.

**Comment by Zilor** [comment]
I got the same issue with Unvanquished 0.48.

Operating System Version | Windows 8.1 (64 bit)
------------ | -------------
NTFS | Supported
Crypto Provider Codes | Supported 311 0x0 0x0 0x0

Processor Information | i3-2100
------------ | -------------
Vendor | GenuineIntel
CPU Family | 0x6
CPU Model | 0x2a
CPU Stepping | 0x7
CPU Type | 0x0
Speed | 3093 Mhz
Logical processors | 4
Physical processors | 2
HyperThreading | Supported
FCMOV | Supported
SSE2 | Supported
SSE3 | Supported
SSSE3 | Supported
SSE4a | Unsupported
SSE41 | Supported
SSE42 | Supported

Video Card | AMD Radeon HD 6670
------------ | -------------
Driver | AMD Radeon HD 6670
DirectX Driver Name | aticfx32.dll
Driver Version | 13.251.9001.1001
DirectX Driver Version | 8.17.10.1247
Driver Date | 4 July 2014
OpenGL Version | 4.3
Desktop Color Depth | 32 bits per pixel
Monitor Refresh Rate | 60 Hz
DirectX Card | AMD Radeon HD 6670
VendorID | 0x1002
DeviceID | 0x6758
Number of Monitors | 2
Number of Logical Video Cards | 2
SLI or Crossfire | None Detected
Primary Display Resolution | 1920 x 1080
Desktop Resolution | 3840 x 1080
Primary Display Size | 20.08" x 11.42"  (23.07" diag)
--- | 51.0cm x 29.0cm  (58.6cm diag)
Primary Bus Type | Not Detected
Primary VRAM | 1024 MB
Supported MSAA Modes | 2x 4x 8x 

Memory | ---
------------ | -------------
RAM | 4077 Mb

**Comment by DolceTriade** [comment]
The only thing I can do is recommend you use https://github.com/apitrace/apitrace to create a dump of this happening. Be sure to use a small resolution and try to trigger this as fast as you can as the dumps can be quite large.

**Comment by Zilor** [comment]
The issue dissappeared with Unvanquished 0.50 and or AMD driver 15.201.1151.1008.

**Comment by DolceTriade** [comment]
Nice.
