### ISSUE TITLE
'missing' models in debug build

### ISSUE THREAD

**Issue by TimePath** [Unvanquished/Unvanquished#903]
The following functions should check for file existence first:

* `CG_ParseWeaponFile`
* `CG_InitBuildables`
* `CG_RegisterClientModelname`

**Comment by mbasaglia** [comment]
There's a merged pull request referencing this issue can it be closed?

**Comment by DolceTriade** [comment]
I reverted that PR.

**Comment by jaytersen** [comment]
It was only a partial revert, i believe the issue is fixed.
