### ISSUE TITLE
Update broken links in Wiki

### ISSUE THREAD

**Issue by dimhotepus** [Unvanquished/Unvanquished#912]
Since wiki still exists, please, update broken links.

from
[official wiki](http://wiki.unvanquished.net/index.php/Main_Page)
to
[official wiki](https://wiki.unvanquished.net/index.php?title=Main_Page)

from
[Compiling the Source](http://wiki.unvanquished.net/index.php/Compiling_the_source)
to
[Compiling the Source](https://wiki.unvanquished.net/index.php?title=Compiling_the_source)

**Comment by mbasaglia** [comment]
Where did you find those broken links?

**Comment by TimePath** [comment]
https://github.com/Unvanquished/Unvanquished/wiki

**Comment by mbasaglia** [comment]
Ah OK, I've updated them.

**Comment by dimhotepus** [comment]
Thank you.
