### ISSUE TITLE
Fedora 23, "Unvanquished is not responding" and Warn: Couldn't load ______.md3

### ISSUE THREAD

**Issue by Ardeof** [Unvanquished/Unvanquished#918]
Edit: After installing the Nvidia drivers (finally), performance jumped to over double. Went from 40~60 fps to nearly a steady 120fps, with some dips to 80 or so depending on particles and whatnot. That's a heavy change of fps and congrats on that guys. I'd also like to mention that once changed over to the Nvidia driver and reinstalling Unvanquished, the game no longer crashes. The application "not responding message" may or may not still occur, but that's only a little issue.

The first quirk along the way is that whenever Unvanquished is launched, it causes a "not responding" error even though Unvanquished loads every time.

Then once in the game, only specific things work. This is because a lot of the Unvanquished content isn't being loaded. 
![md3problem](https://cloud.githubusercontent.com/assets/7959576/13905780/d545ac86-ee9f-11e5-924d-9bfaba79c847.png)

I'm suspecting it's because of somehow completely breaking unvanquished and losing data. Does Unvanquished not do a file check/auto repair to ensure the game is being run somewhat smoothly?

**Comment by Kangz** [comment]
For the "Not responding error" this is a known problem (see #354) but fixing it requires a lot of efforts.

I'm not sure for the model loading warnings, you say only specific things work? What are these things and what doesn't work?

If you connect to a server with the "pure" check (currently all of them have it), Unvanquished will check that you have the right asset files.

**Comment by mbasaglia** [comment]
There's a pull request for the model warnings: #921

**Comment by Ardeof** [comment]
@Kangz I reinstalled Unvanquished and Installed the Nvidia drivers. One of those two solutions seems to have fixed the model issues. What was happening before that with the nouveau drivers though was using certain sprites/animations would drop the fps to 1 momentarily, and crash the game shortly after.

Rifle firing and Turret fire are some of the main causes. Yet when joining Aliens, I could easily run around the map as dretch or Tyrant quite fine. It was an odd bug needless to say. Replicating the problem may be easy to do by installing Fedora with only Nouveau drivers, and trying to play Unvanquished as Human with Rifle. If it doesn't happen in that instance, then it was some kind of fluke.

**Comment by Kangz** [comment]
Mmmmh this seems very hard to repro, we'll fix it when we have someone with a consistent repro. Thanks for reporting the issues though!
