### ISSUE TITLE
Cmake does not properly locate liblua on Arch Linux.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#941]
In order to compile on Arch Linux, it is necessary to manually change `LUA_LIBRARY` from `/usr/lib64/liblua.5.2.so` to `/usr/lib64/liblua.so`. It seems `FindLua.cmake` needs a fix.

**Comment by Kangz** [comment]
Yeah I tried several times to fix it with no success. We need a cmake wizard.

**Comment by rmarquis** [comment]
Have a look at https://github.com/etlegacy/etlegacy/blob/master/cmake/FindLua.cmake.

**Comment by DolceTriade** [comment]
Good find.

**Comment by mbasaglia** [comment]
The CMake docs list a FindLua module. https://cmake.org/cmake/help/v3.0/module/FindLua.html (Sources here: https://github.com/Kitware/CMake/blob/master/Modules/FindLua.cmake).

Does that not work?

**Comment by DolceTriade** [comment]
The version of FindLua that ships with CMake is the problem.

**Comment by mbasaglia** [comment]
Should we report this to the CMake devs then?

**Comment by Viech** [comment]
@Kangz you fixed this with 206d8e0 (now DaemonDevelopers/Daemon@ee1a4cc), right? (if yes, please close.)

**Comment by necessarily-equal** [comment]
I've had the issue on Alpine Linux the other day when I attempted to package it. I had to patch it so that it could find a lua version, so there probably still is an issue.

**Comment by slipher** [comment]
I put in a new version of FindLua.cmake on the 0.52 branch. I wonder if that makes any difference.

**Comment by slipher** [comment]
The aforementioned FindLua.cmake is now in master. I will assume this is fixed if no one complains.
