### ISSUE TITLE
_NET_ACTIVE_WINDOW warning

### ISSUE THREAD

**Issue by guillaume-uH57J9** [Unvanquished/Unvanquished#960]
When running unvanquished and gnome-shell, the following warning is reported in /var/log/messages

```
Sep 11 11:21:43 computername org.gnome.Shell.desktop[3011]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1400014 (Unvanquish)
```

Version details: 
- unvanquished 0.50 universal zip
- gnome-shell 3.20.3-1+b1
- Debian testing
- Linux 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18)

**Comment by Viech** [comment]
@guillaume-uH57J9 seems like a minor issue, if you want it fixed in a timely manner I suggest making a pull request with that message timestamp fixed.

**Comment by guillaume-uH57J9** [comment]
Haven't found how to fix it, and haven't much time right now for further investigation. 
So I'm fine with this not getting fixed quickly. 

My investigation so far: 

* Searching "_NET_ACTIVE_WINDOW" into unvanquished's source code doesn't give any result, I'm probably not knowledgeable enough on X11 to know what to look for. 

* Other programs are affects, some have patches for their own code base: 
  * Eclipse https://bugs.eclipse.org/bugs/show_bug.cgi?id=371545
  * Chromium https://chromium.googlesource.com/chromium/src.git/+/ca3656dc321be956db788c5fc8ee16cd20ed6d86
  * Steam for Linux https://github.com/ValveSoftware/steam-for-linux/issues/930

**Comment by DolceTriade** [comment]
Steam and Unvanquished both rely on SDL2 for all the X11 stuff, so that may be the culprit.

**Comment by bmorel** [comment]
@necessarily-equal  maybe?

**Comment by illwieckz** [comment]
If there is a bug it probably lives in SDL.

**Comment by necessarily-equal** [comment]
It seems to have been fixed on my more recent stack. That is, NixOS 22.05 / GNOME 42 / SDL2.0.20.

I have seen a similar warning message for wayland when I start using the SDL Wayland backend, but it doesn't seems to appear every time I start the game, so it may be something else.
