### ISSUE TITLE
Cannot exec my custom config file

### ISSUE THREAD

**Issue by CrusoeDaWolf** [Unvanquished/Unvanquished#978]
Hello! I just recently found you game and I have been really enjoying it so far! Looking forward to playing with you all tomorrow.

Anyways, my issue here is I have created a modified default.cfg file called controls.cfg with all my controls setup (I have an issue with setting up with the menu, as I can't seem to delete the keys and I am too lazy to unbind them all), however when I launch the game and try to exec the file, it cannot find it.

I have also tried putting it inside a folder called "config" but it still cannot find it. 
Any solution? :c

**Comment by mbasaglia** [comment]
Where did you save that file?

Which OS are you on?

**Comment by DolceTriade** [comment]
What command are you trying to run?

**Comment by CrusoeDaWolf** [comment]
It is within pkg\config\controls.cfg and I am on Windows 8.1.

I have used the tab completion and it only shows two different config files. autogen.cfg and some othed one I can't remember.

The command is:

exec controls.cfg

**Comment by CrusoeDaWolf** [comment]
Alright. Will try it out.

**Comment by CrusoeDaWolf** [comment]
Didn't work. Still can't find the damn thing.
