### ISSUE TITLE
Using restart with switchteams option crashes sgame

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#980]
To reproduce:
- Start a map
- `/team a`
- `/restart st`

It crashes at `sg_client.cpp:1496`.

**Comment by DolceTriade** [comment]
Could you get a backtrace? maybe there is a condition in which bots don't get a gclient_t associated with them?

**Comment by slipher** [comment]
Fixed by 87a6654. The issue was that `ClientSpawn`(which accesses a `ClientComponent`) was called before `ClientBegin` which initializes said component.
