### ISSUE TITLE
Some model animation issues in current master

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#985]
idle animation ok, suffering animation broken (reproducible easily: just attack it):
![weird model](http://dl.illwieckz.net/b/unvanquished/bugs/weird-models/unvanquished_2017-02-11_081002_000.jpg)

I was not able to reproduce this one (idle animation broken, suffering ok):
![weird model](http://dl.illwieckz.net/b/unvanquished/bugs/weird-models/unvanquished_2017-02-11_070741_000.jpg)

**Comment by Viech** [comment]
@illwieckz are you sure you are loading model config files from git and not from the release pk3s? I've seen this bug in the past but not recently.

**Comment by illwieckz** [comment]
@Viech for the drill, I'm 100% sure: latest sgame, latest cgame, latest main/ directory.

For the acid tube… well I'm not able to reproduce, so I don't know. For the drill I'm 100% sure I'm loading the latest stuff all the way down.

**Comment by Viech** [comment]
There's some place in `cgame` where one can specify in an obscure table which animation should be played when. Maybe have a look there first, then see if the actual animations have the proper names.

For the drill, currently I'd use the repeater model for it anyway, as there is no repeater anymore and the repeater model looks a lot better. (Note that we did not yet test these gameplay changes.) So if it's a model and not a code/naming issue just ignore it.

**Comment by illwieckz** [comment]
To reproduce this one you have to remove the overmind (“unpowered“ acid tube):
![weird model](http://dl.illwieckz.net/b/unvanquished/bugs/weird-models/unvanquished_2017-02-11_070741_000.jpg)

**Comment by illwieckz** [comment]
drill fixed in ac31a80, others fixed in 831eaef

**Comment by illwieckz** [comment]
Note that the issue fixed by ac31a80 (_drill: Fix copypasta error that gave a drill a leech entity_) was probably the reason why attacking a drill as alien was providing an "_a forward base is under attack_" message to alien players.
