### ISSUE TITLE
Clean up command/cvar names

### ISSUE THREAD

**Issue by mbasaglia** [Unvanquished/Unvanquished#988]
* [x] Clean up command/cvar names
* [ ] Server-side demos
* [ ] UI/menu to play demos
* [ ] Display hud menus on demo playback
* [ ] Changing playback speed

**Comment by mbasaglia** [comment]
Various bugs I've seen:
* [ ] Starting demos while on a map disconnects but does not start the demo
* [ ] When recording video, it becomes a bit faster than normal
* [ ] The video output isn't really smooth, looks like the camera is jumping around a bit

**Comment by Viech** [comment]
I have to admit I have been experiencing camera jerks also during devmap for quite a while, so maybe not a demo issue.

**Comment by mbasaglia** [comment]
For implementation of server-side demos in similar engines, see:
https://github.com/Amanieu/tremfusion/blob/master/src/server/sv_demo.c
https://github.com/ioquake/ioq3/pull/265/files

**Comment by illwieckz** [comment]
I renamed this issue to `Clean up command/cvar names` like the ticked checkbox it successfully tracked.
Other feature requests or bugs are now tracked on:

- https://github.com/Unvanquished/Unvanquished/issues/2495

**Comment by illwieckz** [comment]
About:

> The video output isn't really smooth, looks like the camera is jumping around a bit

and:

> I have to admit I have been experiencing camera jerks also during devmap for quite a while, so maybe not a demo issue.

This was probably the bug where dead player animation affected non-players like spectators
