### ISSUE TITLE
CG_InitBuildables() looks for complete file path so buildable sound system is not extension independent

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#993]
This issue is very similar to #992.

Even if the engine allows to load path without extension or with a different extension, `CG_InitBuildables()` in [src/cgame/cg_buildable.cpp:711](https://github.com/Unvanquished/Unvanquished/blob/10120d27b1ca50fee81ac74b1349930a60376d98/src/cgame/cg_buildable.cpp#L711) does a check on complete file path:

```c++
if ( trap_FS_FOpenFile( filename, &f, fsMode_t::FS_READ ) > 0 )
{
	//file exists so close it
	trap_FS_FCloseFile( f );

	cg_buildables[ buildable ].sounds[ j ].sound = trap_S_RegisterSound( filename, false );
	}
	else
	{
		//file doesn't exist - use default
		if ( BG_Buildable( buildable )->team == TEAM_ALIENS )
		{
			cg_buildables[ buildable ].sounds[ j ].sound = defaultAlienSounds[ j ];
		}
		else
		{
			cg_buildables[ buildable ].sounds[ j ].sound = defaultHumanSounds[ j ];
		}
	}
}
```

Because of that, `sound/buildables/reactor/idle1` fallbacks on `sound/buildables/human/idle1` even if the sound file is there. Other sound code unrelated to buildable system (and voice one) does not need extension.

**Comment by illwieckz** [comment]
I tested the current `no_sound_ext` branch and confirm this code fixes this issue.

**Comment by DolceTriade** [comment]
It's just a debug log. We should now log at the point of failure instead of in the engine. https://github.com/DaemonEngine/Daemon/commit/bab15b21f651d91601431263e1cb3783fcb515a9
