### ISSUE TITLE
Google Chrome silently invalidates Unvanquished security fixes

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#996]
See: https://bugs.chromium.org/p/chromium/issues/detail?id=479419#c10

Chromes silently rewrites version strings from our packages, rewriting _tilde_ character with _hyphen_ one, giving priority to prereleased packages over ones shipping security fixes.

**Comment by Kangz** [comment]
I will see if I can do something but it seems unlikely.

**Comment by illwieckz** [comment]
I modified my [packaging tool to not produce versions string with tilde](https://github.com/illwieckz/Urcheon/commit/993d45542479d8b1f23e49b9e5f3e8a9e1ea77be) by default, by the way it does not prevent people to override this.

**Comment by Exaeta** [comment]
What if we include metadata before the actual content?

**Comment by DolceTriade** [comment]
What do you mean?

**Comment by Viech** [comment]
What if my new package does not ship security fixes but just an update to my map's visuals? Will Chrome let it through? Because then, Google is clearly trying to crack us. 😛

**Comment by illwieckz** [comment]
The issue is in a third party-product, hence closing this issue as CANTFIX.
