### ISSUE TITLE
Proposal: Use C++ polymorphism for entities instead of generator.

### ISSUE THREAD

**Issue by Exaeta** [Unvanquished/Unvanquished#997]
I would like to suggest that we use C++ polymorphism instead of the object generator.

Some myths about virtual functions:

* Virtual functions are slow: False. Virtual functions are about as fast as function pointers, although both function pointers and virtual functions are slower than inline functions.
  See e.g.:
  http://coldattic.info/shvedsky/pro/blogs/a-foo-walks-into-a-bar/posts/3

* Virtual functions use string look ups to find the right class. False.
   You might be thinking about ```dynamic_cast```, which in some Microsoft implementations, I wouldn't be surprised if it did that. ```dynamic_cast``` is not the same thing as a virtual method call though.

* This will prevent the usage of allocator pools. False.
  The entity class is already a polymorphic (virtual) class, because ~Entity is defined as a virtual method. Whether a class is polymorphic does not affect whether you can use allocator pools. First, you can create polymorphic references, and you can construct an object in allocator pool memory using placement new. You can also define custom new and delete operators to have new and delete versions that use allocator pools.

Additional reasons to use virtual methods:

* Compilers understand virtual methods better, and have virtual method specific optimizations. Those optimizations would not be applied to the custom "virtual method" implementation we are using now. (for example, if the compiler can figure out that a object is actually of a specific type, it can inline the virtual call, something difficult for it to do using generic optimizations).
* Virtual methods are less likely to have bugs. We can rely on very well tested code.
* Requires a lot less overhead in the development process. We only need to declare functions virtual, instead of our current process.

Because of these reasons, I suggest virtual methods.

**Comment by slipher** [comment]
If you don't use `dynamic_cast` (or write your own version of it), then every function of every type of entity would have to be declared in the base class, no? Just because polymorphism is a C++ language feature doesn't make it the right tool for every situation.

**Comment by Exaeta** [comment]
No, it would not. First, the unvanquished code already implements a version of dynamic cast and virtual methods. Only externally visible functions would need to be optimized like that.

If you had a "buildable" class, then as long as the class is buildable, it can implement the buildable requirements. What is "slow" is casting from a base class to a derived class, but you should avoid that in general. There is another, better solution to avoiding ```dynamic_cast```, interface conversion.

Like so:
```
class buildable;
class entity
{
 virtual ~entity() {};
 virtual void damage(int) {};
 virtual void kill() {};
 virtual buildable* to_buildable() { return nullptr; }
 virtual bool is_buildable() const { return false; }
};
```
Now there is a .as_buildable() which gives us the buildable interface... if you want generic qualifiers this is probably the way to do it. Or just write code that doesn't use dynamic cast so often. You shouldn't need ```dynamic_cast``` often enough for it to be a performance issue... once a buildable, always a buildable, no reason to call ```dyanmic_cast``` to figure out if something is a buildable every frame! Better just to have a list of references to buildables and then do buildable specific calls to that instead of filtering like it is done now.

**Comment by Kangz** [comment]
Your approach doesn't allow multiple components to listen to the same message.

Another goal with our version of CBSE is to allow moving some performance critical components out of the memory of the object, in an arena allocator. You can't do that with virtuals + dynamic cast.

**Comment by Exaeta** [comment]
@Kangz No, that is how virtual methods work.

Arena allocation is separate from polymorphism. I addressed that.

**Comment by Exaeta** [comment]
Multiple components can listen for the same message using virtual inheritance.

**Comment by Exaeta** [comment]
e.g. 

```class turret
: public virtual entity, public virtual buildable, public virtual human
{
public:
  virtual void think()
  {
    this->human::think();
    this->buildable::think();
  }
};
```

**Comment by slipher** [comment]
To me, the above code snippet seems to make a good case for code generation. The programmer of `turret` has to manually forward the message to the base classes, and if they forget, the message will be silently dropped for one class. And worse is the diamond case: if `human` and `buildable` both forward the message to a common ancestor, it will be  processed twice. Have you read <https://github.com/DaemonEngine/CBSE-Toolchain/blob/master/README.md>?

**Comment by Exaeta** [comment]
Then use callbacks with std::function? Why is this devlopment pattern even being used?

I can't imagine any reason to use a code generator in this circumstance. If you really need this behavior, it should be done in a template, not a code generator. I mean, that's what templates are for?

**Comment by Kangz** [comment]
@slipher has a good point. Also we want it to be possible to have each component in a different arena allocator. With polymorphism you can only have one arena allocator.

**Comment by Exaeta** [comment]
That's false but whatever. I can see why this project hasn't gotten anything done despite having sommany people...
