### ISSUE TITLE
Files under the non-free Shaderlab license?

### ISSUE THREAD

**Issue by JadedCtrl** [Unvanquished/Unvanquished#998]
COPYING.txt has a non-free license for "shaderlab textures" as follows:

> --------------------------------------------------- Media License Exceptions ---
All shaderlab (http://www.shaderlab.com/) textures (by Randy 'ydnar' Reddig)
are subject to the following license:
  Usage and redistribution policy: Textures may be freely downloaded, modified,
  and used in free maps, mods or total conversions provided this copyright
  notice is left intact and a link to Shaderlab is provided in the credits or
  read-me file. Other non-commercial applications are considered on a
  case-by-case basis via e-mail. All other usage requires written permission.
  Bulk redistribution or archival of the textures in any medium, digital or
otherwise (except mapping packages for mods) is prohibited.  
   
Doing a search in the sources, though, I can't seem to find anything by ydnar/Randy... (Keywords 'ydnar', 'randy', 'reddig', 'shaderlab' turn up no results except for COPYING.txt)  
Randy also isn't in the contributors list on the GH page or on the Unvanquished website.  
What files are under this license, if there are any?

**Comment by Viech** [comment]
I would assume `COPYING.txt` is just severly outdated. I don't think his textures are used anywhere anymore, except for legacy maps from Tremulous. Note that maps ship their own license files and furhtermore Unvanquished does not ship any legacy maps.
