### ISSUE TITLE
Wiki relicensing (remove the non-free NC clause)

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#999]
We are in process to remove the non-free _NC_ clause on the [Unvanquished Wiki](https://wiki.unvanquished.net) to use a free license instead, so I'm looking for permissions from contributors.

- @neumond
- @qrntz 
- @JacksonTech
- @t4im 
- @ZdrytchX 
- @gavlig 
- @Gireen 
- @EmperorJack
- @FreeSlave
- @Velociostrich

Do you give your permission to remove non-free NC clause from your own past contributions to Unvanquished Wiki and give your permission to relicense them from _CC By-NC-SA_ to _CC By-SA_ license?

_[edit: Ingar was a false positive]_

**Comment by illwieckz** [comment]
Same question for @cmf028, do you give your permission to remove the NC clause from your own past contributions to Unvanquished Wiki to relicense them from _CC By-NC-SA_ to _CC By-SA_?

**Comment by gavlig** [comment]
Yes, but I don't think I ever edited anything on wiki

**Comment by FreeSlave** [comment]
I don't remember making any contribution to wiki. But I'm not against change of license.

**Comment by illwieckz** [comment]
Thank you very much! :smiley:

**Comment by illwieckz** [comment]
Same question for @dsalt, do you give your permission to remove the NC clause from your own past contributions to Unvanquished Wiki to relicense them from CC By-NC-SA to CC By-SA?

**Comment by EmperorJack** [comment]
Go for it, I don't think I've contributed to the wiki either though.

**Comment by illwieckz** [comment]
Thanks a lot @EmperorJack! Well, there is many minor contributors with just some minor edits, but the contributor list is still far far smaller than the edition list so it's easier to go through the contributor list. ;-)

**Comment by cmf028** [comment]
Yeah, I give my permission to relicense them.

**Comment by illwieckz** [comment]
Awesome, thank you very much ! :+1:

**Comment by ZdrytchX** [comment]
You've got mine (you've already asked for it but I'll comment down here for record purposes)

**Comment by illwieckz** [comment]
:+1:

**Comment by neumond** [comment]
Yes, I give the permission.

**Comment by illwieckz** [comment]
Thank you very much @neumond, that's very helpful! :+1:

**Comment by illwieckz** [comment]
We now just need the permission from 3 people only, among them are @qrntz and @dsalt.

**Comment by qrntz** [comment]
yeah idc

**Comment by illwieckz** [comment]
thanks a lot! :+1:

**Comment by Viech** [comment]
Also good you're alive @qrntz! 👍

**Comment by ZdrytchX** [comment]
Don't jynx it, the last time I made a comment on this thread I supposedly should've died due to medical ignorance

**Comment by illwieckz** [comment]
We are now just missing @dsalt's permission, everyone else have given permission to remove the NC clause on wiki or stuff had be rewritten but dsalt's contribution is too large to make a rewrite possible. @dsalt can you give your permission to remove the non-free NC clause on Unvanquished wiki?

**Comment by illwieckz** [comment]
Awesome :+1: thank you very much !

**Comment by illwieckz** [comment]
This is done: https://wiki.unvanquished.net/wiki/Wiki_relicensing

We reviewed and rewrote or deleted the contributions we did not get answer for.

The effort lasted 48744 hours, 2031 days, about 5 years and 6 month.

It's now time to celebrate! 🎉

See also: https://forums.unvanquished.net/viewtopic.php?f=4&t=2034&p=18409#p18409
